/* ==========================================================================
   DIAGRAMS: HOW TO READ EACH GRAPH
   ==========================================================================
   The Diagrams tab groups the drawn figures by what she asks a student to do
   with a graph, and gives each one the same five-step walk-through:
     axes   what each axis is and what scale it uses
     shape  what the line does
     eq     the equation that draws it
     how    which part of that equation makes the shape
     asks   what she asks about a graph like this
   `quote` is her own sentence about this kind of graph, taken from the
   question in the bank that already carries it (q6_figures.js).
   Every number is one the figure prints, or one figures.py draws it from.
   Plain strings; {{frac:a|b}} stacks a ratio.
   ========================================================================== */
const DIAGRAM_INTRO = [
  'Read the axis first: an evenly spaced axis and an axis that steps by tens (1, 10, 100) turn the same drug into different shapes.',
  'Then read the line: straight, bending down, rising to a peak, levelling off, or rising and falling in a saw-tooth.',
  'Then name the equation that makes that shape, and the term in it that is responsible.'];
const DIAGRAM_QUOTE = 'you’ve got to pay attention to the axis';

const DIAGRAMS = [
 {group:'Decide the order or the model from the shape', note:'The shape of the line, read against the axis, names the order or the model.',
  figs:[
  {key:'ord_linear_straight', module:1, name:'Straight line on an evenly spaced axis',
   axes:'Time (hours) across; concentration up, evenly spaced (0, 25, 50, 75, 100).',
   shape:'A straight line falling from 100: the same amount is lost every hour (8 per hour here).',
   eq:'C = C0 − k0 t (zero order).',
   how:'C0 − k0 t is a line: k0 is the slope, the same at every concentration.',
   asks:'Which order? Zero order. The rate constant has concentration-per-time units.'},
  {key:'ord_linear_curve', module:1, name:'Curve on an evenly spaced axis',
   axes:'Time across; concentration up, evenly spaced.',
   shape:'A curve, steep at first and flattening: a smaller amount is lost each hour as the concentration falls.',
   eq:'C = C0 e^(−kt) (first order).',
   how:'e^(−kt) removes the same fraction each hour, so the amount removed shrinks with the concentration.',
   asks:'Which order? First order. On an evenly spaced axis first order curves.'},
  {key:'ord_semilog_straight', module:1, name:'Straight line on a decade axis',
   axes:'Time across; concentration up on an axis marked 1, 10, 100, 1000. Each step is ×10: a log scale, even though it is not labelled "log".',
   shape:'A straight line falling from 200 to 2.3 over 6 hours.',
   eq:'log C = log C0 − {{frac:kt|2.3}}, the log form of C = C0 e^(−kt).',
   how:'Taking the log turns e^(−kt) into a straight line with slope −{{frac:k|2.3}}, so k = −2.3 × slope.',
   asks:'Which order? First order: straight on a decade axis.',
   quote:'if you look at that scale and you see that it is not changing by regular one infinite, or it’s increasing by a a function of 10, then that tells you that it is a logarithmic scale'},
  {key:'ord_semilog_curve', module:1, name:'Bending line on a decade axis',
   axes:'Time across; concentration up on a decade axis (1, 10, 100, 1000).',
   shape:'A line that starts nearly flat and bends more and more steeply downward.',
   eq:'C = C0 − k0 t (zero order), drawn on a log axis.',
   how:'The same amount leaves each hour; near the bottom that fixed amount is a large share of what is left, and on a multiplying axis a large share is a long way down.',
   asks:'Which order? Zero order: on a decade axis, anything but a straight line is not first order.'},
  {key:'cpt_one', module:2, name:'One straight line after an IV bolus',
   axes:'Time across; concentration up on a decade axis.',
   shape:'One straight line from time zero.',
   eq:'Cp = Cp0 e^(−kt): one compartment, first-order elimination.',
   how:'A single exponential is a single straight line on a log axis.',
   asks:'Which model? An IV bolus into one compartment.',
   quote:'If I gave you a graph on a log scale that looks just like the blue line all by itself, that tells you it’s an IV bolus dose one compartment model.'},
  {key:'cpt_two', module:2, name:'Steep start, then a shallower straight line',
   axes:'Time across; concentration up on a decade axis.',
   shape:'A steep early fall (distribution) that turns into a shallower straight line (elimination). The dashed line is the straight part extended back to time zero.',
   eq:'Cp = A e^(−αt) + B e^(−βt); here Cp = 15e^(−3.4t) + 7e^(−0.12t).',
   how:'The α term (3.4 hr⁻¹) dies away within the first hour; after that only the β term (0.12 hr⁻¹) is left, a straight line. The dashed line meets the axis at B = 7.',
   asks:'Which model? Two compartments. The elimination half-life comes from β: t½β = {{frac:0.693|β}}.',
   quote:'if I give you a graph that looks something like this without the red and blue and just a log scale and I’m telling you that it is an IV bolus dose, and I just give you a line that looks like this one, the black line. That should say to you that this is a two compartment model.'},
  {key:'elim_rate_linear', module:4, name:'Rate of elimination rising with concentration',
   axes:'Plasma concentration (mg/L) across; rate of elimination (mg/hr) up.',
   shape:'A straight line through the origin: double the concentration, double the rate.',
   eq:'Rate of elimination = Cl × Cp (first order).',
   how:'Clearance is the slope: (mg/hr) ÷ (mg/L) = L/hr. Here the slope is 2 L/hr, the same at every concentration.',
   asks:'Which order? First order: the rate changes with concentration, the clearance does not.'},
  {key:'elim_rate_flat', module:4, name:'Rate of elimination flat with concentration',
   axes:'Plasma concentration across; rate of elimination up.',
   shape:'A horizontal line: 20 mg/hr whatever the concentration.',
   eq:'Rate = k0 (zero order).',
   how:'A zero-order process removes a fixed amount per hour, so the rate does not depend on how much drug is there.',
   asks:'Which order? Zero order.'},
  {key:'input_types', module:5, name:'IV bolus, oral tablet and IV infusion',
   axes:'Time across; concentration up; no numbers, because only the shape matters.',
   shape:'IV bolus (top): highest at time zero, then falls. Oral tablet (middle): rises to a peak, then falls. IV infusion or controlled release (bottom): rises and levels off, then falls once the input stops.',
   eq:'IV bolus: C0 e^(−kt). Tablet: {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)). Infusion: {{frac:R|kVD}}(1 − e^(−kt)).',
   how:'IV bolus: the whole dose enters at once, so there is no rise. Oral: first-order absorption, so the curve peaks where the rate in equals the rate out. Infusion: a constant rate in, so the curve levels off where R equals the rate out.',
   asks:'Which dosage form, and which input order? Name both from the shape.',
   quote:'if I give you a curve on the exam and it looks like this. where there is a clear peak. we go up, we peak, we come back down, then you, I want you to identify that as an oral input. First order in, first order out.'},
 ]},
 {group:'Read a value off the graph', note:'The graph carries a number: a plateau, a peak, a slope.',
  figs:[
  {key:'inf_css', module:3, name:'An infusion rising to a plateau',
   axes:'Time from the start of the infusion (hours) across; concentration up, evenly spaced.',
   shape:'Rises quickly, then flattens toward 20: the plateau is Css.',
   eq:'C = {{frac:R|Cl}}(1 − e^(−kt)); Css = {{frac:R|Cl}}.',
   how:'As t grows, e^(−kt) goes to 0 and C goes to {{frac:R|Cl}}. Half the plateau at 1 t½, 90% at 3.3 t½, 95% at 4.32 t½.',
   asks:'The plateau value, the rate that gives it (R = Css × Cl), and the time to reach a fraction of it.',
   quote:'Our input is zero order, constant in, first order out. When we stop the in, then it’s just out.'},
  {key:'oral_peak', module:5, name:'One oral dose: rise, peak, fall',
   axes:'Time (hours) across; concentration (mg/L) up, evenly spaced.',
   shape:'Rises, peaks, then falls. The dashed line marks the peak: tmax 2.0 hr, Cmax 12.2 mg/L (500 mg, F 0.85, VD 22 L, ka 0.924, k 0.231 hr⁻¹).',
   eq:'Cp = {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)); tmax = {{frac:ln(ka ÷ k)|ka − k}}.',
   how:'Early, the absorption term e^(−ka t) is large and the level climbs; at tmax the rate in equals the rate out; later only e^(−kt) is left.',
   asks:'tmax and Cmax, and what happens to each when the dose, ka or k changes.',
   quote:'Right at CMax, the rate N is going to be equal to the rate out.'},
  {key:'oral_semilog', module:5, name:'One oral dose on a decade axis',
   axes:'Time across; concentration up on an axis marked 0.1, 1, 10, 100.',
   shape:'Rises to a peak, then the tail becomes a straight line.',
   eq:'Cp = A(e^(−kt) − e^(−ka t)); late, Cp ≈ A e^(−kt).',
   how:'Once absorption is over the e^(−ka t) term is near 0, so the tail is a single exponential: straight on a log axis, with slope −{{frac:k|2.3}}.',
   asks:'The elimination rate constant from the slope of the straight tail.'},
  {key:'rate_vs_constant', module:5, name:'Rate against rate constant',
   axes:'Time (hours) across; amount of drug in the body (mg) up.',
   shape:'Two first-order curves, 200 mg and 100 mg. Each dotted segment is the slope: the rate leaving, in mg/hr.',
   eq:'Rate = k × amount; k = 0.2 per hour for both doses.',
   how:'The 200 mg dose loses 40 mg/hr at first, the 100 mg dose 20 mg/hr; once the larger dose has fallen to 100 mg it also loses 20 mg/hr. Rate ÷ amount is 0.2 at every marked point.',
   asks:'Does doubling the dose change k or the half-life? No: it doubles the rate, not the rate constant.'},
 ]},
 {group:'Compare two curves', note:'One thing is changed; read what moves and what does not.',
  figs:[
  {key:'inf_two_rates', module:3, name:'Two infusion rates of the same drug',
   axes:'Time from the start of the infusion across; concentration up, evenly spaced.',
   shape:'Two curves rising to plateaus of 20 and 40; both reach them at the same time.',
   eq:'Css = {{frac:R|Cl}}; fraction of Css = 1 − e^(−kt).',
   how:'R sits only in front of the bracket, so it scales the plateau; the time course depends on k alone.',
   asks:'Doubling the rate doubles Css and does not change the time to reach it.',
   quote:'changing the rate changes our steady state concentration with me. I feel like I’ve said it 5 times, and I’ve said it 5 times because this is one of those things that I want you to take with you. so I’ve said it 5 times. I’m gonna ask it of you 10 times.'},
  {key:'ka_k_effects', module:5, name:'Doubling the dose, ka, or k',
   axes:'Three panels, each: time across, concentration (mg/L) up. The dashed curve is the unchanged drug (100 mg, ka 1.0, k 0.2 hr⁻¹, AUC 25).',
   shape:'Dose doubled: everything twice as high, same tmax. ka doubled: earlier and higher peak. k doubled: earlier and lower peak.',
   eq:'tmax = {{frac:ln(ka ÷ k)|ka − k}}; Cmax from the oral equation; AUC = {{frac:F D0|k VD}}.',
   how:'The dose only multiplies the equation; ka and k set the shape. AUC has k but not ka in it: 25 → 50 (dose ×2), 25 (ka ×2), 12.5 (k ×2).',
   asks:'For each change: tmax earlier, later or the same; Cmax higher or lower; AUC changed or not.'},
  {key:'k_vs_ka', module:5, name:'Raising k against raising ka',
   axes:'Two panels: time across, concentration (µg/mL) up. 100 mg, VD 10 L.',
   shape:'Top: k raised 0.2 → 0.5 hr⁻¹ lowers the whole curve; the shaded area is lost. Bottom: ka raised 0.2 → 0.5 hr⁻¹ peaks earlier and higher; the area gained early is lost later.',
   eq:'AUC = {{frac:F D0|k VD}}.',
   how:'k is in the AUC, so raising k cuts it (50 → 20). ka is not, so raising ka moves the area earlier and leaves the total at 100.',
   asks:'Why AUC follows k and not ka.'},
  {key:'flipflop', module:5, name:'Immediate release against extended release',
   axes:'Time across; concentration up on a log scale; no numbers.',
   shape:'Both curves rise and fall; the immediate-release tail is steep, the extended-release tail shallow.',
   eq:'Cp = A(e^(−kt) − e^(−ka t)). The tail follows whichever constant is smaller.',
   how:'Immediate release: ka > k, so the tail falls with k. Extended release: ka < k, so the tail falls with ka (flip-flop). The drug, and k, are the same.',
   asks:'What the slope of the tail measures, and why it is not always k.'},
 ]},
 {group:'Follow a dosing regimen over time', note:'Doses add on a time line; step through them one at a time.',
  figs:[
  {key:'md_bolus_steps', module:6, name:'Repeated IV bolus, dose by dose',
   axes:'Time (hours) across; concentration (mg/L) up. 10 mg/kg every 8 hours, t½ 4 hr, VD 0.25 L/kg, so each dose adds 40 mg/L.',
   shape:'A saw-tooth: each dose jumps up by 40 and falls first order; the peaks climb to 53.3 and the troughs to 13.3, then stop climbing.',
   eq:'Cmax∞ = {{frac:C0|1 − e^(−kτ)}}; Cmin∞ = Cmax∞ e^(−kτ); Cavg∞ = {{frac:FD0|VD k τ}}.',
   how:'Each dose adds C0 to what is left of the earlier ones (superposition); e^(−kτ) = 0.25 is the share left at each dose, so the climb stops at 40 ÷ 0.75 = 53.3.',
   asks:'Peak, trough and average at steady state, the time to get there (3 to 5 half-lives), and the level after the last dose.'},
  {key:'md_bolus', module:6, name:'Repeated IV bolus, the whole regimen',
   axes:'Same axes and regimen as the step-through above.',
   shape:'Six doses then none. The dashed amber curve is the first dose on its own; the dotted lines are Cmax 53.3, the midpoint 33.3, Cavg 28.9 and Cmin 13.3.',
   eq:'Cavg∞ = {{frac:FD0|VD k τ}} = 28.9 mg/L.',
   how:'The average sits below the midpoint because a first-order fall spends more of each interval at the lower concentrations.',
   asks:'Why Cavg∞ is not the midpoint, {{frac:Cmax∞ + Cmin∞|2}}.'},
  {key:'two_infusions_steps', module:6, name:'Two intermittent infusions, stage by stage',
   axes:'Time (hours) across; concentration (mg/L) up. 300 mg over 2 hours at 0 and 6 hours; k 0.15 hr⁻¹, VD 15 L.',
   shape:'Rise during each infusion, first-order fall after it; the second rise starts from what is left of the first.',
   eq:'End of an infusion: C = {{frac:R|kVD}}(1 − e^(−k tinf)); after it: C = Cend e^(−kt).',
   how:'Each infusion reaches 17.28 mg/L on its own; at 12 hours the first gives 3.86 and the second 9.48, which add to 13.34.',
   asks:'The rate, the end-of-infusion level, and the level a stated time after the last infusion.'},
  {key:'two_infusions', module:6, name:'Two intermittent infusions, the sum',
   axes:'Same axes and doses as the step-through above.',
   shape:'The blue curve is the plasma concentration; the two amber curves are each infusion on its own.',
   eq:'C(12 hr) = 17.28 e^(−0.15 × 10) + 17.28 e^(−0.15 × 4).',
   how:'Each dose gets its own time measured from the end of that infusion: 10 hours for the first, 4 for the second.',
   asks:'The concentration at a time after the second infusion, by adding the two.'},
 ]},
];
