/* ==========================================================================
   DIAGRAMS: HOW TO READ EACH GRAPH
   ==========================================================================
   The Diagrams tab groups the drawn figures by what she asks a student to do
   with a graph, and gives each one the same five-step walk-through:
     axes   what each axis is and what scale it uses
     shape  what the line does
     eq     the equation that draws it
     how    which part of that equation makes the shape
     asks   what she asks about a graph like this
   `quote` is her own sentence about this kind of graph, taken from the
   question in the bank that already carries it (q6_figures.js).
   Every number is one the figure prints, or one figures.py draws it from.
   Plain strings; {{frac:a|b}} stacks a ratio.
   ========================================================================== */
const DIAGRAM_INTRO = [
  'Read the axis first: an evenly spaced axis and an axis that steps by tens (1, 10, 100) turn the same drug into different shapes.',
  'Then read the line: straight, bending down, rising to a peak, levelling off, or rising and falling in a saw-tooth.',
  'Then name the equation that makes that shape, and the term in it that is responsible.'];
const DIAGRAM_QUOTE = 'you’ve got to pay attention to the axis';

const DIAGRAMS = [
 {group:'Tell the dosing models apart by the curve', own:'models',
  note:'How the drug goes in decides the shape. "First order" means the rate is proportional to how much drug is there (a fixed fraction per hour); "zero order" means a constant rate (a fixed amount per hour). Every model here removes drug by first-order elimination with the rate constant k; they differ in the input. The axes carry no numbers because only the shapes are compared.',
  table:[
   ['One-compartment IV bolus (M2)', 'All at once, straight into the blood', 'First order, rate constant k', 'One', 'Starts at its highest point (C0) and falls; one straight line on a log axis', 'A dose "by IV bolus" or "by rapid IV injection" with no absorption; the model is named'],
   ['Two-compartment IV bolus (M2)', 'All at once', 'First order from the central compartment', 'Two: central (blood) and tissue', 'On a log axis, a steep early fall then a shallower straight line', 'A, B, α and β, or an equation with two exponential terms; the model is not named'],
   ['IV infusion (M3)', 'Zero order: a constant rate R, in mg/hr', 'First order, k', 'One', 'Starts at zero and climbs to a plateau (Css); falls once the infusion stops', 'A rate in mg/hr, "infused at", "steady-state concentration"'],
   ['Loading dose with an infusion (M3)', 'An IV bolus at the moment the infusion starts', 'First order, k', 'One', 'Flat at Css from the start when the loading dose is right', '"loading dose", "simultaneously", "reach ... immediately"'],
   ['Single oral dose (M5)', 'First order: absorption rate constant ka, and only the fraction F reaches the blood', 'First order, k', 'One', 'Starts at zero, rises to a peak (Cmax at tmax), then falls', 'A capital F, a ka or an absorption half-life, "tablet" or "capsule"'],
   ['Repeated IV bolus (M6)', 'All at once, repeated every τ hours', 'First order, k', 'One', 'A saw-tooth climbing to a plateau in 3 to 5 half-lives', 'An IV dose "every 8 hours"; steady-state peak, trough or average asked'],
   ['Intermittent IV infusion (M6)', 'Zero order for a set time, repeated', 'First order, k', 'One', 'A rise during each infusion and a fall between; each rise ends higher', 'A dose "over 2 hours" and a second infusion started hours later'],
   ['Multiple oral doses (M6a)', 'First order (ka, F), repeated every τ hours', 'First order, k', 'One', 'Rounded peaks and troughs climbing to a plateau', 'F and ka together with a dosing interval'],
  ],
  figs:[
  {key:'models_all', module:'2 to 6', modules:[2,3,5,6], name:'The eight dosing models side by side',
   axes:'Time across; concentration up, evenly spaced except the two-compartment panel, which is a log axis. No numbers: only the shapes are compared, and every panel uses the same elimination rate constant.',
   shape:'Top to bottom: a fall from time zero (IV bolus); a steep fall then a shallower line (two-compartment, log axis); a climb to a plateau (infusion); a flat line (loading dose with an infusion); a rise to a peak then a fall (single oral dose); a saw-tooth (repeated IV bolus); a rise during each infusion and a fall between (intermittent infusion); rounded peaks climbing (multiple oral doses).',
   eq:'One equation per panel, from Cp = C0 e^(−kt) for the bolus to the accumulation-factor forms for the repeated doses; each is under Tell apart, Explain one.',
   how:'How the drug goes in makes the shape: all at once (starts high), at a constant rate (climbs), or first order (rises to a peak). Repeating a dose every τ adds the curves on top of one another until the peaks level off.',
   asks:'Which model a described regimen or a sketched curve belongs to, and which equation that model uses.'},
  {key:'model_bolus1', module:2, name:'One-compartment IV bolus',
   axes:'Time across; concentration up, evenly spaced, no numbers.',
   inout:'In: the whole dose at once, straight into the blood. Out: first-order elimination with the rate constant k, so a fixed fraction of what is there leaves each hour.',
   shape:'Highest at time zero, at C0, the concentration the dose produces the moment it is spread through the body; then a curve falling and flattening. On a log axis the same curve is one straight line.',
   eq:'Cp = C0 e^(−kt), where Cp is the plasma concentration at time t and C0 = {{frac:D0|VD}}, the dose over the apparent volume of distribution.',
   how:'All of the dose is in the body at time zero, so the curve starts at its highest point; e^(−kt) removes the same fraction each hour.',
   asks:'Which model a curve that starts high and falls belongs to; k from two points; C0 by back-extrapolation.'},
  {key:'model_bolus2', module:2, name:'Two-compartment IV bolus',
   axes:'Time across; concentration up on a log axis, no numbers.',
   inout:'In: the whole dose at once into the central compartment, the blood and the organs it reaches quickly. Drug then moves into a tissue compartment and back. Out: first-order elimination from the central compartment.',
   shape:'A steep early fall (distribution into tissue) that turns into a shallower straight line (elimination).',
   eq:'Cp = A e^(−αt) + B e^(−βt): two exponential terms, A and B the intercepts in concentration units, α and β the two slopes in reciprocal time.',
   how:'Two exponentials: the α term dies away quickly and leaves the β line; β, the smaller constant, sets the terminal half-life.',
   asks:'Why the log plot is not one straight line; which phase is distribution and which is elimination; t½ from β.'},
  {key:'model_infusion', module:3, name:'IV infusion, one compartment',
   axes:'Time across; concentration up, evenly spaced, no numbers; a dashed line marks Css and a dashed vertical the moment the infusion stops.',
   inout:'In: a constant rate R in mg/hr, which is a zero-order input. Out: first-order elimination, k. The rate out grows as the concentration grows, until it equals the rate in.',
   shape:'Starts at zero, climbs quickly, levels off at Css, the steady-state concentration where rate in equals rate out; falls by first-order elimination once the infusion stops.',
   eq:'Cp = {{frac:R|Cl}}(1 − e^(−kt)) during the infusion, Cl being the clearance; Css = {{frac:R|Cl}}; after it stops, Cp = Cstop e^(−kt), where Cstop is the level at the moment it stopped.',
   how:'Constant rate in against a rate out that grows with the concentration: the two meet at Css. (1 − e^(−kt)) is the fraction of Css reached.',
   asks:'What sets the height of the plateau (R and Cl) and what sets the time to reach it (k only).'},
  {key:'model_loading', module:3, name:'Loading dose with an infusion',
   axes:'Time across; concentration up, evenly spaced, no numbers.',
   inout:'In: an IV bolus (the loading dose, DL) at the same moment a constant-rate infusion starts. Out: first-order elimination, k, acting on both.',
   shape:'A flat line at Css, the steady-state concentration, from the start. The dashed amber curve is the infusion alone, climbing to the same level.',
   eq:'DL = Css × VD, the loading dose as the target concentration times the volume of distribution; the two parts add: {{frac:DL|VD}}e^(−kt) + {{frac:R|kVD}}(1 − e^(−kt)).',
   how:'The bolus part falls as the infusion part rises by the same amount each hour, so their sum stays level when DL equals the steady-state amount.',
   asks:'Why the loading dose is set by VD and the rate by Cl; what a dose that is too high or too low looks like.'},
  {key:'model_oral', module:5, name:'Single oral dose',
   axes:'Time across; concentration up, evenly spaced, no numbers; the peak is marked.',
   inout:'In: first-order absorption from the gut with the rate constant ka, and only the fraction F of the dose reaches the blood. Out: first-order elimination, k. Usually ka is much larger than k.',
   shape:'Starts at zero, rises to the peak concentration Cmax at the time tmax, then falls; later the tail is elimination alone.',
   eq:'Cp = {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)); the time of the peak is tmax = {{frac:ln(ka/k)|ka − k}}.',
   how:'Two exponentials with opposite signs: absorption adds drug faster than elimination removes it until tmax, where the two rates are equal.',
   asks:'Why the curve has a peak; what moves tmax (only ka and k) and what moves Cmax (dose, F, VD and the constants).'},
  {key:'model_mdbolus', module:6, name:'Repeated IV bolus',
   axes:'Time across; concentration up, evenly spaced, no numbers; the dashed curve is the first dose on its own.',
   inout:'In: the same IV bolus dose at every dosing interval τ (tau). Out: first-order elimination, k, between doses.',
   shape:'A saw-tooth: each dose jumps the level up by C0, the concentration one dose produces, and it falls until the next; the peaks and troughs climb less each time until they level off.',
   eq:'Cmax∞ = {{frac:C0|1 − e^(−kτ)}} and Cmin∞ = Cmax∞ e^(−kτ): the steady-state peak and trough (∞ means steady state).',
   how:'Superposition: each dose adds its own C0 e^(−kt) to what is left of the earlier ones. The accumulation factor {{frac:1|1 − e^(−kτ)}} is how much higher the plateau sits than the first dose.',
   asks:'Why the plateau takes 3 to 5 half-lives whatever the dose; the steady-state peak, trough and average.'},
  {key:'model_intermit', module:6, name:'Intermittent IV infusion',
   axes:'Time across; concentration up, evenly spaced, no numbers.',
   inout:'In: a constant rate (zero order) for the length of each infusion, then nothing until the next. Out: first-order elimination, k, the whole time.',
   shape:'A rise during each infusion and a first-order fall after it; each rise starts from what is left of the one before, so it ends higher.',
   eq:'End of one infusion: Cp = {{frac:R|VD k}}(1 − e^(−kt)) with t the infusion time; afterwards each infusion contributes Cend e^(−kt), Cend being its end-of-infusion level, one term per infusion.',
   how:'Each infusion is the Module 3 curve stopped early; the contributions add because elimination is first order.',
   asks:'The level at the end of the first infusion, and a stated time after the end of the second.'},
  {key:'model_mdoral', module:6, name:'Multiple oral doses',
   axes:'Time across; concentration up, evenly spaced, no numbers; the dashed curve is the first dose on its own.',
   inout:'In: first-order absorption (ka) of the fraction F, repeated at every dosing interval τ. Out: first-order elimination, k.',
   shape:'Rounded peaks and troughs climbing to a plateau: the single oral curve repeated every τ and added.',
   eq:'Cmax∞ = {{frac:F D0|VD}}({{frac:1|1 − e^(−kτ)}})e^(−k tmax∞), the steady-state peak; tmax∞ = {{frac:1|ka − k}} ln[{{frac:ka(1 − e^(−kτ))|k(1 − e^(−ka τ))}}], the time of that peak.',
   how:'Superposition of oral curves; the accumulation factor raises the plateau and the steady-state tmax comes earlier than the first-dose tmax because each dose starts on a rising baseline.',
   asks:'Which way the plateau and the peak-to-trough swing move when the dose or the interval changes.'},
  ]},
 {group:'Decide the order or the model from the shape', note:'The shape of the line, read against the axis, names the order or the model.',
  figs:[

  {key:'ord_linear_straight', module:1, name:'Straight line on an evenly spaced axis',
   axes:'Time (hours) across; concentration up, evenly spaced (0, 25, 50, 75, 100).',
   shape:'A straight line falling from 100: the same amount is lost every hour (8 per hour here).',
   eq:'C = C0 − k0 t (zero order).',
   how:'C0 − k0 t is a line: k0 is the slope, the same at every concentration.',
   asks:'Which order? Zero order. The rate constant has concentration-per-time units.'},
  {key:'ord_linear_curve', module:1, name:'Curve on an evenly spaced axis',
   axes:'Time across; concentration up, evenly spaced.',
   shape:'A curve, steep at first and flattening: a smaller amount is lost each hour as the concentration falls.',
   eq:'C = C0 e^(−kt) (first order).',
   how:'e^(−kt) removes the same fraction each hour, so the amount removed shrinks with the concentration.',
   asks:'Which order? First order. On an evenly spaced axis first order curves.'},
  {key:'ord_semilog_straight', module:1, name:'Straight line on a decade axis',
   axes:'Time across; concentration up on an axis marked 1, 10, 100, 1000. Each step is ×10: a log scale, even though it is not labelled "log".',
   shape:'A straight line falling from 200 to 2.3 over 6 hours.',
   eq:'log C = log C0 − {{frac:kt|2.3}}, the log form of C = C0 e^(−kt).',
   how:'Taking the log turns e^(−kt) into a straight line with slope −{{frac:k|2.3}}, so k = −2.3 × slope.',
   asks:'Which order? First order: straight on a decade axis.',
   quote:'if you look at that scale and you see that it is not changing by regular one infinite, or it’s increasing by a a function of 10, then that tells you that it is a logarithmic scale'},
  {key:'ord_semilog_curve', module:1, name:'Bending line on a decade axis',
   axes:'Time across; concentration up on a decade axis (1, 10, 100, 1000).',
   shape:'A line that starts nearly flat and bends more and more steeply downward.',
   eq:'C = C0 − k0 t (zero order), drawn on a log axis.',
   how:'The same amount leaves each hour; near the bottom that fixed amount is a large share of what is left, and on a multiplying axis a large share is a long way down.',
   asks:'Which order? Zero order: on a decade axis, anything but a straight line is not first order.'},
  {key:'cpt_one', module:2, name:'One straight line after an IV bolus',
   axes:'Time across; concentration up on a decade axis.',
   shape:'One straight line from time zero.',
   eq:'Cp = Cp0 e^(−kt): one compartment, first-order elimination.',
   how:'A single exponential is a single straight line on a log axis.',
   asks:'Which model? An IV bolus into one compartment.',
   quote:'If I gave you a graph on a log scale that looks just like the blue line all by itself, that tells you it’s an IV bolus dose one compartment model.'},
  {key:'cpt_two', module:2, name:'Steep start, then a shallower straight line',
   axes:'Time across; concentration up on a decade axis.',
   shape:'A steep early fall (distribution) that turns into a shallower straight line (elimination). The dashed line is the straight part extended back to time zero.',
   eq:'Cp = A e^(−αt) + B e^(−βt); here Cp = 15e^(−3.4t) + 7e^(−0.12t).',
   how:'The α term (3.4 hr⁻¹) dies away within the first hour; after that only the β term (0.12 hr⁻¹) is left, a straight line. The dashed line meets the axis at B = 7.',
   asks:'Which model? Two compartments. The elimination half-life comes from β: t½β = {{frac:0.693|β}}.',
   quote:'if I give you a graph that looks something like this without the red and blue and just a log scale and I’m telling you that it is an IV bolus dose, and I just give you a line that looks like this one, the black line. That should say to you that this is a two compartment model.'},
  {key:'elim_rate_linear', module:4, name:'Rate of elimination rising with concentration',
   axes:'Plasma concentration (mg/L) across; rate of elimination (mg/hr) up.',
   shape:'A straight line through the origin: double the concentration, double the rate.',
   eq:'Rate of elimination = Cl × Cp (first order).',
   how:'Clearance is the slope: (mg/hr) ÷ (mg/L) = L/hr. Here the slope is 2 L/hr, the same at every concentration.',
   asks:'Which order? First order: the rate changes with concentration, the clearance does not.'},
  {key:'elim_rate_flat', module:4, name:'Rate of elimination flat with concentration',
   axes:'Plasma concentration across; rate of elimination up.',
   shape:'A horizontal line: 20 mg/hr whatever the concentration.',
   eq:'Rate = k0 (zero order).',
   how:'A zero-order process removes a fixed amount per hour, so the rate does not depend on how much drug is there.',
   asks:'Which order? Zero order.'},
  {key:'input_types', module:5, name:'IV bolus, oral tablet and IV infusion',
   axes:'Time across; concentration up; no numbers, because only the shape matters.',
   shape:'IV bolus (top): highest at time zero, then falls. Oral tablet (middle): rises to a peak, then falls. IV infusion or controlled release (bottom): rises and levels off, then falls once the input stops.',
   eq:'IV bolus: C0 e^(−kt). Tablet: {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)). Infusion: {{frac:R|kVD}}(1 − e^(−kt)).',
   how:'IV bolus: the whole dose enters at once, so there is no rise. Oral: first-order absorption, so the curve peaks where the rate in equals the rate out. Infusion: a constant rate in, so the curve levels off where R equals the rate out.',
   asks:'Which dosage form, and which input order? Name both from the shape.',
   quote:'if I give you a curve on the exam and it looks like this. where there is a clear peak. we go up, we peak, we come back down, then you, I want you to identify that as an oral input. First order in, first order out.'},
 ]},
 {group:'Read a value off the graph', note:'The graph carries a number: a plateau, a peak, a slope.',
  figs:[
  {key:'inf_css', module:3, name:'An infusion rising to a plateau',
   axes:'Time from the start of the infusion (hours) across; concentration up, evenly spaced.',
   shape:'Rises quickly, then flattens toward 20: the plateau is Css.',
   eq:'C = {{frac:R|Cl}}(1 − e^(−kt)); Css = {{frac:R|Cl}}.',
   how:'As t grows, e^(−kt) goes to 0 and C goes to {{frac:R|Cl}}. Half the plateau at 1 t½, 90% at 3.3 t½, 95% at 4.32 t½.',
   asks:'The plateau value, the rate that gives it (R = Css × Cl), and the time to reach a fraction of it.',
   quote:'Our input is zero order, constant in, first order out. When we stop the in, then it’s just out.'},
  {key:'oral_peak', module:5, name:'One oral dose: rise, peak, fall',
   axes:'Time (hours) across; concentration (mg/L) up, evenly spaced.',
   shape:'Rises, peaks, then falls. The dashed line marks the peak: tmax 2.0 hr, Cmax 12.2 mg/L (500 mg, F 0.85, VD 22 L, ka 0.924, k 0.231 hr⁻¹).',
   eq:'Cp = {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)); tmax = {{frac:ln(ka ÷ k)|ka − k}}.',
   how:'Early, the absorption term e^(−ka t) is large and the level climbs; at tmax the rate in equals the rate out; later only e^(−kt) is left.',
   asks:'tmax and Cmax, and what happens to each when the dose, ka or k changes.',
   quote:'Right at CMax, the rate N is going to be equal to the rate out.'},
  {key:'oral_semilog', module:5, name:'One oral dose on a decade axis',
   axes:'Time across; concentration up on an axis marked 0.1, 1, 10, 100.',
   shape:'Rises to a peak, then the tail becomes a straight line.',
   eq:'Cp = A(e^(−kt) − e^(−ka t)); late, Cp ≈ A e^(−kt).',
   how:'Once absorption is over the e^(−ka t) term is near 0, so the tail is a single exponential: straight on a log axis, with slope −{{frac:k|2.3}}.',
   asks:'The elimination rate constant from the slope of the straight tail.'},
  {key:'rate_vs_constant', module:5, name:'Rate against rate constant',
   axes:'Time (hours) across; amount of drug in the body (mg) up.',
   shape:'Two first-order curves, 200 mg and 100 mg. Each dotted segment is the slope: the rate leaving, in mg/hr.',
   eq:'Rate = k × amount; k = 0.2 per hour for both doses.',
   how:'The 200 mg dose loses 40 mg/hr at first, the 100 mg dose 20 mg/hr; once the larger dose has fallen to 100 mg it also loses 20 mg/hr. Rate ÷ amount is 0.2 at every marked point.',
   asks:'Does doubling the dose change k or the half-life? No: it doubles the rate, not the rate constant.'},
 ]},
 {group:'Compare two curves', note:'One thing is changed; read what moves and what does not.',
  figs:[
  {key:'inf_two_rates', module:3, name:'Two infusion rates of the same drug',
   axes:'Time from the start of the infusion across; concentration up, evenly spaced.',
   shape:'Two curves rising to plateaus of 20 and 40; both reach them at the same time.',
   eq:'Css = {{frac:R|Cl}}; fraction of Css = 1 − e^(−kt).',
   how:'R sits only in front of the bracket, so it scales the plateau; the time course depends on k alone.',
   asks:'Doubling the rate doubles Css and does not change the time to reach it.',
   quote:'changing the rate changes our steady state concentration with me. I feel like I’ve said it 5 times, and I’ve said it 5 times because this is one of those things that I want you to take with you. so I’ve said it 5 times. I’m gonna ask it of you 10 times.'},
  {key:'ka_k_effects', module:5, name:'Doubling the dose, ka, or k',
   axes:'Three panels, each: time across, concentration (mg/L) up. The dashed curve is the unchanged drug (100 mg, ka 1.0, k 0.2 hr⁻¹, AUC 25).',
   shape:'Dose doubled: everything twice as high, same tmax. ka doubled: earlier and higher peak. k doubled: earlier and lower peak.',
   eq:'tmax = {{frac:ln(ka ÷ k)|ka − k}}; Cmax from the oral equation; AUC = {{frac:F D0|k VD}}.',
   how:'The dose only multiplies the equation; ka and k set the shape. AUC has k but not ka in it: 25 → 50 (dose ×2), 25 (ka ×2), 12.5 (k ×2).',
   asks:'For each change: tmax earlier, later or the same; Cmax higher or lower; AUC changed or not.'},
  {key:'k_vs_ka', module:5, name:'Raising k against raising ka',
   axes:'Two panels: time across, concentration (µg/mL) up. 100 mg, VD 10 L.',
   shape:'Top: k raised 0.2 → 0.5 hr⁻¹ lowers the whole curve; the shaded area is lost. Bottom: ka raised 0.2 → 0.5 hr⁻¹ peaks earlier and higher; the area gained early is lost later.',
   eq:'AUC = {{frac:F D0|k VD}}.',
   how:'k is in the AUC, so raising k cuts it (50 → 20). ka is not, so raising ka moves the area earlier and leaves the total at 100.',
   asks:'Why AUC follows k and not ka.'},
  {key:'flipflop', module:5, name:'Immediate release against extended release',
   axes:'Time across; concentration up on a log scale; no numbers.',
   shape:'Both curves rise and fall; the immediate-release tail is steep, the extended-release tail shallow.',
   eq:'Cp = A(e^(−kt) − e^(−ka t)). The tail follows whichever constant is smaller.',
   how:'Immediate release: ka > k, so the tail falls with k. Extended release: ka < k, so the tail falls with ka (flip-flop). The drug, and k, are the same.',
   asks:'What the slope of the tail measures, and why it is not always k.'},
  {key:'slide_7a---Bioavailabili_p13', module:7, name:'Three formulations: same area or same peak time',
   axes:'Time across; plasma level up, evenly spaced; no numbers, because only the areas and the peak times are compared.',
   shape:'Three curves of one drug. A and B enclose the same area but B peaks later; A and C peak at the same time but C encloses half the area of A (AUC A = AUC B, AUC C = 0.5 AUC A). Her drawn curve D sits close to A in both.',
   eq:'F(rel) = {{frac:AUC of A|AUC of B}} × {{frac:dose of B|dose of A}}; the peak time is read from the curve, not from F.',
   how:'The area measures extent and the peak time measures rate. A relative F compares only the areas, so A and B would give F(rel) = 1 and still not be bioequivalent, because B peaks later.',
   asks:'Which pair shares an AUC, which pair shares a peak time, and which curve could be called bioequivalent to A: her D, similar in both, not identical in either.',
   quote:'Formulation A and Formulation B have similar AUCs. OK, but they clearly peak at different times.'},
 ]},
 {group:'Her examples, step by step', note:'One of her worked problems per dosing model, drawn one step at a time. Next advances a step; the caption under the figure carries that step\'s arithmetic, each line on its own.',
  figs:[
  {key:'bolus1_steps', module:2, name:'One-compartment IV bolus, from her data to every answer',
   axes:'Time (hours) across; concentration (mg/L) up on a log axis, marked 0.1, 1, 10. Her IV Bolus Practice 1: a 50 mg IV bolus and six measured concentrations.',
   inout:'In: the whole 50 mg at once. Out: first-order elimination, the rate constant k, so a fixed fraction leaves each hour.',
   shape:'Six points on a straight line, which on a log axis is the sign of first-order elimination from one compartment.',
   eq:'ln Cp = ln C0 − kt: the slope is −k; C0 = {{frac:D0|VD}}; t½ = {{frac:0.693|k}}; ClT = k × VD.',
   how:'The slope between two points gives k; extending the line to time zero gives C0; the dose over C0 gives VD; k times VD gives clearance; ten half-lives remove 99.9%.',
   asks:'Her eight-part battery in this order: k, t½, C0, a concentration at 15 minutes, VD, ClT, the amount in the body at a stated time, the time for 99.9% to be gone.'},
  {key:'twocpt_steps', module:2, name:'Two-compartment IV bolus: A, B, α and β off her theophylline curve',
   axes:'Time (hours) across; concentration (mg/L) up on a log axis. Her practice slide: Cp = 12e^(−5.8t) + 18e^(−0.16t).',
   inout:'In: the whole dose at once into the central compartment. Drug moves into a tissue compartment and back. Out: first-order elimination from the central compartment.',
   shape:'Steep at first, then one straight line: the distribution term dies out within an hour and the elimination line remains.',
   eq:'Cp = A e^(−αt) + B e^(−βt); C0 = A + B; t½β = {{frac:0.693|β}}.',
   how:'The late straight part is B e^(−βt); subtracting it from the early points (the method of residuals) leaves A e^(−αt).',
   asks:'The concentration at a stated hour, the elimination half-life from β, C0 from A + B, and which phase a part of the curve belongs to.'},
  {key:'infusion_steps', module:3, name:'IV infusion: the climb to steady state, and the fall when it stops',
   axes:'Time (hours) across; concentration (mg/L) up. Her in-class set: 44.35 mg/hr, t½ 5 hr, VD 16 L.',
   inout:'In: a constant rate R in mg/hr, a zero-order input. Out: first-order elimination, k, so the rate out grows until it equals the rate in.',
   shape:'A climb that flattens at the steady-state concentration Css; after the infusion stops, a first-order fall from wherever it had reached.',
   eq:'Cp = {{frac:R|VD k}}(1 − e^(−kt)) during the infusion; Css = {{frac:R|k VD}}; after it stops, Cp = Cstop e^(−kt).',
   how:'(1 − e^(−kt)) is the fraction of Css reached: half after one half-life, 87.5% after three, 96.9% after five. The rate sets the height, the half-life sets the time.',
   asks:'A rate for a target Css; a level at a stated time into the infusion; the level a stated time after it stops.'},
  {key:'loading_steps', module:3, name:'Loading dose with an infusion: why the level is flat from the start',
   axes:'Time (hours) across; concentration (mg/L) up. Her in-class set: a 320 mg loading dose with the 44.35 mg/hr infusion.',
   inout:'In: an IV bolus (the loading dose) at the same moment the constant-rate infusion starts. Out: first-order elimination, k, acting on both.',
   shape:'The bolus part falls, the infusion part climbs, and their sum is a flat line at Css.',
   eq:'DL = Css × VD; Cp = {{frac:DL|VD}}e^(−kt) + {{frac:R|k VD}}(1 − e^(−kt)).',
   how:'With the right loading dose the two terms add to Css at every moment: what the bolus loses each hour the infusion supplies.',
   asks:'The loading dose and the rate together as one recommendation; the level at a stated time after both start; what changes if clearance changes (the rate) and what does not (the loading dose).'},
  {key:'oral_steps', module:5, name:'A single oral dose, from her Example 1 to the peak and beyond',
   axes:'Time (hours) across; concentration (mg/L) up. Her Example 1: 500 mg, F 0.85, VD 22 L, absorption t½ 45 min, elimination t½ 3 hr.',
   inout:'In: first-order absorption with the rate constant ka, of the fraction F of the dose. Out: first-order elimination, k.',
   shape:'Rises while absorption outpaces elimination, peaks at tmax where the two rates are equal, then falls.',
   eq:'Cp = {{frac:F ka D0|VD (ka − k)}}(e^(−kt) − e^(−ka t)); tmax = {{frac:ln(ka ÷ k)|ka − k}}.',
   how:'The curve is the difference of two exponentials with one front factor; the fast one (ka) dies first and leaves the slow one (k) as the tail.',
   asks:'tmax and then Cmax, in that order; VD from a printed front factor; which way the peak moves when the dose, ka or k changes.'},
  {key:'md_bolus_steps', module:6, name:'Repeated IV bolus, dose by dose',
   axes:'Time (hours) across; concentration (mg/L) up. 10 mg/kg every 8 hours, t½ 4 hr, VD 0.25 L/kg, so each dose adds 40 mg/L.',
   shape:'A saw-tooth: each dose jumps up by 40 and falls first order; the peaks climb to 53.3 and the troughs to 13.3, then stop climbing.',
   eq:'Cmax∞ = {{frac:C0|1 − e^(−kτ)}}; Cmin∞ = Cmax∞ e^(−kτ); Cavg∞ = {{frac:FD0|VD k τ}}.',
   how:'Each dose adds C0 to what is left of the earlier ones (superposition); e^(−kτ) = 0.25 is the share left at each dose, so the climb stops at 40 ÷ 0.75 = 53.3.',
   asks:'Peak, trough and average at steady state, the time to get there (3 to 5 half-lives), and the level after the last dose.'},
  {key:'two_infusions_steps', module:6, name:'Two intermittent infusions, stage by stage',
   axes:'Time (hours) across; concentration (mg/L) up. 300 mg over 2 hours at 0 and 6 hours; k 0.15 hr⁻¹, VD 15 L.',
   shape:'Rise during each infusion, first-order fall after it; the second rise starts from what is left of the first.',
   eq:'End of an infusion: C = {{frac:R|kVD}}(1 − e^(−k tinf)); after it: C = Cend e^(−kt).',
   how:'Each infusion reaches 17.28 mg/L on its own; at 12 hours the first gives 3.86 and the second 9.48, which add to 13.34.',
   asks:'The rate, the end-of-infusion level, and the level a stated time after the last infusion.'},
  {key:'md_oral_steps', module:6, name:'Multiple oral doses, dose by dose: her tetracycline example',
   axes:'Time (hours) across; concentration (mg/L) up. Her Example 1: 250 mg every 8 hr, F 0.75, VD 112.5 L, t½ 10 hr, ka 0.9 hr⁻¹.',
   inout:'In: first-order absorption (ka) of the fraction F, repeated every τ = 8 hr. Out: first-order elimination, k.',
   shape:'Rounded peaks and troughs climbing to a plateau over 3 to 5 half-lives; at steady state the peak comes earlier in the interval than it did for the first dose.',
   eq:'Cmax∞ = {{frac:F D0|VD}}({{frac:1|1 − e^(−kτ)}})e^(−k tmax∞); Cmin∞ = {{frac:ka F D0|VD (ka − k)}}({{frac:1|1 − e^(−kτ)}})e^(−kτ); Cavg∞ = {{frac:F D0|VD k τ}}.',
   how:'Superposition: each dose adds the same single-dose curve to what is left. The accumulation factor {{frac:1|1 − e^(−kτ)}} is how much higher the plateau sits than the first dose.',
   asks:'First-dose tmax and Cmax, then the steady-state peak, trough and average; which way a change of dose or interval moves them.'},
  ]},
 {group:'Follow a dosing regimen over time', note:'Doses add on a time line; step through them one at a time.',
  figs:[
  {key:'md_bolus', module:6, name:'Repeated IV bolus, the whole regimen',
   axes:'Same axes and regimen as the step-through above.',
   shape:'Six doses then none. The dashed amber curve is the first dose on its own; the dotted lines are Cmax 53.3, the midpoint 33.3, Cavg 28.9 and Cmin 13.3.',
   eq:'Cavg∞ = {{frac:FD0|VD k τ}} = 28.9 mg/L.',
   how:'The average sits below the midpoint because a first-order fall spends more of each interval at the lower concentrations.',
   asks:'Why Cavg∞ is not the midpoint, {{frac:Cmax∞ + Cmin∞|2}}.'},
  {key:'two_infusions', module:6, name:'Two intermittent infusions, the sum',
   axes:'Same axes and doses as the step-through above.',
   shape:'The blue curve is the plasma concentration; the two amber curves are each infusion on its own.',
   eq:'C(12 hr) = 17.28 e^(−0.15 × 10) + 17.28 e^(−0.15 × 4).',
   how:'Each dose gets its own time measured from the end of that infusion: 10 hours for the first, 4 for the second.',
   asks:'The concentration at a time after the second infusion, by adding the two.'},
 ]},
];
