/* ==========================================================================
   DIAGRAMS: HOW TO READ EACH GRAPH
   ==========================================================================
   The Diagrams tab groups the drawn figures by what she asks a student to do
   with a graph, and gives each one the same five-step walk-through:
     axes   what each axis is and what scale it uses
     shape  what the line does
     eq     the equation that draws it
     how    which part of that equation makes the shape
     asks   what she asks about a graph like this
   `quote` is her own sentence about this kind of graph, taken from the
   question in the bank that already carries it (q6_figures.js).
   Every number is one the figure prints, or one figures.py draws it from.
   Plain strings; {{frac:a|b}} stacks a ratio.
   ========================================================================== */
const DIAGRAM_INTRO = [
  'Read the axis first: an evenly spaced axis and an axis that steps by tens (1, 10, 100) turn the same drug into different shapes.',
  'Then read the line: straight, bending down, rising to a peak, levelling off, or rising and falling in a saw-tooth.',
  'Then name the equation that makes that shape, and the term in it that is responsible.'];
const DIAGRAM_QUOTE = 'you’ve got to pay attention to the axis';

const DIAGRAMS = [
 {group:'Tell the dosing models apart by the curve', own:'models',
  note:'How the drug goes in decides the shape. "First order" means the rate is proportional to how much drug is there (a fixed fraction per hour); "zero order" means a constant rate (a fixed amount per hour). Every model here removes drug by first-order elimination with the rate constant k, the fraction of the drug removed per hour; they differ in the input. A compartment is a space the drug is treated as spread evenly through. One compartment treats the whole body as that single space. Two compartments add a tissue space that the drug enters from the blood and leaves again more slowly. The axes carry no numbers because only the shapes are compared. Modules 4 and 7a add no model: Module 4 is the drug-out side (clearance) that every curve shares, and Module 7a sets the F inside the oral curves.',
  table:[
   ['One-compartment IV bolus (M2)', 'All at once, straight into the blood', 'First order, rate constant k', 'One', 'Starts at its highest point (C0, the concentration at time zero) and falls; one straight line on a log axis', 'A dose "by IV bolus" or "by rapid IV injection" with no absorption; the model is named'],
   ['Two-compartment IV bolus (M2)', 'All at once', 'First order from the central compartment', 'Two: central (blood) and tissue', 'On a log axis, a steep early fall then a shallower straight line', 'A, B, α and β (the two intercepts and two slopes of a two-exponential equation), or an equation with two exponential terms; the model is not named'],
   ['IV infusion (M3)', 'Zero order: a constant rate R, in mg/hr', 'First order, k', 'One', 'Starts at zero and climbs to a plateau (Css, the steady-state concentration, where the rate in equals the rate out); falls once the infusion stops', 'A rate in mg/hr, "infused at", "steady-state concentration"'],
   ['Loading dose with an infusion (M3)', 'An IV bolus at the moment the infusion starts', 'First order, k', 'One', 'Flat at Css from the start when the loading dose is right', '"loading dose", "simultaneously", "reach ... immediately"'],
   ['Single oral dose (M5)', 'First order: absorption rate constant ka, and only the fraction F reaches the blood', 'First order, k', 'One', 'Starts at zero, rises to a peak (Cmax at tmax), then falls', 'A capital F, a ka or an absorption half-life, "tablet" or "capsule"'],
   ['Repeated IV bolus (M6)', 'All at once, repeated every τ hours (τ, tau, is the dosing interval, the time between doses)', 'First order, k', 'One', 'A saw-tooth climbing to a plateau in 3 to 5 half-lives (a half-life is the time for the concentration to fall by half, {{frac:0.693|k}})', 'An IV dose "every 8 hours"; steady-state peak, trough or average asked'],
   ['Intermittent IV infusion (M6)', 'Zero order for a set time, repeated', 'First order, k', 'One', 'A rise during each infusion and a fall between; each rise ends higher', 'A dose "over 2 hours" and a second infusion started hours later'],
   ['Multiple oral doses (M6a)', 'First order (ka, F), repeated every τ hours', 'First order, k', 'One', 'Rounded peaks and troughs climbing to a plateau', 'F and ka together with a dosing interval'],
  ],
  figs:[
  {key:'models_all', module:'2 to 6', modules:[2,3,5,6], name:'The eight dosing models side by side',
   axes:'Time across; concentration up, evenly spaced except the two-compartment panel, which is a log axis. No numbers: only the shapes are compared, and every panel uses the same elimination rate constant.',
   shape:'Top to bottom: a fall from time zero (IV bolus); a steep fall then a shallower line (two-compartment, log axis). Then a climb to a plateau (infusion) and a flat line (loading dose with an infusion). Then a rise to a peak then a fall (single oral dose) and a saw-tooth (repeated IV bolus). Last, a rise during each infusion and a fall between (intermittent infusion), and rounded peaks climbing (multiple oral doses).',
   eq:'One equation per panel; each is under Tell apart, Explain one. The bolus panel uses Cp = C0 e^(−kt), Cp the plasma concentration at time t and C0 the concentration at time zero. The repeated-dose panels use the forms carrying the accumulation factor, {{frac:1|1 − e^(−kτ)}}: how many times higher the steady-state level is than after one dose.',
   how:'How the drug goes in makes the shape: all at once (starts high), at a constant rate (climbs), or first order (rises to a peak). Repeating a dose every τ adds the curves on top of one another until the peaks level off.',
   asks:'Which model a described regimen or a sketched curve belongs to, and which equation that model uses.'},
  {key:'model_bolus1', module:2, name:'One-compartment IV bolus',
   axes:'Time across; concentration up, evenly spaced, no numbers.',
   inout:'In: the whole dose at once, straight into the blood. Out: first-order elimination with the rate constant k, so a fixed fraction of what is there leaves each hour.',
   shape:'Highest at time zero, at C0, the concentration the dose produces the moment it is spread through the body; then a curve falling and flattening. On a log axis the same curve is one straight line.',
   eq:'Cp = C0 e^(−kt), where Cp is the plasma concentration at time t and C0 = {{frac:D0|VD}}, the dose over the apparent volume of distribution.',
   how:'All of the dose is in the body at time zero, so the curve starts at its highest point; e^(−kt) removes the same fraction each hour.',
   asks:'Which model a curve that starts high and falls belongs to; k from two points; C0 by back-extrapolation. Back-extrapolation extends the straight line on the log axis back to time zero and reads the concentration there.'},
  {key:'model_bolus2', module:2, name:'Two-compartment IV bolus',
   axes:'Time across; concentration up on a log axis, no numbers.',
   inout:'In: the whole dose at once into the central compartment, the blood and the organs it reaches quickly. Drug then moves into a tissue compartment and back. Out: first-order elimination from the central compartment.',
   shape:'A steep early fall (distribution into tissue) that turns into a shallower straight line (elimination).',
   eq:'Cp = A e^(−αt) + B e^(−βt): two exponential terms, A and B the intercepts in concentration units, α and β the two slopes in reciprocal time.',
   how:'Two exponentials: the α term dies away quickly and leaves the β line. β, the smaller constant, sets the terminal half-life: the time for the concentration to fall by half once the steep early phase is over.',
   asks:'Why the log plot is not one straight line; which phase is distribution and which is elimination; the half-life t½ = {{frac:0.693|β}}.'},
  {key:'model_infusion', module:3, name:'IV infusion, one compartment',
   axes:'Time across; concentration up, evenly spaced, no numbers. A dashed line marks Css, the steady-state concentration the curve levels off at; a dashed vertical marks the moment the infusion stops.',
   inout:'In: a constant rate R in mg/hr, which is a zero-order input. Out: first-order elimination, k. The rate out grows as the concentration grows, until it equals the rate in.',
   shape:'Starts at zero, climbs quickly, levels off at Css, the steady-state concentration where rate in equals rate out; falls by first-order elimination once the infusion stops.',
   eq:'Cp, the plasma concentration, = {{frac:R|Cl}}(1 − e^(−kt)) during the infusion, Cl being the clearance, the volume of plasma cleared of drug per hour. Css = {{frac:R|Cl}}. After it stops, Cp = Cstop e^(−kt), where Cstop is the level at the moment it stopped.',
   how:'Constant rate in against a rate out that grows with the concentration: the two meet at Css. (1 − e^(−kt)) is the fraction of Css reached.',
   asks:'What sets the height of the plateau (R and Cl) and what sets the time to reach it (k only).'},
  {key:'model_loading', module:3, name:'Loading dose with an infusion',
   axes:'Time across; concentration up, evenly spaced, no numbers.',
   inout:'In: an IV bolus (the loading dose, DL) at the same moment a constant-rate infusion starts. Out: first-order elimination, k, acting on both.',
   shape:'A flat line at Css, the steady-state concentration, from the start. The dashed amber curve is the infusion alone, climbing to the same level.',
   eq:'DL = Css × VD, the loading dose as the target concentration times the volume of distribution. The two parts add: {{frac:DL|VD}}e^(−kt) + {{frac:R|kVD}}(1 − e^(−kt)), R being the infusion rate in mg/hr.',
   how:'The bolus part falls as the infusion part rises by the same amount each hour, so their sum stays level when DL equals the steady-state amount.',
   asks:'Why the loading dose is set by VD and the rate by Cl, the clearance, the volume of plasma cleared of drug per hour. What a dose that is too high or too low looks like.'},
  {key:'model_oral', module:5, name:'Single oral dose',
   axes:'Time across; concentration up, evenly spaced, no numbers; the peak is marked.',
   inout:'In: first-order absorption from the gut with the rate constant ka, and only the fraction F of the dose reaches the blood. Out: first-order elimination, k. Usually ka is much larger than k.',
   shape:'Starts at zero, rises to the peak concentration Cmax at the time tmax, then falls; later the tail is elimination alone.',
   eq:'Cp, the plasma concentration, = {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)), D0 the dose. VD is the apparent volume of distribution: the volume the dose would have to be dissolved in to give the measured concentration. The time of the peak is tmax = {{frac:ln(ka ÷ k)|ka − k}}.',
   how:'Two exponentials with opposite signs: absorption adds drug faster than elimination removes it until tmax, where the two rates are equal.',
   asks:'Why the curve has a peak; what moves tmax (only ka and k) and what moves Cmax (dose, F, VD and the constants).'},
  {key:'model_mdbolus', module:6, name:'Repeated IV bolus',
   axes:'Time across; concentration up, evenly spaced, no numbers; the dashed curve is the first dose on its own.',
   inout:'In: the same IV bolus dose at every dosing interval τ (tau). Out: first-order elimination, k, between doses.',
   shape:'A saw-tooth: each dose jumps the level up by C0, the concentration one dose produces, and it falls until the next. The peaks and troughs climb less each time until they level off.',
   eq:'Cmax∞ = {{frac:C0|1 − e^(−kτ)}} and Cmin∞ = Cmax∞ e^(−kτ): the steady-state peak and trough. ∞ means steady state, the plateau where each dose only replaces what was lost since the last.',
   how:'Superposition: each dose adds its own C0 e^(−kt) to what is left of the earlier ones. The accumulation factor {{frac:1|1 − e^(−kτ)}} is how much higher the plateau sits than the first dose.',
   asks:'Why the plateau takes 3 to 5 half-lives whatever the dose; a half-life is the time for the concentration to fall by half, {{frac:0.693|k}}. The steady-state peak, trough and average.'},
  {key:'model_intermit', module:6, name:'Intermittent IV infusion',
   axes:'Time across; concentration up, evenly spaced, no numbers.',
   inout:'In: a constant rate (zero order) for the length of each infusion, then nothing until the next. Out: first-order elimination, k, the whole time.',
   shape:'A rise during each infusion and a first-order fall after it; each rise starts from what is left of the one before, so it ends higher.',
   eq:'End of one infusion: Cp, the plasma concentration, = {{frac:R|VD k}}(1 − e^(−kt)), with t the infusion time. R is the infusion rate in mg/hr and VD the apparent volume of distribution. Afterwards each infusion contributes Cend e^(−kt), Cend being its end-of-infusion level, one term per infusion.',
   how:'Each infusion is the single constant-rate infusion curve (Module 3), a climb towards a plateau, stopped early; the contributions add because elimination is first order.',
   asks:'The level at the end of the first infusion, and a stated time after the end of the second.'},
  {key:'model_mdoral', module:6, name:'Multiple oral doses',
   axes:'Time across; concentration up, evenly spaced, no numbers; the dashed curve is the first dose on its own.',
   inout:'In: first-order absorption (ka) of the fraction F, repeated at every dosing interval τ. Out: first-order elimination, k.',
   shape:'Rounded peaks and troughs climbing to a plateau: the single oral curve repeated every τ and added.',
   eq:'Cmax∞ = {{frac:F D0|VD}}({{frac:1|1 − e^(−kτ)}})e^(−k tmax∞), the steady-state peak; ∞ means steady state, D0 is the dose and VD the apparent volume of distribution. tmax∞ = {{frac:1|ka − k}} ln[{{frac:ka(1 − e^(−kτ))|k(1 − e^(−ka τ))}}], the time of that peak.',
   how:'Superposition of oral curves: the curve of each dose adds to what is left of the earlier ones. The accumulation factor, {{frac:1|1 − e^(−kτ)}}, how many times higher the plateau is than one dose, raises the plateau. The steady-state tmax comes earlier than the first-dose tmax because each dose starts on a rising baseline.',
   asks:'Which way the plateau and the peak-to-trough swing move when the dose or the interval changes.'},
  ]},
 {group:'Decide the order or the model from the shape', note:'The shape of the line, read against the axis, names the order or the model.',
  figs:[

  {key:'ord_linear_straight', module:1, name:'Straight line on an evenly spaced axis',
   axes:'Time (hours) across; concentration up, evenly spaced (0, 25, 50, 75, 100).',
   shape:'A straight line falling from 100: the same amount is lost every hour (8 per hour here).',
   eq:'C = C0 − k0 t (zero order: a fixed amount lost per hour whatever the concentration). C is the concentration at time t, C0 the concentration at time zero and k0 the zero-order rate constant, the amount lost per hour.',
   how:'C0 − k0 t is a line: k0 is the slope, the same at every concentration.',
   asks:'Which order? Zero order. The rate constant has concentration-per-time units.'},
  {key:'ord_linear_curve', module:1, name:'Curve on an evenly spaced axis',
   axes:'Time across; concentration up, evenly spaced.',
   shape:'A curve, steep at first and flattening: a smaller amount is lost each hour as the concentration falls.',
   eq:'C = C0 e^(−kt) (first order: a fixed fraction lost per hour, so the rate is proportional to how much is there). C is the concentration at time t, C0 the concentration at time zero and k the elimination rate constant, the fraction lost per hour.',
   how:'e^(−kt) removes the same fraction each hour, so the amount removed shrinks with the concentration.',
   asks:'Which order? First order. On an evenly spaced axis first order curves.'},
  {key:'ord_semilog_straight', module:1, name:'Straight line on a decade axis',
   axes:'Time across; concentration up on an axis marked 1, 10, 100, 1000. Each step is ×10: a log scale, even though it is not labelled "log".',
   shape:'A straight line falling from 200 to 2.3 over 6 hours.',
   eq:'log C = log C0 − {{frac:kt|2.3}}, the log form of the first-order equation C = C0 e^(−kt) (first order: a fixed fraction lost per hour). C0 is the concentration at time zero and k the elimination rate constant, the fraction lost per hour. 2.3 is the conversion between natural and base-10 logs.',
   how:'Taking the log turns e^(−kt) into a straight line with slope −{{frac:k|2.3}}, so k = −2.3 × slope.',
   asks:'Which order? First order: straight on a decade axis.',
   quote:'if you look at that scale and you see that it is not changing by regular one infinite, or it’s increasing by a a function of 10, then that tells you that it is a logarithmic scale'},
  {key:'ord_semilog_curve', module:1, name:'Bending line on a decade axis',
   axes:'Time across; concentration up on a decade axis (1, 10, 100, 1000).',
   shape:'A line that starts nearly flat and bends more and more steeply downward.',
   eq:'C = C0 − k0 t (zero order: a fixed amount lost per hour), drawn on a log axis. C0 is the concentration at time zero and k0 the zero-order rate constant, the amount lost per hour.',
   how:'The same amount leaves each hour. Near the bottom that fixed amount is a large share of what is left, and on a multiplying axis a large share is a long way down.',
   asks:'Which order? Zero order: on a decade axis, anything but a straight line is not first order.'},
  {key:'cpt_one', module:2, name:'One straight line after an IV bolus',
   axes:'Time across; concentration up on a decade axis, marked 1, 10, 100: each step is ten times the last, a log scale.',
   shape:'One straight line from time zero.',
   eq:'Cp = Cp0 e^(−kt): Cp the plasma concentration at time t, Cp0 its value at time zero, k the elimination rate constant, the fraction lost per hour. One compartment (the whole body treated as one evenly mixed space), first-order elimination (a fixed fraction lost per hour).',
   how:'A single exponential is a single straight line on a log axis.',
   asks:'Which model? An IV bolus into one compartment.',
   quote:'If I gave you a graph on a log scale that looks just like the blue line all by itself, that tells you it’s an IV bolus dose one compartment model.'},
  {key:'cpt_two', module:2, name:'Steep start, then a shallower straight line',
   axes:'Time across; concentration up on a decade axis, marked 1, 10, 100: each step is ten times the last, a log scale.',
   shape:'A steep early fall (distribution: drug moving out of the blood into tissue) that turns into a shallower straight line (elimination: drug leaving the body). The dashed line is the straight part extended back to time zero.',
   eq:'Cp = A e^(−αt) + B e^(−βt): Cp the plasma concentration, A and B the two intercepts in concentration units, α and β the two slopes in reciprocal time. α belongs to the steep distribution phase and β to the shallower elimination phase. Here Cp = 15e^(−3.4t) + 7e^(−0.12t).',
   how:'The α term (3.4 hr⁻¹) dies away within the first hour; after that only the β term (0.12 hr⁻¹) is left, a straight line. The dashed line meets the axis at B = 7.',
   asks:'Which model? Two compartments: the blood plus a tissue space the drug enters and leaves more slowly. The elimination half-life comes from β: t½β = {{frac:0.693|β}}. It is the time for the concentration to fall by half once the steep phase is over.',
   quote:'if I give you a graph that looks something like this without the red and blue and just a log scale and I’m telling you that it is an IV bolus dose, and I just give you a line that looks like this one, the black line. That should say to you that this is a two compartment model.'},
  {key:'elim_rate_linear', module:4, name:'Rate of elimination rising with concentration',
   axes:'Plasma concentration (mg/L) across; rate of elimination (mg/hr) up.',
   shape:'A straight line through the origin: double the concentration, double the rate.',
   eq:'Rate of elimination = Cl × Cp (first order: the rate is proportional to the concentration). Cl is the clearance, the volume of plasma cleared of drug per hour, and Cp the plasma concentration.',
   how:'Clearance is the slope: (mg/hr) ÷ (mg/L) = L/hr. Here the slope is 2 L/hr, the same at every concentration.',
   asks:'Which order? First order: the rate changes with concentration, the clearance does not.'},
  {key:'elim_rate_flat', module:4, name:'Rate of elimination flat with concentration',
   axes:'Plasma concentration across; rate of elimination up.',
   shape:'A horizontal line: 20 mg/hr whatever the concentration.',
   eq:'Rate = k0 (zero order), k0 being the zero-order rate constant, a fixed amount removed per hour.',
   how:'A zero-order process removes a fixed amount per hour, so the rate does not depend on how much drug is there.',
   asks:'Which order? Zero order.'},
  {key:'input_types', module:5, name:'IV bolus, oral tablet and IV infusion',
   axes:'Time across; concentration up; no numbers, because only the shape matters.',
   shape:'IV bolus (top): highest at time zero, then falls. Oral tablet (middle): rises to a peak, then falls. IV infusion or controlled release (bottom): rises and levels off, then falls once the input stops.',
   eq:'IV bolus: C0 e^(−kt), C0 the concentration at time zero and k the elimination rate constant, the fraction lost per hour. Tablet: {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)). F is the fraction of the dose D0 that reaches the blood and VD the apparent volume of distribution. ka is the absorption rate constant: the fraction of the unabsorbed dose entering the blood per hour. Infusion: {{frac:R|kVD}}(1 − e^(−kt)), R the infusion rate in mg/hr.',
   how:'IV bolus: the whole dose enters at once, so there is no rise. Oral: first-order absorption, so the curve peaks where the rate in equals the rate out. Infusion: a constant rate in, so the curve levels off where R equals the rate out.',
   asks:'Which dosage form, and which input order? Name both from the shape.',
   quote:'if I give you a curve on the exam and it looks like this. where there is a clear peak. we go up, we peak, we come back down, then you, I want you to identify that as an oral input. First order in, first order out.'},
 ]},
 {group:'Read a value off the graph', note:'The graph carries a number: a plateau, a peak, a slope.',
  figs:[
  {key:'inf_css', module:3, name:'An infusion rising to a plateau',
   axes:'Time from the start of the infusion (hours) across; concentration up, evenly spaced.',
   shape:'Rises quickly, then flattens toward 20: the plateau is Css.',
   eq:'C = {{frac:R|Cl}}(1 − e^(−kt)), R the infusion rate in mg/hr and Cl the clearance, the volume of plasma cleared of drug per hour. k is the elimination rate constant, the fraction lost per hour. Css = {{frac:R|Cl}}, the steady-state concentration, where the rate in equals the rate out.',
   how:'As t grows, e^(−kt) goes to 0 and C goes to {{frac:R|Cl}}. Half the plateau at 1 t½, 90% at 3.3 t½, 95% at 4.32 t½. t½ is the half-life, the time for the level to fall by half, {{frac:0.693|k}}.',
   asks:'The plateau value, the rate that gives it (R = Css × Cl), and the time to reach a fraction of it.',
   quote:'Our input is zero order, constant in, first order out. When we stop the in, then it’s just out.'},
  {key:'oral_peak', module:5, name:'One oral dose: rise, peak, fall',
   axes:'Time (hours) across; concentration (mg/L) up, evenly spaced.',
   shape:'Rises, peaks, then falls. The dashed line marks the peak: tmax 2.0 hr, the time of the peak, and Cmax 12.2 mg/L, the peak concentration. The inputs: dose D0 500 mg; F 0.85, the fraction of the dose that reaches the blood; VD 22 L, the apparent volume of distribution. ka 0.924 hr⁻¹ is the absorption rate constant; k 0.231 hr⁻¹ is the elimination rate constant, the fraction lost per hour.',
   eq:'Cp = {{frac:F ka D0|VD(ka − k)}}(e^(−kt) − e^(−ka t)); tmax = {{frac:ln(ka ÷ k)|ka − k}}.',
   how:'Early, the absorption term e^(−ka t) is large and the level climbs; at tmax the rate in equals the rate out; later only e^(−kt) is left.',
   asks:'tmax and Cmax, and what happens to each when the dose, ka or k changes.',
   quote:'Right at CMax, the rate N is going to be equal to the rate out.'},
  {key:'oral_semilog', module:5, name:'One oral dose on a decade axis',
   axes:'Time across; concentration up on an axis marked 0.1, 1, 10, 100.',
   shape:'Rises to a peak, then the tail becomes a straight line.',
   eq:'Cp = A(e^(−kt) − e^(−ka t)): Cp the plasma concentration and A the constant in front, {{frac:F ka D0|VD(ka − k)}}, in concentration units. k is the elimination rate constant and ka the absorption rate constant, each the fraction moved per hour. Late, Cp ≈ A e^(−kt).',
   how:'Once absorption is over the e^(−ka t) term is near 0, so the tail is a single exponential. It is straight on a log axis, with slope −{{frac:k|2.3}}, 2.3 being the conversion between natural and base-10 logs.',
   asks:'The elimination rate constant from the slope of the straight tail.'},
  {key:'rate_vs_constant', module:5, name:'Rate against rate constant',
   axes:'Time (hours) across; amount of drug in the body (mg) up.',
   shape:'Two first-order curves, 200 mg and 100 mg. Each dotted segment is the slope: the rate leaving, in mg/hr.',
   eq:'Rate = k × amount, k being the elimination rate constant, the fraction of the amount leaving per hour; k = 0.2 per hour for both doses.',
   how:'The 200 mg dose loses 40 mg/hr at first, the 100 mg dose 20 mg/hr; once the larger dose has fallen to 100 mg it also loses 20 mg/hr. Rate ÷ amount is 0.2 at every marked point.',
   asks:'Does doubling the dose change k or the half-life (the time for the amount to fall by half, {{frac:0.693|k}})? No: it doubles the rate, not the rate constant.'},
 ]},
 {group:'Compare two curves', note:'One thing is changed; read what moves and what does not.',
  figs:[
  {key:'inf_two_rates', module:3, name:'Two infusion rates of the same drug',
   axes:'Time from the start of the infusion across; concentration up, evenly spaced.',
   shape:'Two curves rising to plateaus of 20 and 40; both reach them at the same time.',
   eq:'Css, the steady-state concentration, is the plateau where the rate in equals the rate out. Css = {{frac:R|Cl}}, R the infusion rate in mg/hr and Cl the clearance, the volume of plasma cleared of drug per hour. Fraction of Css reached = 1 − e^(−kt), k the elimination rate constant, the fraction lost per hour.',
   how:'R sits only in front of the bracket, so it scales the plateau; the time course depends on k alone.',
   asks:'Doubling the rate doubles Css and does not change the time to reach it.',
   quote:'changing the rate changes our steady state concentration with me. I feel like I’ve said it 5 times, and I’ve said it 5 times because this is one of those things that I want you to take with you. so I’ve said it 5 times. I’m gonna ask it of you 10 times.'},
  {key:'ka_k_effects', module:5, name:'Doubling the dose, ka, or k',
   axes:'Three panels, each: time across, concentration (mg/L) up. The dashed curve is the unchanged drug: 100 mg, all of it absorbed (F 1), VD 20 L, ka 1.0 hr⁻¹, k 0.2 hr⁻¹. ka is the absorption rate constant, the fraction of the unabsorbed dose entering the blood per hour; k is the elimination rate constant, the fraction lost per hour. So AUC, the area under the curve, = {{frac:100|0.2 × 20}} = 25.',
   shape:'Dose doubled: everything twice as high, same tmax, the time of the peak. ka doubled: earlier and higher peak. k doubled: earlier and lower peak.',
   eq:'tmax = {{frac:ln(ka ÷ k)|ka − k}}; Cmax, the peak concentration, from the oral equation. AUC = {{frac:F D0|k VD}}, F the fraction of the dose D0 that reaches the blood and VD the apparent volume of distribution.',
   how:'The dose only multiplies the equation; ka and k set the shape. AUC has k but not ka in it: 25 → 50 (dose ×2), 25 (ka ×2), 12.5 (k ×2).',
   asks:'For each change: tmax earlier, later or the same; Cmax higher or lower; AUC changed or not.'},
  {key:'k_vs_ka', module:5, name:'Raising k against raising ka',
   axes:'Two panels: time across, concentration (µg/mL) up. 100 mg, all of it absorbed (F 1), VD 10 L, the apparent volume of distribution. In each panel the constant that is not raised is held at 0.1 hr⁻¹.',
   shape:'Top: k, the elimination rate constant (the fraction lost per hour), raised 0.2 → 0.5 hr⁻¹ lowers the whole curve; the shaded area is lost. Bottom: ka, the absorption rate constant (the fraction of the unabsorbed dose entering the blood per hour), raised 0.2 → 0.5 hr⁻¹ peaks earlier and higher. The area gained early is lost later.',
   eq:'AUC, the area under the concentration-time curve, = {{frac:F D0|k VD}}, F the fraction of the dose D0 that reaches the blood.',
   how:'k is in the AUC, so raising k cuts it: {{frac:100|0.2 × 10}} = 50 → {{frac:100|0.5 × 10}} = 20. ka is not, so raising ka moves the area earlier. The total stays where k = 0.1 hr⁻¹ puts it: {{frac:100|0.1 × 10}} = 100.',
   asks:'Why AUC follows k and not ka.'},
  {key:'flipflop', module:5, name:'Immediate release against extended release',
   axes:'Time across; concentration up on a log scale; no numbers.',
   shape:'Both curves rise and fall; the immediate-release tail is steep, the extended-release tail shallow.',
   eq:'Cp = A(e^(−kt) − e^(−ka t)): Cp the plasma concentration and A the constant in front, in concentration units. k is the elimination rate constant, the fraction of the drug in the body lost per hour. ka is the absorption rate constant, the fraction of the unabsorbed dose entering the blood per hour. The tail follows whichever constant is smaller.',
   how:'Immediate release: ka > k, so the tail falls with k. Extended release: ka < k, so the tail falls with ka (flip-flop). The drug, and k, are the same.',
   asks:'What the slope of the tail measures, and why it is not always k.'},
  {key:'slide_7a---Bioavailabili_p13', module:7, name:'Three formulations: same area or same peak time',
   axes:'Time across; plasma level up, evenly spaced; no numbers, because only the areas and the peak times are compared.',
   shape:'Three curves of one drug. A and B enclose the same area but B peaks later. A and C peak at the same time but C encloses half the area of A. In terms of AUC, the area under the curve: AUC A = AUC B, AUC C = 0.5 AUC A. Her drawn curve D sits close to A in both.',
   eq:'F(rel) is the relative bioavailability: the extent absorbed from A as a fraction of the extent absorbed from B, the reference product. F(rel) = {{frac:AUC of A|AUC of B}} × {{frac:dose of B|dose of A}}; the peak time is read from the curve, not from F.',
   how:'The area measures the extent of absorption, how much of the dose reaches the blood, and the peak time measures its rate. A relative F compares only the areas, so A and B would give F(rel) = 1 and still not be bioequivalent, because B peaks later. Bioequivalent means no significant difference in either the rate or the extent of absorption at the same dose.',
   asks:'Which pair shares an AUC, which pair shares a peak time, and which curve could be called bioequivalent to A: her D, similar in both, not identical in either.',
   quote:'Formulation A and Formulation B have similar AUCs. OK, but they clearly peak at different times.'},
 ]},
 {group:'See the idea behind the arithmetic', note:'Four pictures of the rules the calculations lean on. Each draws arithmetic the course states or a relation the textbook states, and names which.',
  figs:[
  {key:'halflife_ladder', module:'2 to 6', modules:[2,3,4,5,6], name:'The half-life ladder',
   axes:'Half-lives elapsed across (0 to 10); percent up. The top panel is the percent of a dose still in the body, the bottom panel the percent of steady state reached.',
   shape:'Top: bars halving each step, 100, 50, 25, 12.5, 6.25, 3.1, 1.6, down to 0.1 at ten half-lives. Bottom: the mirror image, a curve climbing 50, 75, 87.5, 93.75 and flattening at 100.',
   eq:'Percent left after n half-lives = 100 × 0.5ⁿ. Percent of steady state reached = 100 × (1 − 0.5ⁿ). The marks are the textbook figures: 90% at 3.3 half-lives, 95% at 4.32, 99% at 6.6.',
   how:'Each half-life removes half of what remains, so the bars never reach zero but become too small to matter. The same fraction decides how far an infusion or a repeated-dose regimen has climbed toward its plateau.',
   asks:'How long until 90% (or 95%, or 99%) of steady state; how much of a dose is left after a given number of half-lives; why "3 to 5 half-lives" is the rule of thumb.'},
  {key:'accum_factor', module:6, name:'The accumulation factor against the dosing interval',
   axes:'Dosing interval τ across, measured in half-lives (0.5 to 4); the accumulation factor R up (1 to 4).',
   shape:'A curve falling steeply from R = 3.41 at half a half-life, through R = 2 at one half-life, to 1.33 at two, 1.14 at three and 1.07 at four half-lives.',
   eq:'R = {{frac:1|1 − e^(−kτ)}}, which is the same as {{frac:1|1 − 0.5^(τ ÷ t½)}} because e^(−kτ) is the fraction left after τ. R is how many times higher the steady-state peak is than the first-dose peak.',
   how:'Only k and τ enter, never the dose: the textbook (Shargel, Multiple-Dosage Regimens) states that R is independent of the dose. When τ equals the half-life, half of each dose is still there at the next one, so the plateau is twice the first dose (the dose ratio of 2.0 for a loading dose).',
   asks:'How much a regimen accumulates; what a loading dose should be relative to the maintenance dose when τ equals the half-life; why dosing less often lowers accumulation.'},
  {key:'renal_handling', module:4, name:'How the kidney handles a drug',
   axes:'No axes: a schematic. Blood on the left, the tubule (the fluid that becomes urine) on the right, urine at the bottom.',
   shape:'Two arrows carry drug from blood into the tubule, filtration (passive, unbound drug times GFR) and secretion (active, by a transporter); one arrow, reabsorption, carries drug back to the blood.',
   eq:'Excretion rate = filtration + secretion − reabsorption. Renal clearance = {{frac:excretion rate|Cp}}, in mL/min, compared with GFR, 120 mL/min.',
   how:'Only unbound drug is filtered, so filtration alone can never exceed GFR. A renal clearance above 120 mL/min therefore needs secretion; one below it means some filtered drug returned to the blood.',
   asks:'The probable mechanism of renal excretion from a renal clearance value: above, about, or below 120 mL/min.'},
  {key:'unit_cancel', module:'1 to 6', modules:[1,2,3,4,5,6], name:'Units that cancel',
   axes:'No axes: five of her equations with the units written in, the cancelled unit struck through in amber and the unit of the answer in blue.',
   shape:'hr⁻¹ × L gives L/hr; mg ÷ (mg·hr/L) gives L/hr; mg/L × L/hr gives mg/hr; 1 ÷ hr⁻¹ gives hr; mg ÷ (mg/L) gives L.',
   eq:'Cl = k × VD; Cl = {{frac:Dose|AUC}}; R = Css × Cl; t½ = {{frac:0.693|k}}; VD = {{frac:Dose|C0}}.',
   how:'Carrying the units with the numbers turns each equation into a check: when the leftover unit is not the unit the question asks for, a value was put in the wrong place or not converted (mL against L, minutes against hours).',
   asks:'Every calculation: she requires the unit on the exam answer, and a wrong unit is a wrong answer even when the number is right.'},
 ]},
 {group:'Her examples, step by step', note:'One of her worked problems per dosing model, drawn one step at a time. Next advances a step; the caption under the figure carries that step\'s arithmetic, each line on its own.',
  figs:[
  {key:'auc_steps', module:1, name:'The trapezoidal rule on her data, one strip at a time',
   axes:'Time (hours) across; plasma level (mcg/mL) up, evenly spaced. Her six points: 38.9, 30.3, 18.4, 11.1, 6.77 and 4.10 mcg/mL at 0.5, 1, 2, 3, 4 and 5 hours.',
   shape:'Points joined by straight lines; the band from 2 to 4 hours is the interval asked, and the two shaded strips inside it are the trapezoids.',
   eq:'AUC of one strip = {{frac:C₁ + C₂|2}} × (t₂ − t₁): the average of the two heights times the width. Strip 2 to 3 hr: {{frac:18.4 + 11.1|2}} × 1 = 14.75; strip 3 to 4 hr: {{frac:11.1 + 6.77|2}} × 1 = 8.935; sum 23.685, reported as 23.7 mcg·hr/mL.',
   how:'Only the rows inside the asked interval enter. The 0.5 and 1 hour rows sit before it and the 5 hour row after it, so none of them is used, and no tail beyond the last point is added.',
   asks:'The AUC between two named times from a table; the unit, concentration × time; and which rows to leave out.'},
  {key:'bolus1_steps', module:2, name:'One-compartment IV bolus, from her data to every answer',
   axes:'Time (hours) across; concentration (mg/L) up on a log axis, marked 0.1, 1, 10. Her IV Bolus Practice 1: a 50 mg IV bolus and six measured concentrations.',
   inout:'In: the whole 50 mg at once. Out: first-order elimination, the rate constant k, so a fixed fraction leaves each hour.',
   shape:'Six points on a straight line, which on a log axis is the sign of first-order elimination from one compartment, the whole body treated as one evenly mixed space.',
   eq:'ln Cp = ln C0 − kt, Cp the plasma concentration at time t and C0 the concentration at time zero: the slope is −k. C0 = {{frac:D0|VD}}, the dose D0 over VD, the apparent volume of distribution. t½ = {{frac:0.693|k}}, the half-life, the time for the concentration to fall by half. ClT = k × VD, the total body clearance, the volume of plasma cleared of drug per hour.',
   how:'The slope between two points gives k; extending the line to time zero gives C0; the dose over C0 gives VD; k times VD gives clearance; ten half-lives remove 99.9%.',
   asks:'Her eight-part battery in this order: k, t½, C0, a concentration at 15 minutes, VD, ClT. Then the amount in the body at a stated time, and the time for 99.9% to be gone.'},
  {key:'twocpt_steps', module:2, name:'Two-compartment IV bolus: A, B, α and β off her theophylline curve',
   axes:'Time (hours) across; concentration (mg/L) up on a log axis. Her practice slide: Cp = 12e^(−5.8t) + 18e^(−0.16t).',
   inout:'In: the whole dose at once into the central compartment, the blood and the organs it reaches at once. Drug moves into a tissue compartment, the slower-filling rest of the body, and back. Out: first-order elimination (a fixed fraction lost per hour) from the central compartment.',
   shape:'Steep at first, then one straight line. The distribution term (drug spreading from the blood into tissue) dies out within an hour; the elimination line (drug leaving the body) remains.',
   eq:'Cp = A e^(−αt) + B e^(−βt): Cp the plasma concentration, A and B the two intercepts in concentration units, α and β the two slopes in reciprocal time. α belongs to the steep distribution phase and β to the shallower elimination phase. C0, the concentration at time zero, = A + B. The elimination half-life, the time for the concentration to fall by half once the steep phase is over, is t½β = {{frac:0.693|β}}.',
   how:'The late straight part is B e^(−βt); subtracting it from the early points (the method of residuals) leaves A e^(−αt).',
   asks:'The concentration at a stated hour, the elimination half-life from β, C0 from A + B, and which phase a part of the curve belongs to.'},
  {key:'infusion_steps', module:3, name:'IV infusion: the climb to steady state, and the fall when it stops',
   axes:'Time (hours) across; concentration (mg/L) up. Her in-class set: an infusion at 44.35 mg/hr; t½ 5 hr, the half-life, the time for the concentration to fall by half; VD 16 L, the apparent volume of distribution.',
   inout:'In: a constant rate R in mg/hr, a zero-order input. Out: first-order elimination, k, so the rate out grows until it equals the rate in.',
   shape:'A climb that flattens at the steady-state concentration Css; after the infusion stops, a first-order fall from wherever it had reached.',
   eq:'Cp, the plasma concentration, = {{frac:R|VD k}}(1 − e^(−kt)) during the infusion; Css = {{frac:R|k VD}}. After it stops, Cp = Cstop e^(−kt), Cstop being the level at the moment it stopped and t the time since.',
   how:'(1 − e^(−kt)) is the fraction of Css reached: half after one half-life, 87.5% after three, 96.9% after five. The rate sets the height, the half-life sets the time.',
   asks:'A rate for a target Css; a level at a stated time into the infusion; the level a stated time after it stops.'},
  {key:'loading_steps', module:3, name:'Loading dose with an infusion: why the level is flat from the start',
   axes:'Time (hours) across; concentration (mg/L) up. Her in-class set: a 320 mg loading dose with the 44.35 mg/hr infusion.',
   inout:'In: an IV bolus (the loading dose) at the same moment the constant-rate infusion starts. Out: first-order elimination, k, acting on both.',
   shape:'The bolus part falls, the infusion part climbs, and their sum is a flat line at Css. Css is the steady-state concentration the infusion alone would level off at, where the rate in equals the rate out.',
   eq:'DL, the loading dose, = Css × VD, VD the apparent volume of distribution. Cp, the plasma concentration, = {{frac:DL|VD}}e^(−kt) + {{frac:R|k VD}}(1 − e^(−kt)), R the infusion rate in mg/hr.',
   how:'With the right loading dose the two terms add to Css at every moment: what the bolus loses each hour the infusion supplies.',
   asks:'The loading dose and the rate together as one recommendation; the level at a stated time after both start. What changes if clearance, the volume of plasma cleared of drug per hour, changes (the rate) and what does not (the loading dose).'},
  {key:'oral_steps', module:5, name:'A single oral dose, from her Example 1 to the peak and beyond',
   axes:'Time (hours) across; concentration (mg/L) up. Her Example 1: 500 mg; F 0.85, the fraction of the dose that reaches the blood; VD 22 L, the apparent volume of distribution. Absorption t½ 45 min and elimination t½ 3 hr: each half-life is the time for that process to get through half of what is left.',
   inout:'In: first-order absorption with the rate constant ka, of the fraction F of the dose. Out: first-order elimination, k.',
   shape:'Rises while absorption outpaces elimination, peaks at tmax where the two rates are equal, then falls.',
   eq:'Cp, the plasma concentration, = {{frac:F ka D0|VD (ka − k)}}(e^(−kt) − e^(−ka t)), D0 the dose; tmax = {{frac:ln(ka ÷ k)|ka − k}}.',
   how:'The curve is the difference of two exponentials with one front factor; the fast one (ka) dies first and leaves the slow one (k) as the tail.',
   asks:'tmax and then Cmax, the peak concentration, in that order; VD from a printed front factor; which way the peak moves when the dose, ka or k changes.'},
  {key:'md_bolus_steps', module:6, name:'Repeated IV bolus, dose by dose',
   axes:'Time (hours) across; concentration (mg/L) up. 10 mg/kg every 8 hours. t½ 4 hr is the half-life, the time for the concentration to fall by half; VD 0.25 L/kg is the apparent volume of distribution. So each dose adds C0 = {{frac:10 mg/kg|0.25 L/kg}} = 40 mg/L.',
   shape:'A saw-tooth: each dose jumps up by 40 and falls first order (a fixed fraction lost per hour, so the level halves every 4 hours). The peaks climb to 53.3 and the troughs to 13.3, then stop climbing.',
   eq:'Cmax∞ = {{frac:C0|1 − e^(−kτ)}}, the steady-state peak; ∞ means steady state. C0 is the 40 mg/L one dose adds; k is the elimination rate constant, {{frac:0.693|t½}} = 0.173 hr⁻¹; τ is the dosing interval, 8 hr. Cmin∞ = Cmax∞ e^(−kτ), the steady-state trough. Cavg∞ = {{frac:FD0|VD k τ}}, the average over one interval at steady state, F the fraction of the dose D0 that reaches the blood, 1 for an IV dose.',
   how:'Each dose adds C0 to what is left of the earlier ones (superposition). e^(−kτ) = 0.25 is the share left at each dose, so the climb stops at 40 ÷ 0.75 = 53.3.',
   asks:'Peak, trough and average at steady state, the time to get there (3 to 5 half-lives), and the level after the last dose.'},
  {key:'two_infusions_steps', module:6, name:'Two intermittent infusions, stage by stage',
   axes:'Time (hours) across; concentration (mg/L) up. 300 mg over 2 hours at 0 and 6 hours. k 0.15 hr⁻¹ is the elimination rate constant, the fraction lost per hour; VD 15 L is the apparent volume of distribution.',
   shape:'Rise during each infusion, first-order fall (a fixed fraction lost per hour) after it; the second rise starts from what is left of the first.',
   eq:'End of an infusion: C = {{frac:R|kVD}}(1 − e^(−k tinf)). R is the infusion rate, dose over infusion time = {{frac:300 mg|2 hr}} = 150 mg/hr; tinf is the length of the infusion, 2 hr. After it: C = Cend e^(−kt), Cend the level at the end of that infusion and t the time since it ended.',
   how:'Each infusion reaches {{frac:150|0.15 × 15}}(1 − e^(−0.15 × 2)) = 17.28 mg/L on its own. At 12 hours the first, 10 hours after it ended, gives 17.28 e^(−0.15 × 10) = 3.86. The second, 4 hours after it ended, gives 17.28 e^(−0.15 × 4) = 9.48; the two add to 13.34.',
   asks:'The rate, the end-of-infusion level, and the level a stated time after the last infusion.'},
  {key:'md_oral_steps', module:6, name:'Multiple oral doses, dose by dose: her tetracycline example',
   axes:'Time (hours) across; concentration (mg/L) up. Her Example 1: 250 mg every 8 hr; F 0.75, the fraction of each dose that reaches the blood; VD 112.5 L, the apparent volume of distribution. t½ 10 hr is the elimination half-life, the time for the concentration to fall by half. ka 0.9 hr⁻¹ is the absorption rate constant, the fraction of the unabsorbed dose entering the blood per hour.',
   inout:'In: first-order absorption (ka) of the fraction F, repeated every τ = 8 hr. Out: first-order elimination, k.',
   shape:'Rounded peaks and troughs climbing to a plateau over 3 to 5 half-lives. At steady state (the plateau, where each dose only replaces what was lost since the last) the peak comes earlier in the interval than it did for the first dose.',
   eq:'Cmax∞ = {{frac:F D0|VD}}({{frac:1|1 − e^(−kτ)}})e^(−k tmax∞), the steady-state peak; ∞ means steady state, D0 is the dose and tmax∞ the time of the steady-state peak after a dose. Cmin∞ = {{frac:ka F D0|VD (ka − k)}}({{frac:1|1 − e^(−kτ)}})e^(−kτ), the steady-state trough. Cavg∞ = {{frac:F D0|VD k τ}}, the average over one interval at steady state.',
   how:'Superposition: each dose adds the same single-dose curve to what is left. The accumulation factor {{frac:1|1 − e^(−kτ)}} is how much higher the plateau sits than the first dose.',
   asks:'First-dose tmax and Cmax, then the steady-state peak, trough and average; which way a change of dose or interval moves them.'},
  ]},
 {group:'Follow a dosing regimen over time', note:'Doses add on a time line; step through them one at a time.',
  figs:[
  {key:'md_bolus', module:6, name:'Repeated IV bolus, the whole regimen',
   axes:'Time (hours) across; concentration (mg/L) up. Six doses of 10 mg/kg every 8 hours, then none. t½ 4 hr is the half-life, the time for the concentration to fall by half; VD 0.25 L/kg is the apparent volume of distribution. So each dose adds C0 = {{frac:10 mg/kg|0.25 L/kg}} = 40 mg/L.',
   shape:'Six doses then none. The dashed amber curve is the first dose on its own. The dotted lines: the steady-state peak Cmax 53.3; the midpoint 33.3, halfway between peak and trough, {{frac:53.3 + 13.3|2}}. Also the average over one dosing interval Cavg 28.9, and the trough Cmin 13.3.',
   eq:'Cavg∞ = {{frac:FD0|VD k τ}} = {{frac:1 × 10 mg/kg|0.25 L/kg × 0.173 hr⁻¹ × 8 hr}} = 28.9 mg/L; ∞ marks steady state. F = 1 is the fraction of the dose D0 that reaches the blood for an IV dose. k = {{frac:0.693|4 hr}} = 0.173 hr⁻¹ is the elimination rate constant; τ = 8 hr is the dosing interval.',
   how:'The average sits below the midpoint. A first-order fall (a fixed fraction lost per hour) is fast at first and slower as the level drops, so it spends more of each interval at the lower concentrations.',
   asks:'Why Cavg∞ is not the midpoint, {{frac:Cmax∞ + Cmin∞|2}}.'},
  {key:'dose_interval', module:6, name:'A larger dose against a shorter interval, at steady state',
   axes:'Time within steady state (hours) across; concentration (mg/L) up, the same scale in all three panels so the heights compare directly.',
   shape:'Top: her Example 1, each dose adding C0 = 40 mg/L every 8 hours, t½ 4 hours: Cmax 53.3, Cmin 13.3, Cavg 28.9. Middle: the same dose every 4 hours: 80.0, 40.0, 57.7. Bottom: double the dose every 8 hours: 106.7, 26.7, 57.7.',
   eq:'Cmax∞ = {{frac:C0|1 − e^(−kτ)}}, Cmin∞ = Cmax∞ e^(−kτ), Cavg∞ = {{frac:C0|kτ}}. The trough as a fraction of the peak is e^(−kτ): 0.25 at τ = 8 hours, 0.5 at τ = 4 hours. The gap Cmax∞ − Cmin∞ is C0.',
   how:'A shorter interval raises all three lines and brings the trough closer to the peak, so the curve is flatter: the gap stays 40 mg/L, but the trough rises from a quarter of the peak to half. A larger dose raises all three lines in proportion and doubles the gap, 40 to 80 mg/L, while the trough stays a quarter of the peak.',
   asks:'Which way Cmax∞, Cmin∞, Cavg∞ and the peak-to-trough fluctuation move when the dose or the interval changes.'},
  {key:'two_infusions', module:6, name:'Two intermittent infusions, the sum',
   axes:'Time (hours) across; concentration (mg/L) up. Two 2-hour infusions of 300 mg, starting at 0 and 6 hours. k 0.15 hr⁻¹ is the elimination rate constant, the fraction lost per hour; VD 15 L is the apparent volume of distribution.',
   shape:'The blue curve is the plasma concentration; the two amber curves are each infusion on its own.',
   eq:'C(12 hr) = 17.28 e^(−0.15 × 10) + 17.28 e^(−0.15 × 4). 17.28 mg/L is the level at the end of each infusion, {{frac:R|kVD}}(1 − e^(−k × 2 hr)). R = {{frac:300 mg|2 hr}} = 150 mg/hr, and 0.15 is k.',
   how:'Each dose gets its own time measured from the end of that infusion: 10 hours for the first, 4 for the second.',
   asks:'The concentration at a time after the second infusion, by adding the two.'},
 ]},
];
