/* ==========================================================================
   EQUATIONS
   ==========================================================================
   The equations this course uses, as structured data, so they can be drilled
   rather than only read. The Reference view is the prose account of the same
   material; this is the same equations in the form a check can be run against.

   SOURCES. Every equation, symbol, unit and condition below is already carried
   by reference.js, which sources each one to BasicPharmacokineticsEquations.pdf
   (the exam equation sheet), one of the five lectured decks, Dr. Mosley's own
   worked solutions in STYLE.md, or her spoken words in TRANSCRIPT_CUES.md.
   Nothing new is asserted here.

   `derive` (only on entries the sheet does not print) says how to reach the
   line from a line that is printed, or that it cannot be reached and has to
   be known.

   `must` marks the five she said out loud she does not put on the equation
   sheet, plus the second ideal-body-weight form. `sheet` records what the
   rendered pages of Basic-Pharmacokinetics-Equations.pdf carry: 'yes' where a
   line prints it, 'no' where she said out loud she does not supply it, and
   'absent' where no line prints it and she never said either way.

   THE SHAPE OF AN ENTRY

     lhs     the left side, as display HTML
     tokens  the right side in the pieces it is built from, in order. The
             right side IS tokens.join(' '), so the reading exercise and the
             building exercise cannot come apart.
     disp    optional: the right side as the slides print it, with a ratio
             written {{frac:numerator|denominator}} so it stacks. Shown in
             the list and after an answer. Where it is absent the right side
             is shown as the pieces joined up. test.js checks it carries the
             same symbols and operators, in the same order, as typed.
     typed   the canonical answer in plain ASCII, which is what a typed answer
             is compared against after both are normalised
     also    other answers that are equally right, not near misses
     lures   wrong pieces for the tray in the building exercise. Each is a
             mistake a student actually makes: an inverted ratio, the rate
             constant where the half-life belongs, the wrong sign.

   test.js checks that lhs and tokens agree with typed under the normaliser, so
   an entry cannot key one thing to a typist and another to a builder, and that
   no lure matches a token of its own equation.

   OMITTED ON PURPOSE. The two Henderson-Hasselbalch forms on
   4---Clearance-and-Elimination.pdf slide 20 are not here. The slide prints
   both; the rendered slide labels pH = pKa + log(ionized/nonionized) for weak
   acids (pKa 3-8) and pH = pKa + log(nonionized/ionized) for weak bases
   (pKa 7.5-10.5). Reference carries them; they are not drilled here.
   ========================================================================== */
const EQUATIONS = [

/* ───────── The ones she said to memorise ───────── */
{id:'thalf-first', module:1, name:'First-order half-life', must:true, sheet:'no',
 lhs:'t&frac12;', tokens:['0.693', '/', 'k'], disp:'{{frac:0.693|k}}', typed:'t1/2 = 0.693/k',
 lures:['&times;', '2.303', '2k'],
 symbols:[['k', 'first-order elimination rate constant, hr&minus;1'],
          ['t&frac12;', 'half-life, the time for the amount or concentration of drug to fall by one-half; a time and never a reciprocal time']],
 holds:'First order only, where the rate of loss is proportional to the amount of drug remaining. Constant at every concentration, so it does not depend on the dose or on where the concentration started.',
 derive:['Start from the printed first-order line: ln C = ln C<sub>0</sub> &minus; kt.',
   'At one half-life the level is half the start: C = {{frac:C<sub>0</sub>|2}} when t = t&frac12;.',
   'Put that in: ln {{frac:C<sub>0</sub>|2}} = ln C<sub>0</sub> &minus; kt&frac12;, which leaves ln 2 = kt&frac12;.',
   'ln 2 = 0.693, so t&frac12; = {{frac:0.693|k}} and, turned round, k = {{frac:0.693|t&frac12;}}.'],
 use:'Any time a stem gives a half-life and the line wants k, or asks for a half-life from k. She said to know it.',
 cite:'Introduction.pdf slide 19; she names it three times as not on the sheet'},

{id:'cl-k-vd', module:2, name:'Clearance from k and volume of distribution', must:true, sheet:'no',
 lhs:'Cl', tokens:['k', '&times;', 'V<sub>D</sub>'], typed:'Cl = k*VD',
 also:['ClT = k*VD'],
 lures:['/', '0.693', 'C<sub>p</sub>', 'AUC', 'D<sub>0</sub>'],
 symbols:[['Cl', 'clearance, L/hr'], ['k', 'first-order elimination rate constant, the fraction of drug removed per hour, hr&minus;1'], ['V<sub>D</sub>', 'apparent volume of distribution, L: the hypothetical volume of body fluid that links the amount of drug in the body to the measured plasma concentration']],
 holds:'First-order elimination, where the rate of loss is proportional to the amount of drug remaining. Clearance is the volume of plasma cleared of drug per unit time, and it stays constant while the elimination rate does not.',
 derive:['Printed: rate of elimination = Cl &times; C<sub>p</sub>.',
   'First-order elimination is also k times the amount in the body: rate = k &times; D<sub>B</sub>.',
   'Printed: C<sub>p</sub> = {{frac:D<sub>B</sub>|V<sub>D</sub>}}, so D<sub>B</sub> = V<sub>D</sub> &times; C<sub>p</sub> and rate = k &times; V<sub>D</sub> &times; C<sub>p</sub>.',
   'Set the two rates equal and cancel C<sub>p</sub>: Cl = k &times; V<sub>D</sub>.'],
 use:'When a stem gives clearance and volume and the line wants k, as k = {{frac:Cl|V<sub>D</sub>}}, or gives k and volume and asks for clearance. She said to know it.',
 cite:'2IVBolusAdministration.pdf, slide "Clearance"; she names it as not on the sheet'},

{id:'cp-db-vd', module:2, name:'Concentration, amount and volume', must:true, sheet:'yes',
 lhs:'C<sub>p</sub>', tokens:['D<sub>B</sub>', '/', 'V<sub>D</sub>'], disp:'{{frac:D<sub>B</sub>|V<sub>D</sub>}}', typed:'Cp = DB/VD',
 also:['Cp = D/VD'],
 lures:['&times;', 'k', 'AUC'],
 symbols:[['C<sub>p</sub>', 'plasma concentration, mg/L'],
          ['D<sub>B</sub>', 'amount of drug in the body at that time, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L: the hypothetical volume of body fluid that links the amount of drug in the body to the measured plasma concentration']],
 holds:'One compartment, meaning the body is treated as a single uniform volume, at any time. At time zero the amount in the body is the dose D<sub>0</sub> and the concentration is C<sub>0</sub>, the plasma concentration at time zero. That is what gives V<sub>D</sub> = {{frac:D<sub>0</sub>|C<sub>0</sub>}}.',
 cite:'2IVBolusAdministration.pdf, slide "Volume of Distribution". She names it as one to know; the sheet carries it too, and both readings stand.'},

{id:'crcl', module:4, name:'Cockcroft-Gault creatinine clearance', must:true, sheet:'no',
 lhs:'CrCl', tokens:['(140 &minus; age)', '(IBW)', '/', '(72', '&times;', 'S<sub>Cr</sub>)'],
 disp:'{{frac:(140 &minus; age)(IBW)|72 &times; S<sub>Cr</sub>}}', typed:'CrCl = (140-age)(IBW)/(72*SCr)',
 also:['CrCl = (140-age)(IBW)/(72*SCr)*0.85', 'CrCl = ((140-age)(IBW)/(72*SCr))*0.85'],
 lures:['(140 + age)', 'age)', '(S<sub>Cr</sub>)', '0.85'],
 symbols:[['age', 'years'], ['IBW', 'ideal body weight, kg: the weight from the height formula, used in place of the patient&rsquo;s actual weight'],
          ['S<sub>Cr</sub>', 'serum creatinine, mg/dL'], ['CrCl', 'creatinine clearance, an estimate of the patient&rsquo;s kidney function; reported in mL/min']],
 holds:'Multiply by 0.85 for a female patient. The answer is reported in mL/min even though the units do not cancel algebraically.',
 derive:['Not printed and not reached from a printed line: she requires it from memory.',
   'Work out the ideal body weight first, from the height and sex.',
   'Put age, IBW and the serum creatinine SCr into the line; the result is in mL/min.'],
 use:'When a stem gives age, height, sex and serum creatinine and asks for creatinine clearance, or needs it to judge kidney function.',
 cite:'4---Clearance-and-Elimination.pdf slide 2; "this one is not there. You need to know this one."'},

{id:'ibw-male', module:4, name:'Ideal body weight, male', must:true, sheet:'no',
 lhs:'IBW<sub>male</sub>', tokens:['50', '+', '2.3', '&times;', '(inches over 5 ft)'],
 typed:'IBWmale = 50 + 2.3*(inches over 5 ft)',
 also:['IBW = 50 + 2.3*(height in inches - 60)', 'IBWmale = 50 + 2.3(inches over 5 ft)'],
 lures:['45.5', '&minus;', '2.54', '60', '/'],
 symbols:[['IBW', 'ideal body weight, kg: the weight used in the creatinine clearance (Cockcroft-Gault) calculation in place of the patient&rsquo;s actual weight'], ['inches over 5 ft', 'height in inches minus 60']],
 holds:'Every patient in this course is 5 ft or taller, and ideal body weight is always the weight used in the creatinine clearance calculation, never the actual weight.',
 derive:['Not printed and not derivable: from memory.',
   'Turn the height into inches over 5 ft: 5 ft is 60 inches, so take 60 from the height in inches (1 inch = 2.54 cm).',
   'IBW = 50 kg plus 2.3 kg for each inch over 5 ft.'],
 use:'For a man, inside the Cockcroft-Gault line; the actual body weight is not used there.',
 cite:'4---Clearance-and-Elimination.pdf slide 2; "again, you need to know this one."'},

{id:'ibw-female', module:4, name:'Ideal body weight, female', must:true, sheet:'no',
 lhs:'IBW<sub>female</sub>', tokens:['45.5', '+', '2.3', '&times;', '(inches over 5 ft)'],
 typed:'IBWfemale = 45.5 + 2.3*(inches over 5 ft)',
 also:['IBW = 45.5 + 2.3*(height in inches - 60)', 'IBWfemale = 45.5 + 2.3(inches over 5 ft)'],
 lures:['50', '&minus;', '2.54', '60', '0.85'],
 symbols:[['IBW', 'ideal body weight, kg: the weight used in the creatinine clearance (Cockcroft-Gault) calculation in place of the patient&rsquo;s actual weight'], ['inches over 5 ft', 'height in inches minus 60']],
 holds:'The male form, IBW = 50 + 2.3 &times; (inches over 5 ft), with a different constant. 45.5 is the only difference.',
 derive:['Not printed and not derivable: from memory.',
   'Turn the height into inches over 5 ft, as for a man.',
   'IBW = 45.5 kg plus 2.3 kg for each inch over 5 ft.'],
 use:'For a woman, inside the Cockcroft-Gault line; the actual body weight is not used there.',
 cite:'4---Clearance-and-Elimination.pdf slide 2'},

/* ───────── Module 1 ───────── */
{id:'zero-line', module:1, name:'Zero-order decline', sheet:'yes',
 lhs:'C', tokens:['C<sub>0</sub>', '&minus;', 'kt'], typed:'C = C0 - kt',
 also:['C = C0 - k0t'],
 lures:['+', 'e<sup>&minus;kt</sup>', '&times;', 'ln', '/'],
 symbols:[['C', 'concentration at time t'], ['C<sub>0</sub>', 'starting concentration, at time zero'],
          ['k', 'zero-order rate constant, amount or concentration per time'], ['t', 'elapsed time']],
 holds:'The amount lost per unit time is constant and does not depend on how much is present. A straight line on linear axes.',
 cite:'Introduction.pdf slide 17'},

{id:'first-exp', module:1, name:'First-order decline, exponential form', sheet:'yes',
 lhs:'C', tokens:['C<sub>0</sub>', 'e<sup>&minus;kt</sup>'], typed:'C = C0*e^(-kt)',
 also:['Cp = Cp0*e^(-kt)', 'C = C0e^-kt'],
 lures:['&minus;', 'e<sup>+kt</sup>', 'kt', '/', 'ln'],
 symbols:[['C', 'concentration at time t'], ['C<sub>0</sub>', 'starting concentration, at time zero'],
          ['k', 'first-order rate constant, the fraction removed per hour, hr&minus;1'], ['t', 'elapsed time, hr']],
 holds:'First-order loss. The rate is proportional to what remains. A curve on linear axes and a straight line on semi-logarithmic axes. On semi-logarithmic axes the concentration axis is a base-10 log scale and the time axis is ordinary.',
 cite:'Introduction.pdf slide 18; equation sheet page 1'},

{id:'first-ln', module:1, name:'First-order decline, natural-log form', sheet:'yes',
 lhs:'ln C', tokens:['ln C<sub>0</sub>', '&minus;', 'kt'], typed:'ln C = ln C0 - kt',
 also:['lnC = lnC0 - kt'],
 lures:['+', 'log C<sub>0</sub>', 'kt/2.3', 'e<sup>&minus;kt</sup>'],
 symbols:[['ln', 'natural logarithm'], ['C', 'concentration at time t'], ['C<sub>0</sub>', 'starting concentration, at time zero'],
          ['k', 'first-order rate constant, the fraction removed per hour, hr&minus;1'], ['t', 'elapsed time, hr']],
 holds:'The exponential form of first-order decline, C = C<sub>0</sub>e<sup>&minus;kt</sup>, with natural logarithms taken of both sides. Plotted as ln C against t this is a straight line whose slope is minus k. That slope is what the two-point calculation reads: from two concentrations C<sub>1</sub> and C<sub>2</sub> sampled a time &Delta;t apart, k = {{frac:ln(C<sub>1</sub>/C<sub>2</sub>)|&Delta;t}}.',
 cite:'Introduction.pdf slide 18; equation sheet page 1'},

{id:'first-log', module:1, name:'First-order decline, base-10 log form', sheet:'yes',
 lhs:'log C', tokens:['log C<sub>0</sub>', '&minus;', 'kt', '/', '2.3'], disp:'log C<sub>0</sub> &minus; {{frac:kt|2.3}}', typed:'log C = log C0 - kt/2.3',
 also:['logC = logC0 - kt/2.3', 'log C = log C0 - (k/2.3)t'],
 lures:['ln C<sub>0</sub>', '+', '0.693', '2.303t'],
 symbols:[['log', 'base-10 logarithm'], ['C', 'concentration at time t'], ['C<sub>0</sub>', 'starting concentration, at time zero'],
          ['k', 'first-order rate constant, the fraction removed per hour, hr&minus;1'], ['t', 'elapsed time, hr'],
          ['2.3', 'the conversion between natural and base-10 logarithms']],
 holds:'The first-order line ln C = ln C<sub>0</sub> &minus; kt written with base-10 logarithms, which is what semi-log graph paper uses. Semi-log paper has a base-10 log scale on the concentration axis and an ordinary time axis. The 2.3 is only a conversion factor.',
 cite:'Introduction.pdf slide 18; equation sheet page 1'},

{id:'amount-exp', module:1, name:'First-order decline in amount', sheet:'yes',
 lhs:'D', tokens:['D<sub>0</sub>', 'e<sup>&minus;kt</sup>'], typed:'D = D0*e^(-kt)',
 also:['DB = D0*e^(-kt)', 'D = D0e^-kt'],
 lures:['C<sub>0</sub>', 'V<sub>D</sub>', '/', 'e<sup>+kt</sup>'],
 symbols:[['D', 'amount remaining, mg'], ['D<sub>0</sub>', 'the dose, mg'],
          ['k', 'first-order elimination rate constant, the fraction removed per hour, hr&minus;1'], ['t', 'elapsed time, hr']],
 holds:'The first-order decline C = C<sub>0</sub>e<sup>&minus;kt</sup> written in amount rather than concentration. The two are not mixed in one calculation.',
 cite:'Introduction.pdf slide 18; equation sheet page 1'},

{id:'thalf-zero', module:1, name:'Zero-order half-life', sheet:'absent',
 lhs:'t&frac12;', tokens:['C<sub>0</sub>', '/', '2k'], disp:'{{frac:C<sub>0</sub>|2k}}', typed:'t1/2 = C0/2k',
 also:['t1/2 = C0/(2*k)'],
 lures:['0.693', '&times;', '2C<sub>0</sub>', 'k'],
 symbols:[['t&frac12;', 'half-life, the time for the concentration to fall by one-half'], ['C<sub>0</sub>', 'starting concentration'],
          ['k', 'zero-order rate constant, amount or concentration lost per unit time']],
 holds:'Zero order only, where a fixed amount is lost per unit time whatever the concentration. It depends on C0, so it is not a fixed property of the drug: start lower and the half-life is shorter.',
 derive:['Printed zero-order line: C = C<sub>0</sub> &minus; k<sub>0</sub>t.',
   'At one half-life C = {{frac:C<sub>0</sub>|2}}, so {{frac:C<sub>0</sub>|2}} = C<sub>0</sub> &minus; k<sub>0</sub>t&frac12;.',
   'That leaves k<sub>0</sub>t&frac12; = {{frac:C<sub>0</sub>|2}}, so t&frac12; = {{frac:C<sub>0</sub>|2k<sub>0</sub>}}.'],
 use:'Only for zero order. The half-life then depends on the starting level, so 0.693 does not apply.',
 cite:'Introduction.pdf slide 19'},

{id:'auc-trap', module:1, name:'Trapezoidal rule, one segment', sheet:'yes',
 lhs:'AUC',
 tokens:['[(C<sub>n&minus;1</sub> + C<sub>n</sub>)', '/', '2]', '&times;', '(t<sub>n</sub> &minus; t<sub>n&minus;1</sub>)'],
 disp:'{{frac:C<sub>n&minus;1</sub> + C<sub>n</sub>|2}} &times; (t<sub>n</sub> &minus; t<sub>n&minus;1</sub>)', typed:'AUC = [(Cn-1 + Cn)/2]*(tn - tn-1)',
 also:['AUC = ((Cn-1+Cn)/2)*(tn-tn-1)'],
 lures:['(C<sub>n</sub> &minus; C<sub>n&minus;1</sub>)', '(t<sub>n</sub> + t<sub>n&minus;1</sub>)', '2'],
 symbols:[['AUC', 'area under the concentration-time curve for this segment; units concentration &times; time, e.g. mcg&middot;hr/mL'],
          ['C<sub>n&minus;1</sub>, C<sub>n</sub>', 'the two concentrations bounding the segment'],
          ['t<sub>n&minus;1</sub>, t<sub>n</sub>', 'the times at which those two concentrations were measured, hr']],
 holds:'Any concentration-time data set, any route. The total area is the sum of the segments. Her shorter statement of it is one half base times height.',
 cite:'Introduction.pdf slides 24-25; equation sheet page 1, first line'},

{id:'f-auc', module:1, name:'Bioavailability from two areas', sheet:'yes',
 lhs:'F', tokens:['AUC<sub>oral</sub>', '/', 'AUC<sub>IV</sub>'], disp:'{{frac:AUC<sub>oral</sub>|AUC<sub>IV</sub>}}', typed:'F = AUCoral/AUCiv',
 also:['F = AUCpo/AUCiv'],
 lures:['&times;', 'D<sub>IV</sub>', 'D<sub>po</sub>'],
 symbols:[['F', 'bioavailability, the fraction of the oral dose reaching plasma, no units'],
          ['AUC<sub>oral</sub>, AUC<sub>IV</sub>', 'the area under the concentration-time curve after the oral dose and after the IV dose, in the same units']],
 holds:'Comparing two routes at the same dose. Where the doses differ the exam equation sheet carries the dose-corrected form, F = {{frac:AUC<sub>po</sub>|AUC<sub>IV</sub>}} &times; {{frac:D<sub>IV</sub>|D<sub>po</sub>}}. In it po means oral, AUC<sub>po</sub> and AUC<sub>IV</sub> are the two areas and D<sub>po</sub> and D<sub>IV</sub> are the two doses.',
 cite:'Introduction.pdf slide 23'},

/* ───────── Module 2 ───────── */
{id:'k-sum', module:2, name:'Elimination as metabolism plus excretion', sheet:'absent',
 lhs:'k', tokens:['k<sub>m</sub>', '+', 'k<sub>e</sub>'], typed:'k = km + ke',
 lures:['&minus;', '&times;', 'f<sub>e</sub>', 'k<sub>a</sub>'],
 symbols:[['k<sub>m</sub>', 'rate constant for metabolism'], ['k<sub>e</sub>', 'rate constant for excretion']],
 holds:'Any first-order elimination, where the rate of loss is proportional to the amount of drug remaining. An unsubscripted k is the overall constant with every route wrapped into it.',
 derive:['Printed: f<sub>e</sub> = {{frac:k<sub>e</sub>|k}}, so the excretion constant is k<sub>e</sub> = f<sub>e</sub> &times; k.',
   'The rest of k is metabolism: k<sub>m</sub> = (1 &minus; f<sub>e</sub>) &times; k.',
   'The two parts add back to the whole: k = k<sub>m</sub> + k<sub>e</sub>.'],
 use:'When a stem splits elimination into excretion and metabolism and asks for one of the parts.',
 cite:'2IVBolusAdministration.pdf; her words on what an unsubscripted k means'},

{id:'cl-auc', module:2, name:'Clearance from dose and area', sheet:'yes',
 lhs:'Cl', tokens:['D<sub>0</sub>', '/', 'AUC'], disp:'{{frac:D<sub>0</sub>|AUC}}', typed:'Cl = D0/AUC',
 also:['Cl = FD0/AUC', 'Cl = F*D0/AUC'],
 lures:['&times;', 'k', 'V<sub>D</sub>'],
 symbols:[['Cl', 'clearance, the volume of plasma cleared of drug per unit time, L/hr'], ['D<sub>0</sub>', 'dose, mg'],
          ['AUC', 'area under the concentration-time curve from time zero to infinity, mg&middot;hr/L']],
 holds:'Any route, provided F, the bioavailability (the fraction of the dose that reaches the circulation), is known. With F known the dose on top is written FD<sub>0</sub>; F is 1 for an intravenous dose. This is what relates the dose directly to the exposure, the AUC.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet page 1'},

{id:'thalf-cl-vd', module:2, name:'Half-life from volume and clearance', sheet:'absent',
 lhs:'t&frac12;', tokens:['0.693', 'V<sub>D</sub>', '/', 'Cl<sub>T</sub>'], disp:'{{frac:0.693 V<sub>D</sub>|Cl<sub>T</sub>}}', typed:'t1/2 = 0.693*VD/ClT',
 also:['t1/2 = 0.693VD/Cl'],
 lures:['&times;', 'k', '2.3', 'Cl<sub>R</sub>'],
 symbols:[['t&frac12;', 'half-life, the time for the concentration to fall by one-half, hr'],
          ['V<sub>D</sub>', 'apparent volume of distribution, the hypothetical volume linking the amount in the body to the plasma concentration, L'],
          ['Cl<sub>T</sub>', 'total body clearance, the volume of plasma cleared of drug per unit time, L/hr']],
 holds:'Clearance from k and V<sub>D</sub>, Cl = k &times; V<sub>D</sub>, combined with the first-order half-life, t&frac12; = {{frac:0.693|k}}. Here k is the first-order elimination rate constant. It says which way the half-life moves when clearance falls and the volume does not. That is the question asked when kidney failure lowers clearance.',
 derive:['Two lines she said to know: t&frac12; = {{frac:0.693|k}} and Cl = k &times; V<sub>D</sub>.',
   'Turn the second round for k: k = {{frac:Cl|V<sub>D</sub>}}.',
   'Put that into the first: t&frac12; = {{frac:0.693 V<sub>D</sub>|Cl}}.'],
 use:'When a stem gives clearance and volume and asks for the half-life, or asks how a change in clearance moves it.',
 cite:'4---Clearance-and-Elimination.pdf slide 21'},

{id:'biexp', module:2, name:'Two-compartment concentration', sheet:'yes',
 lhs:'C<sub>p</sub>', tokens:['Ae<sup>&minus;at</sup>', '+', 'Be<sup>&minus;bt</sup>'], typed:'Cp = A*e^(-at) + B*e^(-bt)',
 also:['Cp = Ae^-at + Be^-bt'],
 lures:['&minus;', 'Ae<sup>&minus;bt</sup>', 'Be<sup>&minus;at</sup>', '&times;'],
 symbols:[['C<sub>p</sub>', 'plasma concentration at time t, mg/L'], ['t', 'time since the dose, hr'],
          ['A, B', 'the intercepts on the concentration axis of the two straight lines that make up the semi-log concentration-time plot, in concentration units'],
          ['a, b', 'a (alpha) and b (beta), the slopes of those two lines, hr&minus;1, with a the larger']],
 holds:'Two compartment, meaning the drug spreads into a central compartment and a tissue compartment at different rates; IV bolus, the whole dose given into a vein at once. Alpha (a) is larger because distribution, the spread of drug into the tissues, happens faster than elimination, its removal from the body.',
 cite:'2IVBolusAdministration.pdf; equation sheet page 1'},

{id:'c0-ab', module:2, name:'Two-compartment initial concentration', sheet:'absent',
 lhs:'C<sub>p</sub><sup>0</sup>', tokens:['A', '+', 'B'], typed:'Cp0 = A + B',
 also:['C0 = A + B', 'Cp^0 = A + B'],
 lures:['&minus;', '&times;', '/'],
 symbols:[['C<sub>p</sub><sup>0</sup>', 'the plasma concentration at time zero, mg/L'],
          ['A, B', 'the two intercepts on the concentration axis of the two straight lines in a two-compartment semi-log plot, in concentration units']],
 holds:'Two compartment, meaning the drug spreads into a central and a tissue compartment at different rates, at time zero. Both exponentials in C<sub>p</sub> = Ae<sup>&minus;at</sup> + Be<sup>&minus;bt</sup> are 1 at t = 0, so the concentration is the sum of the intercepts.',
 derive:['Printed: C<sub>p</sub> = Ae<sup>&minus;at</sup> + Be<sup>&minus;bt</sup>.',
   'At t = 0 both exponentials equal 1.',
   'So C<sub>p</sub><sup>0</sup> = A + B, the same sum the printed V<sub>p</sub> = {{frac:D<sub>0</sub>|A + B}} divides by.'],
 use:'When a two-compartment stem asks for the starting concentration, or gives A and B and wants V<sub>p</sub>.',
 cite:'2IVBolusAdministration.pdf'},

{id:'thalf-beta', module:2, name:'Beta half-life', sheet:'absent',
 lhs:'t&frac12;<sub>&beta;</sub>', tokens:['0.693', '/', 'b'], disp:'{{frac:0.693|b}}', typed:'t1/2beta = 0.693/b',
 also:['t1/2 = 0.693/b'],
 lures:['a', '&times;', 'k', 'A'],
 symbols:[['t&frac12;<sub>&beta;</sub>', 'the elimination half-life of a two-compartment drug, the time for the concentration to fall by one-half once distribution is complete'],
          ['b', 'beta, the slope of the final straight segment of the semi-log concentration-time plot, hr&minus;1']],
 holds:'Two compartment, meaning the drug spreads into a central and a tissue compartment at different rates. It is the first-order half-life, 0.693 divided by a rate constant, applied to the terminal slope. Solving first for k, the overall elimination rate constant, is more work than the question needs.',
 derive:['The terminal slope b (written &beta; in class) is a first-order rate constant.',
   'Use t&frac12; = {{frac:0.693|k}} with b in place of k: t&frac12;<sub>&beta;</sub> = {{frac:0.693|b}}.'],
 use:'For a two-compartment drug, the elimination half-life comes from b, not from a, which is the distribution phase.',
 cite:'2IVBolusAdministration.pdf, slide "Beta Half-life"'},

{id:'k-overall', module:2, name:'Overall elimination constant from the intercepts and slopes', sheet:'yes',
 lhs:'k', tokens:['(A + B)ab', '/', '(Ab + Ba)'], disp:'{{frac:(A + B)ab|Ab + Ba}}', typed:'k = (A+B)ab/(Ab+Ba)',
 lures:['(Ab &minus; Ba)', '(A &minus; B)', '&times;', '(A + B)'],
 symbols:[['k', 'overall elimination rate constant from the central compartment, hr&minus;1'],
          ['A, B', 'the intercepts on the concentration axis of the two straight lines of the semi-log plot, concentration units'],
          ['a, b', 'alpha and beta, the slopes of those two lines, hr&minus;1']],
 holds:'Two-compartment IV bolus, model A: drug moves to and from the tissue compartment and leaves the body from the central compartment only.',
 cite:'2IVBolusAdministration.pdf, slide "Rate Constants"; equation sheet'},

{id:'k12', module:2, name:'Transfer constant, central to tissue', sheet:'yes',
 lhs:'k<sub>12</sub>', tokens:['AB(b &minus; a)<sup>2</sup>', '/', '[(A + B)(Ab + Ba)]'],
 disp:'{{frac:AB(b &minus; a)<sup>2</sup>|(A + B)(Ab + Ba)}}', typed:'k12 = AB(b-a)^2/[(A+B)(Ab+Ba)]',
 also:['k12 = AB(b-a)^2/((A+B)(Ab+Ba))'],
 lures:['(Ab + Ba)', '(A + B)', 'AB(b + a)<sup>2</sup>', '&times;'],
 symbols:[['k<sub>12</sub>', 'transfer rate constant for drug moving from the central compartment to the tissue compartment, hr&minus;1'],
          ['A, B', 'the intercepts on the concentration axis of the two straight lines of the semi-log plot, concentration units'],
          ['a, b', 'alpha and beta, the slopes of those two lines, hr&minus;1']],
 holds:'Two-compartment IV bolus. Read straight off the A, B, alpha (a) and beta (b) she supplies in the stem.',
 cite:'2IVBolusAdministration.pdf, slide "Rate Constants"; equation sheet'},

{id:'k21', module:2, name:'Transfer constant, tissue to central', sheet:'yes',
 lhs:'k<sub>21</sub>', tokens:['(Ab + Ba)', '/', '(A + B)'], disp:'{{frac:Ab + Ba|A + B}}', typed:'k21 = (Ab+Ba)/(A+B)',
 lures:['(Ab &minus; Ba)', 'ab', '&times;'],
 symbols:[['k<sub>21</sub>', 'transfer rate constant for drug moving from the tissue compartment back to the central compartment, hr&minus;1'],
          ['A, B', 'the intercepts on the concentration axis of the two straight lines of the semi-log plot, concentration units'],
          ['a, b', 'alpha and beta, the slopes of those two lines, hr&minus;1']],
 holds:'Two-compartment IV bolus. It is the reciprocal arrangement of the overall elimination constant equation, k = {{frac:(A + B)ab|Ab + Ba}}, which is the pair most often swapped.',
 cite:'2IVBolusAdministration.pdf, slide "Rate Constants"; equation sheet'},

{id:'vp-ab', module:2, name:'Central compartment volume from the intercepts', sheet:'yes',
 lhs:'V<sub>p</sub>', tokens:['D<sub>0</sub>', '/', '(A + B)'], disp:'{{frac:D<sub>0</sub>|A + B}}', typed:'Vp = D0/(A+B)',
 lures:['&times;', '(A &minus; B)', 'k', 'AUC'],
 symbols:[['V<sub>p</sub>', 'volume of the central compartment, L'], ['D<sub>0</sub>', 'the IV dose, mg'],
          ['A, B', 'the intercepts on the concentration axis of the two straight lines of the semi-log plot, concentration units']],
 holds:'Two compartment, when A and B are supplied. It is the one-compartment relation V<sub>D</sub> = {{frac:D<sub>0</sub>|C<sub>0</sub>}}, where C<sub>0</sub> is the concentration at time zero, with A + B standing in for C<sub>0</sub>.',
 cite:'2IVBolusAdministration.pdf, slide "Apparent Volumes of Distribution"'},

{id:'vp-auc', module:2, name:'Central compartment volume from the area', sheet:'yes',
 lhs:'V<sub>p</sub>', tokens:['D<sub>0</sub>', '/', '(k', '&times;', 'AUC)'], disp:'{{frac:D<sub>0</sub>|k &times; AUC}}', typed:'Vp = D0/(k*AUC)',
 lures:['(A + B)', 'b', 'Cl'],
 symbols:[['V<sub>p</sub>', 'volume of the central compartment, L'], ['D<sub>0</sub>', 'the IV dose, mg'],
          ['k', 'overall elimination rate constant, hr&minus;1'],
          ['AUC', 'area under the concentration-time curve from time zero to infinity, mg&middot;hr/L']],
 holds:'Two compartment, when a dose and an area are supplied rather than the intercepts A and B of the two-compartment plot.',
 cite:'2IVBolusAdministration.pdf, slide "Apparent Volumes of Distribution"'},

{id:'vt', module:2, name:'Tissue compartment volume', sheet:'yes',
 lhs:'V<sub>t</sub>', tokens:['V<sub>p</sub>', 'k<sub>12</sub>', '/', 'k<sub>21</sub>'], disp:'{{frac:V<sub>p</sub>k<sub>12</sub>|k<sub>21</sub>}}', typed:'Vt = Vp*k12/k21',
 lures:['&times;', 'D<sub>0</sub>', '+', 'k'],
 symbols:[['V<sub>t</sub>', 'volume of the tissue compartment, L'], ['V<sub>p</sub>', 'volume of the central compartment, L'],
          ['k<sub>12</sub>', 'transfer rate constant, central to tissue, hr&minus;1'], ['k<sub>21</sub>', 'transfer rate constant, tissue to central, hr&minus;1']],
 holds:'Two compartment. The central volume scaled by the ratio of the two transfer constants.',
 cite:'2IVBolusAdministration.pdf, slide "Apparent Volumes of Distribution"'},

/* ───────── Module 3 ───────── */
{id:'css', module:3, name:'Steady-state concentration', sheet:'yes',
 lhs:'C<sub>ss</sub>', tokens:['R', '/', 'Cl'], disp:'{{frac:R|Cl}}', typed:'Css = R/Cl',
 also:['Css = R/(k*VD)', 'Css = R/kVD'],
 lures:['&times;', 'k', '(1 &minus; e<sup>&minus;kt</sup>)'],
 symbols:[['C<sub>ss</sub>', 'steady-state concentration, mg/L'], ['R', 'infusion rate, mg/hr'],
          ['Cl', 'clearance, the volume of plasma cleared of drug per unit time, L/hr']],
 holds:'At steady state only, where rate in equals rate out. It carries no t, so it says nothing about when steady state arrives.',
 cite:'3IntravenousInfusions.pdf; equation sheet page 1'},

{id:'cp-infusing', module:3, name:'Concentration during an infusion', sheet:'yes',
 lhs:'C<sub>p</sub>', tokens:['(R/Cl)', '(1 &minus; e<sup>&minus;kt</sup>)'], disp:'{{frac:R|Cl}}(1 &minus; e<sup>&minus;kt</sup>)', typed:'Cp = (R/Cl)(1 - e^(-kt))',
 also:['Cp = (R/(k*VD))(1 - e^(-kt))', 'Cp = (R/Cl)*(1-e^-kt)', 'Cp = (R/(VD*k))(1 - e^(-kt))'],
 lures:['(1 + e<sup>&minus;kt</sup>)', 'e<sup>&minus;kt</sup>', '(Cl/R)', '&times;'],
 symbols:[['C<sub>p</sub>', 'plasma concentration at time t, mg/L'], ['R', 'infusion rate, the amount of drug put in per unit time, mg/hr'],
          ['Cl', 'clearance, the volume of plasma cleared of drug per unit time, L/hr'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['t', 'time since the infusion started, hr'],
          ['(1 &minus; e<sup>&minus;kt</sup>)', 'the fraction of steady state reached']],
 holds:'During an infusion, before steady state, the plateau where the rate of drug in equals the rate out. The first factor, {{frac:R|Cl}}, is the plateau concentration C<sub>ss</sub> and the bracket is how much of it has been reached.',
 cite:'3IntravenousInfusions.pdf; equation sheet page 1'},

{id:'cp-after-stop', module:3, name:'Concentration after an infusion stops', sheet:'yes',
 lhs:'C<sub>p</sub>', tokens:['C<sub>peak</sub>', 'e<sup>&minus;kt</sup>'], typed:'Cp = Cpeak*e^(-kt)',
 also:['Cp = Css*e^(-kt)', 'Cp = Cpeak e^-kt'],
 lures:['(1 &minus; e<sup>&minus;kt</sup>)', 'R/Cl', '+', 'e<sup>+kt</sup>'],
 symbols:[['C<sub>p</sub>', 'plasma concentration at time t, mg/L'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['C<sub>peak</sub>', 'the concentration at the moment the infusion stopped, mg/L'],
          ['t', 'time since cessation, hr']],
 holds:'After cessation. Ordinary first-order decay, the rate of loss proportional to what remains, from a new starting point. Cpeak is Css, the steady-state concentration, only if the infusion actually ran to steady state. Steady state is the plateau where the rate of drug in equals the rate out.',
 cite:'3IntravenousInfusions.pdf, slide "Drug Concentration after an IV Infusion has Ended"'},

{id:'r-dose-time', module:3, name:'Infusion rate from the dose and the time it runs', sheet:'absent',
 lhs:'R', tokens:['D<sub>0</sub>', '/', 't<sub>inf</sub>'], disp:'{{frac:D<sub>0</sub>|t<sub>inf</sub>}}', typed:'R = D0/tinf',
 also:['R = D0/t', 'R = dose/time'],
 lures:['&times;', 'k', 'V<sub>D</sub>'],
 symbols:[['R', 'infusion rate, mg/hr'], ['D<sub>0</sub>', 'the dose infused, mg'], ['t<sub>inf</sub>', 'the time the infusion runs, hr']],
 holds:'Any constant-rate infusion. A dose given over a stated time is a rate: the whole dose divided by the hours it runs. The sheet writes R as given, so when a stem gives a dose and a duration the rate is made first.',
 derive:['A dose given over a stated time goes in at a constant rate.',
   'The rate is the amount over the time: R = {{frac:D<sub>0</sub>|t<sub>inf</sub>}}, in mg/hr.',
   'That R is the R every printed infusion line wants.'],
 use:'When an infusion is stated as a dose over a number of hours rather than as mg/hr.',
 cite:'3IntravenousInfusions.pdf, slide "Example 1" (a dose and an infusion time stated, the rate made from them)'},

{id:'dl-rk', module:3, name:'Loading dose from the rate', sheet:'yes',
 lhs:'D<sub>L</sub>', tokens:['R', '/', 'k'], disp:'{{frac:R|k}}', typed:'DL = R/k',
 lures:['&times;', 'Cl', 'V<sub>D</sub>'],
 symbols:[['D<sub>L</sub>', 'loading dose, mg'], ['R', 'infusion rate, the amount of drug put in per unit time, mg/hr'], ['k', 'first-order elimination rate constant, hr&minus;1']],
 holds:'An IV bolus given at the moment an infusion starts. It is only as good as the rate already chosen.',
 cite:'3IntravenousInfusions.pdf; equation sheet page 1'},

{id:'dl-css-vd', module:3, name:'Loading dose from the target', sheet:'yes',
 lhs:'D<sub>L</sub>', tokens:['C<sub>ss</sub>', '&times;', 'V<sub>D</sub>'], typed:'DL = Css*VD',
 also:['DL = Css VD'],
 lures:['/', 'k', 'Cl', 'R'],
 symbols:[['D<sub>L</sub>', 'loading dose, the IV bolus given as the infusion starts, mg'],
          ['C<sub>ss</sub>', 'the target steady-state concentration, mg/L'],
          ['V<sub>D</sub>', 'apparent volume of distribution, the hypothetical volume linking the amount in the body to the plasma concentration, L']],
 holds:'The amount that fills the volume of distribution to the target in one go. It depends on the volume, not on the half-life.',
 cite:'3IntravenousInfusions.pdf, slide "IV Bolus Loading Dose and Continuous IV Infusion"'},

{id:'load-plus-infusion', module:3, name:'Loading dose and infusion together', sheet:'absent',
 lhs:'C<sub>p</sub>',
 tokens:['(D<sub>L</sub>/V<sub>D</sub>)', 'e<sup>&minus;kt</sup>', '+', '(R/kV<sub>D</sub>)', '(1 &minus; e<sup>&minus;kt</sup>)'],
 disp:'{{frac:D<sub>L</sub>|V<sub>D</sub>}}e<sup>&minus;kt</sup> + {{frac:R|kV<sub>D</sub>}}(1 &minus; e<sup>&minus;kt</sup>)', typed:'Cp = (DL/VD)*e^(-kt) + (R/(k*VD))*(1 - e^(-kt))',
 also:['Cp = (DL/VD)e^-kt + (R/kVD)(1-e^-kt)'],
 lures:['&minus;', '(V<sub>D</sub>/D<sub>L</sub>)', '(1 + e<sup>&minus;kt</sup>)', 'C<sub>ss</sub>'],
 symbols:[['C<sub>p</sub>', 'plasma concentration at time t, mg/L'], ['D<sub>L</sub>', 'loading dose, the IV bolus given as the infusion starts, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L'], ['R', 'infusion rate, mg/hr'],
          ['k', 'first-order elimination rate constant, hr&minus;1'], ['t', 'time measured from the start of therapy, hr']],
 holds:'The loading dose and the infusion running at once, so the two contributions add: a decaying bolus term and a climbing infusion term. With the right loading dose the sum stays flat at C<sub>ss</sub>, the steady-state concentration, {{frac:R|kV<sub>D</sub>}}.',
 derive:['The loading dose behaves as a bolus: printed C = C<sub>0</sub>e<sup>&minus;kt</sup>, with C<sub>0</sub> = {{frac:D<sub>L</sub>|V<sub>D</sub>}}.',
   'The infusion follows the printed infusion line: C<sub>p</sub> = {{frac:R|Cl}}(1 &minus; e<sup>&minus;kt</sup>), with Cl = kV<sub>D</sub>.',
   'Both run at once and elimination is first order, so the two levels add.'],
 use:'When a stem gives a loading dose and an infusion started together and asks for the level before steady state.',
 cite:'3IntravenousInfusions.pdf, slide "IV Bolus Loading Dose and Continuous IV Infusion"'},

/* ───────── Module 4 ───────── */
{id:'rate-elim', module:4, name:'Rate of elimination', sheet:'yes',
 lhs:'Rate of elimination', tokens:['Cl', '&times;', 'C<sub>p</sub>'], typed:'rate of elimination = Cl*Cp',
 also:['rate = Cl*Cp'],
 lures:['/', 'k', 'V<sub>D</sub>', 'AUC'],
 symbols:[['Rate', 'amount per time, mcg/min or mg/hr'], ['Cl', 'clearance, the volume of plasma cleared of drug per unit time, L/hr or mL/min'],
          ['C<sub>p</sub>', 'plasma concentration, amount per volume, mg/L or mcg/mL']],
 holds:'First-order elimination, where the rate of loss is proportional to the amount of drug remaining, any route. Clearance is the factor between the rate and the concentration, which is why clearance stays constant while the rate does not.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet'},

{id:'clt-sum', module:4, name:'Total clearance as its parts', sheet:'yes',
 lhs:'Cl<sub>T</sub>', tokens:['Cl<sub>R</sub>', '+', 'Cl<sub>H</sub>'], typed:'ClT = ClR + ClH',
 lures:['&minus;', '&times;', 'f<sub>e</sub>', '(1 &minus; f<sub>e</sub>)'],
 symbols:[['Cl<sub>T</sub>', 'total body clearance, the volume of plasma cleared of drug per unit time by every route, L/hr'],
          ['Cl<sub>R</sub>', 'renal clearance, the part done by the kidney, L/hr'], ['Cl<sub>H</sub>', 'hepatic clearance, the part done by the liver, L/hr']],
 holds:'Clearances add. Hepatic clearance is obtained by subtraction, because the liver is not sampled directly.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet page 1, last line'},

{id:'fe', module:4, name:'Fraction excreted unchanged', sheet:'yes',
 lhs:'f<sub>e</sub>', tokens:['D<sub>u</sub>', '/', 'FD<sub>0</sub>'], disp:'{{frac:D<sub>u</sub>|FD<sub>0</sub>}}', typed:'fe = Du/(F*D0)',
 also:['fe = Du/FD0', 'fe = Du/D0'],
 lures:['&times;', 'k', 'k<sub>e</sub>', 'Cl<sub>T</sub>'],
 symbols:[['f<sub>e</sub>', 'fraction excreted unchanged, no units'],
          ['D<sub>u</sub>', 'cumulative unchanged drug recovered in urine over the whole collection, mg'],
          ['F', 'bioavailability, the fraction of the dose that reaches the circulation; 1 for an IV dose, no units'], ['D<sub>0</sub>', 'the dose, mg']],
 holds:'A complete urine collection. Lower-case fe is the fraction excreted; capital F is bioavailability. They are different quantities sharing a letter.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet'},

{id:'fe-k', module:4, name:'Excretion rate constant from the fraction', sheet:'yes',
 lhs:'k<sub>e</sub>', tokens:['f<sub>e</sub>', '&times;', 'k'], typed:'ke = fe*k',
 also:['ke = fek'],
 lures:['/', 'k<sub>m</sub>', 'Cl<sub>T</sub>', 'D<sub>u</sub>'],
 symbols:[['k<sub>e</sub>', 'excretion rate constant, for the drug leaving unchanged in urine, hr&minus;1'],
          ['f<sub>e</sub>', 'fraction of the dose excreted unchanged in urine, no units'],
          ['k', 'overall elimination rate constant, all routes together, hr&minus;1']],
 holds:'The same fraction that splits the dose splits the rate constant, since fe is also ke over k.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet'},

{id:'clr', module:4, name:'Renal clearance from the fraction', sheet:'yes',
 lhs:'Cl<sub>R</sub>', tokens:['f<sub>e</sub>', '&times;', 'Cl<sub>T</sub>'], typed:'ClR = fe*ClT',
 also:['ClR = feClT'],
 lures:['(1 &minus; f<sub>e</sub>)', '/', 'Cl<sub>H</sub>', 'k'],
 symbols:[['Cl<sub>R</sub>', 'renal clearance, the volume of plasma cleared of drug per unit time by the kidney, L/hr'],
          ['f<sub>e</sub>', 'fraction of the dose excreted unchanged in urine, dimensionless'],
          ['Cl<sub>T</sub>', 'total body clearance, by every route, L/hr']],
 holds:'Splitting a total clearance once fe is known. The renal share is the excreted fraction of the whole.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet'},

{id:'clh', module:4, name:'Hepatic clearance from the fraction', sheet:'yes',
 lhs:'Cl<sub>H</sub>', tokens:['(1 &minus; f<sub>e</sub>)', '&times;', 'Cl<sub>T</sub>'], typed:'ClH = (1-fe)*ClT',
 also:['ClH = ClT - ClR', 'ClH = (1-fe)ClT'],
 lures:['f<sub>e</sub>', '+', 'Cl<sub>R</sub>', '/'],
 symbols:[['Cl<sub>H</sub>', 'hepatic clearance, the volume of plasma cleared of drug per unit time by the liver, L/hr'],
          ['f<sub>e</sub>', 'fraction of the dose excreted unchanged in urine, no units'],
          ['Cl<sub>T</sub>', 'total body clearance, by every route, L/hr']],
 holds:'The remainder after the renal share. Equivalently total clearance minus renal clearance; the two forms are one statement.',
 cite:'4---Clearance-and-Elimination.pdf; equation sheet'},

/* ───────── Module 5 ───────── */
{id:'oral-cp', module:5, name:'Concentration after a single oral dose', sheet:'yes',
 lhs:'C<sub>p</sub>',
 tokens:['[Fk<sub>a</sub>D<sub>0</sub>', '/', 'V<sub>D</sub>(k<sub>a</sub> &minus; k)]',
         '&times;', '(e<sup>&minus;kt</sup> &minus; e<sup>&minus;k<sub>a</sub>t</sup>)'],
 disp:'{{frac:Fk<sub>a</sub>D<sub>0</sub>|V<sub>D</sub>(k<sub>a</sub> &minus; k)}} (e<sup>&minus;kt</sup> &minus; e<sup>&minus;k<sub>a</sub>t</sup>)', typed:'Cp = [F*ka*D0/(VD(ka-k))]*(e^(-kt) - e^(-ka*t))',
 also:['Cp = (F*ka*D0/(VD*(ka-k)))*(e^(-kt)-e^(-ka*t))',
       'Cp = [F*ka*D0/VD(ka-k)]*(e^(-kt) - e^(-ka*t))'],
 lures:['(e<sup>&minus;k<sub>a</sub>t</sup> &minus; e<sup>&minus;kt</sup>)', '(k &minus; k<sub>a</sub>)',
        '+', 'V<sub>D</sub>'],
 symbols:[['F', 'oral bioavailability fraction, no units'],
          ['k<sub>a</sub>', 'absorption rate constant, hr&minus;1'],
          ['k', 'elimination rate constant, hr&minus;1'], ['D<sub>0</sub>', 'oral dose, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L'], ['C<sub>p</sub>', 'plasma concentration at time t, mg/L'], ['t', 'time since the dose, hr']],
 holds:'Single oral dose, one compartment (the body treated as one uniform volume), first order in and first order out (each rate proportional to the amount still to move). The bracket is drug in minus drug out. The lumped prefactor, the fraction in front of the bracket, is not C<sub>0</sub>, the time-zero concentration of an IV bolus.',
 cite:'5---Pharmacokinetics-of-Oral-Absorption.pdf; equation sheet page 1'},

{id:'tmax', module:5, name:'Time to peak concentration', sheet:'yes',
 lhs:'t<sub>max</sub>', tokens:['ln(k<sub>a</sub>/k)', '/', '(k<sub>a</sub> &minus; k)'], disp:'{{frac:ln(k<sub>a</sub>/k)|k<sub>a</sub> &minus; k}}', typed:'tmax = ln(ka/k)/(ka-k)',
 also:['tmax = (ln(ka/k))/(ka-k)'],
 lures:['ln(k/k<sub>a</sub>)', '(k &minus; k<sub>a</sub>)', '&times;', '0.693', 'D<sub>0</sub>'],
 symbols:[['t<sub>max</sub>', 'the time at which the plasma concentration peaks after an oral dose; a time, hr'],
          ['k<sub>a</sub>, k', 'the absorption rate constant and the elimination rate constant, both in the same reciprocal time unit']],
 holds:'Single oral dose. It carries no dose and no volume, so tmax depends only on the two rate constants and doubling the dose does not move it. It is always found before Cmax, the peak concentration, which is reached at tmax.',
 cite:'5---Pharmacokinetics-of-Oral-Absorption.pdf; equation sheet page 1'},

{id:'thalf-abs', module:5, name:'Absorption half-life', sheet:'absent',
 lhs:'t&frac12;<sub>a</sub>', tokens:['0.693', '/', 'k<sub>a</sub>'], disp:'{{frac:0.693|k<sub>a</sub>}}', typed:'t1/2a = 0.693/ka',
 also:['t1/2 = 0.693/ka'],
 lures:['k', '&times;', '2.3'],
 symbols:[['t&frac12;<sub>a</sub>', 'absorption half-life, the time for half of the drug still at the absorption site to be absorbed, hr'],
          ['k<sub>a</sub>', 'absorption rate constant, the first-order constant for drug entering the circulation, hr&minus;1']],
 holds:'The first-order half-life, 0.693 divided by a rate constant, applied to absorption, the drug&rsquo;s entry into the circulation. Stems usually give the absorption half-life in minutes, so converting it to ka is the first step. An unqualified half-life means elimination.',
 derive:['Absorption is first order too, with its own constant k<sub>a</sub>.',
   'Use t&frac12; = {{frac:0.693|k}} with k<sub>a</sub> in place of k: t&frac12;<sub>a</sub> = {{frac:0.693|k<sub>a</sub>}}.'],
 use:'When an oral stem gives the absorption half-life and the line wants k<sub>a</sub>, or the reverse.',
 cite:'5---Pharmacokinetics-of-Oral-Absorption.pdf, slide "Kinetics of Absorption"'},
/* ───────── Module 6 ───────── */
{id:'db-tau', module:6, name:'Amount left after one dosing interval', sheet:'absent',
 lhs:'D<sub>B</sub>', tokens:['D<sub>0</sub>', 'e<sup>&minus;k&tau;</sup>'], typed:'DB = D0*e^(-k*tau)',
 also:['DB = D0e^(-kτ)'],
 lures:['e<sup>&minus;kt</sup>', '(1 &minus; e<sup>&minus;k&tau;</sup>)', '/'],
 symbols:[['D<sub>B</sub>', 'amount of drug in the body one interval after a dose, mg'], ['D<sub>0</sub>', 'the dose, mg'],
          ['&tau;', 'the dosing interval, hr: the time between doses'], ['k', 'first-order elimination rate constant, hr&minus;1']],
 holds:'A single IV bolus, the whole dose given into a vein at once, with first-order elimination, where the rate of loss is proportional to the amount remaining. {{frac:D<sub>B</sub>|D<sub>0</sub>}} = e<sup>&minus;k&tau;</sup> is the fraction of the dose still in the body when the next dose is due.',
 derive:['Printed: D = D<sub>0</sub>e<sup>&minus;kt</sup>.',
   'Read it at the end of one dosing interval, t = &tau;: D<sub>B</sub> = D<sub>0</sub>e<sup>&minus;k&tau;</sup>.'],
 use:'When a stem asks how much of one dose is left when the next is due.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body Following Repeated IV Bolus Injections"'},

{id:'dmax-ss', module:6, name:'Maximum amount at steady state', sheet:'yes',
 lhs:'D<sub>max</sub><sup>&infin;</sup>', tokens:['D<sub>0</sub>', '/', '(1 &minus; e<sup>&minus;k&tau;</sup>)'],
 disp:'{{frac:D<sub>0</sub>|1 &minus; e<sup>&minus;k&tau;</sup>}}', typed:'Dmax,ss = D0/(1 - e^(-k*tau))',
 also:['Dmax^inf = D0/(1 - e^(-k*tau))', 'Dmax∞ = D0/(1 - e^(-kτ))'],
 lures:['D<sub>0</sub>e<sup>&minus;k&tau;</sup>', '(1 + e<sup>&minus;k&tau;</sup>)', '&times;'],
 symbols:[['D<sub>max</sub><sup>&infin;</sup>', 'the largest amount of drug in the body during a dosing interval at steady state, just after a dose, mg'],
          ['D<sub>0</sub>', 'the dose given at each interval, mg'], ['k', 'first-order elimination rate constant, hr&minus;1'], ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Repeated IV bolus at a fixed dose and interval, first-order elimination (rate of loss proportional to the amount remaining), at steady state. Steady state is the plateau reached when each dose adds back exactly what was lost over the interval. {{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}} is the accumulation factor, how many times the single-dose amount the steady-state amount is.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"'},

{id:'dmin-ss', module:6, name:'Minimum amount at steady state', sheet:'yes',
 lhs:'D<sub>min</sub><sup>&infin;</sup>', tokens:['D<sub>0</sub>e<sup>&minus;k&tau;</sup>', '/', '(1 &minus; e<sup>&minus;k&tau;</sup>)'],
 disp:'{{frac:D<sub>0</sub>e<sup>&minus;k&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}}', typed:'Dmin,ss = D0*e^(-k*tau)/(1 - e^(-k*tau))',
 also:['Dmin^inf = D0*e^(-k*tau)/(1 - e^(-k*tau))', 'Dmin∞ = D0e^(-kτ)/(1 - e^(-kτ))'],
 lures:['D<sub>0</sub>', '(1 + e<sup>&minus;k&tau;</sup>)', 'e<sup>&minus;kt</sup>'],
 symbols:[['D<sub>min</sub><sup>&infin;</sup>', 'the smallest amount of drug in the body during a dosing interval at steady state, just before the next dose, mg'],
          ['D<sub>0</sub>', 'dose, mg'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Repeated IV bolus at a fixed dose and interval, first-order elimination, at steady state, the plateau reached when each dose adds back what was lost over the interval. The minimum comes at the end of the dosing interval, so it is the maximum amount at steady state multiplied by e<sup>&minus;k&tau;</sup>.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"'},

{id:'davg-ss', module:6, name:'Average amount at steady state', sheet:'yes',
 lhs:'D<sub>avg</sub><sup>&infin;</sup>', tokens:['FD<sub>0</sub>', '/', 'k&tau;'],
 disp:'{{frac:FD<sub>0</sub>|k&tau;}}', typed:'Davg,ss = F*D0/(k*tau)',
 also:['Davg^inf = F*D0/(k*tau)', 'Davg∞ = FD0/(kτ)'],
 lures:['V<sub>D</sub>', '2', '(1 &minus; e<sup>&minus;k&tau;</sup>)'],
 symbols:[['D<sub>avg</sub><sup>&infin;</sup>', 'the time-averaged amount of drug in the body over one dosing interval at steady state, mg'],
          ['F', 'bioavailability, the fraction of the dose reaching the circulation; 1 for an IV dose'], ['D<sub>0</sub>', 'dose, mg'],
          ['k', 'first-order elimination rate constant, hr&minus;1'], ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Steady state, the plateau reached when each dose adds back what was lost over the interval. Not the average of the maximum and minimum amounts, because the decline between doses is exponential.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"'},

{id:'cmax-ss', module:6, name:'Maximum concentration at steady state', sheet:'yes',
 lhs:'C<sub>max</sub><sup>&infin;</sup>', tokens:['C<sub>0</sub>', '/', '(1 &minus; e<sup>&minus;k&tau;</sup>)'],
 disp:'{{frac:C<sub>0</sub>|1 &minus; e<sup>&minus;k&tau;</sup>}}', typed:'Cmax,ss = C0/(1 - e^(-k*tau))',
 also:['Cmax^inf = C0/(1 - e^(-k*tau))', 'Cmax∞ = C0/(1 - e^(-kτ))', 'Cmax,ss = (D0/VD)/(1 - e^(-k*tau))'],
 lures:['C<sub>0</sub>e<sup>&minus;k&tau;</sup>', '(1 + e<sup>&minus;k&tau;</sup>)', '&times;'],
 symbols:[['C<sub>max</sub><sup>&infin;</sup>', 'the peak concentration in a dosing interval at steady state, just after a dose, mg/L'],
          ['C<sub>0</sub>', 'the first-dose peak: the dose D<sub>0</sub> divided by the volume of distribution V<sub>D</sub>, mg/L'],
          ['k', 'first-order elimination rate constant, hr&minus;1'], ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Repeated IV bolus at steady state, the plateau reached when each dose adds back what was lost over the interval. The first-dose peak divided by (1 &minus; e<sup>&minus;k&tau;</sup>), so it is always higher than C<sub>0</sub>.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"'},

{id:'cmin-ss', module:6, name:'Minimum concentration at steady state', sheet:'yes',
 lhs:'C<sub>min</sub><sup>&infin;</sup>', tokens:['C<sub>0</sub>e<sup>&minus;k&tau;</sup>', '/', '(1 &minus; e<sup>&minus;k&tau;</sup>)'],
 disp:'{{frac:C<sub>0</sub>e<sup>&minus;k&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}}', typed:'Cmin,ss = C0*e^(-k*tau)/(1 - e^(-k*tau))',
 also:['Cmin^inf = C0*e^(-k*tau)/(1 - e^(-k*tau))', 'Cmin∞ = C0e^(-kτ)/(1 - e^(-kτ))'],
 lures:['C<sub>0</sub>', '(1 + e<sup>&minus;k&tau;</sup>)', 'e<sup>&minus;kt</sup>'],
 symbols:[['C<sub>min</sub><sup>&infin;</sup>', 'the trough concentration at steady state, at the end of a dosing interval just before the next dose, mg/L'],
          ['C<sub>0</sub>', 'the first-dose peak: the dose D<sub>0</sub> divided by the volume of distribution V<sub>D</sub>, mg/L'],
          ['k', 'first-order elimination rate constant, hr&minus;1'], ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Steady state, the plateau reached when each dose adds back what was lost over the interval, at the end of the interval. Equal to the steady-state maximum multiplied by e<sup>&minus;k&tau;</sup>, one interval of first-order decline, where the rate of loss is proportional to what remains.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"'},

{id:'cmin-from-cmax', module:6, name:'Trough from the steady-state peak', sheet:'absent',
 lhs:'C<sub>min</sub><sup>&infin;</sup>', tokens:['C<sub>max</sub><sup>&infin;</sup>', '&times;', 'e<sup>&minus;k&tau;</sup>'], typed:'Cmin,ss = Cmax,ss*e^(-k*tau)',
 also:['Cmin^inf = Cmax^inf*e^(-k*tau)', 'Cmin∞ = Cmax∞e^(-kτ)', 'Cmin∞ = Cmax∞ × e^(-kτ)'],
 lures:['/', '(1 &minus; e<sup>&minus;k&tau;</sup>)', 'C<sub>0</sub>', 'e<sup>&minus;kt</sup>'],
 symbols:[['C<sub>min</sub><sup>&infin;</sup>', 'the trough concentration at steady state, at the end of a dosing interval just before the next dose, mg/L'],
          ['C<sub>max</sub><sup>&infin;</sup>', 'the peak concentration at steady state, just after a dose, mg/L'],
          ['k', 'first-order elimination rate constant, hr&minus;1'], ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Repeated IV bolus at steady state, when the peak of the interval is known or given. From the peak to the trough is one interval of first-order decline and nothing else, so the peak is multiplied by e<sup>&minus;k&tau;</sup>. It needs no dose, no volume and no C<sub>0</sub>.',
 derive:['Printed: C<sub>max</sub><sup>&infin;</sup> = {{frac:C<sub>0</sub>|1 &minus; e<sup>&minus;k&tau;</sup>}} and C<sub>min</sub><sup>&infin;</sup> = {{frac:C<sub>0</sub>e<sup>&minus;k&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}}.',
   'The trough line is the peak line with one more factor, e<sup>&minus;k&tau;</sup>.',
   'So C<sub>min</sub><sup>&infin;</sup> = C<sub>max</sub><sup>&infin;</sup> &times; e<sup>&minus;k&tau;</sup>: one dosing interval of first-order decline from the peak.'],
 use:'Only when the stem gives the steady-state peak, such as "a steady-state peak of 10 mg/L". When it gives the dose and the volume instead, use the printed trough line with C<sub>0</sub> = {{frac:D<sub>0</sub>|V<sub>D</sub>}}: that is the direct route, and this line is not needed.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections" (the two lines divided)'},

{id:'cp-after-last', module:6, name:'Concentration after the last dose at steady state', sheet:'absent',
 lhs:'C<sub>p</sub>', tokens:['C<sub>max</sub><sup>&infin;</sup>', '&times;', 'e<sup>&minus;kt</sup>'], typed:'Cp = Cmax,ss*e^(-k*t)',
 also:['Cp = Cmax^inf*e^(-k*t)', 'C = Cmax∞e^(-kt)', 'Cp = Cmax∞ × e^(-kt)'],
 lures:['/', '(1 &minus; e<sup>&minus;k&tau;</sup>)', 'C<sub>0</sub>', 'e<sup>&minus;k&tau;</sup>'],
 symbols:[['C<sub>p</sub>', 'the plasma concentration t hours after the last dose, mg/L'],
          ['C<sub>max</sub><sup>&infin;</sup>', 'the peak concentration at steady state, just after a dose, mg/L'],
          ['k', 'first-order elimination rate constant, hr&minus;1'], ['t', 'time since the last dose, hr']],
 holds:'Repeated IV bolus at steady state, after the last dose is given and no further dose follows. Nothing is added, so the level falls from the steady-state peak by first order alone. At t = &tau; it is the steady-state trough.',
 derive:['Printed: C<sub>max</sub><sup>&infin;</sup> = {{frac:C<sub>0</sub>|1 &minus; e<sup>&minus;k&tau;</sup>}}, the level the moment the last dose is in.',
   'After the last dose nothing more is added, so the level falls by first order from that peak, as in the printed C = C<sub>0</sub>e<sup>&minus;kt</sup>.',
   'With the peak as the start: C<sub>p</sub> = C<sub>max</sub><sup>&infin;</sup>e<sup>&minus;kt</sup>, with t counted from the last dose.'],
 use:'When a stem asks for the level some hours after the last dose at steady state. If it gives the peak, start there; if not, find the peak first from the printed line.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections" (the C<sub>p</sub> line with its first two factors read as the peak)'},

{id:'cavg-ss', module:6, name:'Average concentration at steady state', sheet:'yes',
 lhs:'C<sub>avg</sub><sup>&infin;</sup>', tokens:['FD<sub>0</sub>', '/', 'Cl<sub>T</sub>&tau;'],
 disp:'{{frac:FD<sub>0</sub>|Cl<sub>T</sub>&tau;}}', typed:'Cavg,ss = F*D0/(ClT*tau)',
 also:['Cavg^inf = F*D0/(ClT*tau)', 'Cavg∞ = FD0/(ClTτ)', 'Cavg,ss = F*D0/(VD*k*tau)'],
 lures:['k&tau;', '2', '(1 &minus; e<sup>&minus;k&tau;</sup>)'],
 symbols:[['C<sub>avg</sub><sup>&infin;</sup>', 'the time-averaged concentration over one dosing interval at steady state, mg/L'],
          ['F', 'bioavailability, the fraction of the dose reaching the circulation; 1 for an IV dose'], ['D<sub>0</sub>', 'dose, mg'],
          ['Cl<sub>T</sub>', 'total body clearance, the volume of plasma cleared of drug per unit time, equal to the volume of distribution V<sub>D</sub> times the elimination rate constant k, L/hr'],
          ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Steady state, the plateau reached when each dose adds back what was lost over the interval, IV or oral. The same as {{frac:FD<sub>0</sub>|V<sub>D</sub>k&tau;}}. Not the midpoint of the steady-state peak C<sub>max</sub> and trough C<sub>min</sub>.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"'},

{id:'cav-auc', module:6, name:'Average concentration from the area over one interval', sheet:'absent',
 lhs:'C<sub>av</sub><sup>&infin;</sup>', tokens:['[AUC]<sub>t1</sub><sup>t2</sup>', '/', '&tau;'],
 disp:'{{frac:[AUC]<sub>t1</sub><sup>t2</sup>|&tau;}}', typed:'Cav,ss = [AUC]t1^t2/tau',
 also:['Cav^inf = [AUC]t1^t2/tau', 'Cav∞ = AUC t1^t2/τ'],
 lures:['AUC<sub>0</sub><sup>&infin;</sup>', 'k', '&times;'],
 symbols:[['C<sub>av</sub><sup>&infin;</sup>', 'the time-averaged concentration over one dosing interval at steady state, mg/L'],
          ['[AUC]<sub>t1</sub><sup>t2</sup>', 'area under the concentration-time curve from t1, one dose, to t2, the next dose, at steady state'],
          ['&tau;', 'the dosing interval, t2 &minus; t1, hr'], ['&infin;', 'at steady state']],
 holds:'Steady state, the plateau reached when each dose adds back what was lost over the interval; one dosing interval. The area over the interval divided by its length.',
 derive:['Printed: C<sub>avg</sub><sup>&infin;</sup> = {{frac:FD<sub>0</sub>|V<sub>D</sub>k&tau;}}.',
   'V<sub>D</sub>k is the clearance, and by the printed Cl = {{frac:D<sub>0</sub>|AUC}} the dose over the clearance is the area under one dose, which at steady state is the area over one interval.',
   'So C<sub>av</sub><sup>&infin;</sup> = {{frac:[AUC]<sub>t1</sub><sup>t2</sup>|&tau;}}: the area over one interval spread over its length.'],
 use:'When a stem gives the area over one dosing interval at steady state instead of the dose.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Superposition"'},

{id:'cp-n', module:6, name:'Concentration at any time after n doses', sheet:'yes',
 lhs:'C<sub>p</sub>', tokens:['(D<sub>0</sub>/V<sub>D</sub>)', '&times;', '(1 &minus; e<sup>&minus;nk&tau;</sup>)', '/', '(1 &minus; e<sup>&minus;k&tau;</sup>)', '&times;', 'e<sup>&minus;kt</sup>'],
 disp:'{{frac:D<sub>0</sub>|V<sub>D</sub>}} ({{frac:1 &minus; e<sup>&minus;nk&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}}) e<sup>&minus;kt</sup>',
 typed:'Cp = (D0/VD)*((1 - e^(-n*k*tau))/(1 - e^(-k*tau)))*e^(-kt)',
 also:['Cp = D0/VD*(1-e^(-nkτ))/(1-e^(-kτ))*e^(-kt)'],
 lures:['(1 &minus; e<sup>&minus;nkt</sup>)', 'e<sup>&minus;k&tau;</sup>', '(1 + e<sup>&minus;k&tau;</sup>)'],
 symbols:[['C<sub>p</sub>', 'plasma concentration, mg/L'], ['D<sub>0</sub>', 'the dose given each time, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['n', 'the dose number just given'], ['t', 'time since that dose, hr'], ['&tau;', 'dosing interval, hr']],
 holds:'Repeated IV bolus (the whole dose into a vein at once, every &tau; hours) before steady state. Steady state is the plateau reached when each dose adds back what was lost over the interval. As n grows, e<sup>&minus;nk&tau;</sup> approaches 0 and this becomes the steady-state equation.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Plasma Drug Concentration at Any Time After n Doses"'},

{id:'cp-ss', module:6, name:'Concentration at any time at steady state', sheet:'absent',
 lhs:'C<sub>p</sub>', tokens:['(D<sub>0</sub>/V<sub>D</sub>)', '&times;', '1', '/', '(1 &minus; e<sup>&minus;k&tau;</sup>)', '&times;', 'e<sup>&minus;kt</sup>'],
 disp:'{{frac:D<sub>0</sub>|V<sub>D</sub>}} ({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}}) e<sup>&minus;kt</sup>',
 typed:'Cp = (D0/VD)*(1/(1 - e^(-k*tau)))*e^(-kt)',
 also:['Cp = D0/VD*1/(1-e^(-kτ))*e^(-kt)'],
 lures:['(1 &minus; e<sup>&minus;nk&tau;</sup>)', 'e<sup>&minus;k&tau;</sup>', 'C<sub>min</sub><sup>&infin;</sup>'],
 symbols:[['C<sub>p</sub>', 'plasma concentration, mg/L'], ['D<sub>0</sub>', 'the dose given each time, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['t', 'time since the most recent dose, hr'], ['&tau;', 'dosing interval, hr']],
 holds:'Steady state, the plateau reached when each dose adds back what was lost over the interval. The first two factors are C<sub>max</sub><sup>&infin;</sup>, the peak concentration at steady state, so this is C<sub>max</sub><sup>&infin;</sup> &times; e<sup>&minus;kt</sup>, which also gives the level after the last dose.',
 derive:['Printed: the level after n doses, C<sub>p</sub> = {{frac:D<sub>0</sub>|V<sub>D</sub>}}({{frac:1 &minus; e<sup>&minus;nk&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;kt</sup>.',
   'At steady state n is large, so e<sup>&minus;nk&tau;</sup> is close to 0 and the top of the bracket becomes 1.',
   'That leaves C<sub>p</sub> = {{frac:D<sub>0</sub>|V<sub>D</sub>}}({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;kt</sup>.'],
 use:'When a stem asks for the level at a stated time within a dosing interval at steady state and gives the dose, not the peak.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Plasma Drug Concentration at Steady State"'},
/* ───────── Module 6, second lecture: multiple oral doses ───────── */
{id:'tmax-ss', module:6, name:'Time to peak at steady state, oral', sheet:'yes',
 lhs:'t<sub>max</sub><sup>&infin;</sup>',
 tokens:['[1/(k<sub>a</sub> &minus; k)]', '&times;', 'ln[k<sub>a</sub>(1 &minus; e<sup>&minus;k&tau;</sup>)', '/', 'k(1 &minus; e<sup>&minus;k<sub>a</sub>&tau;</sup>)]'],
 disp:'{{frac:1|k<sub>a</sub> &minus; k}} ln[{{frac:k<sub>a</sub>(1 &minus; e<sup>&minus;k&tau;</sup>)|k(1 &minus; e<sup>&minus;k<sub>a</sub>&tau;</sup>)}}]',
 typed:'tmax,ss = [1/(ka-k)]*ln[ka*(1-e^(-k*tau))/(k*(1-e^(-ka*tau)))]',
 also:['tmax∞ = (1/(ka-k))*ln((ka(1-e^(-kτ)))/(k(1-e^(-kaτ))))', 'tmax^inf = (1/(ka-k))*ln((ka(1-e^(-kτ)))/(k(1-e^(-kaτ))))'],
 lures:['ln(k<sub>a</sub>/k)', 'k(1 &minus; e<sup>&minus;k&tau;</sup>)', '[1/(k &minus; k<sub>a</sub>)]'],
 symbols:[['t<sub>max</sub><sup>&infin;</sup>', 'the time after a dose at which the concentration peaks, once repeated oral dosing has reached steady state, hr'],
          ['k<sub>a</sub>, k', 'the absorption rate constant and the elimination rate constant, hr&minus;1'], ['&tau;', 'dosing interval, hr'], ['&infin;', 'at steady state']],
 holds:'Multiple oral doses at steady state, the plateau reached when each dose adds back what was lost over the interval. It holds k, ka and &tau;; the single-dose tmax holds only k and ka, so a new interval means a new tmax. Generally shorter than the first-dose tmax.',
 cite:'6a---Multiple-Oral-Doses.pdf, slide "Time to Peak at Steady State"; "on your equation sheet ... the bottom of the right hand column"'},

{id:'cmax-ss-oral', module:6, name:'Maximum concentration at steady state, oral', sheet:'yes',
 lhs:'C<sub>max</sub><sup>&infin;</sup>',
 tokens:['(FD<sub>0</sub>/V<sub>D</sub>)', '&times;', '[1/(1 &minus; e<sup>&minus;k&tau;</sup>)]', '&times;', 'e<sup>&minus;kt<sub>max</sub>&infin;</sup>'],
 disp:'{{frac:FD<sub>0</sub>|V<sub>D</sub>}} ({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}}) e<sup>&minus;kt<sub>max</sub>&infin;</sup>',
 typed:'Cmax,ss = (F*D0/VD)*(1/(1-e^(-k*tau)))*e^(-k*tmax,ss)',
 also:['Cmax∞ = (FD0/VD)(1/(1-e^(-kτ)))e^(-k tmax∞)', 'Cmax^inf = (FD0/VD)(1/(1-e^(-kτ)))e^(-k tmax∞)', 'Cmax,ss = F*D0/VD/(1-e^(-k*tau))*e^(-k*tmax)'],
 lures:['(D<sub>0</sub>/V<sub>D</sub>)', 'e<sup>&minus;k&tau;</sup>', '(1 + e<sup>&minus;k&tau;</sup>)'],
 symbols:[['C<sub>max</sub><sup>&infin;</sup>', 'the peak concentration in a dosing interval at steady state, mg/L'],
          ['F', 'bioavailability, the fraction of the oral dose reaching the circulation'], ['D<sub>0</sub>', 'the oral dose given each time, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['t<sub>max</sub><sup>&infin;</sup>', 'the time to peak at steady state, found first from its own equation'], ['&tau;', 'dosing interval, hr']],
 holds:'Multiple oral doses at steady state, the plateau reached when each dose adds back what was lost over the interval. The F and the tmax mark it as oral; without them it is the repeated-bolus Cmax. tmax at steady state is found first, from the time-to-peak-at-steady-state equation.',
 cite:'6a---Multiple-Oral-Doses.pdf, slide "Peak, Trough and Average Plasma Concentrations at Steady State"'},

{id:'cmin-ss-oral', module:6, name:'Minimum concentration at steady state, oral', sheet:'yes',
 lhs:'C<sub>min</sub><sup>&infin;</sup>',
 tokens:['[k<sub>a</sub>FD<sub>0</sub>', '/', 'V<sub>D</sub>(k<sub>a</sub> &minus; k)]', '&times;', '[1/(1 &minus; e<sup>&minus;k&tau;</sup>)]', '&times;', 'e<sup>&minus;k&tau;</sup>'],
 disp:'{{frac:k<sub>a</sub>FD<sub>0</sub>|V<sub>D</sub>(k<sub>a</sub> &minus; k)}} ({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}}) e<sup>&minus;k&tau;</sup>',
 typed:'Cmin,ss = [ka*F*D0/(VD*(ka-k))]*(1/(1-e^(-k*tau)))*e^(-k*tau)',
 also:['Cmin∞ = (kaFD0/(VD(ka-k)))(1/(1-e^(-kτ)))e^(-kτ)', 'Cmin^inf = (kaFD0/(VD(ka-k)))(1/(1-e^(-kτ)))e^(-kτ)'],
 lures:['(FD<sub>0</sub>/V<sub>D</sub>)', 'e<sup>&minus;kt<sub>max</sub></sup>', '(k &minus; k<sub>a</sub>)]'],
 symbols:[['C<sub>min</sub><sup>&infin;</sup>', 'the trough concentration at steady state, at the end of a dosing interval, mg/L'],
          ['k<sub>a</sub>', 'absorption rate constant, hr&minus;1'], ['k', 'first-order elimination rate constant, hr&minus;1'],
          ['F', 'bioavailability, the fraction of the oral dose reaching the circulation'], ['D<sub>0</sub>', 'the oral dose given each time, mg'],
          ['V<sub>D</sub>', 'apparent volume of distribution, L'], ['&tau;', 'dosing interval, hr']],
 holds:'Multiple oral doses at steady state, the plateau reached when each dose adds back what was lost over the interval, at the end of the interval. Carries three factors. The single-dose prefactor is the first bracket, the factor in front of the single oral dose equation. The accumulation factor, {{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}}, is how many times the single-dose level the steady-state level is. The last, e<sup>&minus;k&tau;</sup>, is one interval of decline.',
 cite:'6a---Multiple-Oral-Doses.pdf, slide "Peak, Trough and Average Plasma Concentrations at Steady State"'},

/* ───────── Module 7a: bioavailability and bioequivalence ───────── */
{id:'f-abs', module:7, name:'Absolute bioavailability, dose-corrected', sheet:'yes',
 lhs:'F<sub>abs</sub>', tokens:['(AUC<sub>po</sub>', '/', 'AUC<sub>IV</sub>)', '&times;', '(D<sub>IV</sub>', '/', 'D<sub>po</sub>)'],
 disp:'{{frac:AUC<sub>po</sub>|AUC<sub>IV</sub>}} &times; {{frac:D<sub>IV</sub>|D<sub>po</sub>}}', typed:'Fabs = (AUCpo/AUCiv)*(Div/Dpo)',
 also:['F = (AUCpo/AUCiv)(Div/Dpo)', 'F = (AUCpo/AUCiv)*(Div/Dpo)', 'Fabs = (AUCpo/AUCiv)(Div/Dpo)', 'F = AUCpo/AUCiv*Div/Dpo'],
 lures:['(AUC<sub>IV</sub>', '(D<sub>po</sub>', 'Cl', '+'],
 symbols:[['F<sub>abs</sub>', 'absolute bioavailability, the fraction of the oral dose that reaches the circulation, measured against an IV dose of the same drug; no units; written 0.55 or 55%, never a bare decimal point'],
          ['AUC<sub>po</sub>, AUC<sub>IV</sub>', 'areas under the concentration-time curve after the oral (po, by mouth) dose and after the IV dose, in the same units'],
          ['D<sub>IV</sub>, D<sub>po</sub>', 'the IV dose and the oral dose, mg']],
 holds:'An extravascular dose, one given outside the blood vessels, such as by mouth, compared with an IV dose of the same drug. The IV AUC is in the denominator and the IV dose on top; with equal doses only the AUC ratio is left. Cannot exceed 1.',
 cite:'7a---Bioavailability-and-Bioequivalence.pdf, slide "Absolute Bioavailability"; equation sheet page 2; "the IVAUC is going to be in the denominator"'},

{id:'div-cl-auc', module:7, name:'IV dose from clearance and area', sheet:'yes',
 lhs:'D<sub>IV</sub>', tokens:['Cl', '&times;', 'AUC<sub>IV</sub>'], typed:'Div = Cl*AUCiv',
 also:['Div = (Cl)(AUCiv)', 'DIV = Cl × AUCIV', 'Div = ClT*AUCiv', 'Div = k*VD*AUCiv'],
 lures:['/', 'k', 'V<sub>D</sub>', 'F', 'AUC<sub>po</sub>'],
 symbols:[['D<sub>IV</sub>', 'the IV dose, mg'],
          ['Cl', 'clearance, the volume of plasma cleared of drug per unit time, L/hr; for one compartment it is k, the elimination rate constant, times V<sub>D</sub>, the volume of distribution'],
          ['AUC<sub>IV</sub>', 'area under the concentration-time curve after the IV dose, mg&middot;hr/L']],
 holds:'An IV dose, where F, the bioavailability (the fraction of the dose reaching the circulation), is 1. Rearranged, AUC<sub>IV</sub> = {{frac:D<sub>IV</sub>|Cl}} gives the IV area from a half-life and a volume when the stem states no IV AUC. For that, k = {{frac:0.693|t&frac12;}} and Cl = k &times; V<sub>D</sub>. The Module 4 line Cl<sub>T</sub> = {{frac:FD<sub>0</sub>|AUC}}, with Cl<sub>T</sub> the total body clearance and D<sub>0</sub> the dose, is the same relationship.',
 cite:'7a---Bioavailability-and-Bioequivalence.pdf, slide "Absolute Bioavailability"; equation sheet page 2; In-Class Activity 1(a)'},

{id:'fabs-dpo', module:7, name:'Absorbed oral dose from clearance and area', sheet:'yes',
 lhs:'F<sub>abs</sub>D<sub>po</sub>', tokens:['Cl', '&times;', 'AUC<sub>po</sub>'], typed:'Fabs*Dpo = Cl*AUCpo',
 also:['FabsDpo = (Cl)(AUCpo)', 'F*Dpo = Cl*AUCpo', 'FDpo = Cl × AUCpo', 'F*Dpo = k*VD*AUCpo'],
 lures:['/', 'AUC<sub>IV</sub>', 'D<sub>IV</sub>', 'k'],
 symbols:[['F<sub>abs</sub>D<sub>po</sub>', 'the absolute bioavailability F<sub>abs</sub> (the fraction of the oral dose reaching the circulation) times the oral dose D<sub>po</sub>: the part of the oral dose that entered the circulation, mg'],
          ['Cl', 'clearance, the volume of plasma cleared of drug per unit time, L/hr'],
          ['AUC<sub>po</sub>', 'area under the concentration-time curve after the oral dose, mg&middot;hr/L']],
 holds:'The oral dose, written the same way as the IV line D<sub>IV</sub> = Cl &times; AUC<sub>IV</sub>. Solved for Fabs it is the second route, after F<sub>abs</sub> = {{frac:AUC<sub>po</sub>|AUC<sub>IV</sub>}} &times; {{frac:D<sub>IV</sub>|D<sub>po</sub>}}, to the same answer. That answer is {{frac:Cl &times; AUC<sub>po</sub>|D<sub>po</sub>}}, and every unit cancels.',
 cite:'7a---Bioavailability-and-Bioequivalence.pdf, slide "Absolute Bioavailability"; equation sheet page 2; "it doesn\'t matter which approach you use"'},

{id:'dpo-equiv', module:7, name:'Oral dose equivalent to an IV dose', sheet:'absent',
 lhs:'D<sub>po</sub>', tokens:['D<sub>IV</sub>', '/', 'F'], disp:'{{frac:D<sub>IV</sub>|F}}', typed:'Dpo = Div/F',
 also:['Dpo = Div/Fabs'],
 lures:['&times;', 'AUC<sub>IV</sub>', 'Cl', 'AUC<sub>po</sub>'],
 symbols:[['D<sub>po</sub>', 'the oral dose that gives the same AUC as the IV dose, mg'], ['D<sub>IV</sub>', 'the IV dose to be matched, mg'],
          ['F', 'absolute bioavailability of the oral product, the fraction of the oral dose that reaches the circulation, no units']],
 holds:'When the oral AUC (area under the concentration-time curve after the oral dose) is to equal the IV AUC, Fabs simplifies. The absolute bioavailability F<sub>abs</sub> = {{frac:AUC<sub>po</sub>|AUC<sub>IV</sub>}} &times; {{frac:D<sub>IV</sub>|D<sub>po</sub>}} reduces to {{frac:D<sub>IV</sub>|D<sub>po</sub>}}. The answer is larger than the IV dose and is then rounded to a strength that exists: 400 mg at 70% gives 571.43 mg, offered as 575 or 600 mg.',
 derive:['Printed: F<sub>abs</sub>D<sub>po</sub> = Cl &times; AUC<sub>po</sub> and D<sub>IV</sub> = Cl &times; AUC<sub>IV</sub>.',
   'For the oral dose to give the same area as the IV dose, the right-hand sides are equal, so F<sub>abs</sub>D<sub>po</sub> = D<sub>IV</sub>.',
   'Divide by F<sub>abs</sub>: D<sub>po</sub> = {{frac:D<sub>IV</sub>|F<sub>abs</sub>}}.'],
 use:'When a stem gives F and an IV dose and asks for the oral dose that matches it.',
 cite:'7a---Bioavailability-and-Bioequivalence.pdf, slide "Absolute Bioavailability" with her working; In-Class Activity page 18'},

{id:'f-rel', module:7, name:'Relative bioavailability', sheet:'yes',
 lhs:'F<sub>rel</sub>', tokens:['(AUC<sub>A</sub>', '/', 'AUC<sub>B</sub>)', '&times;', '(D<sub>B</sub>', '/', 'D<sub>A</sub>)'],
 disp:'{{frac:AUC<sub>A</sub>|AUC<sub>B</sub>}} &times; {{frac:D<sub>B</sub>|D<sub>A</sub>}}', typed:'Frel = (AUCa/AUCb)*(Db/Da)',
 also:['Frel = (AUCa/AUCb)(Db/Da)', 'Frel = AUCa/AUCb*Db/Da'],
 lures:['(AUC<sub>B</sub>', '(D<sub>A</sub>', 'AUC<sub>IV</sub>)', '+'],
 symbols:[['F<sub>rel</sub>', 'relative bioavailability, the extent of absorption of one formulation compared with another formulation of the same drug; no units; may exceed 1'],
          ['AUC<sub>A</sub>, AUC<sub>B</sub>', 'the areas under the concentration-time curve after product A and after product B, in the same units'],
          ['D<sub>A</sub>, D<sub>B</sub>', 'the doses of product A and product B, mg'],
          ['A', 'the product being compared, the test'], ['B', 'the reference standard or comparator, in the denominator']],
 holds:'Two formulations of the same drug, neither IV. Says nothing about bioequivalence on its own, because the rate of absorption, read from tmax, is not in it. Bioequivalence means no significant difference in both the rate and the extent of absorption.',
 cite:'7a---Bioavailability-and-Bioequivalence.pdf, slide "Relative Bioavailability"; equation sheet page 2'},
];
