/* ==========================================================================
   MODULE 2 — IV BOLUS, ONE- AND MULTI-COMPARTMENT
   ==========================================================================
   Exam 1, module 2. L02 = one-compartment IV bolus (24 August);
   L03 = multicompartment IV bolus (26 August). Deck for both:
   2IVBolusAdministration.pdf. Revision slides: RecapExam1.pdf.
   Equation sheet: BasicPharmacokineticsEquations.pdf.

   TOPICS is declared in the first question file, not here.
   ========================================================================== */
const Q_MODULE2 = [

/* ════════════════ L02 — ONE-COMPARTMENT IV BOLUS ════════════════ */

/* ---------- the model and its assumptions ---------- */
{id:'m2-mod-1', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'model', concept:'onecpt-assumptions', skill:'recall',
 source:'both',
 stem:'A drug is given by intravenous bolus injection and is described by a one-compartment open model. What does the model assume happens to the dose?',
 options:[
  {t:'All of it enters at once and distributes uniformly', correct:true,
   why:'The bolus puts the whole dose into the body instantaneously, and the one-compartment assumption says the drug spreads evenly through that single body compartment at the same instant. Dr. Mosley states both halves together and then says plainly that this does not actually happen, so the model is a simplification chosen because it is the simplest way to describe distribution and elimination. Elimination begins the moment the drug is in, so there is no lag between input and loss.'},
  {t:'All of it enters at once and then distributes over several hours', correct:false,
   why:'A distribution step that takes measurable time is what forces a second compartment, so describing one is describing the two-compartment model instead. The one-compartment model has no distribution phase at all; the drug is uniform from time zero. Choosing this means holding the instantaneous input but not the instantaneous distribution.'},
  {t:'It enters at a constant rate and distributes uniformly', correct:false,
   why:'Constant-rate input is intravenous infusion, which is a zero-order process at the input end and belongs to a later module. The word bolus is what fixes the input as instantaneous, so attaching a rate to it replaces the mode of administration named in the question.'},
  {t:'It enters at once and stays in the plasma until elimination begins', correct:false,
   why:'This adds a waiting period before elimination starts, which the model does not have. Dr. Mosley says all the drug goes in and all the drug goes out, and that as soon as the drug is in the body it starts immediately being eliminated. Confining the dose to plasma also confuses the plasma sample with the volume of distribution.'}],
 teach:'The one-compartment open model makes two simplifications at once, and both are stated at time zero. The input is instantaneous, so the amount in the body at time zero is the whole dose. The distribution is instantaneous and uniform, so one measured plasma concentration describes the whole body. Open means drug can leave, and it leaves from that same instant. Everything else in this module, including Cp = DB/VD and the exponential decay, follows from those two assumptions.',
 cite:'2IVBolusAdministration.pdf, slide "One-Compartment Open Model: IV Bolus Administration"',
 quote:'the drug goes into the body all at once, like instantly all the drug is into the body and all the drug is instantly uniformly distributed throughout the body. Assumptions, simplifications, this does not happen.'},

{id:'m2-mod-2', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02', multi:true,
 topic:'bolus1', sub:'model', concept:'onecpt-assumptions', skill:'recall',
 source:'both', dupOf:'m2-mod-1',
 stem:'Select every statement that the one-compartment open model for intravenous bolus administration assumes. Select all that apply.',
 options:[
  {t:'The body behaves as a single uniform compartment', correct:true,
   why:'The body acts like a single, uniform compartment, which is what allows one plasma concentration to stand for the whole body. Uniform is the operative word: no region holds a different concentration from any other.'},
  {t:'Drug can both enter and leave the body', correct:true,
   why:'This is what open means in the model name. A closed compartment would retain everything put into it; the open model has an exit, and the differential equation dDB/dt = −kDB describes that exit as first order in the amount present.'},
  {t:'Input of the dose is instantaneous', correct:true,
   why:'Dr. Mosley calls this instantaneous input of drug into the body, and it is what distinguishes a bolus from an infusion. It sets the amount in the body at time zero equal to the full dose, which is the starting point for every calculation in this module.'},
  {t:'Drug concentration is the same in plasma and in tissue', correct:false,
   why:'Uniform distribution in the model means the drug behaves as though it occupies one compartment, not that a tissue biopsy and a plasma sample would read the same number. If they did, the volume of distribution would always equal a real physiological volume, and large volumes of distribution could not exist. This is the most common overreading of the word uniform.'},
  {t:'Elimination begins only after distribution is complete', correct:false,
   why:'There is nothing for elimination to wait for, because distribution is instantaneous in this model. The idea of waiting for distribution is imported from the two-compartment model, where a distribution phase genuinely precedes the elimination phase on the curve.'}],
 teach:'Three assumptions define the model and each one is doing a specific job. Instantaneous input fixes the starting amount. A single uniform compartment lets one measured plasma concentration represent the whole body. Open means elimination is running the whole time. Read the list as three separate claims rather than one, because exam distractors usually keep two and corrupt the third.',
 cite:'2IVBolusAdministration.pdf, slide "One-Compartment Open Model: IV Bolus Administration"',
 quote:'Assumes that the drug can enter and leave the body. Body acts like a single, uniform compartment'},

{id:'m2-mod-3', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'model', concept:'k-subscripts', skill:'tell',
 source:'both',
 stem:'In the relationship k = km + ke, what does a rate constant written as k with no subscript represent?',
 options:[
  {t:'The overall elimination rate constant', correct:true,
   why:'An unsubscripted k gathers every route by which the drug leaves the body into a single number. The slide splits it into km for metabolism and ke for excretion, and Dr. Mosley says that if you see k with no subscript, that is the overall rate constant for elimination, with all the processes wrapped up into it. Every calculation in this module that uses k is using that total.'},
  {t:'The rate constant for excretion only', correct:false,
   why:'Excretion has its own symbol, ke, precisely so that it can be separated from the total. Reading the bare k as excretion drops the metabolic route entirely, which would underestimate how fast the drug leaves and inflate any half-life computed from it.'},
  {t:'The rate constant for metabolism only', correct:false,
   why:'Metabolism is km. Picking this makes the same substitution error as picking excretion, and it is often made because metabolism is the route students meet first. The sum of the two subscripted constants, not either one alone, is what the concentration-time data actually measure.'},
  {t:'The transfer rate constant between plasma and tissue', correct:false,
   why:'Transfer between compartments is written k12 and k21, and those belong to the multicompartment model, where drug moves back and forth without leaving the body. A transfer constant describes redistribution; k describes irreversible loss. Confusing them puts a distribution term into an elimination calculation.'}],
 teach:'Subscripts on rate constants name the route. km is metabolism, ke is excretion, and the bare k is their sum, which is why it is called the overall elimination rate constant. Plasma concentration data see only the total, because the drug leaving by one route and the drug leaving by another are indistinguishable in a plasma sample. That is why k, and not km or ke, is what a concentration-time slope gives you.',
 cite:'2IVBolusAdministration.pdf, slide "One-Compartment Open Model: IV Bolus Administration"',
 quote:'KM is a rate constant for metabolism, KE is the rate constant for excretion … If you see K with no subscript, that is our overall rate constant for elimination.'},

{id:'m2-mod-4', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'model', concept:'integrated-forms', skill:'read',
 source:'both',
 stem:'The decline of plasma concentration after an intravenous bolus can be written as Cp = Cp0·e^(−kt), as ln Cp = ln Cp0 − kt, or as log Cp = log Cp0 − kt/2.3. Which form does Dr. Mosley say she prefers?',
 options:[
  {t:'The natural-logarithm form', correct:true,
   why:'She states a preference for the natural-log equations while adding that either one gets you there, so the base-ten form is not wrong, just not her route. The natural-log form needs no conversion factor, which is why the 2.3 never appears in her worked solutions. Her keys throughout the IV bolus practice sets compute k as ln of a concentration ratio divided by a time difference.'},
  {t:'The base-ten logarithm form', correct:false,
   why:'This is the form that carries the 2.3, and it is the one she works away from rather than toward. Choosing it usually comes from having met semi-logarithmic graph paper first, which is base ten, and assuming the algebra must match the graph paper. The two forms describe the same line; only the scaling of the slope differs.'},
  {t:'The exponential form', correct:false,
   why:'The exponential form is the one she uses for going forward from a known concentration to a later one, but it is not the form she names as preferred when the three are shown together. It is also the form where she warns about the sign of the exponent, since throwing in a minus when solving back to Cp0 produces a number lower than where you started.'},
  {t:'Whichever form the plotted axis uses', correct:false,
   why:'The axis of a plot decides how the data look, not which algebraic form you must solve with. A concentration measured at a time is the same number whichever equation you rearrange, so tying the choice of equation to the graph paper adds a constraint that does not exist.'}],
 teach:'The three forms are one relationship written three ways. Exponential form predicts a concentration at a time. Natural-log form linearises it so that a slope gives k directly. Base-ten log form linearises it for semi-logarithmic graph paper, and the 2.3 is only the conversion between the two logarithm bases. Since nothing physical changes between them, the choice is about which rearrangement is least error-prone, and she settles that by using natural logs throughout.',
 cite:'2IVBolusAdministration.pdf, slide "Concentration of Drug in the Plasma, Cp"',
 quote:'this is my preferred equations down here with natural log, but either one gets you there.',
 note:'The slide itself prints all three forms without marking a preference; the annotation "Dr. Mosley prefers this equation" on this copy of the deck is handwritten and is not used as the source here. The preference is taken from the 19 August transcript, where she says it about the same set of equations. An exam written from these lectures would accept any of the three forms, since the base-ten and exponential forms are both on the equation sheet.'},

/* ---------- volume of distribution ---------- */
{id:'m2-vd-1', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'vd', concept:'vd-definition', skill:'recall',
 source:'both',
 stem:'What does the apparent volume of distribution of a drug represent?',
 options:[
  {t:'A hypothetical volume that would hold the whole dose', correct:true,
   why:'The slide defines it as the hypothetical volume of body fluid that would be required to dissolve the total amount of drug at the same concentration as that found in the blood. Hypothetical is the load-bearing word: the number can exceed total body water, which no real volume can. Dr. Mosley says it is not an actual volume and that it depends on the drug.'},
  {t:'The total volume of blood and extracellular fluid present', correct:false,
   why:'Blood volume is a fixed physiological quantity of a few litres that does not change from drug to drug, whereas the volume of distribution does. A drug that sits almost entirely in tissue has a volume of distribution far larger than any blood volume, which is the clearest evidence that the two are different quantities.'},
  {t:'The volume of plasma completely cleared of drug each hour', correct:false,
   why:'That is the definition of clearance, and swapping the two is easy because both are quoted in units of volume. Clearance carries a time in its units and the volume of distribution does not, so checking whether the unit has a per-hour on it separates them immediately.'},
  {t:'The volume of the dosage form administered', correct:false,
   why:'The injected volume is a property of the preparation, not of how the drug behaves in the body, and changing the syringe volume would not change the concentration achieved. The volume of distribution is derived from the dose and the resulting plasma concentration, never from the formulation.'}],
 teach:'The volume of distribution answers one question: how big would a container have to be to hold this whole dose at the concentration actually measured in plasma? If the drug leaves the plasma for tissue, the measured plasma concentration is low, so the implied container is large. Nothing requires that container to correspond to an anatomical space, which is why it is called hypothetical and apparent.',
 cite:'2IVBolusAdministration.pdf, slide "Volume of Distribution"',
 quote:'The volume of distribution is a hypothetical volume of body fluid that would be required to dissolve the total amount of drug at the same concentration as that found in the blood.'},

{id:'m2-vd-2', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'vd', concept:'vd-definition', skill:'recall',
 source:'both', dupOf:'m2-vd-1',
 stem:'The volume of distribution acts as a proportionality constant. Which two quantities does it relate?',
 options:[
  {t:'The amount in the body and the plasma concentration', correct:true,
   why:'The slide calls it a proportionality constant relating the amount of drug in the body to the measured concentration in the biological fluid, and the relationship is written Cp = DB/VD. Because it is a constant, the same value converts amount to concentration at any time after the dose, not only at time zero.'},
  {t:'The dose and the elimination rate constant', correct:false,
   why:'Dose and elimination rate constant are independent of each other in a linear first-order system, so no constant links them. This answer usually comes from remembering that the volume of distribution appears in the clearance equation alongside k and assuming the pairing runs the other way.'},
  {t:'The plasma concentration and the elimination half-life', correct:false,
   why:'For a first-order process the half-life is the same at every concentration, so there is no proportionality between them to describe. That independence is one of the defining properties of first-order elimination, which makes this the exact opposite of a proportional relationship.'},
  {t:'The clearance and the area under the curve', correct:false,
   why:'Clearance and area under the curve are related, but through the dose, as Cl = D0/AUC, and the constant of proportionality there is the dose rather than the volume of distribution. Placing the volume of distribution in that relationship mixes up the two things clearance is liked for.'}],
 teach:'Calling the volume of distribution a proportionality constant is a statement about arithmetic, not anatomy. Amount and concentration are two readings of the same drug in the body, and one number converts between them in both directions: multiply concentration by the volume to get the amount, divide amount by the volume to get the concentration. Because the constant does not change with time, either reading can be converted to the other at any point on the curve.',
 cite:'2IVBolusAdministration.pdf, slide "Volume of Distribution"',
 quote:'we are talking about the volume distribution being a proportionality constant which relates the amount of drug into the in the body to whatever concentration we measure.'},

{id:'m2-vd-3', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'vd', concept:'vd-magnitude', skill:'apply',
 source:'both',
 stem:'Two drugs are given at the same dose to the same patient. Drug A has a much larger apparent volume of distribution than drug B. What does that tell you about drug A?',
 options:[
  {t:'It is more concentrated outside the vasculature', correct:true,
   why:'A large volume of distribution arises because the measured plasma concentration is low for the dose given, and the drug has to be somewhere, so it is in extravascular tissue. A large volume of distribution means more concentrated in extravascular tissues and less concentrated intravascularly. Dr. Mosley describes the same drug as widely distributed rather than hanging out in the plasma.'},
  {t:'It is more highly bound to plasma proteins', correct:false,
   why:'Heavy plasma protein binding holds drug in the vascular space, which raises the measured plasma concentration and therefore produces a smaller volume of distribution. This option states the opposite of the slide, and it is chosen when binding is read as a form of sequestration without asking where the drug is being held.'},
  {t:'It is eliminated more quickly', correct:false,
   why:'Elimination speed is set by clearance and by the rate constant, not by the volume of distribution alone. In fact, with clearance held constant a larger volume of distribution lengthens the half-life rather than shortening it, because k = Cl/VD. Reading a large volume as fast elimination inverts that relationship.'},
  {t:'It produces a higher initial plasma concentration', correct:false,
   why:'Initial plasma concentration is the dose divided by the volume of distribution, so with the dose fixed a larger volume gives a lower initial concentration. Selecting this treats a larger distribution volume as if it meant more drug rather than more space for the same drug.'}],
 teach:'The volume of distribution is read backwards from the plasma concentration. The dose is known, so a low measured concentration can only mean the drug is somewhere other than the sampled plasma, and the arithmetic reports that as a large volume. The reverse case is a drug held in the vascular space, whether by plasma protein binding or by poor tissue penetration: the plasma concentration is high and the computed volume is small.',
 cite:'2IVBolusAdministration.pdf, slide "Volume of Distribution" (second slide of that title)',
 quote:'Large VD → more concentrated in extravascular tissues and less concentrated intravascularly. Drug highly bound to plasma proteins or remaining in the vascular region → higher Cp and smaller VD'},

{id:'m2-vd-4', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'vd', concept:'vd-percent-bw', skill:'recall',
 source:'both',
 stem:'A 70 kg patient is given a drug whose apparent volume of distribution is 20% of body weight. What is the volume of distribution?',
 options:[
  {t:'14 L', correct:true,
   why:'Expressing the volume of distribution as a percent of body weight uses the convention that a 1 L volume is assumed to equal the weight of 1 kg, so 20% of 70 kg is 14 kg of body weight and therefore 14 L. Dr. Mosley works exactly this example aloud and insists on the unit: 14 L, not 14 kg, because the volume of distribution is a volume.'},
  {t:'14 kg', correct:false,
   why:'The arithmetic is right and the unit is wrong, and she corrects this out loud in class. A volume of distribution must be reported in units of volume; the kilogram only enters as the bridge that lets a percentage of body weight be converted into litres.'},
  {t:'20 L', correct:false,
   why:'This takes the percentage figure itself as the answer and never multiplies it by the patient weight. A percent of body weight is not a volume until a weight is supplied, which is why the stem gives one.'},
  {t:'3.5 L', correct:false,
   why:'This divides the weight by 20 instead of taking 20% of it, which is the same as using 5% of body weight. The error comes from treating the 20 as a divisor because volume of distribution often appears in a denominator elsewhere.'}],
 teach:'A volume of distribution can be quoted as an absolute volume, per kilogram of body weight, or as a percent of body weight. The percent form needs the one-to-one assumption that 1 L corresponds to 1 kg, and with that in hand the conversion is a single multiplication. In pharmacokinetics body weight is always in kilograms, so a weight given in pounds is converted first and the percentage applied afterwards.',
 cite:'2IVBolusAdministration.pdf, slide "Volume of Distribution" (second slide of that title)',
 quote:'In expressing the apparent VD in terms of percent body weight, a 1-L volume is assumed to be equal to the weight of 1 kg.'},

/* ---------- clearance ---------- */
{id:'m2-cl-1', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'cl', concept:'cl-definition', skill:'recall',
 source:'both',
 stem:'Which parameter describes the elimination of drug in terms of the volume of fluid cleared of drug per unit time?',
 options:[
  {t:'Clearance', correct:true,
   why:'The slide defines clearance as the volume of plasma that is cleared of drug per unit time, and as a measure of drug elimination from the body without identifying the mechanism or process. That last clause is why clearance can be quoted for a whole body without separating metabolism from excretion. Dr. Mosley repeats the definition almost word for word in the exam review.'},
  {t:'Excretion', correct:false,
   why:'Excretion names one route of loss, the removal of intact drug or metabolite, rather than a rate parameter with units. It answers where the drug goes, not how much volume is stripped of it per hour, so it cannot be the quantity the units describe.'},
  {t:'Elimination rate', correct:false,
   why:'An elimination rate is an amount per unit time, such as milligrams per hour, and for a first-order drug it changes continuously as the concentration falls. Clearance is what stays constant while that rate changes; multiplying clearance by the current concentration is what produces the rate.'},
  {t:'Biotransformation', correct:false,
   why:'Biotransformation is the chemical conversion of the drug to another species, so it is a process rather than a measurement. It contributes to clearance through hepatic metabolism, but it carries no volume-per-time meaning of its own.'}],
 teach:'Clearance is deliberately defined without naming a mechanism, so it can describe the whole body at once. Its units are volume per time, which is what makes it a clearance rather than a rate: it says how much fluid is completely stripped of drug each hour, not how many milligrams leave. The amount leaving follows from multiplying clearance by whatever concentration is present at the time.',
 cite:'2IVBolusAdministration.pdf, slide "Clearance"',
 quote:'Volume of plasma that is cleared of drug per unit time'},

{id:'m2-cl-2', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'cl', concept:'cl-equation-sheet', skill:'tell',
 source:'transcript',
 stem:'Two relationships in this course must be carried in memory because Dr. Mosley states they will not be supplied on the exam equation sheet. Which pair is it?',
 options:[
  {t:'Cl = k·VD and t½ = 0.693/k', correct:true,
   why:'She names both explicitly and in the same terms. On 19 August she says the first-order half-life will not be on the equation sheet, and on 24 August she says clearance equals k times VD is another one that will not be on your equation sheet. On 26 August she lists what is already in your bone marrow as clearance and half-life. Everything else she says she will supply.'},
  {t:'Cl = D0/AUC and Cp = DB/VD', correct:false,
   why:'Both of these are on the supplied sheet, so neither has to be supplied from memory. Choosing this pair usually comes from grouping all the clearance relationships together, when the carve-out she named is specifically the product form Cl = k·VD.'},
  {t:'t½ = 0.693/k and Cp = Ae^(−αt) + Be^(−βt)', correct:false,
   why:'The half-life is right and the biexponential equation is not. The two-compartment equations, including the biexponential form and the expressions for k, k12 and k21, are printed on the equation sheet, which is consistent with her saying she will simply give you A, B, alpha and beta.'},
  {t:'Cl = k·VD and the trapezoidal rule for AUC', correct:false,
   why:'Clearance is right and the trapezoidal rule is not. The trapezoidal expression is the first line of the supplied equation sheet, and she has never named it as something to be held in memory.'}],
 teach:'The equation sheet changes what a question is testing. Anything printed on it is testing whether you can choose and rearrange the right relationship. The two she withholds are the two that appear inside almost every other calculation, so a student who cannot produce them from memory cannot begin. Knowing which side of that line a relationship sits on is itself examinable information she has stated repeatedly.',
 cite:'Basic Pharmacokinetics - 08-26 Lecture.txt (quiz debrief); confirmed 08-19 and 08-24 lectures',
 quote:'this is another one that it will not be on your equation sheet cause I want you to take this one with you to your grave along with the half-life equation. Clearance is equal to k times vd.',
 note:'The printed slide carries Cl = kVD without saying whether it is supplied; the note "equation will not be given on EXAM" on this copy of the deck is handwritten and is not used as the source. The text extract of BasicPharmacokineticsEquations.pdf garbles several symbol-only lines, so the sheet cannot be read as confirming or contradicting this. The transcript statement, made three times across three lectures, is what an exam written from these lectures would key.'},

{id:'m2-cl-3', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02', multi:true,
 topic:'bolus1', sub:'cl', concept:'cl-constant', skill:'apply',
 source:'both',
 stem:'A drug follows one-compartment, first-order kinetics. Select every statement that is true of its total body clearance. Select all that apply.',
 options:[
  {t:'It is the product of k and the volume of distribution', correct:true,
   why:'Both k and VD are constants for a given drug in a given patient, so their product is a constant too. Dr. Mosley makes exactly that argument: a constant times a constant is a constant, which is the reason clearance is used as a parameter at all.'},
  {t:'It relates the dose directly to the area under the curve', correct:true,
   why:'Cl = D0/AUC stands on the same slide as Cl = k·VD, and she names this as another reason clearance is liked, because it ties the dose to the area under the curve without requiring any rate constant to be found first. That route is what makes clearance computable from a single dose and a full concentration-time profile.'},
  {t:'It increases in proportion to the plasma concentration present', correct:false,
   why:'This is the poll question she sets in class, and the answer she wanted was false. Changing the concentration changes the rate of elimination in milligrams per hour, but the volume stripped per hour is unchanged. Selecting this confuses the rate with the clearance, which is the single most common error on this parameter.'},
  {t:'It is expressed in units of volume rather than volume per time', correct:false,
   why:'Clearance is volume per unit time, usually litres per hour, and the per-hour is not optional. A quantity in plain litres is a volume of distribution, and dropping the time from the units is exactly what collapses the two parameters into each other.'}],
 teach:'Clearance is prized for being constant while everything visible is changing. The plasma concentration falls, the milligrams removed per hour fall with it, but the volume of plasma stripped of drug per hour does not move. Two routes lead to it: multiply the two constants k and VD, or divide the dose by the area under the whole curve. Both give the same number, in volume per unit time.',
 cite:'2IVBolusAdministration.pdf, slide "Clearance"',
 quote:'what we like about clearance is that clearance. For most drugs in most situations, it is going to be a constant … a constant times a constant is a constant.'},

/* ---------- L02 numeric: her eight-part battery ---------- */
{id:'m2-n-k1', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'k-from-two-points', skill:'krate',
 source:'slide',
 stem:'The data below are plasma concentrations of a new drug at different time points after an intravenous bolus injection of 50 mg to a 70-kg patient. Time (hr) and plasma concentration (mg/L): 0.5 and 2.52; 1.0 and 1.59; 1.5 and 1.00; 2.0 and 0.64; 2.5 and 0.40; 3.0 and 0.25. Using the 1.0 hr and 2.0 hr points, what is the elimination rate constant?',
 units:'hr⁻¹',
 answer:0.9100,
 tol:0.04,
 steps:[
  {k:'setup', t:'k = −slope = [ln Cp1 − ln Cp2] / (t2 − t1), taking the 1.0 hr and 2.0 hr points, which is the pair Dr. Mosley works in her own key',
   why:'On semi-logarithmic axes a first-order decline is a straight line whose slope is −k, so taking natural logarithms of two measured concentrations and dividing by the elapsed time recovers the rate constant. The pair is named in the question because it is the one her key uses; on a perfectly first-order line any pair would give the same slope, but these are measured concentrations rounded to two decimals, so different pairs differ slightly. The rate constant is never negative, so the minus sign is carried on the slope, not on k.'},
  {k:'algebra', t:'k = [ln 1.59 − ln 0.64] / (2.0 − 1.0) hr = ln(1.59/0.64) / 1.0 hr',
   why:'The difference of two natural logarithms is the natural logarithm of their ratio, which is the rearrangement she uses because the concentration units cancel inside the ratio and leave a pure number. Dividing that pure number by a time in hours is what produces reciprocal hours.'},
  {k:'algebra', t:'k = 0.91002 / 1.0 hr = 0.91002 hr⁻¹',
   why:'The ratio 1.59/0.64 is 2.4844 and its natural logarithm is 0.91002. Because the two sampling times are exactly one hour apart the division leaves the logarithm unchanged in magnitude and only attaches the reciprocal-hour unit.'},
  {k:'round', t:'k = 0.9100 hr⁻¹',
   why:'She reports rate constants to four decimal places, and she warns in class not to truncate k early because a k rounded to one or two figures propagates a large error into every later part. Four decimals is the precision her own key prints for this problem.'}],
 teach:'Every rate constant in this module comes from the same operation: take the natural logarithm of the ratio of two concentrations and divide by the time between them. The earlier concentration goes on top so that the ratio exceeds one and the logarithm is positive, which matches the rule that a rate constant is never negative. On data rounded to two decimal places, different pairs of points give slightly different answers, so a question that expects one particular value has to say which pair to use.',
 note:'Her key works the 1.0 hr and 2.0 hr points and prints 0.9100 hr⁻¹. The other adjacent pairs in the same table give 0.893 to 0.940 hr⁻¹, and a least-squares fit through all six points gives 0.922 hr⁻¹, so a student who picked a different pair has not made an error of method; the spread is measurement rounding in the printed concentrations, not a mistake. The tolerance is set wide enough to admit that spread.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part a',
 quote:'k = −slope = −[ln 0.64 − ln 1.59] / (2 − 1) hr = 0.9100 hr⁻¹'},

{id:'m2-n-t1', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'halflife-from-k', skill:'krate',
 source:'slide',
 stem:'A drug given by intravenous bolus injection has an elimination rate constant of 0.91 hr⁻¹. What is its half-life of elimination?',
 units:'hr',
 answer:0.76,
 tol:0.03,
 steps:[
  {k:'setup', t:'t½ = 0.693 / k',
   why:'Setting the concentration to half its starting value in Cp = Cp0·e^(−kt) leaves the natural logarithm of two, 0.693, divided by the rate constant. This relationship is not on the equation sheet, so it has to be recalled rather than looked up.'},
  {k:'algebra', t:'t½ = 0.693 / 0.91 hr⁻¹',
   why:'The rate constant sits in the denominator of the rearranged equation. Dividing a pure number by a quantity in reciprocal hours gives hours, which is the check that the answer will come out as a time rather than a rate.'},
  {k:'round', t:'t½ = 0.76 hr',
   why:'The division gives 0.7615, which her key prints as 0.76 hr, two decimal places. Half-life must be reported in units of time and never in reciprocal time, a distinction she calls out by name in the exam review.'}],
 teach:'Half-life and the elimination rate constant are two readings of the same first-order decline, joined by the natural logarithm of two. Because that logarithm is a fixed number and k is fixed for a given drug and patient, the half-life is fixed too, which is why it does not depend on the starting concentration. The unit is always a time.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part b',
 quote:'t½ = 0.693 / 0.91 hr = 0.76 hr'},

{id:'m2-n-c0a', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'c0-back-extrapolated', skill:'conctime',
 source:'slide',
 stem:'After an intravenous bolus injection of 50 mg, a drug with an elimination rate constant of 0.91 hr⁻¹ has a plasma concentration of 0.40 mg/L at 2.5 hours. What is the initial plasma concentration?',
 units:'mg/L',
 answer:3.89,
 tol:0.08,
 steps:[
  {k:'setup', t:'Cp0 = Cp·e^(+kt)',
   why:'Going backwards along the curve from a measured point to time zero reverses the sign of the exponent in Cp = Cp0·e^(−kt). She warns that always throwing in the minus sign here gives a number lower than the one you started from, which cannot be right, because the initial concentration must be the highest point in the data set.'},
  {k:'algebra', t:'Cp0 = (0.40 mg/L)·e^(0.91 hr⁻¹ × 2.5 hr)',
   why:'Reciprocal hours multiplied by hours leaves the exponent dimensionless, which it must be. The 2.5 hr is the full elapsed time from the dose to the sample being extrapolated from, so the whole decline over that interval is undone in one step.'},
  {k:'algebra', t:'Cp0 = (0.40 mg/L)(9.7279) = 3.8912 mg/L',
   why:'The exponent is 2.275 and e raised to it is 9.7279. Multiplying a concentration by a pure number keeps the concentration unit, so the answer is in milligrams per litre.'},
  {k:'round', t:'Cp0 = 3.89 mg/L',
   why:'Her key prints 3.89 mg/L, three significant figures. The value is higher than the earliest measured concentration of 2.52 mg/L at 0.5 hr, which is the sanity check she asks for: the initial concentration should be the highest point.'}],
 teach:'Back-extrapolation to time zero is the forward equation run in reverse, and the only change is the sign of the exponent. Any measured point on the line can be used, because the line is the same line, and the result is the concentration that would have been measured if sampling had been instantaneous. That extrapolated value, not the first measured sample, is what pairs with the dose to give the volume of distribution.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part c',
 quote:'C₀ = (0.4 mg/L)e^(0.91)(2.5) = 3.89 mg/L'},

{id:'m2-n-c15', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'conc-at-15min', skill:'conctime',
 source:'slide',
 stem:'A drug given by intravenous bolus injection has an initial plasma concentration of 3.89 mg/L and an elimination rate constant of 0.91 hr⁻¹. What is the concentration of drug in the plasma 15 minutes after the dose was given?',
 units:'mg/L',
 answer:3.1,
 tol:0.1,
 steps:[
  {k:'unit', t:'15 min × (1 hr / 60 min) = 0.25 hr',
   why:'The rate constant is in reciprocal hours, so the time must be in hours before the two are multiplied or the exponent will be sixty times too large. She converts 15 minutes to 0.25 hr silently in her key, but the conversion is the step that decides whether the answer is right.'},
  {k:'setup', t:'Cp = Cp0·e^(−kt)',
   why:'This is the forward form of the integrated first-order equation, used whenever a concentration at a stated later time is wanted from a known starting concentration. The minus sign belongs here because the concentration is falling.'},
  {k:'algebra', t:'Cp = (3.89 mg/L)·e^(−0.91 hr⁻¹ × 0.25 hr) = (3.89 mg/L)(0.79652)',
   why:'The exponent is −0.2275, and e raised to it is 0.79652, the fraction of the starting concentration still present. Multiplying the initial concentration by that fraction gives the concentration at 15 minutes.'},
  {k:'round', t:'Cp = 3.0985 mg/L, reported as 3.1 mg/L',
   why:'Her key prints 3.1 mg/L. Since a quarter of an hour is well under one half-life of 0.76 hr, the answer must lie between 3.89 and half of 3.89, which it does.'}],
 teach:'Two things have to agree before this equation can be evaluated: the unit of time in the exponent and the unit of time in the rate constant. Every one of her problems states the interval in minutes at least once, and hours everywhere else, so the conversion is deliberate. Once the exponent is dimensionless, the exponential term is simply the fraction remaining, and multiplying it by the starting concentration finishes the problem.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part d',
 quote:'C₀.₂₅ = (3.89 mg/L)e^−(0.91)(0.25) = 3.1 mg/L'},

{id:'m2-n-vd1', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'vd-from-dose-c0', skill:'vddose',
 source:'slide',
 stem:'A 50 mg intravenous bolus dose produces an initial plasma concentration of 3.89 mg/L in a 70-kg patient. What is the apparent volume of distribution?',
 units:'L',
 answer:12.85,
 tol:0.2,
 steps:[
  {k:'setup', t:'VD = DB / Cp, with DB = D0 at time zero',
   why:'The volume of distribution is the proportionality constant between the amount of drug in the body and the measured plasma concentration, so rearranging Cp = DB/VD puts the amount on top. Immediately after a bolus the amount in the body is the whole dose, which is what lets the dose be used here.'},
  {k:'algebra', t:'VD = 50 mg / 3.89 mg/L',
   why:'The milligrams cancel between numerator and denominator and the litre in the denominator of the concentration inverts, leaving litres. That unit check is also the apples-to-apples check she insists on: an amount is divided by a concentration, never by another amount.'},
  {k:'round', t:'VD = 12.853 L, reported as 12.85 L',
   why:'Her key prints 12.85 L, two decimal places. The patient weight of 70 kg is given in the stem and is not used, which is a habit of hers in these problems.'}],
 teach:'The volume of distribution is always the amount in the body divided by the concentration at the same instant. The convenient instant is time zero, because the amount there is the whole dose and the concentration there is the back-extrapolated initial value. Using a measured later concentration with the full dose would pair an amount from one time with a concentration from another, which is the mismatch she warns about.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part e',
 quote:'V_D = 50 mg / 3.89 mg/L = 12.85 L'},

{id:'m2-n-cl1', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'cl-from-k-vd', skill:'clearance',
 source:'slide',
 stem:'A drug has an apparent volume of distribution of 12.85 L and an elimination rate constant of 0.91 hr⁻¹ in a patient. What is the total body clearance of this drug in this patient?',
 units:'L/hr',
 answer:11.7,
 tol:0.3,
 steps:[
  {k:'setup', t:'ClT = k · VD',
   why:'Total body clearance is the product of the overall elimination rate constant and the volume of distribution. This relationship is one of the two she says will not be supplied on the equation sheet, so it has to be recalled. Both factors are constants, which is why their product is constant too.'},
  {k:'algebra', t:'ClT = (12.85 L)(0.91 hr⁻¹) = 11.6935 L/hr',
   why:'Litres multiplied by reciprocal hours gives litres per hour, which is the unit a clearance must carry. A result in plain litres would mean the rate constant had been left out and a volume of distribution reported instead.'},
  {k:'round', t:'ClT = 11.694 L/hr, reported as 11.7 L/hr',
   why:'Her key prints 11.7 L/hr, three significant figures. Carrying both inputs unrounded, as VD = 12.8535 L and k = 0.91002 hr⁻¹, gives 11.697 L/hr, which rounds to the same value.'}],
 teach:'Clearance in this course is reached by multiplying the two parameters that have already been found. The rate constant says what fraction of the body content leaves per hour; the volume of distribution says how large the body content appears to be; their product says how much volume is stripped of drug per hour. Because both inputs are constants for the drug in that patient, the clearance does not change as the concentration falls.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part f',
 quote:'Cl_T = (12.85 L)(0.91 hr⁻¹) = 11.7 L/hr'},

{id:'m2-n-d3a', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'amount-at-t', skill:'conctime',
 source:'slide',
 stem:'A 50 mg intravenous bolus dose of a drug with a volume of distribution of 12.85 L gives a plasma concentration of 0.25 mg/L at 3 hours. What is the amount of drug in the body 3 hours after the drug was administered?',
 units:'mg',
 answer:3.2,
 tol:0.15,
 steps:[
  {k:'setup', t:'DB = VD · Cp, evaluated at 3 hr',
   why:'The volume of distribution converts a concentration into an amount at any time, not only at time zero, because it is a constant. Since the plasma concentration at 3 hours is already given, this is the shorter of the two routes her key shows.'},
  {k:'algebra', t:'DB = (12.85 L)(0.25 mg/L) = 3.2125 mg',
   why:'Litres multiplied by milligrams per litre leaves milligrams, which is the unit an amount must have. Getting litres out instead would mean the two quantities had been divided rather than multiplied.'},
  {k:'algebra', t:'Alternative route: DB = D0·e^(−kt) = (50 mg)·e^(−0.91 hr⁻¹ × 3 hr) = 3.2610 mg',
   why:'The same amount can be found by decaying the whole dose forward for three hours, which avoids needing the volume of distribution. She prints both routes deliberately. The two differ slightly only because the 0.25 mg/L reading is rounded to two decimal places in the data table.'},
  {k:'round', t:'DB = 3.2 mg by either route',
   why:'Her key gives 3.2 mg from both calculations. Reporting to two significant figures is what makes the two routes agree, which is her reason for showing them side by side.'}],
 teach:'An amount in the body at a stated time can be reached from either direction. If a concentration at that time is available, multiply it by the volume of distribution. If it is not, decay the dose forward with the exponential equation. Both work because the volume of distribution is constant and the decline is first order, so the two answers must agree to within the rounding of the data.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part g',
 quote:'D₃ = (12.85 L)(0.25 mg/L) = 3.2 mg or D₃ = 50 mg · e^−(0.91)(3) = 3.2 mg'},

{id:'m2-n-999a', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'time-to-999', skill:'krate',
 source:'slide',
 stem:'A drug given by intravenous bolus injection has an elimination half-life of 0.76 hours. How much time is required for 99.9% of the drug to be eliminated from the body?',
 units:'hr',
 answer:7.6,
 tol:0.2,
 steps:[
  {k:'setup', t:'99.9% eliminated corresponds to 10 half-lives',
   why:'For a first-order process each half-life leaves half of what was there, so after ten half-lives 0.1% remains and 99.9% has gone. Dr. Mosley states the ten-half-life figure outright as a fact to carry, and her Module 1 key builds the same result from a table of percent remaining.'},
  {k:'algebra', t:'t = 10 × t½ = 10 × 0.76 hr = 7.6 hr',
   why:'Multiplying a count of half-lives by the length of one half-life gives a time. Nothing needs to be exponentiated because the percentage asked for is a power of one half, which is the route she prefers whenever it is available.'},
  {k:'algebra', t:'Logarithmic route: t = ln(100/0.1) / k = ln(1000) / 0.91 hr⁻¹ = 7.591 hr',
   why:'Setting the fraction remaining to 0.001 in Cp = Cp0·e^(−kt) and solving for t gives the natural logarithm of 1000 divided by k. This is the general route for percentages that are not powers of one half, and she prints it beside the half-life count in the parallel problem.'},
  {k:'round', t:'t = 7.6 hr',
   why:'Her key gives 7.6 hr. The small gap between 7.6 and the exact 7.59 is the rounding already carried in the half-life of 0.76 hr, so both routes report the same answer at this precision.'}],
 teach:'Elimination of a fixed percentage takes a fixed number of half-lives regardless of the dose, because a first-order process removes proportions rather than amounts. Ten half-lives for 99.9% recurs in every one of her bolus problem sets. When the percentage is not a clean power of one half, set the fraction remaining into the exponential equation and solve for time instead.',
 cite:'IV-Bolus-Practice-1---Solutions.pdf, part h',
 quote:'First order processes, it is gonna take 10 half-lives for 99.9% of the drug to be eliminated from the body.'},

/* ---------- L02 numeric: second wording, two plasma points ---------- */
{id:'m2-n-k2', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'k-from-two-points', skill:'krate',
 source:'slide', dupOf:'m2-n-k1',
 stem:'250 mg of an antibiotic was administered as an IV bolus injection to a 70-kg patient. The concentration at 4 and 8 hours after administration of the dose was 6.6 mcg/mL and 2.18 mcg/mL, respectively. What is the elimination rate constant?',
 units:'hr⁻¹',
 answer:0.2769,
 tol:0.008,
 steps:[
  {k:'setup', t:'k = ln(Cp1/Cp2) / (t2 − t1)',
   why:'Two concentrations at two times define the slope of the log-linear decline, and the rate constant is that slope with the sign reversed. The earlier and larger concentration goes on top so the logarithm is positive, which is what keeps k from coming out negative.'},
  {k:'unit', t:'6.6 mcg/mL = 6.6 mg/L and 2.18 mcg/mL = 2.18 mg/L',
   why:'Dr. Mosley tells the class to take it on her word that micrograms per millilitre equals milligrams per litre, so no arithmetic conversion is needed. Here the units cancel inside the ratio anyway, but the equivalence matters for the later parts that pair a concentration with a dose in milligrams.'},
  {k:'algebra', t:'k = ln(6.6/2.18) / (8 − 4) hr = 1.10774 / 4 hr',
   why:'The ratio 6.6/2.18 is 3.0275 and its natural logarithm is 1.10774. Dividing by the four-hour interval between the samples converts a dimensionless logarithm into a quantity in reciprocal hours.'},
  {k:'round', t:'k = 0.2769 hr⁻¹',
   why:'The quotient is 0.276936, which her key prints as 0.2769 hr⁻¹. She asks for three to four decimal places on k so that early truncation does not shift every downstream answer.'}],
 teach:'The same two-point slope calculation works whether the data arrive as a table of six samples or as two concentrations stated in a sentence. What changes is only which two numbers are available. The interval in the denominator is the difference between the two sampling times, not the time since the dose, which is the step most often lost when the points are given in prose.',
 cite:'IV-Bolus-Practice-2---Solutions.pdf, part a',
 quote:'k = −ln(6.6/2.18) / (4 − 8) hr = 0.2769 hr⁻¹'},

/* ---------- L02 numeric: pounds, mg/kg, VD as % of body weight ---------- */
{id:'m2-n-cl2', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'cl-from-k-vd', skill:'clearance',
 source:'slide', dupOf:'m2-n-cl1',
 stem:'A 187-pound male patient received a drug by rapid IV injection. The drug has a half-life of 4 hours and an apparent volume of distribution that is 20% of body weight. What is the total body clearance in this patient?',
 units:'L/hr',
 answer:2.95,
 tol:0.08,
 steps:[
  {k:'unit', t:'187 lb ÷ 2.2 lb/kg = 85.0 kg',
   why:'Body weight in pharmacokinetics is always in kilograms, so a weight stated in pounds is converted before anything else is done with it. She divides by 2.2 and does not show the step, but every absolute quantity in this problem depends on it.'},
  {k:'setup', t:'ClT = k · VD, so the half-life has to become a rate constant and the percentage of body weight has to become an absolute volume before the two can be multiplied',
   why:'Total body clearance is the product of the elimination rate constant and the apparent volume of distribution, and neither is handed over directly here: the stem gives a half-life and a percentage. Naming the relation first is what shows which two quantities have to be assembled. Dr. Mosley withholds this relation from the exam equation sheet, so it has to be known rather than looked up.'},
  {k:'algebra', t:'VD = 0.2 L/kg × 85.0 kg = 17.0 L',
   why:'A volume of distribution that is 20% of body weight becomes 0.2 L per kilogram under the assumption that 1 L corresponds to 1 kg. Multiplying by the patient weight in kilograms converts it into the absolute volume that clearance needs.'},
  {k:'algebra', t:'k = 0.693 / 4 hr = 0.1733 hr⁻¹',
   why:'The clearance equation takes a rate constant, not a half-life, so the stated half-life is converted first. Her keys report k to four decimal places throughout.'},
  {k:'algebra', t:'ClT = k·VD = (0.1733 hr⁻¹)(17.0 L) = 2.9461 L/hr',
   why:'Reciprocal hours multiplied by litres gives litres per hour. This is the relationship she withholds from the equation sheet, so both factors have to be assembled before it can be used.'},
  {k:'round', t:'ClT = 2.95 L/hr',
   why:'Her key prints 2.95 L/hr, two decimal places. Carrying k unrounded as 0.17325 hr⁻¹ gives 2.9453 L/hr, which rounds to the same value.'}],
 teach:'A clearance question with the weight in pounds is really three steps stacked. Convert the weight to kilograms, turn the per-kilogram or percent-of-body-weight volume into an absolute volume in litres, and convert the half-life into a rate constant. Only then does the one-line product k·VD apply. Each of the three steps has its own unit check, and skipping any of them changes the answer by a whole factor rather than a rounding.',
 cite:'IV-Bolus-Practice-3---Solutions.pdf, problem 1 part c',
 quote:'Cl_T = (17 L)(0.1733 hr⁻¹) = 2.95 L/hr'},

{id:'m2-n-deck12', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L02',
 topic:'bolus1', sub:'calc', concept:'amount-at-t', skill:'conctime',
 source:'both', dupOf:'m2-n-d3a',
 stem:'A new drug was administered as a single IV dose of 200 mg to an 80-kg adult male. After 6 hours the plasma drug concentration was 15 mg/L of plasma. Assuming that the apparent VD is 10% of body weight, estimate the amount of drug in the body after 12 hours.',
 units:'mg',
 answer:72.0,
 tol:1.5,
 steps:[
  {k:'setup', t:'The amount left at 12 hr is DB = D0·e^(−kt), so the rate constant has to be recovered first from the measured 6-hour concentration by way of the volume of distribution',
   why:'The question asks for an amount at a time no measurement was taken at, so the route runs through the rate constant rather than through the data directly. The one measured concentration becomes an amount only once the volume of distribution is known, and that volume is given as a percentage of body weight rather than as a number of litres. Naming the whole chain first is what keeps the three conversions in order.'},
  {k:'algebra', t:'VD = 10% of 80 kg = 8 L, using 1 L per 1 kg of body weight',
   why:'The volume of distribution is stated as a percent of body weight, so the one-to-one litre-per-kilogram assumption converts it to an absolute volume. Dr. Mosley confirms 8 L with the class before going any further.'},
  {k:'algebra', t:'DB at 6 hr = VD · Cp = (8 L)(15 mg/L) = 120 mg',
   why:'The measured quantity is a concentration but the rate constant has to be found from two amounts or two concentrations of the same kind. Converting the 6-hour concentration into an amount lets it be compared directly with the 200 mg dose, which is the apples-to-apples step she insists on.'},
  {k:'algebra', t:'k = ln(D0/D6) / t = ln(200 mg / 120 mg) / 6 hr = 0.08514 hr⁻¹',
   why:'The dose is the amount at time zero and 120 mg is the amount at 6 hours, so their ratio over the 6-hour interval gives the rate constant. Because both are amounts in milligrams, the units cancel inside the logarithm.'},
  {k:'algebra', t:'DB at 12 hr = D0·e^(−kt) = (200 mg)·e^(−0.08514 hr⁻¹ × 12 hr) = 72.0 mg',
   why:'The exponent is −1.0217 and e raised to it is 0.3600, so 36% of the dose remains at 12 hours. Milligrams multiplied by a dimensionless fraction leaves milligrams.'},
  {k:'round', t:'DB = 72 mg',
   why:'She reports 72-ish milligrams in class and the handwritten working on the slide agrees. Twelve hours is a little under two half-lives of roughly 8.14 hr, so somewhat more than a quarter of 200 mg should remain, which 72 mg is.'}],
 teach:'This problem hides a unit mismatch in the middle. The dose is an amount and the measured value is a concentration, and a rate constant cannot be taken from the ratio of one to the other. The volume of distribution is what converts between them, so it is found first even though the question does not ask for it. Once both quantities are amounts, the ordinary two-point slope calculation applies.',
 cite:'2IVBolusAdministration.pdf, slide "Practice" (one-compartment section)',
 quote:'estimate the amount of drug in the body after 12 hours',
 note:'She reports the half-life of this drug as 8.15 hr in class, which follows from k rounded to 0.085 hr⁻¹. Carrying k unrounded at 0.085138 hr⁻¹ gives 8.14 hr. The 12-hour amount is 72 mg either way, so this question keys the amount rather than the half-life.'},

/* ════════════════ L03 — MULTICOMPARTMENT IV BOLUS ════════════════ */

{id:'m2-mc-1', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'why', concept:'why-multicpt', skill:'recall',
 source:'both',
 stem:'Why do some drugs require a multicompartment rather than a one-compartment model?',
 options:[
  {t:'They reach different tissues at different rates', correct:true,
   why:'Multicompartment models describe the observation that some drugs distribute at various rates into different tissue groups. Dr. Mosley puts the same point as the drug going preferentially to some organs before it is widely distributed uniformly throughout the body. That staggered distribution is what the one-compartment assumption of instantaneous uniformity cannot represent.'},
  {t:'They are eliminated by more than one route', correct:false,
   why:'Multiple elimination routes are already handled inside the one-compartment model, where k is the sum of km and ke. Adding a metabolic route does not change the shape of the plasma curve, so it cannot be what forces a second compartment.'},
  {t:'They follow zero-order rather than first-order elimination', correct:false,
   why:'Kinetic order and compartment count are separate questions. A zero-order decline would be a straight line on linear axes; the two-compartment signature is a curve that is biphasic on logarithmic axes while remaining first order throughout.'},
  {t:'They are given by a route other than intravenous bolus', correct:false,
   why:'The multicompartment material in this module is taught specifically for intravenous bolus administration, so the route is not what distinguishes it. A different route changes the input function, which is the subject of the infusion and oral absorption modules.'}],
 teach:'The compartment count is decided by what the plasma curve looks like, and the plasma curve reflects how quickly the drug reaches its various destinations. If everything equilibrates fast enough to look instantaneous, one compartment suffices. If some tissues take up drug measurably more slowly than others, the plasma concentration falls steeply at first as drug moves into them and then more gently once that redistribution is complete, and two compartments are needed to describe the two slopes.',
 cite:'2IVBolusAdministration.pdf, slide "One- versus Two-Compartment Models"',
 quote:'Multi-compartment models describe the observation of some drugs that distribute at various rates into different tissue groups'},

{id:'m2-mc-2', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'why', concept:'graph-id', skill:'read',
 source:'transcript',
 stem:'A plasma concentration-versus-time curve after an intravenous bolus dose is plotted on a logarithmic concentration scale. The curve has a steep initial segment that then bends into a shallower straight segment. What does that shape indicate?',
 options:[
  {t:'A two-compartment model', correct:true,
   why:'On a logarithmic scale a one-compartment first-order decline is a single straight line. A curve that is steep and then bends into a shallower line has two slopes, which means two processes with different rate constants, and the first of them is distribution into the tissue compartment. Dr. Mosley states this as a graph-reading rule she will use on the exam.'},
  {t:'A one-compartment model', correct:false,
   why:'A one-compartment model gives one straight line on a logarithmic scale, not a bend, because a single first-order process has a single slope. Choosing this usually means reading the shallow later segment on its own and ignoring the steep segment that precedes it.'},
  {t:'A zero-order elimination process', correct:false,
   why:'Zero-order elimination is a straight line on a linear scale and a curve on a logarithmic scale, and it produces no two-slope bend. She warns specifically against calling a line zero order without first checking whether the scale is logarithmic.'},
  {t:'A drug given by oral administration', correct:false,
   why:'An oral curve rises to a peak before falling, because absorption competes with elimination at early times. The curve described here starts at its maximum and only ever falls, which is what identifies the input as a bolus.'}],
 teach:'Read the axis before reading the line. On a logarithmic concentration scale, the number of straight segments equals the number of exponential terms in the equation. One segment means one compartment and one rate constant. Two segments joined by a bend mean two exponential terms, a fast one for distribution and a slow one for elimination, and the model needs two compartments to produce them.',
 cite:'Basic Pharmacokinetics - 08-26 Lecture.txt (exam cue on graph reading)',
 quote:'if I give you a graph that looks something like this without the red and blue and just a log scale and I am telling you that it is an IV bolus dose … That should say to you that this is a two compartment model.',
 note:'The deck slide "Why Multicompartment Models?" plots log Cp against time without labelling the scale as logarithmic. Dr. Mosley supplies the reading rule out loud and repeats it in the exam review, so the rule is taken from the transcript. An exam written from these lectures would expect the scale to be inferred from the axis values.'},

{id:'m2-mc-3', type:'match', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'why', concept:'tissue-groups', skill:'read',
 source:'slide',
 stem:'Match each tissue group to the percent of body weight it makes up.',
 left:['Heart, brain, hepatic-portal system, kidney and endocrine glands',
       'Skin and muscle',
       'Adipose tissue and marrow',
       'Bone, ligaments, tendons, cartilage, teeth and hair'],
 right:['9%', '50%', '19%', '22%'],
 pairs:[
  {l:'Heart, brain, hepatic-portal system, kidney and endocrine glands', r:'9%',
   why:'These are the highly perfused organs, and they make up the smallest share of body weight of the four groups while receiving the largest share of cardiac output. That mismatch between mass and blood supply is why drug reaches them first and why they dominate the early distribution phase.'},
  {l:'Skin and muscle', r:'50%',
   why:'Skin and muscle are half the body weight and sit between the highly and the slowly perfused extremes. Their bulk is why drug moving into them shifts the plasma concentration noticeably even at a moderate perfusion rate.'},
  {l:'Adipose tissue and marrow', r:'19%',
   why:'Fat and marrow are grouped together on the slide at 19% of body weight. Their perfusion is lower than that of muscle, so lipophilic drugs continue to accumulate there after the fast compartments have equilibrated.'},
  {l:'Bone, ligaments, tendons, cartilage, teeth and hair', r:'22%',
   why:'These are the slowly perfused tissues at 22% of body weight. Their blood supply is low enough that drug entering them contributes little to the shape of the plasma curve over the sampling period of a typical study.'}],
 teach:'The grouping is by blood supply, and the percent-of-body-weight column is there to show that mass and perfusion do not track each other. The organs that see the drug first are only 9% of the body, and the tissues that make up half the body weight see it more slowly. The distribution phase of a two-compartment curve is the plasma concentration falling as drug moves from the small, fast group into the larger, slower ones.',
 cite:'2IVBolusAdministration.pdf, slide "General Grouping of Tissues According to Blood Supply"',
 note:'Dr. Mosley tells the class not to memorise tables unless she says otherwise, and on this table specifically she says "general grouping of tissues, table, don\'t panic". She also adds a qualification that is not on the slide: the brain is listed as highly perfused, but the blood-brain barrier keeps many drugs out, so the brain is not necessarily seen in the distribution phase. An exam written from these lectures would test the perfusion ordering rather than the exact percentages.'},

{id:'m2-mc-4', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'two-cpt-structure', skill:'recall',
 source:'both',
 stem:'In the two-compartment open model used in this course for intravenous bolus injection, from where is drug eliminated?',
 options:[
  {t:'From the central compartment only', correct:true,
   why:'The model diagram places the elimination rate constant k on the central compartment, with k12 and k21 moving drug reversibly between the central and tissue compartments. Dr. Mosley describes it as drug equilibrating with the peripheral compartment while being eliminated from the central compartment only, and says this is the version used most of the time.'},
  {t:'From the tissue compartment only', correct:false,
   why:'The slide showing examples of two-compartment models does include a variant with elimination from the tissue compartment, but it is not the one this course uses. Choosing it puts the exit on the wrong side of the diagram, which changes the differential equations and every rate-constant expression that follows.'},
  {t:'From both compartments at equal rates', correct:false,
   why:'Equal elimination from both compartments would collapse the distinction between them, since the two would then differ only in their transfer constants. The model is built precisely so that one compartment is the site of both measurement and elimination.'},
  {t:'From whichever compartment holds the higher concentration', correct:false,
   why:'Elimination is a structural feature of the model, fixed when the model is drawn, not something that moves with the concentrations. The concentrations decide the rates of transfer through k12 and k21, but not the location of the exit.'}],
 teach:'The two-compartment open model has three arrows. Drug moves from central to tissue at k12, back from tissue to central at k21, and out of the body from the central compartment at k. The central compartment is also the one that is sampled, which is why plasma concentration reflects elimination directly and reflects tissue uptake only through its effect on the central concentration.',
 cite:'2IVBolusAdministration.pdf, slide "Two-Compartment Open Model (IV Bolus Injection)"',
 quote:'if we have got a central compartment, it is going to and from that tissue compartment … and then that the drug is being eliminated from the central compartment only.'},

{id:'m2-mc-5', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'two-cpt-diffeq', skill:'read',
 source:'slide',
 stem:'The two-compartment open model is written as dCt/dt = k12·Cp − k21·Ct for the tissue compartment. What does the equation for the central compartment, dCp/dt = k21·Ct − k12·Cp − k·Cp, add?',
 options:[
  {t:'A loss term for elimination from the body', correct:true,
   why:'The first two terms mirror the tissue equation with the signs reversed, since drug returning from tissue is a gain to the central compartment and drug leaving for tissue is a loss. The third term, −k·Cp, has no counterpart in the tissue equation because it is drug leaving the body altogether, and in this model that happens only from the central compartment.'},
  {t:'A gain term for drug entering from the tissue compartment', correct:false,
   why:'The gain from tissue is the k21·Ct term, which is already present in both equations as the reverse of the transfer described by k12. The term that appears in one equation and not the other is the elimination term.'},
  {t:'A term describing input of the bolus dose', correct:false,
   why:'A bolus is instantaneous, so it appears as the initial condition rather than as a term in the differential equation. Input terms belong to infusion and oral models, where drug continues to arrive over time.'},
  {t:'A term for drug binding to plasma proteins', correct:false,
   why:'Protein binding is not represented explicitly in this model; its effect is absorbed into the volume of distribution and into the transfer constants. Nothing in either differential equation distinguishes bound from unbound drug.'}],
 teach:'Read a compartmental differential equation as a bookkeeping statement: everything entering the compartment is positive, everything leaving is negative. The two transfer terms appear in both equations with opposite signs because what leaves one compartment arrives in the other. The elimination term appears only where the exit is, which in this model is the central compartment, and that asymmetry is the whole structural content of the diagram.',
 cite:'2IVBolusAdministration.pdf, slide "Two-Compartment Open Model (IV Bolus Injection)"',
 quote:'dCp/dt = k21·Ct − k12·Cp − k·Cp'},

{id:'m2-mc-6', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'transfer-constants', skill:'tell',
 source:'both',
 stem:'What do k12 and k21 describe in the two-compartment open model?',
 options:[
  {t:'Movement of drug between the two compartments', correct:true,
   why:'k12 is the transfer constant from compartment one, the central compartment, to compartment two, the tissue compartment, and k21 is the return. Dr. Mosley calls them transfer constants and describes them as how fast the drug goes from the central compartment to the peripheral compartment and back and forth. Neither removes drug from the body.'},
  {t:'Elimination of drug by metabolism and by excretion', correct:false,
   why:'Metabolism and excretion are km and ke, and both are routes out of the body that sum into k. The transfer constants describe movement within the body, so drug governed by them is still present and still counted in the total amount.'},
  {t:'The slopes of the distribution and elimination phases', correct:false,
   why:'Those slopes are alpha and beta, which are hybrid constants derived from k, k12 and k21 together. The transfer constants are what the curve is fitted back to, not what is read off it, which is why the equation sheet gives expressions for k12 and k21 in terms of A, B, alpha and beta rather than the reverse.'},
  {t:'The volumes of the central and tissue compartments', correct:false,
   why:'Volumes are Vp and Vt and carry units of litres, whereas rate constants carry reciprocal time. The two are linked by Vt = Vp·k12/k21, which is a relationship between them rather than an identity.'}],
 teach:'Two kinds of constant operate in this model and the subscript tells you which. A single subscript or none at all means loss from the body: k, km, ke. A double subscript means movement between compartments, read in order from the source compartment to the destination. Transfer constants conserve the drug; elimination constants do not.',
 cite:'2IVBolusAdministration.pdf, slide "Two-Compartment Open Model (IV Bolus Injection)"',
 quote:'our K12 and our K21. Remember, those are our transfer constants, so how fast is the drug going from one compartment or the central compartment to the peripheral compartment and back and forth.'},

{id:'m2-mc-7', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'residuals', skill:'recall',
 source:'both',
 stem:'What is the method of residuals, also called feathering or peeling?',
 options:[
  {t:'Subtraction of the extrapolated line from the observed data', correct:true,
   why:'The slide defines it as a procedure for fitting a curve to experimental data when the drug does not clearly follow a one-compartment model, and states that the residual concentrations of the rapidly distributed phase are obtained by subtracting the extrapolated line from the observed data. The extrapolated line is the terminal elimination phase carried back to time zero; what is left over at early times is the distribution term.'},
  {t:'A method for measuring drug remaining in the tissue compartment', correct:false,
   why:'Nothing in the procedure measures tissue at all. Dr. Mosley points out that plasma is what gets sampled and that tissue concentrations are theoretical for this purpose, so the method works entirely from plasma data.'},
  {t:'A way of correcting for drug bound to plasma proteins', correct:false,
   why:'Protein binding is not what the residuals represent. The residual is the difference between what was observed early and what the elimination phase alone would have predicted, and that difference is distribution into tissue.'},
  {t:'A technique for choosing which two data points give the rate constant', correct:false,
   why:'Picking two points off a straight line is the one-compartment calculation and needs no special method. Residuals exist because the early data are not on the terminal straight line at all, so no choice of two early points would give the elimination rate constant.'}],
 teach:'The method of residuals separates two overlapping exponential processes. The later data lie on the elimination phase alone, because distribution has finished, so a straight line fitted there and extrapolated back to time zero gives B and beta. Subtracting that extrapolated line from the observed early concentrations leaves the distribution contribution, and a straight line through those residuals gives A and alpha.',
 cite:'2IVBolusAdministration.pdf, slide "Method of Residuals"',
 quote:'Residual plasma concentration (rapidly distributed a phase) is obtained by subtracting the extrapolated line from observed data',
 note:'The slide presents the method as a procedure to be carried out. Dr. Mosley says in the 26 August lecture that she wants the concept known but will not ask students to perform it, and that she will supply A, B, alpha and beta instead. This question therefore tests the definition only; an exam written from these lectures would not ask for a feathered fit.'},

{id:'m2-mc-8', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'abab-meaning', skill:'read',
 source:'both',
 stem:'A drug given by intravenous bolus is described by Cp = A·e^(−αt) + B·e^(−βt). What are A and B?',
 options:[
  {t:'The intercepts of the two phases', correct:true,
   why:'A and B are the values each exponential term takes at time zero, so they are the intercepts obtained by extrapolating the distribution and elimination lines back to the vertical axis. Dr. Mosley names them as the intercepts and the lowercase alpha and beta as the slopes. Their sum is the initial plasma concentration.'},
  {t:'The slopes of the two phases', correct:false,
   why:'The slopes are alpha and beta, which sit in the exponents and carry units of reciprocal time. A and B sit in front and carry units of concentration, which is the quickest way to tell them apart on an unlabelled equation.'},
  {t:'The volumes of the two compartments', correct:false,
   why:'Volumes are Vp and Vt in litres, and they are calculated from A and B rather than being them. The central volume is the dose divided by the sum A + B, so confusing the two would make the volume of distribution a concentration.'},
  {t:'The transfer rate constants between the compartments', correct:false,
   why:'Transfer constants are k12 and k21 and carry reciprocal time. The equation sheet gives them in terms of A, B, alpha and beta, which shows that the two sets are different quantities rather than alternative names.'}],
 teach:'A biexponential equation has four parameters and they come in two pairs. Each pair is one phase: a coefficient in front, which is that phase extrapolated to time zero and has the units of concentration, and a rate constant in the exponent, which is that phase slope and has units of reciprocal time. Reading the units off the equation is enough to assign any of the four correctly.',
 cite:'2IVBolusAdministration.pdf, slide "Concentration of Drug in the Central Compartment"',
 quote:'Is our B intercept. And The slope here is going to be our beta or our lowercase b. And the intercept here is going to be capital A and the slope is going to be A or alpha.'},

{id:'m2-mc-9', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'alpha-gt-beta', skill:'recall',
 source:'both',
 stem:'In the biexponential equation for a two-compartment model, why is alpha larger than beta?',
 options:[
  {t:'Distribution happens faster than elimination', correct:true,
   why:'Alpha is the rate constant of the distribution phase and beta that of the elimination phase, and a drug reaches its tissues faster than it leaves the body. Dr. Mosley says alpha is bigger because the distribution phase is going to happen a lot faster than the elimination phase. This is also how the two terms are identified when an equation is handed over with no labels.'},
  {t:'The distribution phase lasts longer than the elimination phase', correct:false,
   why:'The distribution phase is the shorter of the two, which is exactly why its rate constant is larger. A large rate constant means a short half-life, so a term with a large alpha decays away quickly and leaves the slower term to dominate the rest of the curve.'},
  {t:'More drug is distributed than is eliminated', correct:false,
   why:'The relative size of alpha and beta says nothing about how much drug takes each path, only how fast each process runs. The amounts are governed by the intercepts A and B, and in some drugs B exceeds A even though beta is the smaller rate constant.'},
  {t:'Alpha is measured on a logarithmic scale and beta is not', correct:false,
   why:'Both are read from the same logarithmic plot and both are ordinary first-order rate constants in reciprocal time. Nothing about the scale differs between them; only the steepness of the segment each is fitted to differs.'}],
 teach:'When a biexponential equation is supplied without labels, the larger rate constant is the distribution term and the smaller one is elimination. That ordering is what makes the curve steep first and shallow later, and it is why the terminal straight segment carries beta. Dr. Mosley also notes the consequence of the ordering failing: if elimination were fast relative to distribution, the drug would never build to an effective concentration.',
 cite:'2IVBolusAdministration.pdf, slide "Concentration of Drug in the Central Compartment"',
 quote:'Alpha bigger because the, the distribution phase is gonna happen a lot faster than an elimination phase'},

{id:'m2-mc-10', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'beta-halflife', skill:'tell',
 source:'transcript',
 stem:'A two-compartment drug is described by Cp = A·e^(−αt) + B·e^(−βt). How is the elimination half-life obtained?',
 options:[
  {t:'Divide 0.693 by beta', correct:true,
   why:'Beta is the elimination rate constant for a two-compartment drug, so the ordinary half-life relationship applies to it directly. Dr. Mosley says not to complicate it by solving for the overall k first and then dividing, because that is more work for the same answer. She also says she will name it as either the beta half-life or the elimination half-life so that there is no ambiguity.'},
  {t:'Divide 0.693 by alpha', correct:false,
   why:'Alpha belongs to the distribution phase, and its half-life describes how quickly drug reaches the tissues rather than how quickly it leaves the body. She says outright that the half-life of the distribution phase is not what the course cares about.'},
  {t:'Solve for the overall rate constant k from A, B, alpha and beta, then divide 0.693 by k', correct:false,
   why:'This gives a different number and is the specific detour she warns against. The overall k is a composite that includes the transfer constants, whereas beta is what the terminal slope of the plasma curve actually is, and the terminal slope is what governs the drug disappearing from the body.'},
  {t:'Divide 0.693 by the sum of alpha and beta', correct:false,
   why:'Adding two rate constants that belong to different phases produces a quantity with no meaning in the model. Intercepts are summed to give the initial concentration; the exponents are never summed.'}],
 teach:'In a two-compartment drug, beta is the elimination rate constant, so the half-life relationship from module one applies unchanged with beta in place of k. The overall k that appears on the equation sheet is a different quantity, computed from the intercepts and both exponents, and it describes elimination from the central compartment within the model rather than the terminal decline of the whole curve.',
 cite:'2IVBolusAdministration.pdf, slide "Beta Half-life"; Basic Pharmacokinetics - 08-26 Lecture.txt (exam cues on beta half-life)',
 quote:'we do not really care about the half-life of the distribution phase. We care about the half-life of the elimination phase … 0.693 over B or beta'},

{id:'m2-mc-11', type:'match', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'params', concept:'apparent-volumes', skill:'multicpt',
 source:'slide',
 stem:'Match each apparent volume expression for a two-compartment model to what it requires.',
 left:['Vp = D0 / (A + B)', 'Vp = D0 / (k · AUC)', 'Vt = Vp · k12 / k21'],
 right:['The dose and the two intercepts',
        'The dose, the overall rate constant and the area under the curve',
        'The central volume and the two transfer constants'],
 pairs:[
  {l:'Vp = D0 / (A + B)', r:'The dose and the two intercepts',
   why:'Because A + B is the plasma concentration at time zero, this is the same dose-over-initial-concentration relationship used in the one-compartment model, applied to the central compartment. It needs nothing but the dose and the two intercepts, which is why it is the route her practice sets always take.'},
  {l:'Vp = D0 / (k · AUC)', r:'The dose, the overall rate constant and the area under the curve',
   why:'This route reaches the same central volume through the area under the whole concentration-time curve rather than through the extrapolated intercepts. It requires the overall rate constant k, which must itself be computed from A, B, alpha and beta, so it is the longer of the two routes to the same volume.'},
  {l:'Vt = Vp · k12 / k21', r:'The central volume and the two transfer constants',
   why:'The tissue volume is not obtained from the dose at all, because the tissue compartment is never sampled. It is scaled from the central volume by the ratio of the two transfer constants, which is the model saying how much drug the tissue holds relative to plasma at equilibrium.'}],
 teach:'A two-compartment model supports several volumes because there is more than one compartment to have a volume. The central volume Vp is the one that pairs with the measured plasma concentration and can be reached either from the intercepts or from the area under the curve. The tissue volume Vt has no directly measurable concentration behind it, so it is derived from the central volume and the ratio of the transfer constants.',
 cite:'2IVBolusAdministration.pdf, slide "Apparent Volumes of Distribution"',
 quote:'Can calculate several different volumes of distribution for multi-compartment models'},

/* ---------- L03 numeric ---------- */
{id:'m2-n-tb1', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'beta-halflife-calc', skill:'multicpt',
 source:'slide',
 stem:'A 300-mg IV bolus dose of a drug was administered to six healthy volunteers. The parameters below best describe the pharmacokinetics of the drug: A = 10.21 mg/L, B = 8.53 mg/L, α = 3.14 hr⁻¹, β = 0.198 hr⁻¹. What is the elimination half-life in these volunteers?',
 units:'hr',
 answer:3.5,
 tol:0.1,
 steps:[
  {k:'setup', t:'t½β = 0.693 / β',
   why:'Beta is the elimination rate constant for a two-compartment drug, so the half-life relationship applies to it directly. The larger exponent alpha belongs to the distribution phase and is not used here.'},
  {k:'algebra', t:'t½β = 0.693 / 0.198 hr⁻¹ = 3.5000 hr',
   why:'Dividing the dimensionless 0.693 by a rate constant in reciprocal hours leaves hours. No other parameter from the stem enters, which is why she instructs students not to solve for the overall k first.'},
  {k:'round', t:'t½β = 3.5 hr',
   why:'Her key prints 3.5 hr, one decimal place. Half-life must be reported in units of time, never in reciprocal time.'}],
 teach:'A two-compartment problem often hands over four parameters when only one is needed. Sorting them first by unit and then by role is what keeps the calculation short: the two in reciprocal time are the rate constants, the smaller of those is elimination, and the elimination half-life follows in one division. The intercepts and the dose belong to the other parts of the problem.',
 cite:'IV-Bolus-Practice-3---Solutions.pdf, problem 2 part a',
 quote:'t½β = 0.693 / 0.198 hr⁻¹ = 3.5 hr'},

{id:'m2-n-c0ab', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'c0-a-plus-b', skill:'multicpt',
 source:'slide',
 stem:'A 300-mg IV bolus dose of a drug was administered to six healthy volunteers. A = 10.21 mg/L, B = 8.53 mg/L, α = 3.14 hr⁻¹ and β = 0.198 hr⁻¹. What is the initial concentration of drug in the plasma in these volunteers?',
 units:'mg/L',
 answer:18.74,
 tol:0.1,
 steps:[
  {k:'setup', t:'Cp0 = A + B',
   why:'Setting t to zero in Cp = A·e^(−αt) + B·e^(−βt) makes both exponential terms equal one, so the initial concentration is simply the sum of the two coefficients. This is why A and B are called intercepts: each is its own phase extrapolated back to the vertical axis.'},
  {k:'algebra', t:'Cp0 = 10.21 mg/L + 8.53 mg/L = 18.74 mg/L',
   why:'Both intercepts are already in milligrams per litre, so they add directly with no conversion. Only quantities in the same units may be added, which is the check that the intercepts and not the exponents are being summed.'},
  {k:'round', t:'Cp0 = 18.74 mg/L',
   why:'Her key prints 18.74 mg/L, two decimal places, matching the precision the two intercepts were given to.'}],
 teach:'The initial plasma concentration of a two-compartment drug is the sum of the intercepts, because at time zero every exponential term equals one. The result is a concentration, so it carries the units of A and B and not of alpha or beta. This same sum is what the dose is divided by to obtain the volume of the central compartment.',
 cite:'IV-Bolus-Practice-3---Solutions.pdf, problem 2 part b',
 quote:'C₀ = (10.21 + 8.53) mg/L = 18.74 mg/L'},

{id:'m2-n-vp1', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'vp-from-intercepts', skill:'multicpt',
 source:'slide',
 stem:'A 300-mg IV bolus dose of a drug was administered to six healthy volunteers. A = 10.21 mg/L, B = 8.53 mg/L, α = 3.14 hr⁻¹ and β = 0.198 hr⁻¹. What is the volume of distribution of the central compartment?',
 units:'L',
 answer:16.0,
 tol:0.4,
 steps:[
  {k:'setup', t:'Vp = D0 / (A + B)',
   why:'The sum A + B is the plasma concentration at time zero, and the amount in the body at time zero is the whole dose, so this is the ordinary amount-over-concentration relationship applied to the central compartment. The equation is printed on the supplied equation sheet.'},
  {k:'algebra', t:'Vp = 300 mg / (10.21 + 8.53) mg/L = 300 mg / 18.74 mg/L',
   why:'The two intercepts are summed first because the denominator is the whole initial concentration, not either phase alone. Milligrams divided by milligrams per litre leaves litres.'},
  {k:'round', t:'Vp = 16.009 L, reported as 16 L',
   why:'Her key prints 16 L, rounded to the whole litre. The distribution and elimination rate constants play no part in this calculation, which is why the intercept route is the short one.'}],
 teach:'The central compartment volume is found exactly as a one-compartment volume of distribution is, with the sum of the intercepts standing in for the initial concentration. The alternative route on the equation sheet, Vp = D0/(k·AUC), reaches the same volume but first requires the overall rate constant to be assembled from all four parameters, so it is reserved for problems that supply an area under the curve instead of intercepts.',
 cite:'IV-Bolus-Practice-3---Solutions.pdf, problem 2 part d',
 quote:'V_c = 300 mg / (18.74 mg/L) = 16 L'},

{id:'m2-n-theo', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'biexp-conc-at-t', skill:'conctime',
 source:'both',
 stem:'The equation Cp = 12·e^(−5.8t) + 18·e^(−0.16t) describes theophylline kinetics in nine human volunteers, with concentration in mg/L and time in hours. What is the plasma level of theophylline 3 hours after an IV bolus dose?',
 units:'mg/L',
 answer:11.14,
 tol:0.25,
 steps:[
  {k:'setup', t:'Cp = A·e^(−αt) + B·e^(−βt), with A = 12 mg/L, α = 5.8 hr⁻¹, B = 18 mg/L, β = 0.16 hr⁻¹',
   why:'The coefficients and exponents are read straight off the equation. The larger rate constant, 5.8 hr⁻¹, is the distribution term, so the 12 mg/L that sits in front of it is A; the smaller rate constant and its coefficient are the elimination term. Here B exceeds A, which is allowed: the ordering rule applies to the exponents, not to the intercepts.'},
  {k:'algebra', t:'First term: (12 mg/L)·e^(−5.8 × 3) = (12 mg/L)(2.76e−8) = 0.00000033 mg/L',
   why:'The exponent is −17.4, so the distribution term has effectively disappeared by 3 hours. Its half-life is only 0.12 hr, so three hours is about twenty-five distribution half-lives.'},
  {k:'algebra', t:'Second term: (18 mg/L)·e^(−0.16 × 3) = (18 mg/L)(0.61878) = 11.138 mg/L',
   why:'The exponent is −0.48 and e raised to it is 0.61878. The beta half-life is 4.33 hr, so at 3 hours somewhat more than half of the 18 mg/L intercept should remain, which it does.'},
  {k:'round', t:'Cp = 11.138 mg/L, reported as 11.14 mg/L',
   why:'Dr. Mosley reports this as eleven-ish milligrams per litre in class, and the working on this copy of the deck shows 11.14. The initial concentration is A + B = 30 mg/L, which she confirms aloud as the time-zero value.'}],
 teach:'An equation handed over with no labels still identifies its own terms. The exponents are rate constants in reciprocal time and the larger one is always distribution; the coefficients are intercepts in units of concentration and either may be the larger. Their sum is the concentration at time zero, which is a quick check that the equation has been read correctly before any time is substituted.',
 cite:'2IVBolusAdministration.pdf, slide "Practice" (multicompartment section, theophylline)',
 quote:'The equation below describes theophylline kinetics in nine human volunteers. What is the plasma level of theophylline 3 hours after an IV bolus dose?'},

{id:'m2-n-koverall', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'rate-constants-from-abab', skill:'multicpt',
 source:'both',
 stem:'A 250-mg IV bolus dose of a drug is described by A = 8.45 mg/L, B = 5.32 mg/L, α = 2.18 hr⁻¹ and β = 0.114 hr⁻¹. What is the overall elimination rate constant k?',
 units:'hr⁻¹',
 answer:0.272,
 tol:0.008,
 steps:[
  {k:'setup', t:'k = αβ(A + B) / (Aβ + Bα)',
   why:'The overall elimination rate constant of the two-compartment model is a composite of both intercepts and both exponents, and this expression is printed on the supplied equation sheet. It is not the same quantity as beta, which is the terminal slope of the plasma curve.'},
  {k:'algebra', t:'Numerator: (2.18)(0.114)(8.45 + 5.32) = (0.248520)(13.77) = 3.42212',
   why:'The two rate constants multiply to 0.248520 in units of reciprocal hours squared, and the sum of the intercepts is 13.77 mg/L. Multiplying them gives a quantity in mg/L per hour squared, which the denominator will reduce.'},
  {k:'algebra', t:'Denominator: (8.45)(0.114) + (5.32)(2.18) = 0.96330 + 11.5976 = 12.56090',
   why:'Each intercept is paired with the exponent of the other phase, which is what makes this a cross product rather than a simple sum. The result is in mg/L per hour, so dividing the numerator by it leaves reciprocal hours.'},
  {k:'algebra', t:'k = 3.42212 / 12.56090 = 0.272442 hr⁻¹',
   why:'The division cancels the concentration units entirely and leaves one power of reciprocal time, which is what a first-order rate constant must carry.'},
  {k:'round', t:'k = 0.272 hr⁻¹',
   why:'Dr. Mosley reads the answer to this practice sheet aloud as 0.272 per hour, three decimal places. Note that k is larger than beta, as it always is, because beta is slowed by drug returning from the tissue compartment.'}],
 teach:'The overall rate constant and the terminal slope are different numbers and the model needs both. Beta describes how fast the plasma concentration actually falls once distribution is over, which is slowed by drug coming back out of tissue. The overall k describes elimination from the central compartment itself, which is why it is always the larger of the two. The cross-product form of the expression is what mixes both phases into one constant.',
 cite:'2IVBolusAdministration.pdf, slide "Rate Constants"; in-class two-compartment practice sheet problem 1, answers read aloud in Basic Pharmacokinetics - 08-26 Lecture.txt',
 quote:'I got for the overall rate constant K 0.272 per hour.',
 note:'The A, B, alpha and beta values for this practice sheet appear on this copy of the deck as handwriting, which is not on its own a source. They are used here only because every answer Dr. Mosley reads aloud in the 26 August lecture reproduces from them exactly: beta half-life six-ish hours, initial concentration 13.8 mg/L, concentration at 4 hours 3.4 mg/L, central volume 18-ish litres, k 0.272 per hour, k12 1.1 per hour and k21 0.9 per hour.'},

{id:'m2-n-k21', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'rate-constants-from-abab', skill:'multicpt',
 source:'both',
 stem:'A 250-mg IV bolus dose of a drug is described by A = 8.45 mg/L, B = 5.32 mg/L, α = 2.18 hr⁻¹ and β = 0.114 hr⁻¹. What is the transfer rate constant from the tissue compartment to the central compartment?',
 units:'hr⁻¹',
 answer:0.912,
 tol:0.02,
 steps:[
  {k:'setup', t:'k21 = (Aβ + Bα) / (A + B)',
   why:'The transfer constant from compartment two back to compartment one is a weighted average of the two exponents, with each exponent weighted by the intercept of the other phase. The expression is printed on the supplied equation sheet.'},
  {k:'algebra', t:'Numerator: (8.45)(0.114) + (5.32)(2.18) = 0.96330 + 11.5976 = 12.56090',
   why:'This is the same cross product that formed the denominator of the overall k, so once it has been computed for one part of a problem it can be reused for the other. Its units are mg/L per hour.'},
  {k:'algebra', t:'k21 = 12.56090 / 13.77 = 0.912193 hr⁻¹',
   why:'Dividing by the sum of the intercepts, 13.77 mg/L, cancels the concentration and leaves reciprocal hours. Because it is a weighted average of alpha and beta, k21 must lie between them, which 0.912 does.'},
  {k:'round', t:'k21 = 0.912 hr⁻¹',
   why:'Dr. Mosley reads this answer aloud as 0.9 per hour. Three decimal places is carried here because the value feeds directly into the tissue volume, where rounding early would shift the result.'}],
 teach:'Both transfer constants are computed from the same four parameters, and both must fall between alpha and beta because they are averages of the two exponents in different weightings. Apply that range check before moving on: a transfer constant larger than alpha or smaller than beta means the intercepts and exponents have been paired the wrong way round in the cross product.',
 cite:'2IVBolusAdministration.pdf, slide "Rate Constants"; in-class two-compartment practice sheet problem 1, answers read aloud in Basic Pharmacokinetics - 08-26 Lecture.txt',
 quote:'And then from 2 to 1, 0.9 per hour.',
 note:'As with the overall k for this sheet, the parameter values are handwritten on this copy of the deck and are used only because every answer she reads aloud on 26 August reproduces from them exactly. She reports k21 to one decimal place as 0.9 per hour.'},

{id:'m2-n-k12', type:'numeric', prof:'Mosley', tier:'new', exam:1, module:2, lecture:'L03',
 topic:'bolus2', sub:'calc', concept:'rate-constants-from-abab', skill:'multicpt',
 source:'both', dupOf:'m2-n-k21',
 stem:'A 250-mg IV bolus dose of a drug is described by A = 8.45 mg/L, B = 5.32 mg/L, α = 2.18 hr⁻¹ and β = 0.114 hr⁻¹. What is the transfer rate constant from the central compartment to the tissue compartment?',
 units:'hr⁻¹',
 answer:1.109,
 tol:0.03,
 steps:[
  {k:'setup', t:'k12 = AB(β − α)² / [(A + B)(Aβ + Bα)]',
   why:'The transfer constant out to the tissue compartment is the one expression of the three that squares the difference between the two exponents. The square means the sign of that difference does not matter, so writing it as alpha minus beta gives the same answer. The expression is printed on the supplied equation sheet.'},
  {k:'algebra', t:'(β − α)² = (0.114 − 2.18)² = (−2.066)² = 4.268356',
   why:'Squaring removes the negative sign that arises because beta is the smaller exponent. A negative value surviving to the end would give a negative rate constant, which cannot occur.'},
  {k:'algebra', t:'Numerator: (8.45)(5.32)(4.268356) = (44.954)(4.268356) = 191.8797',
   why:'The product of the two intercepts carries units of concentration squared and the squared exponent difference carries reciprocal hours squared, so the numerator is in mg²/L² per hour².'},
  {k:'algebra', t:'Denominator: (13.77)(12.56090) = 172.9636; k12 = 191.8797 / 172.9636 = 1.109365 hr⁻¹',
   why:'The denominator carries mg²/L² per hour, so the division leaves one power of reciprocal time. Reusing the cross product 12.56090 that was already computed for k and k21 saves repeating the arithmetic.'},
  {k:'round', t:'k12 = 1.109 hr⁻¹',
   why:'Dr. Mosley reads this answer aloud as 1.1 per hour. That k12 exceeds k21 here means the drug moves into tissue faster than it returns, which is consistent with an apparent tissue volume larger than the central volume.'}],
 teach:'Three expressions on the equation sheet convert the four fitted parameters into the three rate constants of the model diagram. All three share the cross product Aβ + Bα, so computing it once serves all of them. The k12 expression is the only one with a squared term, which is the quickest way to tell the three apart on the sheet under exam conditions.',
 cite:'2IVBolusAdministration.pdf, slide "Rate Constants"; in-class two-compartment practice sheet problem 1, answers read aloud in Basic Pharmacokinetics - 08-26 Lecture.txt',
 quote:'And then transfer from 1 to 2, 1.1 per hour.',
 note:'As with the other two rate constants for this sheet, the parameter values are handwritten on this copy of the deck and are used only because her spoken answers reproduce from them exactly. She reports k12 to one decimal place as 1.1 per hour.'},

];
