/* ==========================================================================
   MODULE 6 — MULTIPLE DOSING, PART 1: REPETITIVE IV BOLUS INJECTIONS
   (Exam 2, lecture L07, 23 September)
   ==========================================================================
   Deck: 6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, the part
   lectured on 23 September (title slide through Example 3). The intermittent
   infusion slides that follow are Part 2 and carry no questions yet.
   Also sourced: Basic Pharmacokinetics - 09.23 Lecture Transcript.txt,
   Multiple-IV-Bolus-Practice-1.pdf with its solutions, and Chapter 9,
   Multiple-Dosage Regimens (the assigned reading: the opening section, then
   Repetitive Intravenous Injections).

   Every number is hers. The Example 1 to 3 values are her own spoken answers
   (40, 10, 53.3, 13.3, 28.9 and 29.7 mg/L). Two values are carried one step
   past where the recording ends, from her own inputs, and each says so in
   `audit`: the concentration 3 hours after the last dose (Example 3) and the
   one 4 hours after it, which she set as a question as the recording ends.
   The Practice 1 values are her keyed solutions.

   Homework 5 question 2 is a graded assignment with no posted key, so it is
   not worked here.

   TOPICS is declared in q1_module1.js. The topic id is 'multi' and the four
   subtopic ids are declared there: accum, superpos, ssbolus, ndose.
   ========================================================================== */

/* Sections several questions share, written once. */
const M6_ACCUM = {h:'What steady state is', list:[
  'With the same dose at the same interval, each dose is added to what is left of the doses before it, so the peaks and troughs climb.',
  'The climb stops when the drug eliminated over one interval equals one dose. From then on every dose reaches the same peak, Cmax∞, and falls to the same trough, Cmin∞. That repeating pattern is the plateau, also called steady state.',
  'Time to plateau is 3 to 5 half-lives, not 3 to 5 doses, and it does not depend on the dose.',
  'After the last dose, most of the drug is eliminated in another 3 to 5 half-lives.',
  'The ∞ sign on a symbol means steady state.']};

const M6_SUP = {h:'Superposition and its two assumptions', list:[
  'Assumption 1: the drug is eliminated by first-order kinetics. First order is also called linear pharmacokinetics.',
  'Assumption 2: the pharmacokinetics after one dose are not altered by later doses, so k, the half-life and clearance stay constant from dose to dose.',
  'Under those two assumptions each dose follows its own C0e^(-kt) curve, and the concentration at any time is the sum of what is left of every dose given so far.',
  'After a dose at steady state the concentration falls with the same k as after the first dose. It starts higher, at Cmax∞, because drug from the earlier doses is still in the body.']};

const M6_EQ = {h:'The steady-state equations for repeated IV bolus doses', list:[
  'Cmax∞ = {{frac:C0|1 - e^(-kτ)}}: the first-dose peak, C0 = D0/VD, divided by (1 - e^(-kτ)).',
  'Cmin∞ = {{frac:C0e^(-kτ)|1 - e^(-kτ)}}, which is Cmax∞ × e^(-kτ): the steady-state peak after one full interval of first-order decline.',
  'Cavg∞ = {{frac:FD0|VD kτ}} = {{frac:FD0|ClT τ}}. F = 1 for an IV dose.',
  'τ (tau) is the dosing interval in hours, the time between doses. TID, three times a day, is τ = 8 hr.',
  'The amount forms, Dmax∞, Dmin∞ and Davg∞, carry D0 where the concentration forms carry C0. Dividing an amount by VD gives the concentration.']};

const M6_ACCFAC = {h:'The accumulation factor', table:{head:['', 'First dose', 'At steady state'],
  rows:[['Drug already in the body when a dose is given', 'None', 'The steady-state trough, Cmin∞, left from earlier doses'],
        ['Peak', 'C0 = D0/VD', 'Cmax∞ = C0 × {{frac:1|1 - e^(-kτ)}}'],
        ['Trough, at the end of the interval', 'C0e^(-kτ)', 'Cmax∞e^(-kτ)'],
        ['Decline between doses', 'First order, rate constant k', 'First order, the same k']]},
  after:'The factor {{frac:1|1 - e^(-kτ)}} is the accumulation factor: the steady-state peak divided by the first-dose peak. It holds only k and τ, so it does not depend on the dose. A shorter interval makes e^(-kτ) larger and the factor larger, which means more accumulation.'};

const M6_FIG = {h:'Her Example 1 regimen drawn out', fig:'md_bolus',
  t:'10 mg/kg every 8 hours with a half-life of 4 hours and VD 0.25 L/kg. Each dose adds C0 = 40 mg/L. The first dose falls to 10 mg/L at 8 hours because 8 hours is two half-lives.',
  after:'The peaks climb from 40 to 53.3 mg/L and the troughs from 10 to 13.3 mg/L, and the climb is over within 3 to 5 half-lives, 12 to 20 hours. The average at steady state, 28.9 mg/L, sits below the midpoint of peak and trough, 33.3 mg/L, because the curve spends more of each interval at the lower concentrations. After the sixth dose the level falls by first-order elimination alone.'};

const M6_CH = {h:'What the chapter adds', list:[
  'The accumulation index is R = Cmax∞ divided by the first-dose Cmax, which equals {{frac:1|1 - e^(-kτ)}}. It depends on k and τ and not on the dose.',
  'Time to steady state depends on the elimination half-life only. It does not depend on the dose, the dosing interval or the number of doses; changing the dose or the interval changes the plateau level, not how long it takes to reach it.',
  'Fractions of steady state: 90 per cent at 3.3 half-lives, 95 per cent at 4.32 and 99 per cent at 6.6.',
  'If each dose is given after the previous dose has been eliminated, there is no accumulation.',
  'Superposition fails when the pharmacokinetics change with repeated doses: a change in the patient\'s pathophysiology, saturation of a drug carrier system, enzyme induction or enzyme inhibition. Drugs with nonlinear pharmacokinetics are not predictable by superposition.']};

const M6_NDOSE = {h:'Before steady state, and after the last dose', list:[
  'After n doses: Cp = {{frac:D0|VD}} ({{frac:1 - e^(-nkτ)|1 - e^(-kτ)}}) e^(-kt). n is the dose number just given; t is the time since that dose.',
  'As n grows, e^(-nkτ) shrinks towards 0, the top of the bracket becomes 1 and the equation becomes the steady-state one: Cp = {{frac:D0|VD}} ({{frac:1|1 - e^(-kτ)}}) e^(-kt) = Cmax∞e^(-kt).',
  'After the last dose at steady state no more drug goes in, so the level falls from Cmax∞ by first-order elimination: C = Cmax∞e^(-kt).']};

const Q_MODULE6 = [

/* ═══════════════ DRUG ACCUMULATION AND STEADY STATE ════════════════════ */

{id:'m6-c01', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'accum', concept:'time-to-plateau', skill:'recall',
 source:'both',
 stem:'A drug eliminated by first-order kinetics is given as the same IV bolus dose at a fixed interval. How long does it take to reach the plateau?',
 options:[
  {t:'3 to 5 half-lives', correct:true,
   why:'Elimination is first order, so how close the level is to its plateau is set by how many half-lives have passed. After 3 to 5 half-lives the peaks and troughs have stopped climbing and each dose reaches the same maximum and minimum.'},
  {t:'3 to 5 doses',
   why:'Choosing this confuses doses with half-lives: it counts doses where the rule counts half-lives. The number of doses given in 3 to 5 half-lives depends on the interval: with a half-life of 4 hours and a dose every 8 hours, 3 to 5 half-lives is 12 to 20 hours, by which time 2 to 3 doses have been given (at 0, 8 and 16 hours). With a dose every 2 hours the same 12 to 20 hours holds 7 to 11 doses.'},
  {t:'One dosing interval',
   why:'Choosing this treats the first trough as the plateau. One interval brings the level down to the first trough, not to the plateau. The second dose then starts from that trough, and the peaks keep climbing for several more intervals, which is the accumulation this module is about.'},
  {t:'A time that doubles when the dose doubles',
   why:'This answer ties the time to plateau to the dose. A first-order rate is proportional to the amount present, so a larger dose is eliminated faster in proportion, and the time to plateau does not change. Doubling the dose doubles the plateau level instead.'}],
 teach:[
  {t:'The plateau is reached when the peaks and troughs stop rising, and with first-order elimination that takes 3 to 5 half-lives whatever the dose. The same count applies in reverse: after the last dose most of the drug is gone in 3 to 5 half-lives.'},
  M6_ACCUM, M6_FIG, M6_CH],
 teachImg:'slide_6RepetitiveIVBolus_p3',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Drug accumulation with repeated administration"; 09.23 lecture',
 quote:'and not 3 to 5 doses, 3 to 5 half-lives, OK?'},

{id:'m6-c02', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'accum', concept:'plateau-dose-independent', skill:'apply',
 source:'both',
 stem:'The dose of a drug given by repeated IV bolus injection is doubled while the dosing interval is unchanged. What happens to the time needed to reach steady state?',
 options:[
  {t:'It does not change', correct:true,
   why:'The time to steady state is set by the elimination half-life alone. Doubling the dose doubles the amount present and so doubles the first-order elimination rate, and the level approaches its new, doubled plateau in the same 3 to 5 half-lives.'},
  {t:'It doubles',
   why:'This reads a larger dose as more drug to accumulate and therefore more time. With first-order elimination the rate of loss rises in proportion to the amount, so the extra drug is removed in proportion and the time is unchanged. The plateau level doubles instead.'},
  {t:'It halves',
   why:'Choosing this treats a larger dose as if it sped up elimination. Halving the time would need a faster rate constant. The dose changes the amount in the body and the elimination rate, but not k or the half-life, and the half-life is the only thing that sets the time to plateau.'},
  {t:'It cannot be predicted without the new peak',
   why:'Choosing this mixes up the height of the plateau with the time to reach it. The time to steady state needs only the half-life, which the dose does not change. The new peak would be twice the old one, but it is not needed to answer how long it takes to get there.'}],
 teach:[
  {t:'The dose and the half-life control two different things. The dose sets how high the plateau is. The half-life sets how long it takes to get there. Changing the dose moves the plateau up or down and leaves the time the same.'},
  M6_ACCUM, M6_CH],
 teachImg:'slide_6RepetitiveIVBolus_p3',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Drug accumulation with repeated administration"; 09.23 lecture',
 quote:'Cause the 2nd bullet, independent of dose, right? Because 3 to 5 half-lives. We\'re looking at first-order processes. The rate depends on how much is there.'},

{id:'m6-c03', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'accum', concept:'washout', skill:'recall',
 source:'both',
 stem:'A patient at steady state on repeated IV bolus doses receives the last dose. About how long until most of the drug has been eliminated?',
 options:[
  {t:'3 to 5 half-lives', correct:true,
   why:'Once dosing stops, only first-order elimination is left, and each half-life removes half of what remains. After 3 half-lives 12.5 per cent remains and after 5 half-lives about 3 per cent, which is most of the drug gone.'},
  {t:'One dosing interval',
   why:'Choosing this treats the steady-state trough as if it were zero. One interval takes the level from the steady-state peak down to the steady-state trough, and the trough is not near zero, because it is the drug that had accumulated. It takes several more half-lives for that to be eliminated.'},
  {t:'One half-life',
   why:'Choosing this confuses half with most. One half-life removes half of the drug, and half is still in the body at that point; it takes 3 to 5 half-lives to get down to between 12.5 and 3 per cent.'},
  {t:'As long as the dosing lasted',
   why:'This answer ties the washout to the length of the regimen. First-order elimination depends only on the half-life, so a patient dosed for a week and one dosed for a month both lose most of the drug in 3 to 5 half-lives once they are at steady state.'}],
 teach:[
  {t:'Reaching steady state and eliminating the drug afterwards both run on the same first-order clock, so both take 3 to 5 half-lives.'},
  M6_ACCUM, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p3',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Drug accumulation with repeated administration"; 09.23 lecture',
 quote:'if we stop putting drug in the body, 3 to 5 half-lives to get most of that drug out of the body'},

{id:'m6-c04', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'accum', concept:'steady-state-defn', skill:'recall',
 source:'both',
 stem:'During repeated IV bolus dosing at a fixed dose and interval, what defines the plateau?',
 options:[
  {t:'Every dose reaches the same peak and trough', correct:true,
   why:'At the plateau the maximum after each dose is the same, Cmax∞, and the minimum before each dose is the same, Cmin∞. The concentration still rises and falls within every interval; what stops changing is the pattern from one interval to the next.'},
  {t:'The concentration stops changing with time',
   why:'Choosing this carries the infusion plateau into bolus dosing. A constant-rate infusion has a flat plateau. With bolus doses the whole dose goes in at once, so the level jumps at each dose and falls between doses even at steady state.'},
  {t:'The peak equals the first-dose peak',
   why:'Choosing this treats the first dose as if it were already at steady state. The steady-state peak is higher than the first-dose peak, because at steady state each dose is added to drug left over from the earlier ones. The first dose goes into a body with no drug in it.'},
  {t:'The trough falls to zero before each dose',
   why:'Choosing this confuses a regimen with no accumulation with one at steady state. If the level reached zero before each dose, nothing would be left over and there would be no accumulation. The steady-state trough is above zero; that leftover drug is what raises the steady-state peak above the first-dose peak.'}],
 teach:[
  {t:'Peaks are the maximum concentrations and troughs the minimum concentrations. At the plateau, also called steady state, both repeat exactly from dose to dose.'},
  M6_ACCUM, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p3',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Drug accumulation with repeated administration"; 09.23 lecture',
 quote:'every dose at steady state, we should reach the same max and the same min'},

/* ═══════════════ SUPERPOSITION ═════════════════════════════════════════ */

{id:'m6-c05', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07', multi:true,
 topic:'multi', sub:'superpos', concept:'superposition-assumptions', skill:'recall',
 source:'both',
 stem:'Which are assumptions of the principle of superposition? Select all that apply.',
 options:[
  {t:'The drug is eliminated by first-order kinetics', correct:true,
   why:'This is the first assumption. First order means a constant fraction is removed per unit time, which is what lets each dose be treated as its own C0e^(-kt) curve and the curves be added.'},
  {t:'The pharmacokinetics after one dose are unchanged by later doses', correct:true,
   why:'This is the second assumption. It means the half-life and clearance measured after a single dose still hold after many doses, so the first-dose curve can be laid over the curve at steady state.'},
  {t:'The drug is eliminated by zero-order kinetics',
   why:'Choosing this reverses the first assumption. Zero order removes a fixed amount per unit time whatever is present, so the loss from one dose depends on how much drug the earlier doses left. The curves could then not be added independently. Superposition needs first order.'},
  {t:'The half-life shortens as the drug accumulates',
   why:'Choosing this reverses the second assumption: a half-life that changes with accumulation is exactly what it rules out. If later doses changed the half-life, the first-dose curve would no longer describe the later ones.'}],
 teach:[
  {t:'Superposition lets the concentration after many doses be predicted from the curve after one dose. It rests on two assumptions, and both are about the kinetics staying the same.'},
  M6_SUP, M6_CH],
 teachImg:'slide_6RepetitiveIVBolus_p4',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Superposition"; 09.23 lecture',
 quote:'the first assumption when we\'re talking about this superposition is that the drug is eliminated from the body via first orderer process. And then the second big assumption is that the pharmacokinetics don\'t change after multiple doses'},

{id:'m6-c06', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'superpos', concept:'linear-pk', skill:'recall',
 source:'transcript',
 stem:'First-order elimination is also described by which term?',
 options:[
  {t:'Linear pharmacokinetics', correct:true,
   why:'In first-order elimination the rate is proportional to the amount present, so doubling the dose doubles every concentration and the curves scale in a straight-line way. That proportionality is why first order is called linear.'},
  {t:'Nonlinear pharmacokinetics',
   why:'Nonlinear pharmacokinetics is the case where the kinetics change with the dose, for example when an enzyme or a carrier becomes saturated. Superposition does not hold for those drugs, which is the opposite of first order.'},
  {t:'Zero-order kinetics',
   why:'Choosing this confuses the two elimination orders. Zero order removes a fixed amount per unit time rather than a fixed fraction. It is the other elimination order in this course, not another name for first order.'},
  {t:'Flip-flop kinetics',
   why:'Choosing this carries a Module 5 term into the wrong place. Flip-flop describes an oral curve whose tail falls with ka because absorption is slower than elimination. It is about which of two first-order constants shows in the tail, not a name for first order itself.'}],
 teach:[
  {t:'Linear and first order name the same behaviour: a constant fraction removed per unit time, a constant half-life and a constant clearance. That is the first assumption of superposition.'},
  M6_SUP],
 teachImg:'slide_6RepetitiveIVBolus_p4',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Superposition"; 09.23 lecture',
 quote:'I\'m gonna put this word in your brain right now. First order kinetics equals linear pharmacokinetics.'},

{id:'m6-c07', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'superpos', concept:'superposition-meaning', skill:'tell',
 source:'both',
 stem:'Under superposition, how does the decline after a dose at steady state compare with the decline after the first dose?',
 options:[
  {t:'Same k; it starts higher because drug has accumulated', correct:true,
   why:'Both declines are C = C0e^(-kt) with the same k, because the second assumption keeps the kinetics constant. The difference is the starting point: the first dose starts from a body with no drug, and a dose at steady state is added to the drug left from earlier doses, so it starts at Cmax∞.'},
  {t:'Same starting level; a smaller k',
   why:'This has both halves reversed. The starting level is higher at steady state, because of the accumulated drug, and k is the same, because superposition assumes the kinetics do not change.'},
  {t:'Same starting level and the same k',
   why:'The k is right and the starting level is not. If each dose at steady state started at the first-dose peak, no drug would have accumulated and the steady-state peak would equal the first-dose peak.'},
  {t:'A larger k, because more drug is present',
   why:'Choosing this confuses the elimination rate with the rate constant. More drug means a faster elimination rate in mg per hour, but the rate constant k is a fraction per hour and stays the same. A rate that rises with the amount is what first order means; it does not change k.'}],
 teach:[
  {t:'The only difference between the first dose and a dose at steady state is the drug already in the body. The kinetics are the same, so the steady-state values can be worked from the first-dose values.'},
  M6_SUP, M6_ACCFAC],
 teachImg:'slide_6RepetitiveIVBolus_p4',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Superposition"; 09.23 lecture',
 quote:'It is the same kinetics, but now we just remember that we\'ve got drug that\'s accumulated in the body.'},

{id:'m6-c08', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'superpos', concept:'superposition-failure', skill:'apply',
 source:'slide',
 stem:'For which drug would superposition fail to predict the concentrations after repeated doses?',
 options:[
  {t:'One that induces its own metabolizing enzymes', correct:true,
   why:'Enzyme induction raises clearance as doses continue, so the pharmacokinetics after the tenth dose differ from those after the first. That breaks the second assumption, and the first-dose curve no longer predicts the later ones.'},
  {t:'One with a half-life longer than the interval',
   why:'Choosing this confuses accumulation with a change in kinetics. A long half-life relative to the interval only means more accumulation. The kinetics stay first order and constant, so superposition still predicts the higher peaks and troughs.'},
  {t:'One given by IV bolus',
   why:'Choosing this confuses how the dose enters with how the drug is eliminated. The IV bolus is the route this module applies superposition to. The route sets how the dose enters, not whether the elimination kinetics stay constant.'},
  {t:'One eliminated mainly by the kidney',
   why:'Choosing this treats the organ of elimination as the issue rather than whether the kinetics stay constant. The route of elimination does not matter so long as elimination is first order and does not change with dosing. Renal elimination with a stable clearance meets both assumptions.'}],
 teach:[
  {t:'Superposition holds while the kinetics after each dose are the same as after the first. Anything that changes k or clearance as doses continue breaks it.'},
  M6_SUP, M6_CH],
 teachImg:'slide_6RepetitiveIVBolus_p4',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Superposition"; Chapter 9, Multiple-Dosage Regimens, section Drug Accumulation',
 quote:'the pharmacokinetics of the drug change after multiple dosing due to various factors, including changing pathophysiology in the patient, saturation of a drug carrier system, enzyme induction, and enzyme inhibition'},

{id:'m6-c09', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'superpos', concept:'cav-auc-tau', skill:'read',
 source:'both',
 stem:'At steady state, the average plasma concentration is Cav∞ = [AUC] from t1 to t2, divided by τ. What do t1 and t2 mark?',
 options:[
  {t:'The start and end of one dosing interval', correct:true,
   why:'t1 is the time of one dose and t2 the time of the next, so t2 − t1 = τ. The area over that one interval divided by its length is the average concentration during it, and at steady state every interval gives the same value.'},
  {t:'The first dose and the last dose',
   why:'Choosing this reads t1 and t2 as the ends of the whole regimen. That would take the area over the whole regimen, including the climb before steady state. The steady-state average uses one interval at steady state, and the division is by τ, the length of that one interval.'},
  {t:'Time zero and infinity after one dose',
   why:'Choosing this confuses the single-dose area, AUC from 0 to ∞, with the area over one interval. It has the same value as the area over one interval at steady state, but it is not what t1 and t2 mark here, and dividing it by τ only works because the two areas are equal.'},
  {t:'The peak and the trough concentrations',
   why:'Choosing this reads t1 and t2 as concentrations rather than times. The peak and trough are the heights of the curve at the start and end of the interval.'}],
 teach:[
  {t:'This is the area under the curve from Module 1 applied to one piece of the steady-state curve: take the area over one interval and divide by the interval.'},
  {h:'Why it is not the midpoint', list:[
    'The average is an area divided by a time. The curve falls exponentially, quickly at first and then slowly, so it spends more of each interval at the lower concentrations.',
    'That makes the average lower than (Cmax∞ + Cmin∞)/2.',
    'Chapter 9 adds that the area over one interval at steady state equals the area from 0 to ∞ after a single dose.']},
  M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p4',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Superposition"; 09.23 lecture',
 quote:'the average concentration should be the AUC of each little segment divided by tau, right? And I keep saying tau. Too. Is our dosing interval.'},

/* ═══════════════ STEADY STATE AFTER REPEATED IV BOLUS ══════════════════ */

{id:'m6-c10', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'tau-from-frequency', skill:'apply',
 source:'both',
 stem:'A drug is ordered TID. What value of τ goes into the repeated-dose equations?',
 options:[
  {t:'8 hr', correct:true,
   why:'TID is three times a day, which is the frequency. τ is the interval, the time between doses: 24 hours divided by 3 doses is 8 hours.'},
  {t:'3 hr',
   why:'This answer puts the frequency, 3 doses a day, where the interval belongs. The equations need the time between doses in hours, not the number of doses.'},
  {t:'24 hr',
   why:'Choosing this mistakes the length of the day for the time between doses. 24 hours is the length of the day the three doses are spread over. The time from one dose to the next is a third of that.'},
  {t:'12 hr',
   why:'Choosing this confuses TID with BID. 12 hours is the interval for BID, twice a day, when 24 hours is split into two; TID splits it into three, so each interval is 8 hours.'}],
 teach:[
  {t:'Frequency and interval are inverses of each other. Orders are written as a frequency, BID or TID; the equations use the interval, τ, in hours.'},
  {h:'Frequency against interval', table:{head:['Order', 'Frequency', 'τ'], rows:[['BID', 'twice a day', '12 hr'], ['TID', 'three times a day', '8 hr']]}},
  M6_EQ],
 teachImg:'slide_6RepetitiveIVBolus_p6',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'What does TID mean? 3 times a day. That is the frequency ... So, the interval would be what? ... 8 hours, OK?'},

{id:'m6-c11', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'db-over-d0', skill:'read',
 source:'both',
 stem:'After a single IV bolus, DB = D0e^(-kτ). What does DB/D0 = e^(-kτ) represent?',
 options:[
  {t:'The fraction of the dose still in the body after one interval', correct:true,
   why:'DB is the amount in the body at time τ and D0 is the dose, so their ratio is the fraction of the dose left when the next dose is due. With a half-life of 4 hours and τ = 8 hours it is e^(-1.386) = 0.25, a quarter of the dose.'},
  {t:'The fraction of the dose eliminated in one interval',
   why:'That is 1 − e^(-kτ), the other part of the dose. Reading the remaining fraction as the eliminated one reverses every steady-state result that is built from it.'},
  {t:'The accumulation factor',
   why:'Choosing this confuses the fraction left with the accumulation factor, which is 1/(1 − e^(-kτ)), built from this fraction but not equal to it. With e^(-kτ) = 0.25 the accumulation factor is 1.33.'},
  {t:'The number of doses to reach steady state',
   why:'Choosing this treats a fraction as a count. e^(-kτ) is a number between 0 and 1 and carries no units, so it cannot be a count of doses. The time to steady state is 3 to 5 half-lives.'}],
 teach:[
  {t:'This is C = C0e^(-kt) written in amounts, with the time set to one dosing interval. It gives how much of each dose is still present when the next dose is given, which is what accumulates.'},
  M6_EQ, M6_ACCFAC],
 teachImg:'slide_6RepetitiveIVBolus_p6',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'So that says the amount of drug in the body relative to the dose that was given, right? So the fraction of drug that\'s still in the body, that is equal to E minus K tau.'},

{id:'m6-c12', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'accumulation-factor', skill:'read',
 source:'both',
 stem:'In Cmax∞ = C0/(1 − e^(-kτ)), what does the factor 1/(1 − e^(-kτ)) account for?',
 options:[
  {t:'The drug accumulated in the body at steady state', correct:true,
   why:'Multiplying the first-dose peak C0 by this factor gives the steady-state peak, so the factor is how much higher the peak is once earlier doses have left drug behind. It is 1 only if nothing is left from one dose to the next.'},
  {t:'The fraction of the dose absorbed',
   why:'Choosing this confuses the accumulation factor with F, the bioavailability. For an IV bolus F = 1, and F appears only in the average equations. This factor is built from k and τ, not from absorption.'},
  {t:'The fraction of each dose eliminated',
   why:'Choosing this reads the denominator as the whole factor. The fraction eliminated in one interval is 1 − e^(-kτ), the denominator itself. Its reciprocal is what multiplies C0, and that reciprocal is the accumulation.'},
  {t:'The conversion from amount to concentration',
   why:'Choosing this mixes the accumulation factor up with VD. The conversion from amount to concentration is division by VD, which is already inside C0 = D0/VD. This factor has no units.'}],
 teach:[
  {t:'The same factor, 1/(1 − e^(-kτ)), appears in the steady-state maximum, the minimum and the concentration after n doses. Each time it carries the drug that has accumulated.'},
  M6_ACCFAC, M6_EQ],
 teachImg:'slide_6RepetitiveIVBolus_p7',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'we\'ve got this 1/1 minus E to the -K tau, which will, you will see over and over again, because that tells us how much drug is accumulated in the body at steady state'},

{id:'m6-c13', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'when-cmin', skill:'recall',
 source:'both',
 stem:'With repeated IV bolus dosing, when does the minimum concentration of each interval occur?',
 options:[
  {t:'At the end of the dosing interval', correct:true,
   why:'A bolus puts the whole dose in at once, so the level is highest just after the dose and falls by first-order elimination until the next dose. The lowest point is the moment before the next dose, at the end of the interval, which is why Cmin∞ carries e^(-kτ).'},
  {t:'Halfway through the dosing interval',
   why:'Choosing this treats the middle of the interval as its end. Halfway through, the level is still falling and has not reached its lowest point. The curve keeps falling until the next dose arrives.'},
  {t:'Just after each dose',
   why:'Just after a bolus dose is when the level is highest, because the whole dose enters at once. Picking this reverses the peak and the trough.'},
  {t:'One half-life after each dose',
   why:'Choosing this confuses the half-life with the dosing interval. One half-life after a dose the level is at half its peak, and it keeps falling. The trough depends on τ, not on the half-life alone.'}],
 teach:[
  {t:'For an IV bolus the peak is at the time of the dose and the trough is at the end of the interval. The steady-state trough is therefore the steady-state peak after one interval of decline: Cmin∞ = Cmax∞e^(-kτ).'},
  M6_EQ, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p7',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'the min occurs at the end of the dosing interval'},

{id:'m6-c14', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cavg-not-midpoint', skill:'tell',
 source:'both',
 stem:'At steady state Cmax∞ is 53.3 mg/L and Cmin∞ is 13.3 mg/L. How does Cavg∞ compare with (53.3 + 13.3)/2 = 33.3 mg/L?',
 options:[
  {t:'Lower, because the decline is exponential', correct:true,
   why:'Between doses the level falls fast at first and then slowly, so it spends more of the interval near the trough than near the peak. The average over time is therefore below the midpoint: for this regimen it is 28.9 mg/L.'},
  {t:'Equal, since the average is the midpoint',
   why:'Choosing this confuses the midpoint of two numbers with the average of the curve over time. It would equal the time average only if the level fell in a straight line, which is zero order.'},
  {t:'Higher, because drug has accumulated',
   why:'Choosing this counts accumulation twice. Accumulation has already raised both the peak and the trough, and the midpoint is taken from those raised values. The shape of the decline between them is what puts the average below the midpoint.'},
  {t:'It cannot be compared without the AUC',
   why:'Choosing this treats the AUC as the only route to the average. Cavg∞ can be found without an AUC from FD0/(VD kτ), and the shape of the curve alone puts it below the midpoint. The exponential decline is enough to answer.'}],
 teach:[
  {t:'Cavg∞ is not (Cmax∞ + Cmin∞)/2. It is the area over one interval divided by τ, or FD0/(VD kτ). Because first-order decline is logarithmic, not algebraic, the average sits below the midpoint.'},
  M6_FIG, M6_EQ],
 teachImg:'slide_6RepetitiveIVBolus_p8',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'I want you to realize that the average is not the max plus the min divided by 2'},

{id:'m6-c15', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'f-in-cavg', skill:'read',
 source:'both',
 stem:'Cavg∞ = FD0/(VD kτ) is used for a drug given by repeated IV bolus. What value does F take?',
 options:[
  {t:'1', correct:true,
   why:'F is the fraction of the dose that reaches the systemic circulation. An IV bolus puts the whole dose into the circulation, so F = 1. F is written into the equation because the same average applies to repeated oral dosing, where F is less than 1.'},
  {t:'0',
   why:'Choosing this reverses what F measures. F = 0 would mean none of the dose reached the circulation and the average concentration would be zero. An IV dose is the case where all of it does.'},
  {t:'The accumulation factor',
   why:'Choosing this confuses F with the accumulation factor. The average-concentration equation has no accumulation factor in it; the average does not need one. F is bioavailability, a fraction of the dose.'},
  {t:'e^(-kτ)',
   why:'Choosing this confuses F with the fraction remaining. e^(-kτ) is the fraction of a dose left after one interval, which appears in the minimum equations. F is the fraction absorbed, which for an IV dose is all of it.'}],
 teach:[
  {t:'F is bioavailability from Module 5. It is in the average equation so that one equation serves both IV and oral repeated dosing.'},
  M6_EQ],
 teachImg:'slide_6RepetitiveIVBolus_p8',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'Bolus dosing, IV dosing, this F is equal to 1. Right? For for IV dosing.'},

{id:'m6-c16', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cmax-ss-vs-first', skill:'apply',
 source:'both',
 stem:'A drug is given by repeated IV bolus at a fixed dose and interval. How does Cmax∞ compare with the peak after the first dose?',
 options:[
  {t:'Higher, because drug has accumulated', correct:true,
   why:'The first dose enters a body with no drug in it. At steady state each dose is added to what is left of earlier doses, so the peak is C0 multiplied by 1/(1 − e^(-kτ)), which is more than 1. A calculated Cmax∞ below C0 means a setup error.'},
  {t:'Equal, because the dose is the same',
   why:'Choosing this treats the same dose as the same peak. The dose is the same, but the starting point is not. Equal peaks happen only when each dose is eliminated before the next, which needs an interval long compared with the half-life.'},
  {t:'Lower, because elimination has increased',
   why:'Choosing this confuses a faster elimination rate with a larger rate constant. The elimination rate in mg per hour is higher at steady state because more drug is present, but that is balanced by the dose; k is unchanged. The peak is higher, not lower.'},
  {t:'Twice as high, whatever the interval',
   why:'Choosing this treats the accumulation factor as a fixed number. The ratio is 1/(1 − e^(-kτ)), which depends on k and τ. It is 2 only when τ is one half-life. With τ equal to two half-lives, as in her Example 1, it is 1.33.'}],
 teach:[
  {t:'The steady-state peak is higher than the first-dose peak by the accumulation factor. With a very long interval compared with the half-life, e^(-kτ) is close to 0, the factor is close to 1, and there is little accumulation.'},
  M6_ACCFAC, M6_CH],
 teachImg:'slide_6RepetitiveIVBolus_p8',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Concentration of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"; 09.23 lecture',
 quote:'Anybody get a value greater than 40 mg per liter? ... Cause if you got a value less than 40 mg per liter, you\'ve done something wrong.'},

{id:'m6-c17', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'accumulation-tau', skill:'apply',
 source:'slide',
 stem:'Which change increases the accumulation of a drug given by repeated IV bolus?',
 options:[
  {t:'Shortening the dosing interval', correct:true,
   why:'A shorter τ leaves less time for each dose to be eliminated, so e^(-kτ) is larger and the accumulation factor 1/(1 − e^(-kτ)) is larger. More of each dose is still present when the next is given.'},
  {t:'Increasing the dose',
   why:'Choosing this confuses higher levels with more accumulation. A larger dose raises the peaks and troughs in proportion, but the accumulation factor holds only k and τ. The ratio of the steady-state peak to the first-dose peak stays the same.'},
  {t:'Lengthening the dosing interval',
   why:'This answer runs the other way. A longer interval gives each dose more time to be eliminated, so less is left over and accumulation falls. With a long enough interval there is none.'},
  {t:'Giving each dose more slowly',
   why:'Choosing this confuses the injection rate with the dosing interval. How fast one dose is pushed changes the shape of the curve just after the dose, not how much remains a full interval later. The accumulation factor is still set by k and τ.'}],
 teach:[
  {t:'Accumulation depends on how much of a dose is left when the next one arrives, and that depends only on k and τ. The dose scales the whole curve without changing the ratio.'},
  M6_ACCFAC, M6_CH],
 teachImg:'slide_6RepetitiveIVBolus_p7',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Amount of Drug in the Body at Steady-State Following Repeated IV Bolus Injections"; Chapter 9, Multiple-Dosage Regimens, section Drug Accumulation',
 quote:'drug accumulation measured with the R index depends on the elimination constant and the dosing interval and is independent of the dose'},

/* ═══════════════ BEFORE STEADY STATE AND AFTER THE LAST DOSE ═══════════ */

{id:'m6-c18', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'n-and-t', skill:'read',
 source:'both',
 stem:'In Cp = (D0/VD)[(1 − e^(-nkτ))/(1 − e^(-kτ))]e^(-kt), what are n and t?',
 options:[
  {t:'n is the dose number; t is the time since that dose', correct:true,
   why:'n counts which dose was just given, so 3 hours after the second dose n = 2. t is measured from that dose, not from the first one, so t = 3 hr. The bracket carries what has accumulated after n doses and e^(-kt) carries the decline since the last of them.'},
  {t:'n is the dose number; t is the time since the first dose',
   why:'Choosing this is the commonest setup error here. The time since the first dose is already counted by n and τ in the bracket. Using it again as t counts the earlier intervals twice and gives a value far too low.'},
  {t:'n is the number of half-lives; t is the interval',
   why:'Choosing this confuses the dose number with a count of half-lives. Half-lives do not appear in this equation; k and τ do. And τ is already in the bracket, while t is the time into the current interval.'},
  {t:'n is the number of doses left; t is the interval',
   why:'This answer reads the equation backwards: it looks back at the doses already given, not forward. Doses still to come have not added any drug yet.'}],
 teach:[
  {t:'Two quantities place the time on the curve: n says which dose was last given, and t says how long ago it was given. For 3 hours after the second dose, n = 2 and t = 3 hr.'},
  M6_NDOSE],
 teachImg:'slide_6RepetitiveIVBolus_p14',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Plasma Drug Concentration at Any Time After n Doses"; 09.23 lecture',
 quote:'So, in this one, the um N is 2, right? Because that\'s the dose number, the second dose, and the um lowercase t at the end of it is 3, because we\'re looking at the concentration 3 hours out.'},

{id:'m6-c19', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'n-large', skill:'read',
 source:'both',
 stem:'In the equation for Cp after n doses, what happens to the term (1 − e^(-nkτ)) as n becomes very large?',
 options:[
  {t:'It approaches 1', correct:true,
   why:'e^(-nkτ) shrinks towards 0 as n grows, so 1 minus it approaches 1. The equation then becomes Cp = (D0/VD)[1/(1 − e^(-kτ))]e^(-kt), which is the steady-state equation.'},
  {t:'It approaches 0',
   why:'This has the exponential and the whole term the wrong way round. It is e^(-nkτ) that approaches 0; one minus a vanishing number approaches 1.'},
  {t:'It grows without limit',
   why:'Choosing this confuses the growing dose number with a growing term. The term is 1 minus a positive fraction, so it can never exceed 1. That limit is why the concentration levels off at a plateau instead of rising forever.'},
  {t:'It equals the accumulation factor',
   why:'Choosing this confuses the n term with the accumulation factor, which is 1/(1 − e^(-kτ)), with τ and not nτ. The n term approaches 1 and drops out, leaving the accumulation factor behind.'}],
 teach:[
  {t:'The n-dose equation and the steady-state equation are the same equation. Steady state is the limit reached when the dose number is large.'},
  M6_NDOSE],
 teachImg:'slide_6RepetitiveIVBolus_p17',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Plasma Drug Concentration at Steady State"; 09.23 lecture',
 quote:'as N increases, that nation numerator portion up there reduces down to 1'},

{id:'m6-c20', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'after-last-dose', skill:'read',
 source:'both',
 stem:'A patient at steady state on repeated IV bolus doses receives the last dose. Which expression gives the concentration t hours after it?',
 options:[
  {t:'Cmax∞e^(-kt)', correct:true,
   why:'At the last dose the level rises to the steady-state peak, and with no more drug going in it falls by first-order elimination from there. C = C0e^(-kt) with Cmax∞ in place of C0.'},
  {t:'C0e^(-kt)',
   why:'This answer starts from the first-dose peak and drops the drug that had accumulated. It gives the right answer only after a single dose.'},
  {t:'Cmin∞e^(-kt)',
   why:'Choosing this confuses the trough with the peak. The trough is the level just before a dose. Straight after the last dose the level is at the peak, so the decline starts from Cmax∞.'},
  {t:'Cmax∞(1 − e^(-kt))',
   why:'Choosing this carries the infusion build-up equation into a decline. 1 − e^(-kt) describes a rise towards a plateau, as during an infusion. After the last dose the level only falls.'}],
 teach:[
  {t:'After the last dose the regimen is just first-order elimination from the steady-state peak. The equation sheet does not need to be searched for this: C = C0e^(-kt) with Cmax∞ as the starting value.'},
  M6_NDOSE, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p17',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Plasma Drug Concentration at Steady State"; 09.23 lecture',
 quote:'Last dose, we\'re gonna start at 53.3, and then it\'s just C0E minus KT.'},

/* ═══════════════ EXAMPLE 1 — the steady-state battery ══════════════════ */

{id:'m6-n01', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'first-dose-c0', skill:'vddose',
 source:'both',
 stem:'An antibiotic has an average t½ of approximately 4 hours and an apparent VD that is 25% of body weight. The drug is to be administered 10 mg/kg every 8 hours by multiple IV bolus injections to a 65-kg female. What is the expected maximum concentration after the first dose?',
 units:'mg/L',
 answer:40,
 tol:0.2,
 steps:[
  {k:'setup', t:'C0 = D0 / VD',
   why:'For an IV bolus the whole dose is in the body at time zero, so the first-dose peak is the dose divided by the volume of distribution. No drug was present before this dose.'},
  {k:'unit', t:'C0 = (10 mg/kg) / (0.25 L/kg)',
   why:'Both the dose and the volume are given per kilogram, so the kilograms cancel and the patient\'s weight is not needed. 25% of body weight is 0.25 L per kg.'},
  {k:'algebra', t:'C0 = 40 mg/L',
   why:'10 divided by 0.25 is 40, and mg over L leaves a concentration. The same result comes from 650 mg divided by 16.25 L.'},
  {k:'round', t:'C0 = 40 mg/L',
   why:'Her value, exact here. Every steady-state concentration in this example is this 40 mg/L multiplied by a factor that holds only k and τ, so an error here carries into every later part.'}],
 teach:[
  {t:'Every steady-state value in this example is built from this first-dose peak, so it is found first. When dose and volume are both per kilogram, the weight cancels.'},
  M6_EQ, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p9',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Example 1"; 09.23 lecture',
 quote:'Got 10 mg per kilogram. And 0.25 L per kilogram. Those are canceling. Do we get 40 mg per liter?'},

{id:'m6-n02', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'first-dose-cmin', skill:'conctime',
 source:'both',
 stem:'The same antibiotic (t½ 4 hours, VD 25% of body weight, 10 mg/kg every 8 hours by IV bolus to a 65-kg female) peaks at 40 mg/L after the first dose. What is the expected minimum concentration after the first dose?',
 units:'mg/L',
 answer:10,
 tol:0.1,
 steps:[
  {k:'setup', t:'Cmin = C0e^(-kτ)',
   why:'After the first dose the level falls by first-order elimination until the next dose, so the minimum is at the end of the interval, t = τ = 8 hr.'},
  {k:'algebra', t:'8 hr / 4 hr = 2 half-lives',
   why:'The interval is exactly two half-lives, so the level halves twice: 40, then 20, then 10. This can be done without a calculator.'},
  {k:'algebra', t:'Cmin = 40 mg/L × e^(-(0.693/4 hr)(8 hr)) = 40 × 0.25 = 10 mg/L',
   why:'k = 0.693/4 hr = 0.173 hr⁻¹, and kτ = 1.386 with no units, so e^(-1.386) = 0.25. The hours cancel inside the exponent.'},
  {k:'round', t:'Cmin = 10 mg/L',
   why:'Her value, 10 mg/L. It is the first-dose trough, the level just before the second dose, and the steady-state trough will be higher than it by the same accumulation factor as the peak.'}],
 teach:[
  {t:'This is single-dose kinetics from Module 2: C = C0e^(-kt) with t = τ. It is the value the steady-state trough is compared with.'},
  M6_ACCFAC, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p12',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Example 1"; 09.23 lecture',
 quote:'Half-Life is 4 hours. I\'m asking you concentration and 2 half-lives. 10 ... mg per liter? Yes.'},

{id:'m6-n03', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cmax-ss', skill:'multidose',
 source:'both',
 stem:'An antibiotic has an average t½ of approximately 4 hours and an apparent VD that is 25% of body weight. The drug is to be administered 10 mg/kg every 8 hours by multiple IV bolus injections to a 65-kg female. What is the expected maximum concentration at steady state?',
 units:'mg/L',
 answer:53.3,
 tol:0.3,
 steps:[
  {k:'setup', t:'Cmax∞ = C0 / (1 - e^(-kτ))',
   why:'At steady state each dose is added to drug left from earlier doses. Dividing the first-dose peak by (1 − e^(-kτ)) adds that accumulated drug.'},
  {k:'unit', t:'C0 = (10 mg/kg)/(0.25 L/kg) = 40 mg/L; k = 0.693/4 hr = 0.173 hr⁻¹',
   why:'The kilograms cancel in C0. The rate constant comes from the half-life, so it is in reciprocal hours, matching τ in hours.'},
  {k:'algebra', t:'kτ = (0.173 hr⁻¹)(8 hr) = 1.386; e^(-1.386) = 0.25',
   why:'Reciprocal hours times hours leaves a pure number, which is what an exponent must be. 0.25 is the fraction of each dose left at the end of the interval.'},
  {k:'algebra', t:'Cmax∞ = 40 mg/L / (1 - 0.25) = 40 / 0.75 = 53.3 mg/L',
   why:'Dividing by 0.75 raises the peak by a third, the accumulation factor 1.33 for an interval of two half-lives. 40 divided by 0.75 is 53.33.'},
  {k:'round', t:'Cmax∞ = 53.3 mg/L',
   why:'Her value, 53.3 mg/L. It is greater than the first-dose peak of 40 mg/L, as a steady-state peak must be; a result below 40 means the factor was multiplied instead of divided.'}],
 teach:[
  {t:'The steady-state peak is the first-dose peak multiplied by the accumulation factor. A result below the first-dose peak means the factor was inverted.'},
  M6_EQ, M6_ACCFAC, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p11',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "(a) What is the expected maximum concentration at steady state?" (Example 1); 09.23 lecture',
 quote:'53.3? OK, 53.3 mg per liter, which is greater than 40, right? That is what we expect.'},

{id:'m6-n04', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cmin-ss', skill:'multidose',
 source:'both',
 stem:'The same antibiotic (t½ 4 hours, VD 25% of body weight, 10 mg/kg every 8 hours by IV bolus to a 65-kg female) reaches a maximum of 53.3 mg/L at steady state. What is the expected minimum concentration at steady state?',
 units:'mg/L',
 answer:13.3,
 tol:0.2,
 steps:[
  {k:'setup', t:'Cmin∞ = Cmax∞e^(-kτ)',
   why:'From the steady-state peak to the steady-state trough is one interval of first-order elimination, so C = C0e^(-kt) with Cmax∞ as the starting value and t = τ. This is the same as the printed C0e^(-kτ)/(1 − e^(-kτ)).'},
  {k:'algebra', t:'Cmin∞ = 53.3 mg/L × e^(-(0.693/4 hr)(8 hr)) = 53.3 × 0.25',
   why:'k is unchanged at steady state, 0.173 hr⁻¹, and kτ = 1.386, a pure number. The interval is two half-lives, so the peak is halved twice.'},
  {k:'algebra', t:'Cmin∞ = 13.3 mg/L',
   why:'53.3 × 0.25 = 13.3. Starting from the first-dose peak instead gives 40/0.75 × 0.25, the same value by a longer route.'},
  {k:'round', t:'Cmin∞ = 13.3 mg/L',
   why:'Her value. It is above the first-dose trough of 10 mg/L by the same factor, 1.33, as the peak is above 40 mg/L.'}],
 teach:[
  {t:'The trough follows from the peak by one interval of decline, so there is no need to find a separate equation once Cmax∞ is known.'},
  M6_EQ, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p12',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "(b) What is the expected minimum concentration at steady state?" (Example 1); 09.23 lecture',
 quote:'So we\'re starting at 53.3 mg per liter, E to the minus. Our K has not changed, 0.693/4 ... the minimum occurs at 8 hours.'},

{id:'m6-n05', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cavg-ss', skill:'multidose',
 source:'both',
 stem:'An antibiotic has an average t½ of approximately 4 hours and an apparent VD that is 25% of body weight. The drug is to be administered 10 mg/kg every 8 hours by multiple IV bolus injections to a 65-kg female. What is the expected average concentration at steady state?',
 units:'mg/L',
 answer:28.9,
 tol:0.2,
 steps:[
  {k:'setup', t:'Cavg∞ = FD0 / (VD kτ), with F = 1',
   why:'The average over one interval at steady state is the dose divided by clearance times the interval, and clearance is VD k. An IV dose has F = 1.'},
  {k:'unit', t:'D0/VD = (10 mg/kg)/(0.25 L/kg) = 40 mg/L',
   why:'D0/VD is the first-dose C0 again, so the kilograms cancel and the value from part one can be reused. The dose is 650 mg and VD is 16.25 L, which give the same 40 mg/L.'},
  {k:'algebra', t:'Cavg∞ = 40 mg/L / ((0.693/4 hr)(8 hr)) = 40 / 1.386',
   why:'k is 0.693/4 = 0.173 hr⁻¹ and τ is 8 hr. k times τ is reciprocal hours times hours, a pure number, so the result stays in mg/L.'},
  {k:'algebra', t:'Cavg∞ = 28.9 mg/L',
   why:'40 divided by 1.386 is 28.86. kτ is 1.386 because the interval is two half-lives: 2 × 0.693. No exponential is needed for the average.'},
  {k:'round', t:'Cavg∞ = 28.9 mg/L',
   why:'Her value, 28.9 mg/L. It lies between the steady-state trough, 13.3, and peak, 53.3, and below their midpoint, 33.3, because the decline is exponential.'}],
 teach:[
  {t:'The average needs no accumulation factor and no exponential: only the dose, the clearance and the interval. It is not the midpoint of peak and trough.'},
  M6_EQ, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p13',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "(c) What is the expected average concentration at steady state?" (Example 1); 09.23 lecture',
 quote:'I\'m getting 28.9 mg per liter.'},

/* ═══════════════ EXAMPLES 2 AND 3 — before and after steady state ══════ */

{id:'m6-n06', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'cp-after-n', skill:'multidose',
 source:'both',
 stem:'An antibiotic has an average t½ of approximately 4 hours and an apparent VD that is 25% of body weight. The drug is to be administered 10 mg/kg every 8 hours by multiple IV bolus injections to a 65-kg female. What is the expected concentration 3 hours after injection of the 2nd dose?',
 units:'mg/L',
 answer:29.7,
 tol:0.2,
 steps:[
  {k:'setup', t:'Cp = (D0/VD)[(1 - e^(-nkτ))/(1 - e^(-kτ))]e^(-kt), with n = 2 and t = 3 hr',
   why:'Two doses are not steady state, so the n-dose equation is used. n is the dose just given and t is the time since it was given.'},
  {k:'unit', t:'D0/VD = 40 mg/L; k = 0.693/4 hr = 0.173 hr⁻¹; kτ = 1.386',
   why:'The kilograms cancel in D0/VD, giving 40 mg/L. All times are in hours, so kτ = 0.173 × 8 = 1.386 and each exponent is a pure number.'},
  {k:'algebra', t:'(1 - e^(-2 × 1.386))/(1 - e^(-1.386)) = (1 - 0.0625)/(1 - 0.25) = 0.9375/0.75 = 1.25',
   why:'e^(-2.772) = 0.25² = 0.0625. The bracket is how far the peak has risen after two doses: 1.25 times C0, against 1.33 at steady state.'},
  {k:'algebra', t:'e^(-kt) = e^(-(0.173 hr⁻¹)(3 hr)) = e^(-0.520) = 0.595',
   why:'This is the decline for the 3 hours since the second dose. Three hours is less than one half-life, so the factor must lie between 1 and 0.5.'},
  {k:'algebra', t:'Cp = 40 mg/L × 1.25 × 0.595 = 29.7 mg/L',
   why:'40 × 1.25 = 50 mg/L is the peak just after the second dose: 40 from the new dose plus the 10 left from the first. Three hours of decline takes it to 29.7.'},
  {k:'round', t:'Cp = 29.7 mg/L',
   why:'Her value, 29.7 mg/L. It is below the 31.7 mg/L found 3 hours after a dose at steady state, because after two doses less drug has accumulated.'}],
 teach:[
  {t:'Before steady state the n-dose equation places the time: the bracket gives the peak after dose n and e^(-kt) gives the decline since then. Most errors here are brackets, so each piece is worked separately.'},
  M6_NDOSE, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p14',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Example 2"; slide "Plasma Drug Concentration at Any Time After n Doses"; 09.23 lecture',
 quote:'Now this one becomes an exercise in parentheses, etc. So I\'m gonna tell you I got 29.7 mg per liter.'},

{id:'m6-n07', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'cp-after-last', skill:'multidose',
 source:'both',
 stem:'An antibiotic has an average t½ of approximately 4 hours and an apparent VD that is 25% of body weight. The drug is administered 10 mg/kg every 8 hours by multiple IV bolus injections to a 65-kg female, and the maximum at steady state is 53.3 mg/L. What is the expected concentration 3 hours after injection of the last dose (assuming steady state was attained)?',
 units:'mg/L',
 answer:31.7,
 tol:0.2,
 steps:[
  {k:'setup', t:'C = Cmax∞e^(-kt), with t = 3 hr',
   why:'After the last dose no more drug goes in, so the level falls from the steady-state peak by first-order elimination alone.'},
  {k:'algebra', t:'e^(-kt) = e^(-(0.693/4 hr)(3 hr)) = e^(-0.520) = 0.595',
   why:'k = 0.173 hr⁻¹ and t = 3 hr, so the exponent is a pure number. The time is the 3 hours after the last dose, not the 8-hour interval.'},
  {k:'algebra', t:'C = 53.3 mg/L × 0.595 = 31.7 mg/L',
   why:'Three hours is less than one half-life, so the level has fallen by less than half, and the answer must lie between 53.3 and 26.7 mg/L.'},
  {k:'round', t:'C = 31.7 mg/L',
   why:'31.7 mg/L, three significant figures as in her other values. It is higher than 29.7 mg/L at the same time after the second dose, because more drug has accumulated by steady state.'}],
 teach:[
  {t:'Once steady state is reached, the last dose starts the same decline as every other dose, from Cmax∞, and nothing follows it. The same value comes from the steady-state equation, (D0/VD)[1/(1 − e^(-kτ))]e^(-kt).'},
  M6_NDOSE, M6_FIG],
 teachImg:'slide_6RepetitiveIVBolus_p17',
 audit:'The 09.23 recording ends before she states a value for Example 3. Her method is on record ("Last dose, we\'re gonna start at 53.3, and then it\'s just C0E minus KT") and so are both inputs, 53.3 mg/L and t = 3 hr from the printed stem; 31.7 is 53.34 × e^(-0.17325 × 3) = 31.72. The handwritten working on the Example 3 slide of the annotated copy writes the exponent with 8 in place of 3, which would give the trough, so that slide is not attached as the image.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Example 3"; slide "Plasma Drug Concentration at Steady State"; 09.23 lecture',
 quote:'It should, it should definitely be less than 53.3, right?'},

{id:'m6-n08', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'cp-after-last', skill:'multidose',
 source:'both',
 stem:'An antibiotic with a t½ of 4 hours is at steady state on repeated IV bolus doses, with a maximum of 53.3 mg/L. What is the expected concentration 4 hours after injection of the last dose?',
 units:'mg/L',
 answer:26.7,
 tol:0.2,
 steps:[
  {k:'setup', t:'C = Cmax∞e^(-kt), with t = 4 hr',
   why:'After the last dose no more drug goes in, so the level falls from the steady-state peak, 53.3 mg/L, by first-order elimination.'},
  {k:'algebra', t:'4 hr = 1 half-life, so C = 53.3 mg/L / 2',
   why:'Four hours is exactly one half-life, so the level halves. With the exponential: e^(-(0.693/4)(4)) = e^(-0.693) = 0.5.'},
  {k:'algebra', t:'C = 26.7 mg/L',
   why:'Half of 53.3 is 26.65. Using the exponential gives the same: 53.3 × e^(-0.693) = 53.3 × 0.5, because kt = 0.693 exactly when t is one half-life.'},
  {k:'round', t:'C = 26.7 mg/L',
   why:'26.7 mg/L to three significant figures. After a second half-life, 8 hours after the last dose, it would be 13.3 mg/L, the steady-state trough.'}],
 teach:[
  {t:'When the time asked for is a whole number of half-lives, the answer can be found by halving, without the exponential.'},
  M6_NDOSE],
 teachImg:'slide_6RepetitiveIVBolus_p17',
 audit:'She sets this as a question at the end of the 09.23 recording ("So it\'s 1, so 4 hours is 1 half-life. So if I ask you the concentration 4 hours after the last.") and the recording stops there. 26.7 is 53.34 × 0.5 = 26.67, from her own 53.3 mg/L and t½ of 4 hours.',
 cite:'6---Repetitive-IV-Bolus-and-Intermittent-IV-Infusions.pdf, slide "Plasma Drug Concentration at Steady State"; 09.23 lecture',
 quote:'Now, if I asked you 4 hours after the last dose, What would you tell me? ... So it\'s 1, so 4 hours is 1 half-life.'},

/* ═══════════════ MULTIPLE IV BOLUS PRACTICE 1 (a–i) ════════════════════ */

{id:'m6-p1a', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'thalf-from-cl-vd', skill:'krate',
 source:'slide',
 stem:'One gram of a drug was administered by IV bolus injection every 8 hours to a 65-kg patient. The drug has an apparent VD of 26.2 L/100 kg. The total body clearance is 52.95 mL/min per 70 kg and renal clearance is 34.72 mL/min per 70 kg. Calculate the elimination half-life.',
 units:'hr',
 answer:4,
 tol:0.05,
 steps:[
  {k:'unit', t:'ClT = (52.95 mL/min / 70 kg) × 65 kg × (1 L / 1000 mL) × (60 min / hr) = 2.95 L/hr',
   why:'The clearance is given per 70 kg, so it is scaled to this 65-kg patient first. mL to L and minutes to hours put it in the same units as the volume and the answer.'},
  {k:'unit', t:'VD = (26.2 L / 100 kg) × 65 kg = 17.03 L',
   why:'The volume is also given per unit weight, per 100 kg here, so it is scaled to 65 kg the same way: 26.2 × 0.65 = 17.03 L.'},
  {k:'setup', t:'k = ClT / VD; t½ = 0.693 / k',
   why:'Clearance is k times VD, so k is clearance divided by volume, and the half-life follows from k. Both relations are ones she does not put on the equation sheet.'},
  {k:'algebra', t:'k = 2.95 L/hr / 17.03 L = 0.1732 hr⁻¹; t½ = 0.693 / 0.1732 hr⁻¹ = 4 hr',
   why:'In k = ClT/VD the litres cancel, leaving reciprocal hours; 0.693 divided by reciprocal hours leaves hours. 0.693/0.1732 = 4.00.'},
  {k:'round', t:'t½ = 4 hr',
   why:'Her keyed value, 4 hr. With τ = 8 hr the interval is two half-lives, the same as in Example 1, so the accumulation factor in the later parts is again 1.33.'}],
 teach:[
  {t:'Scale every per-weight parameter to the patient before combining them, and convert clearance to L/hr so that it cancels with a volume in litres.'},
  M6_EQ],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(a)',
 quote:'t½ = 0.693 / 0.1732 hr⁻¹ = 4hr'},

{id:'m6-p1b', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'first-dose-c0', skill:'vddose',
 source:'slide',
 stem:'One gram of a drug was administered by IV bolus injection every 8 hours to a 65-kg patient. The drug has an apparent VD of 26.2 L/100 kg. Calculate the maximum plasma drug concentration of the first dose.',
 units:'mg/L',
 answer:58.72,
 tol:0.1,
 steps:[
  {k:'unit', t:'D0 = 1 g = 1000 mg; VD = (26.2 L/100 kg)(65 kg) = 17.03 L',
   why:'Grams to milligrams so the answer is in mg/L, and the volume scaled to the patient, because it is given per 100 kg of body weight.'},
  {k:'setup', t:'Cmax (first dose) = D0 / VD',
   why:'The first bolus enters a body with no drug, so its peak is simply C0, the whole dose divided by the volume at time zero.'},
  {k:'algebra', t:'Cmax = 1000 mg / 17.03 L = 58.72 mg/L',
   why:'1000 divided by 17.03 is 58.72, and mg over L is a concentration. This C0 is the starting value for every later part.'},
  {k:'round', t:'Cmax = 58.72 mg/L',
   why:'Her keyed value, 58.72 mg/L, to two decimal places, the precision she carries through the rest of the set. It is also the first-dose Cmax.'}],
 teach:[
  {t:'The first-dose peak is C0 = D0/VD, the starting value for every steady-state concentration in this problem.'},
  M6_EQ],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(b)',
 quote:'Cmax = 1000mg / 17.03L = 58.72mg/L'},

{id:'m6-p1c', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'first-dose-cmin', skill:'conctime',
 source:'slide',
 stem:'One gram of a drug was given by IV bolus every 8 hours. The first dose peaks at 58.72 mg/L and k is 0.1732 hr⁻¹. Calculate the minimum plasma drug concentration of the first dose.',
 units:'mg/L',
 answer:14.69,
 tol:0.05,
 steps:[
  {k:'setup', t:'Cmin = Cmax e^(-kτ)',
   why:'After the first dose the level falls by first-order elimination until the next dose, so the minimum is at t = τ = 8 hr.'},
  {k:'algebra', t:'Cmin = 58.72 mg/L × e^(-(8 hr)(0.1732 hr⁻¹)) = 58.72 × 0.2502',
   why:'kτ = 8 × 0.1732 = 1.386, a pure number. The interval is two half-lives, so about a quarter of the peak remains.'},
  {k:'algebra', t:'Cmin = 14.69 mg/L',
   why:'58.72 × 0.2502 = 14.69. The same result comes from halving twice: 58.72, 29.36, 14.68, with the last digit set by rounding.'},
  {k:'round', t:'Cmin = 14.69 mg/L',
   why:'Her keyed value, 14.69 mg/L. It is the first-dose trough, and the steady-state trough in part (e) is higher by the accumulation factor.'}],
 teach:[
  {t:'The first-dose trough is single-dose decline over one interval.'},
  M6_ACCFAC],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(c)',
 quote:'Cmin = (58.72mg/L)e^−(8)(0.1732) = 14.69 mg/L'},

{id:'m6-p1d', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cmax-ss', skill:'multidose',
 source:'slide',
 stem:'One gram of a drug is given by IV bolus every 8 hours. The first dose peaks at 58.72 mg/L and k is 0.1732 hr⁻¹. Calculate the maximum steady-state plasma drug concentration.',
 units:'mg/L',
 answer:78.31,
 tol:0.2,
 steps:[
  {k:'setup', t:'Cmax∞ = C0 / (1 - e^(-kτ))',
   why:'The first-dose peak divided by (1 − e^(-kτ)) adds the drug accumulated from earlier doses, so the result must be larger than 58.72 mg/L.'},
  {k:'algebra', t:'e^(-(8 hr)(0.1732 hr⁻¹)) = e^(-1.386) = 0.2502; 1 - 0.2502 = 0.7498',
   why:'e^(-kτ) is the fraction of each dose left at the end of an interval, and 1 minus it is the fraction removed during the interval.'},
  {k:'algebra', t:'Cmax∞ = 58.72 mg/L / 0.7498 = 78.31 mg/L',
   why:'Dividing by a number less than 1 raises the peak, as accumulation must: 58.72/0.7498 = 78.31, a factor of 1.33.'},
  {k:'round', t:'Cmax∞ = 78.31 mg/L',
   why:'Her keyed value, 78.31 mg/L, higher than the first-dose 58.72 mg/L by the accumulation factor 1.33, as a steady-state peak must be.'}],
 teach:[
  {t:'The interval is two half-lives here too, so the accumulation factor is again 1.33: 58.72 × 1.33 = 78.3.'},
  M6_EQ, M6_ACCFAC],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(d)',
 quote:'C∞max = 58.72mg/L / (1 − e^−(8)(0.1732)) = 78.31mg/L'},

{id:'m6-p1e', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cmin-ss', skill:'multidose',
 source:'slide',
 stem:'A drug given by IV bolus every 8 hours reaches 78.31 mg/L at its steady-state peak, and k is 0.1732 hr⁻¹. Calculate the minimum steady-state plasma drug concentration.',
 units:'mg/L',
 answer:19.59,
 tol:0.1,
 steps:[
  {k:'setup', t:'Cmin∞ = Cmax∞e^(-kτ)',
   why:'From the steady-state peak to the steady-state trough is one interval of first-order decline, so the peak is multiplied by e^(-kτ).'},
  {k:'algebra', t:'Cmin∞ = 78.31 mg/L × e^(-(8)(0.1732)) = 78.31 × 0.2502',
   why:'The same fraction remains as after the first dose, 0.2502, because k and τ have not changed; only the starting level is higher.'},
  {k:'algebra', t:'Cmin∞ = 19.59 mg/L',
   why:'78.31 × 0.2502 = 19.59. Checked the other way, 14.69 × 1.3336 = 19.59, the first-dose trough times the accumulation factor.'},
  {k:'round', t:'Cmin∞ = 19.59 mg/L',
   why:'Her keyed value, 19.59 mg/L. It is above the first-dose trough of 14.69 mg/L, which is the drug that has accumulated.'}],
 teach:[
  {t:'Peak to trough at steady state is the same decline as after the first dose, starting higher.'},
  M6_EQ],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(e)',
 quote:'C∞min = (78.31mg/L)e^−(8)(0.1732) = 19.59mg/L'},

{id:'m6-p1f', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'cavg-ss', skill:'multidose',
 source:'slide',
 stem:'One gram of a drug is given by IV bolus every 8 hours to a patient whose total body clearance is 2.95 L/hr. Calculate the average steady-state plasma drug concentration.',
 units:'mg/L',
 answer:42.37,
 tol:0.1,
 steps:[
  {k:'setup', t:'Cavg∞ = FD0 / (ClT τ), with F = 1',
   why:'With clearance already known from part (a), the ClT form is the direct one; it is the same as FD0/(VD kτ) because ClT = kVD. IV dosing gives F = 1.'},
  {k:'algebra', t:'Cavg∞ = 1000 mg / ((2.95 L/hr)(8 hr))',
   why:'In the denominator L/hr times hr leaves L, so mg over L gives a concentration in mg/L. The dose is 1000 mg, one gram converted to milligrams.'},
  {k:'algebra', t:'Cavg∞ = 1000 / 23.6 = 42.37 mg/L',
   why:'2.95 × 8 = 23.6 L, the volume of plasma cleared of drug in one interval, and 1000 mg divided by 23.6 L is 42.37 mg/L.'},
  {k:'round', t:'Cavg∞ = 42.37 mg/L',
   why:'Her keyed value, 42.37 mg/L. It lies between the trough, 19.59, and the peak, 78.31, and below their midpoint, 48.95, because the decline is exponential.'}],
 teach:[
  {t:'Cavg∞ = FD0/(ClT τ) and FD0/(VD kτ) are the same equation, since ClT = kVD. Use whichever matches what the stem gives.'},
  M6_EQ],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(f)',
 quote:'C∞avg = 1000mg / (2.95L/hr)(8hr) = 42.37mg/L'},

{id:'m6-p1g', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'davg-ss', skill:'multidose',
 source:'slide',
 stem:'A drug given by repeated IV bolus has an average steady-state concentration of 42.37 mg/L and an apparent VD of 17.03 L. Calculate the average amount of drug in the body during steady state.',
 units:'mg',
 answer:721.6,
 tol:2,
 steps:[
  {k:'setup', t:'Davg∞ = Cavg∞ × VD',
   why:'Amount and concentration are linked by the volume of distribution at every time, including on average at steady state.'},
  {k:'algebra', t:'Davg∞ = (42.37 mg/L)(17.03 L)',
   why:'mg/L times L: the litres cancel, leaving mg, an amount, which is what the question asks for. The volume is the 17.03 L found in part (a).'},
  {k:'algebra', t:'Davg∞ = 721.6 mg',
   why:'42.37 × 17.03 = 721.6. The same result comes from the amount form, FD0/(kτ) = 1000/(0.1732 × 8) = 721.7, within rounding.'},
  {k:'round', t:'Davg∞ = 721.61 mg',
   why:'Her keyed value is 721.61 mg. It is less than the 1000-mg dose, because the average amount lies between the minimum and maximum amounts.'}],
 teach:[
  {t:'The amount forms of the steady-state equations are the concentration forms multiplied by VD. The same result comes from Davg∞ = FD0/(kτ) = 1000/(0.1732 × 8).'},
  M6_EQ],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(g)',
 quote:'D∞avg = (42.37mg/L)(17.03 L) = 721.61mg'},

{id:'m6-p1h', type:'numeric', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ndose', concept:'cp-after-last', skill:'multidose',
 source:'slide',
 stem:'A drug given by IV bolus every 8 hours has a steady-state peak of 78.31 mg/L and k of 0.1732 hr⁻¹. Calculate the plasma level 12 hours after the last dose, assuming steady-state levels are achieved.',
 units:'mg/L',
 answer:9.799,
 tol:0.05,
 steps:[
  {k:'setup', t:'C = Cmax∞e^(-kt), with t = 12 hr',
   why:'After the last dose at steady state the level falls from the steady-state peak by first-order elimination. The 12 hours is measured from the last dose.'},
  {k:'algebra', t:'e^(-(12 hr)(0.1732 hr⁻¹)) = e^(-2.078) = 0.1251',
   why:'12 × 0.1732 = 2.078, a pure number. Twelve hours is three half-lives, so one eighth remains: e^(-2.078) = 0.1251.'},
  {k:'algebra', t:'C = 78.31 mg/L × 0.1251 = 9.799 mg/L',
   why:'78.31 × e^(-2.078) = 9.799. Dividing 78.31 by 8 gives 9.79, the same result by halving three times: 39.16, 19.58, 9.79.'},
  {k:'round', t:'C = 9.799 mg/L',
   why:'Her keyed value, 9.799 mg/L. It is below the steady-state trough of 19.59 mg/L because 12 hours is longer than the 8-hour interval.'}],
 teach:[
  {t:'After the last dose, count half-lives from the steady-state peak. The interval τ plays no part once dosing has stopped.'},
  M6_NDOSE],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(h)',
 quote:'C∞12 = (78.31 mg/L)e^−(12)(0.1732) = 9.799 mg/L'},

{id:'m6-p1i', prof:'Mosley', tier:'new', exam:2, module:6, lecture:'L07',
 topic:'multi', sub:'ssbolus', concept:'renal-mechanism-p1', skill:'apply',
 source:'slide',
 stem:'The same drug has a renal clearance of 34.72 mL/min per 70 kg. What is the probable mechanism of its renal clearance?',
 options:[
  {t:'Glomerular filtration with tubular reabsorption', correct:true,
   why:'A renal clearance of 34.72 mL/min is below the glomerular filtration rate of 120 mL/min. The kidney removes less drug than filtration alone would, so some of the filtered drug must be reabsorbed in the tubule.'},
  {t:'Glomerular filtration with active tubular secretion',
   why:'Secretion adds drug to the urine beyond what is filtered, which would push renal clearance above 120 mL/min. A clearance below the filtration rate points the other way.'},
  {t:'Glomerular filtration only',
   why:'Choosing this reads a low clearance as plain filtration. Filtration alone would give a renal clearance about equal to the filtration rate, 120 mL/min. 34.72 mL/min is well below that.'},
  {t:'Hepatic metabolism',
   why:'Choosing this confuses renal clearance with hepatic clearance. The question is about renal clearance, the part of total clearance done by the kidney. Hepatic clearance here is the remainder, 52.95 − 34.72 = 18.23 mL/min, but it does not describe a renal mechanism.'}],
 teach:[
  {t:'Comparing renal clearance with the glomerular filtration rate of 120 mL/min, from Module 4, gives the mechanism: about equal means filtration only, above means secretion as well, below means reabsorption.'},
  {h:'Renal clearance against the filtration rate', table:{head:['Renal clearance', 'Mechanism'], rows:[['About 120 mL/min', 'Filtration only'], ['Above 120 mL/min', 'Filtration and active secretion'], ['Below 120 mL/min', 'Filtration and reabsorption']]}}],
 cite:'Multiple-IV-Bolus-Practice-1---Solutions.pdf, question 1(i)',
 quote:'ClR = 34.72 mL/min < GFR 120 mL/min → glomerular filtration with tubular reabsorption'},

];
