"""Checks the module layout on the Topics page, in a real browser.

Each module is one card with Concepts, Calculations and (where she handed
out problems) Worksheets. Concepts lists her objectives and a drill started
from one draws only concept questions from that objective. Calculations
lists the kinds of problem; Single problems draws only calculations of that
kind, every calculation belongs to exactly one kind, and each kind carries a
worked example. Worksheets holds only her handout problems, never a lecture
example. Every problem set has a Start button somewhere.

    python3 review_test.py
"""
import os, pathlib, sys
REPO = pathlib.Path(__file__).resolve().parent.parent
from playwright.sync_api import sync_playwright

OUT = pathlib.Path('/mnt/user-data/outputs/PHAR4221_Drill.html')
fails = []
def ok(msg, cond):
    print(('  ok    ' if cond else '  FAIL  ') + msg)
    if not cond: fails.append(msg)

def drain(pg):
    ids, seen = [], set()
    for _ in range(300):
        cur = pg.evaluate("Q && Q.current && Q.current.id")
        if not cur or cur in seen: break
        seen.add(cur); ids.append(cur)
        pg.evaluate("Q.revealed = true; nextQuestion()")
    return ids

def page(pg, module, sec):
    pg.evaluate("MODPAGE = null; show('topics')"); pg.wait_for_timeout(100)
    # a module's buttons sit inside its exam's card, which may start closed
    btn = f'.modbtn[data-mod="{module}"][data-sec="{sec}"]'
    if not pg.is_visible(btn):
        pg.click(f'details.examgrp:has({btn}) > summary'); pg.wait_for_timeout(100)
    pg.click(btn); pg.wait_for_timeout(150)

with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={'width': 1100, 'height': 1300})
    errs = []; pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.add_init_script("window.prompt = () => 'Layout'")
    pg.goto(OUT.as_uri()); pg.wait_for_timeout(700)
    print('\n=== Folded sections ===')
    pg.evaluate("show('ref')"); pg.wait_for_timeout(200)
    ok('Reference opens with its sections folded and grouped by exam',
       pg.locator('#v-ref details.dsec').count() >= 10 and pg.locator('#v-ref details.dsec[open]').count() == 0 and pg.locator('#v-ref details.dgrp').count() == 2)
    ok('the exam being prepared for is the open group', pg.evaluate("document.querySelector('#v-ref details.dgrp[data-examgrp=\"doc-2\"]').open") is True and pg.evaluate("document.querySelector('#v-ref details.dgrp[data-examgrp=\"doc-1\"]').open") is False)
    pg.click('#v-ref [data-fold="open"]'); pg.wait_for_timeout(150)
    ok('Expand all opens every section', pg.locator('#v-ref details.dsec:not([open])').count() == 0)
    pg.reload(); pg.wait_for_timeout(600); pg.evaluate("show('ref')"); pg.wait_for_timeout(200)
    ok('the choice survives a reload', pg.locator('#v-ref details.dsec:not([open])').count() == 0)
    pg.evaluate("show('guide')"); pg.wait_for_timeout(200)
    ok('Guides folds each objective inside its module', pg.locator('#v-guide details.dmod').count() >= 8 and pg.locator('#v-guide details.dsec').count() >= 30)
    pg.evaluate("show('tell')"); pg.wait_for_timeout(200)
    ok('Tell apart has an Exam 1, a both-exams and an Exam 2 group', pg.locator('#v-tell details.dgrp').count() == 3)
    pg.evaluate("show('settings')"); pg.wait_for_timeout(200)
    ok('the change log in Settings starts folded', pg.evaluate("document.getElementById('changelog').open") is False)
    pg.evaluate("['guide','ref','tell','diag'].forEach(p => LS.set(FOLD_KEY + p, 'open'))"); pg.evaluate("show('topics')"); pg.wait_for_timeout(200)

    print('\n=== Module layout ===')
    mods = pg.evaluate("outline().filter(m => m.module != null && modulePool(m.module).length).map(m => m.module)")
    ok(f'one card per module ({len(mods)})', pg.locator('.modcard').count() == len(mods))
    grp = pg.evaluate("[...document.querySelectorAll('details.examgrp')].map(d => [+d.dataset.examgrp, [...d.querySelectorAll('.modbtn[data-sec=concepts]')].map(x => +x.dataset.mod), !!d.querySelector('.recapcard'), d.open])")
    want = {e: sorted({l['module'] for l in pg.evaluate('COURSE.lectures') if l['exam'] == e and l['module'] in mods}) for e, *_ in grp}
    ok('each exam card holds exactly its own modules: ' + '; '.join(f'exam {e}: {m}' for e, m, *_ in grp),
       all(sorted(m) == want[e] for e, m, *_ in grp) and sorted(x for _, m, *_ in grp for x in m) == sorted(mods))
    ok('each exam card ends with a review of the whole exam', all(r for *_, r, _ in grp))
    ok('only the exam being prepared for starts open',
       all(o == (e == pg.evaluate('EXAM.id')) for e, _, _, o in grp))
    print('\n=== Quiz prep ===')
    live = pg.evaluate("(COURSE.quizzes||[]).filter(quizLive).map(z=>z.id)")
    if live:
        qid = live[0]
        ok(f'a card for {qid} is on the page', pg.locator('.quizcard').count() == len(live))
        qmods = pg.evaluate("COURSE.quizzes.find(z=>z.id===%r).modules" % qid)
        pool_mods = pg.evaluate("[...new Set(quizScope(COURSE.quizzes.find(z=>z.id===%r)).map(q=>q.module))]" % qid)
        ok('the quiz pool holds only the modules she named', bool(pool_mods) and all(m in qmods for m in pool_mods))
        avail = pg.evaluate("quizScope(COURSE.quizzes.find(z=>z.id===%r)).filter(q=>!q.lowYield).length" % qid)
        pg.click('[data-quizn="8"]'); pg.wait_for_timeout(150)
        pg.click(f'[data-quizpaper="{qid}"]'); pg.wait_for_timeout(300)
        n = pg.evaluate("EX && EX.running ? EX.qs.length : 0")
        ok('a practice quiz of the chosen length starts on the exam engine', n == min(8, avail))
        ok('its clock runs on the quiz minutes', pg.evaluate("Math.round((EX.ends-Date.now())/60000)") == pg.evaluate("COURSE.quizzes.find(z=>z.id===%r).minutes" % qid))
        kinds = pg.evaluate("EX.qs.map(q => kindOf(q))")
        ok('the paper is half concept, half calculation, as her quizzes are', kinds.count('concept') == min(8, avail) // 2 and kinds.count('calc') == min(8, avail) - min(8, avail) // 2)
        ok('no worksheet part is on the paper while stand-alone items suffice', not any(i.startswith(('ws', 'hw')) for i in pg.evaluate("EX.qs.map(q => q.id)")))
        pg.evaluate("finishExam()"); pg.wait_for_timeout(200)
        ok('the paper is logged under the quiz, not the exam', pg.evaluate("DB.exams[DB.exams.length-1].exam") == qid)
        pg.evaluate("EX=null; show('topics')"); pg.wait_for_timeout(200)
        pg.click('[data-quizmin="15"]'); pg.wait_for_timeout(150)
        pg.click(f'[data-quizpaper="{qid}"]'); pg.wait_for_timeout(300)
        ok('a minutes chip sets the clock of the practice quiz', pg.evaluate("Math.round((EX.ends-Date.now())/60000)") == 15)
        pg.evaluate("clearInterval(EX.timer); EX=null; show('topics')"); pg.wait_for_timeout(200)
        pg.evaluate("EX=null; show('topics')"); pg.wait_for_timeout(200)
        pg.click(f'[data-quizhide="{qid}"]'); pg.wait_for_timeout(150)
        gone = pg.locator('.quizcard').count() == len(live) - 1
        pg.reload(); pg.wait_for_timeout(500)
        ok('Hide removes the card and the choice survives a reload', gone and pg.locator('.quizcard').count() == len(live) - 1)
        pg.evaluate("localStorage.removeItem(QUIZ_HIDE_KEY + %r)" % qid); pg.reload(); pg.wait_for_timeout(500)
        ok('a quiz whose time has passed shows no card',
           pg.evaluate("quizLive(Object.assign({}, COURSE.quizzes[0], {id:'past', when:'2000-01-01T08:00', minutes:24}))") is False)
    else:
        print('  skip  no quiz is live today, so the card is not on the page')

    ok('no topic list or review switch on the main page',
       pg.locator('#v-topics details.topic').count() == 0 and pg.locator('#v-topics .rtab').count() == 0)
    untyped = pg.evaluate("QUESTIONS.filter(q => kindOf(q) === 'calc' && !calcTypeOf(q)).map(q => q.id)")
    ok('every calculation belongs to a kind of problem', not untyped)
    orphan = pg.evaluate("""QUESTIONS.filter(q => kindOf(q) === 'concept' &&
        !OBJECTIVES.some(o => o.module === q.module && o.subs.includes(subKey(q)))).map(q => q.id)""")
    ok('every concept question belongs to one of her objectives', not orphan)
    badex = pg.evaluate("CALC_TYPES.filter(t => !byId(t.example) || calcTypeOf(byId(t.example)) !== t).map(t => t.id)")
    ok('every kind of problem has a worked example of its own kind', not badex)

    chain_buttons = set()
    for m in mods:
        page(pg, m, 'concepts')
        n = pg.locator('#v-topics [data-obj]').count()
        ok(f'module {m}: {n} objectives listed', n > 0)
        pg.locator('#v-topics [data-obj]').first.click(); pg.wait_for_timeout(150)
        pool = pg.evaluate("Q.pool.map(kindOf)"); served = drain(pg)
        ok(f'module {m}: an objective drill draws only concepts ({len(pool)})', pool and all(k == 'concept' for k in pool))

        page(pg, m, 'calcs')
        types = pg.locator('#v-topics [data-ctype]').count()
        ok(f'module {m}: {types} kinds of calculation, each with a worked example',
           types > 0 and pg.locator('#v-topics .ctype details.worked .steps').count() >= types)
        tid = pg.get_attribute('#v-topics [data-ctype]', 'data-ctype')
        pg.locator('#v-topics [data-ctype]').first.click(); pg.wait_for_timeout(150)
        pool = pg.evaluate(f"Q.pool.map(q => calcTypeOf(q) && calcTypeOf(q).id)")
        ok(f'module {m}: Single problems draws only its own kind ({len(pool)})', pool and all(x == tid for x in pool))
        page(pg, m, 'calcs')
        pg.evaluate("document.querySelectorAll('#v-topics details').forEach(d => d.open = true)")
        chain_buttons |= set(pg.eval_on_selector_all('#v-topics button[data-chain]', 'bs => bs.map(b => b.dataset.chain)'))

        pg.evaluate("MODPAGE = null; show('topics')")
        if pg.locator(f'.modbtn[data-mod="{m}"][data-sec="worksheets"]').count():
            page(pg, m, 'worksheets')
            ws = pg.eval_on_selector_all('#v-topics button[data-chain]', 'bs => bs.map(b => b.dataset.chain)')
            srcs = pg.evaluate("ids => ids.map(id => CHAINS.find(c => c.id === id).src)", ws)
            ok(f'module {m}: worksheets hold only handout problems ({len(ws)})', ws and 'example' not in srcs)
            chain_buttons |= set(ws)

    ok('extra practice stays out of the main bank and the exam pools',
       pg.evaluate("EXTRAS.length > 0 && !EXTRAS.some(x => QUESTIONS.includes(x)) && !POOLS.some(p => poolQuestions(p).some(q => q.extra))"))
    pg.evaluate("MODPAGE = {module: 6, sec: 'calcs'}; show('topics')")
    pg.locator('#v-topics [data-xtype]').first.click(); pg.wait_for_timeout(150)
    ok('an Extra practice row draws only extra problems of its kind',
       pg.evaluate("Q.pool.length > 0 && Q.pool.every(q => q.extra && q.xtype === Q.pool[0].xtype)"))
    allc = set(pg.evaluate("CHAINS.map(c => c.id)"))
    ok(f'every problem set has a Start button ({len(chain_buttons & allc)} of {len(allc)})', allc <= chain_buttons)

    pg.evaluate("MODPAGE = null; show('topics')")
    pg.click('#v-topics button[data-view="eq"]'); pg.wait_for_timeout(200)
    ok('the Equations entry in the outline opens the equation drill', pg.evaluate("VIEW") == 'eq')
    pg.evaluate("MODPAGE = {module: 6, sec: 'calcs'}; show('topics')")
    pg.click('#nav button[data-v="topics"]'); pg.wait_for_timeout(150)
    ok('tapping Topics while on a module page returns to the module list', pg.locator('.modcard').count() == len(mods))

    # answer layout: on one page, then back to one at a time, never repeating
    pg.evaluate("MODPAGE = {module: 6, sec: 'calcs'}; show('topics')")
    pg.click('#v-topics [data-calcall]'); pg.wait_for_timeout(150)
    pg.click('#v-quiz [data-layout="all"]'); pg.wait_for_timeout(200)
    cards = pg.locator('#v-quiz .allcard').count()
    ok(f'All on one page shows the drill as cards ({cards})', cards >= 2)
    first = pg.locator('#v-quiz .allcard').first
    fid = first.get_attribute('data-qid')
    first.locator('input.numin').fill(str(pg.evaluate(f"byId('{fid}').answer")))
    first.locator('[data-check]').click(); pg.wait_for_timeout(150)
    ok('a card answered on the page is marked in place and logged',
       pg.locator(f'#v-quiz .allcard[data-qid="{fid}"] .verdict.ok').count() == 1 and pg.evaluate("DB.answers.slice(-1)[0].qid") == fid)
    pg.click('#v-quiz [data-layout="one"]'); pg.wait_for_timeout(150)
    seen = []
    for _ in range(40):
        cur = pg.evaluate("Q && Q.current && Q.current.id")
        if not cur: break
        seen.append(cur); pg.evaluate("Q.revealed = true; markDone(Q.current.id); nextQuestion()")
    ok(f'switching back to one at a time never asks it again ({len(seen)} served)', fid not in seen)
    pg.evaluate("DB.settings.layout = 'all'; EX = null; show('exam')"); pg.wait_for_timeout(150)
    pg.click('#startExam'); pg.wait_for_timeout(300)
    n = pg.locator('#v-exam .allcard').count()
    ok(f'the exam on one page shows every question ({n})', n == pg.evaluate("EX.qs.length") and pg.locator('#exClock').count() == 1)
    pg.evaluate("window.confirm = () => true"); pg.click('#exEnd'); pg.wait_for_timeout(300)
    ok('submitting the one-page paper shows the result', pg.evaluate("EX && EX.done"))
    pg.evaluate("DB.settings.layout = 'one'; EX = null")

    # Explain more: every question links somewhere, and every target exists
    nolink = pg.evaluate("QUESTIONS.concat(EXTRAS).filter(q => !linksFor(q).length).map(q => q.id)")
    ok(f'every question has at least one Explain-more link ({len(nolink)} without)', not nolink)
    targets = pg.evaluate("[...new Set(QUESTIONS.concat(EXTRAS).flatMap(q => linksFor(q).map(l => l[0] + ':' + l[1])))]")
    missing = []
    for t in targets:
        v, a = t.split(':')
        pg.evaluate(f"show('{v}')")
        if not pg.evaluate(f"!!document.getElementById('{a}')"): missing.append(t)
    ok(f'every Explain-more target exists ({len(targets)} targets)', not missing)
    if missing: print('   ', missing[:8])
    pg.evaluate("RET = []; startChain('m6-ex1')"); pg.wait_for_timeout(150)
    pg.fill('#numIn', '1'); pg.click('#btnCheck'); pg.wait_for_timeout(150)
    pg.click('#v-quiz [data-mk="setup"]'); pg.wait_for_timeout(150)
    qid = pg.evaluate("Q.current.id")
    pg.locator('#v-quiz [data-jump]').first.click(); pg.wait_for_timeout(250)
    went = pg.evaluate("VIEW")
    ok(f'an Explain-more button opens its section ({went}) and offers the way back', went != 'quiz' and pg.locator('#backbtn').count() == 1)
    pg.click('#backbtn'); pg.wait_for_timeout(250)
    ok('the way back returns to the same answered question',
       pg.evaluate("VIEW") == 'quiz' and pg.evaluate("Q.current.id") == qid and pg.locator('#v-quiz .verdict').count() == 1 and pg.locator('#backbtn').count() == 0)

    pg.evaluate("RET = []; backBtn(); show('tell')"); pg.wait_for_timeout(200)
    pg.select_option('select[data-xsel="dosing"]', 'm3-infusion'); pg.wait_for_timeout(200)
    pg.click('[data-jump="diag:dg-infusion_steps"]'); pg.wait_for_timeout(500)
    pg.click('#backbtn'); pg.wait_for_timeout(300)
    ok('the way back from a step-through reopens the Explain-one card it left',
       pg.evaluate("VIEW") == 'tell' and pg.evaluate("document.querySelector('select[data-xsel=\"dosing\"]').value") == 'm3-infusion' and pg.locator('[data-xout="dosing"] .xexp').count() == 1)
    pg.evaluate("RET = []; backBtn(); show('quiz')"); pg.wait_for_timeout(150)

    pg.evaluate("RET = []; backBtn(); startPool(QUESTIONS.filter(q => q.id === 'fig-ord-4'), 'x')"); pg.wait_for_timeout(150)
    pg.locator('#v-quiz .opt').first.click(); pg.wait_for_timeout(150)
    pg.locator('#v-quiz [data-jump^="diag"]').click(); pg.wait_for_timeout(900)
    top = pg.evaluate("document.getElementById('dg-ord_semilog_curve').getBoundingClientRect().top")
    ok(f'a jump lands its section just below the header ({round(top)} px from the top)', 40 <= top <= 160)
    pg.click('#backbtn'); pg.wait_for_timeout(200)

    print('\n=== Number boxes on two tabs ===')
    # a numeric question parked on the Quiz tab must not catch the exam's typing
    pg.evaluate("RET = []; backBtn(); EX = null; startPool(QUESTIONS.filter(q => qType(q) === 'numeric').slice(0, 1), 'x')"); pg.wait_for_timeout(150)
    pg.evaluate("const qs = QUESTIONS.filter(q => qType(q) === 'numeric').slice(1, 3); startPaper(qs, 5, {title:'probe', paper:'probe', sata:{per:[],drawn:0}, coverage:{drawn:0,missing:0,short:[],shares:[]}}); show('exam')"); pg.wait_for_timeout(200)
    ok('the exam shows its own number box', pg.locator('#v-exam #numIn').count() == 1)
    pg.fill('#v-exam #numIn', '12.5'); pg.wait_for_timeout(100)
    ok('typing in the exam box is kept as the exam answer', pg.evaluate("EX.picks[0]") == '12.5')
    ok('the parked quiz question is untouched', pg.evaluate("Q.picked") is None)
    pg.evaluate("clearInterval(EX.timer); EX = null; show('quiz')"); pg.wait_for_timeout(150)
    ok('the quiz hint names the 2% rule and no absolute tolerance', 'within 2% of the keyed value' in pg.locator('#v-quiz .sata').inner_text() and 'within 0.' not in pg.locator('#v-quiz .sata').inner_text())
    pg.fill('#v-quiz #numIn', '7'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    ok('a quiz answer typed after the paper is graded from the quiz box', pg.evaluate("Q.revealed && String(Q.picked) === '7'"))
    ok('a blank numeric miss reads as left blank', pg.evaluate("pickedRead(Q.current, {picked: ''}).txt") == 'left blank')
    pg.evaluate("RET = []; backBtn(); EX = null; startPool(QUESTIONS.filter(q => q.id === 'cq3-5'), 'x'); show('quiz')"); pg.wait_for_timeout(150)
    pg.fill('#v-quiz #numIn', '2.6 hr'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    ok('a number typed with its unit is graded right', pg.evaluate("Q.revealed && gradeAnswer(Q.current, Q.picked)"))
    ok('the article before a miss kind is right', pg.evaluate("[an('unit conversion'), an('algebra'), an('set-up')].join('|')") == 'a unit conversion|an algebra|a set-up')

    print('\n=== Equations: one module at a time ===')
    pg.evaluate("RET = []; backBtn(); EX = null; SU = null; EQ = null; show('eq')"); pg.wait_for_timeout(150)
    pg.click('#v-eq button[data-pick="m:4"]'); pg.wait_for_timeout(200)
    ok('Only Module 4 selects that module and nothing else', pg.evaluate("eqChosen().length === EQUATIONS.filter(e => e.module === 4).length && eqChosen().every(id => EQ_BY_ID[id].module === 4)"))
    pg.click('#v-eq button[data-start="type"]'); pg.wait_for_timeout(200)
    ok('Start then drills only that module', pg.evaluate("EQ && EQ.queue.every(id => EQ_BY_ID[id].module === 4)"))
    pg.evaluate("EQ = null")

    print('\n=== Set-up drill, sheet map, guess then stuck ===')
    pg.evaluate("RET = []; backBtn(); EX = null; SU = null; EQ = null; show('eq')"); pg.wait_for_timeout(150)
    ok('the Equations picker offers the set-up drill with a scope per module', pg.locator('#v-eq .sucard').count() == 1 and pg.locator('#v-eq button[data-su="all"]').count() == 1 and pg.locator('#v-eq button[data-su="3"]').count() == 1)
    pg.click('#v-eq button[data-su="3"]'); pg.wait_for_timeout(200)
    ok('starting it shows one of her Module 3 stems with four lines to choose from', pg.locator('#v-eq .suq .stem').count() == 1 and pg.locator('#v-eq .suopt').count() == 4 and pg.evaluate("SU.queue.every(q => q.module === 3)"))
    wrong = pg.evaluate("(() => { const q = SU.queue[SU.i]; return SU.page[q.id].options.findIndex(o => o.id !== q.setup.eq); })()")
    pg.click(f'#v-eq button[data-suopt="{wrong}"]'); pg.wait_for_timeout(200)
    sud = pg.evaluate("({w: document.querySelectorAll('#v-eq .suopt.wrong').length, r: document.querySelectorAll('#v-eq .suopt.right').length, vb: document.querySelectorAll('#v-eq .verdict.bad').length, sr: document.querySelectorAll('#v-eq .suright').length, asked: SU.asked, right: SU.right, id: SU.queue[SU.i].id, layout: layoutOf(), picked: SU.page[SU.queue[SU.i].id].picked})")
    ok(f'a wrong pick is marked, the right line is shown with why, and the lines used on the way ({sud})', sud['w'] == 1 and sud['r'] == 1 and sud['vb'] == 1 and sud['sr'] == 1 and sud['asked'] == 1 and sud['right'] == 0)
    ok('the wrong line is tallied per equation', pg.evaluate("Object.values(suStats()).some(r => r.wrong === 1)"))
    pg.click('#v-eq [data-sushow]'); pg.wait_for_timeout(150)
    ok('Show the problem worked out opens the keyed answer and the steps in place', pg.locator('#v-eq .suwork .steps .step').count() >= 1 and pg.locator('#v-eq .suq').count() == 1)
    pg.evaluate("(() => { const q = suPoolAll().find(x => x.setup.eq === 'thalf-cl-vd'); SU = {queue: [q], i: 0, right: 0, asked: 0, scope: 'all', page: {}}; renderEq(); })()"); pg.wait_for_timeout(150)
    right = pg.evaluate("(() => { const q = SU.queue[0]; return SU.page[q.id].options.findIndex(o => o.id === q.setup.eq); })()")
    pg.click(f'#v-eq button[data-suopt="{right}"]'); pg.wait_for_timeout(150)
    ok('a line the sheet does not print comes with the way to reach it', pg.locator('#v-eq .derive').count() == 1 and 'Cl = k' in pg.locator('#v-eq .derive').inner_text())
    ok('the stems come shuffled', pg.evaluate("(() => { const a = suScopePool('all').map(q => q.id); const s1 = shuffle(a.slice()), s2 = shuffle(a.slice()); return s1.join() !== s2.join() || s1.join() !== a.join(); })()"))
    ok('Work the full problem opens that stem in the quiz', (pg.click('#v-eq [data-suwork]'), pg.wait_for_timeout(200), pg.evaluate("VIEW === 'quiz' && Q.pool.length === 1 && Q.current.setup != null"))[2])
    pg.evaluate("show('ref')"); pg.wait_for_timeout(200)
    pg.evaluate("(() => { const s = document.querySelector('#v-ref .sheetmap'); let d = s.closest('details'); while(d){ d.open = true; d = d.parentElement.closest('details'); } })()")
    ok('Reference opens with the sheet map first: 52 lines in four columns, coloured by module', pg.locator('#v-ref .sheetmap .smlines .smline').count() == 52 + 5 and pg.locator('#v-ref .sheetmap .smcol').count() == 5 and pg.locator('#v-ref .sheetmap .smline.m6').count() >= 10)
    ok('the first folded section of Reference is the sheet map', pg.locator('#v-ref details.dsec').first.locator('h3').inner_text().startswith('Her equation sheet'))
    ok('every line carries its dosing model label', pg.locator('#v-ref .sheetmap .smline .smmodel').count() == 52 + 5)
    pg.click('#v-ref [data-sheetorder="asks"]'); pg.wait_for_timeout(200)
    ok('By what is asked regroups the same lines under the quantity asked, C at a time first', pg.locator('#v-ref .sheetmap .smline').count() == 52 + 5 and pg.locator('#v-ref .sheetmap .smcol').first.inner_text().startswith('C at a time') and pg.evaluate("sheetOrder()") == 'asks')
    pg.click('#v-ref [data-sheetorder="model"]'); pg.wait_for_timeout(200)
    ok('By dosing model groups them by model and the choice is remembered', pg.locator('#v-ref .sheetmap .smcol').count() >= 15 and pg.evaluate("localStorage.getItem(SHEET_ORDER_KEY)") == 'model')
    pg.click('#v-ref [data-sheetorder="print"]'); pg.wait_for_timeout(200)
    ok('the printable sheet reproduces the two pages in two columns with a model tag on every line', pg.evaluate("(() => { const d = document.createElement('div'); d.innerHTML = sheetPrintHTML(); return d.querySelectorAll('.sppage').length === 2 && d.querySelectorAll('.spcol').length === 4 && d.querySelectorAll('.spline').length === 57 && d.querySelectorAll('.sptag').length === 57; })()"))
    pg.click('#v-ref .sheetmap [data-sheetdrill="css"]'); pg.wait_for_timeout(200)
    ok('Drill this line starts the typing drill on that one line', pg.evaluate("VIEW === 'eq' && EQ && EQ.queue.length === 1 && EQ.queue[0] === 'css' && EQ.mode === 'type'"))
    pg.evaluate("EQ = null; SU = null; startPool(QUESTIONS.filter(q => q.id === 'inf-n5'), 'x'); show('quiz')"); pg.wait_for_timeout(150)
    pg.fill('#v-quiz #numIn', '2.84'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    pg.click('#btnGuess'); pg.wait_for_timeout(200)
    ok('a correct answer marked as a guess is asked where it got stuck', pg.locator('#v-quiz .misskind').count() == 1 and 'stuck' in pg.locator('#v-quiz .misskind p').inner_text())
    pg.click('#v-quiz [data-mk="setup"]'); pg.wait_for_timeout(200)
    last = pg.evaluate("DB.answers[DB.answers.length-1]")
    ok('the kind of miss is written onto the guessed entry', last['result'] == 'guessed' and last.get('missKind') == 'setup')
    ok('a set-up miss names the line and offers the set-up drill for the module', pg.locator('#v-quiz [data-sheetsetup="3"]').count() == 1 and pg.locator('#v-quiz .misskind').count() == 0)
    pg.click('#v-quiz [data-sheetsetup="3"]'); pg.wait_for_timeout(200)
    ok('that chip starts the drill scoped to the module', pg.evaluate("VIEW === 'eq' && SU && SU.scope === '3'"))
    pg.click('#v-eq [data-layout="all"]'); pg.wait_for_timeout(200)
    ok('All on one page shows ten stems at once, each with its own four lines', pg.locator('#v-eq .suq').count() == 10 and pg.locator('#v-eq .suq').first.locator('.suopt').count() == 4)
    right = pg.evaluate("(() => { const q = SU.queue[SU.i + 2]; return SU.page[q.id].options.findIndex(o => o.id === q.setup.eq); })()")
    pg.click(f'#v-eq [data-suq="2"] button[data-suopt="{right}"]'); pg.wait_for_timeout(150)
    ok('a card answered on the page is marked in place and the tally moves', pg.locator('#v-eq [data-suq="2"] .verdict.ok').count() == 1 and pg.locator('#v-eq .suq').count() == 10 and pg.evaluate("SU.asked === 1 && SU.right === 1"))
    pg.click('#v-eq [data-sunext="page"]'); pg.wait_for_timeout(200)
    ok('Next moves on by a page', pg.evaluate("SU.i === 10"))
    pg.click('#v-eq [data-layout="one"]'); pg.wait_for_timeout(200)
    ok('switching back shows one stem at a time', pg.locator('#v-eq .suq').count() == 1 and pg.evaluate("layoutOf() === 'one'"))
    pg.evaluate("SU = null")

    print('\n=== No, I was right ===')
    pg.evaluate("RET = []; backBtn(); EX = null; startPool(QUESTIONS.filter(q => q.id === 'cq3-7'), 'x'); show('quiz')"); pg.wait_for_timeout(150)
    pg.evaluate("st('renal-clearance-from-urine').box = 2; st('renal-clearance-from-urine').streak = 2; save()")
    pg.fill('#v-quiz #numIn', '=3.13'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    ok('a number with a stray character is graded wrong', pg.evaluate("Q.revealed && !gradeAnswer(Q.current, Q.picked)") and pg.locator('#btnRight').count() == 1)
    pg.click('#btnRight'); pg.wait_for_timeout(200)
    last = pg.evaluate("DB.answers[DB.answers.length-1]")
    stc = pg.evaluate("DB.concepts['renal-clearance-from-urine']")
    ok('the log entry flips to correct and is marked as an override', last['result'] == 'correct' and last.get('overrode') is True and 'missKind' not in last)
    ok('box and streak go back to where they were and advance', stc['box'] == 3 and stc['streak'] == 3)
    ok('the verdict reads as counted right and the miss-kind prompt is gone', pg.locator('#v-quiz .verdict.ok').count() == 1 and pg.locator('#v-quiz .misskind').count() == 0 and pg.locator('#btnRight').count() == 0)
    ok('a second press has nothing to flip', pg.evaluate("markRight(Q.current)") is False)

    pg.evaluate("const qs = QUESTIONS.filter(q => q.id === 'cq3-6'); startPaper(qs, 5, {title:'probe', paper:'probe', sata:{per:[],drawn:0}, coverage:{drawn:0,missing:0,short:[],shares:[]}}); show('exam')"); pg.wait_for_timeout(200)
    pg.fill('#v-exam #numIn', '188..2'); pg.wait_for_timeout(100)
    pg.evaluate("finishExam()"); pg.wait_for_timeout(200)
    ok('the paper scores the slip as a miss', pg.evaluate("DB.exams[DB.exams.length-1].right") == 0 and pg.locator('#v-exam button[data-right]').count() == 1)
    pg.click('#v-exam button[data-right]'); pg.wait_for_timeout(200)
    ok('a submitted paper offers the clip and does not play it on its own', pg.locator('#cheerGo').count() == 1 and pg.locator('#cheer').count() == 0)
    # the headless browser cannot decode the clip, so the box is read in the same tick it opens
    src = pg.evaluate("(() => { document.getElementById('cheerGo').click(); const v = document.querySelector('#cheer video'); return v ? v.getAttribute('src') : null; })()")
    ok('pressing the offer opens the box with one of the two clips', src in ('media/cheer-1.mp4', 'media/cheer-2.mp4'))
    ok('Close removes it', pg.evaluate("(() => { const b = document.getElementById('cheer'); if(b) b.remove(); celebrate(); document.getElementById('cheerClose').click(); return !document.getElementById('cheer'); })()"))
    ok('two clips are on offer and both files are in the repository', pg.evaluate("CHEER.length") == 2 and all((REPO / p).exists() for p in pg.evaluate("CHEER")))
    pg.evaluate("DB.settings.cheer = false; save(); const b = document.getElementById('cheer'); if(b) b.remove(); renderExamResult()"); pg.wait_for_timeout(100)
    ok('with the setting off there is no offer', pg.locator('#cheerGo').count() == 0 and pg.locator('#cheer').count() == 0)
    pg.evaluate("DB.settings.cheer = true; save()")
    ok('the paper remembers which log entry each answer made', pg.evaluate("Array.isArray(EX.logQn) && EX.logQn.length === EX.qs.length"))
    ok('the review counts it right and the paper record follows', pg.evaluate("DB.exams[DB.exams.length-1].right") == 1 and pg.locator('#v-exam h2').inner_text().startswith('probe — 1 / 1') and pg.locator('#v-exam button[data-right]').count() == 0)
    pg.evaluate("EX = null")

    pg.evaluate("show('eq')"); pg.wait_for_timeout(150)
    eqid = pg.evaluate("EQUATIONS[0].id")
    pg.evaluate("EQ = {queue:[%r], i:0, mode:'type', step:'type', asked:0, right:0, slots:[], tray:[]}; eqLoad(); renderEq()" % eqid); pg.wait_for_timeout(150)
    pg.fill('#eqIn', 'nonsense'); pg.keyboard.press('Enter'); pg.wait_for_timeout(200)
    ok('a wrong equation offers the override', pg.locator('#eqRight').count() == 1 and pg.evaluate("eqStat(%r).wrong" % eqid) >= 1)
    before = pg.evaluate("eqStat(%r).right" % eqid)
    pg.click('#eqRight'); pg.wait_for_timeout(150)
    ok('the equation record flips to right', pg.evaluate("eqStat(%r).right" % eqid) == before + 1 and pg.evaluate("EQ.ok") is True and pg.locator('#eqRight').count() == 0)
    pg.evaluate("EQ = null; show('eq')"); pg.wait_for_timeout(100)
    pg.evaluate("EQ = {queue:[%r], i:0, mode:'type', step:'type', asked:0, right:0, slots:[], tray:[]}; eqLoad(); renderEq()" % eqid); pg.wait_for_timeout(150)
    pg.click('#eqShow'); pg.wait_for_timeout(150)
    ok('Show me offers no override', pg.locator('#eqRight').count() == 0)
    pg.evaluate("EQ = null")

    print('\n=== What the wrong number says ===')
    pg.evaluate("Q = null; EQ = null; SU = null; startSweepOf([byId('m6-p1g')], 'probe')"); pg.wait_for_timeout(200)
    pg.fill('#v-quiz #numIn', '2.49'); pg.keyboard.press('Enter'); pg.wait_for_timeout(250)
    diag = pg.evaluate("(() => { const d = document.querySelector('#v-quiz .misskind .diag'); return d ? d.textContent : ''; })()")
    ok('a wrong number is read back: ' + diag[:60], '2.49 is 42.37 ÷ 17.03' in diag and 'points to algebra' in diag)
    ok('the kind it points to is marked as suggested, and every kind stays choosable', pg.evaluate("document.querySelector('#v-quiz .misskind button.suggest').dataset.mk") == 'algebra' and pg.locator('#v-quiz .misskind button[data-mk]').count() == 4)
    pg.click('#v-quiz .misskind button[data-mk="setup"]'); pg.wait_for_timeout(200)
    last = pg.evaluate("DB.answers[DB.answers.length-1]")
    ok('the student\'s choice is logged, with what the number pointed to beside it', last['missKind'] == 'setup' and last.get('missSuggest') == 'algebra')
    ok('the feedback says both', 'The number itself pointed to algebra' in pg.inner_text('#v-quiz'))
    pg.evaluate("show('gaps')"); pg.wait_for_timeout(150)
    ok('Weak spots shows the disagreement on the missed card', 'the number itself pointed to algebra' in pg.inner_text('#v-gaps'))
    pg.evaluate("DB.answers.pop(); save(); Q = null")

    print('\n=== The givens table and the sanity check ===')
    pg.evaluate("Q = null; EQ = null; SU = null; DB.settings.layout = 'one'; startSweepOf([byId('ws6-b2g')], 'probe')"); pg.wait_for_timeout(200)
    ok('before the answer, a button offers the givens and no table shows', pg.locator('#v-quiz [data-givens]').count() == 1 and pg.locator('#v-quiz .givens').count() == 0)
    pg.click('#v-quiz [data-givens]'); pg.wait_for_timeout(150)
    ok('the table lists symbol and value only, roles hidden', pg.locator('#v-quiz .givens tr').count() == 7 and pg.locator('#v-quiz .givens .grole').count() == 0 and 'not needed' not in pg.inner_text('#v-quiz .givens'))
    pg.fill('#v-quiz #numIn', '0.033'); pg.keyboard.press('Enter'); pg.wait_for_timeout(250)
    diag = pg.evaluate("(() => { const d = document.querySelector('#v-quiz .misskind .diag'); return d ? d.textContent : ''; })()")
    ok('a number outside the stem\'s bounds is read as a set-up slip with the check text: ' + diag[:50], 'lies outside what the stem allows' in diag and 'two half-lives' in diag and pg.evaluate("document.querySelector('#v-quiz .misskind button.suggest').dataset.mk") == 'setup')
    pg.click('#v-quiz .misskind button[data-mk="setup"]'); pg.wait_for_timeout(200)
    ok('after the answer the table shows every role, distractors marked not needed', pg.locator('#v-quiz .givens .grole').count() == 7 and pg.locator('#v-quiz .givens .gskip').count() == 4)
    ok('the roles render fractions and the sanity check follows the working', pg.locator('#v-quiz .givens .frac').count() >= 1 and pg.locator('#v-quiz .sanity').count() == 1 and '10 → 5 → 2.5' in pg.inner_text('#v-quiz .sanity'))
    ok('the trough question names the trough-from-peak line, not the C0 form', pg.evaluate("byId('ws6-b2g').setup.eq") == 'cmin-from-cmax' and 'Divide the two sheet lines' in pg.inner_text('#v-quiz .derive'))
    pg.evaluate("DB.answers.pop(); save(); Q = null; suStart('6')"); pg.wait_for_timeout(200)
    pg.evaluate("SU.queue.unshift(SU.queue.splice(SU.queue.findIndex(q => q.id === 'ws6-b2g'), 1)[0]); SU.i = 0; renderEq()"); pg.wait_for_timeout(150)
    pg.evaluate("(() => { const q = SU.queue[0], st = suState(q); const i = st.options.findIndex(o => o.id === q.setup.eq); document.querySelector('#v-eq [data-suopt=\"' + i + '\"]').click(); })()"); pg.wait_for_timeout(150)
    pg.click('#v-eq [data-sushow]'); pg.wait_for_timeout(150)
    ok('the set-up drill\'s worked block carries the givens and the check too', pg.locator('#v-eq .suwork .givens').count() == 1 and pg.locator('#v-eq .suwork .sanity').count() == 1)
    pg.evaluate("SU = null; show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Plan the problem: what is asked, its unit, the sheet; names hidden; stacked pieces ===')
    pg.evaluate("Q = null; EQ = null; SU = null; DB.settings.layout = 'one'; localStorage.setItem(SU_FROM_KEY, 'four'); suStart('plan:6')"); pg.wait_for_timeout(200)
    pg.evaluate("SU.queue.unshift(SU.queue.splice(SU.queue.findIndex(q => q.id === 'm6-p1g'), 1)[0]); SU.i = 0; renderEq()"); pg.wait_for_timeout(150)
    ok('the plan opens on "What is asked?" with six symbols and nothing else yet', pg.locator('#v-eq [data-suask]').count() == 6 and pg.locator('#v-eq [data-sumodel]').count() == 0 and pg.evaluate("byId('m6-p1g').asks") == 'Davgss')
    pg.evaluate("[...document.querySelectorAll('#v-eq [data-suask]')].find(b => b.dataset.suask !== 'Davgss').click()"); pg.wait_for_timeout(150)
    ok('a wrong symbol is named against the right one, with its meaning', 'the stem asks for' in pg.inner_text('#v-eq .verdict') and 'average amount of drug in the body' in pg.inner_text('#v-eq') and pg.locator('#v-eq [data-suunit]').count() == 6)
    pg.evaluate("[...document.querySelectorAll('#v-eq [data-suunit]')].find(b => normUnit(b.dataset.suunit) === normUnit(byId('m6-p1g').units)).click()"); pg.wait_for_timeout(150)
    ok('the unit step accepts the answer\'s unit and then asks the model', pg.evaluate("SU.page['m6-p1g'].unitOk") is True and pg.locator('#v-eq [data-sumodel]').count() == 10)
    pg.click('#v-eq [data-sumodel="multi"]'); pg.wait_for_timeout(150)
    ok('the line options show equations only, no names, before the pick', pg.locator('#v-eq [data-suopt]').count() == 4 and pg.locator('#v-eq [data-suopt] .suname').count() == 0)
    pg.evaluate("(() => { const q = SU.queue[0], st = suState(q); const i = st.options.findIndex(o => o.id === q.setup.eq); document.querySelector('#v-eq [data-suopt=\"' + i + '\"]').click(); })()"); pg.wait_for_timeout(150)
    ok('after the pick the names appear and the sheet question follows', pg.locator('#v-eq [data-suopt] .suname').count() == 4 and pg.locator('#v-eq [data-susheet]').count() == 2)
    printed = pg.evaluate("EQ_BY_ID[byId('m6-p1g').setup.eq].sheet === 'yes'")
    pg.click('#v-eq [data-susheet="%s"]' % ('yes' if printed else 'no')); pg.wait_for_timeout(150)
    ok('the sheet step is judged and the givens follow', pg.evaluate("SU.page['m6-p1g'].sheetOk") is True and pg.locator('#v-eq [data-sugiv]').count() >= 2)
    pg.evaluate("SU = null; show('eq'); EQ = {from: 'eq', queue: ['cavg-ss'], i: 0, mode: 'build', step: 'build', asked: 0, right: 0, slots: [], tray: []}; eqLoad()"); pg.wait_for_timeout(150)
    ok('the piece drill lays the slots out as a stacked fraction with the bar drawn, not placed', pg.locator('#v-eq .eqfrac').count() == 1 and pg.locator('#v-eq .eqfrac .eqfn .eqslot').count() == 1 and pg.locator('#v-eq .eqfrac .eqfd .eqslot').count() == 1 and pg.locator('#v-eq .eqtile').count() >= 2 and pg.evaluate("[...document.querySelectorAll('#v-eq .eqtile')].every(t => t.textContent.trim() !== '/')"))
    pg.evaluate("(() => { const e = EQ_BY_ID['cavg-ss']; e.tokens.forEach((t, i) => { if(!EQ_OP(t)){ const tile = EQ.tray.find(x => x.t === t); eqPlace(tile.i, i); } }); })()"); pg.wait_for_timeout(100)
    pg.click('#eqCheck'); pg.wait_for_timeout(150)
    ok('placing the operands in the stacked slots checks as right', pg.evaluate("EQ.ok") is True)
    stacked = pg.evaluate("EQUATIONS.filter(e => eqLayout(e)).length")
    ok('most lines with a division take the stacked layout (%d)' % stacked, stacked >= 30)
    pg.evaluate("EQ = null; SU = null; show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Plan the problem: model, line, givens ===')
    pg.evaluate("Q = null; EQ = null; SU = null; DB.settings.layout = 'one'; suStart('plan:6')"); pg.wait_for_timeout(200)
    pg.evaluate("SU.queue.unshift(SU.queue.splice(SU.queue.findIndex(q => q.id === 'ws6-b2g'), 1)[0]); SU.i = 0; const q0 = SU.queue[0], s0 = suState(q0); s0.ask = q0.asks; s0.askOk = true; s0.unit = q0.units; s0.unitOk = true; renderEq()"); pg.wait_for_timeout(150)
    ok('with the asked quantity and unit answered, the card asks for the dosing model and holds the line back', pg.locator('#v-eq [data-sumodel]').count() == 10 and pg.locator('#v-eq [data-suopt]').count() == 0)
    pg.click('#v-eq [data-sumodel="oral"]'); pg.wait_for_timeout(150)
    vlast = pg.locator('#v-eq .verdict').last.inner_text()
    ok('a wrong model is named against the right one, with the stem\'s words', 'Not Single oral dose' in vlast and 'Repeated IV bolus' in vlast and pg.locator('#v-eq [data-suopt]').count() == 4)
    pg.evaluate("(() => { const q = SU.queue[0], st = suState(q); const i = st.options.findIndex(o => o.id === q.setup.eq); document.querySelector('#v-eq [data-suopt=\"' + i + '\"]').click(); })()"); pg.wait_for_timeout(150)
    pg.evaluate("(() => { const q = SU.queue[0], st = suState(q); st.sheet = EQ_BY_ID[q.setup.eq].sheet === 'yes' ? 'yes' : 'no'; st.sheetOk = true; renderEq(); })()"); pg.wait_for_timeout(100)
    ok('after the line and the sheet question, the givens are offered as ticks with the roles hidden', pg.locator('#v-eq [data-sugiv]').count() == 7 and pg.locator('#v-eq .surole').count() == 0 and pg.locator('#v-eq [data-sugivcheck]').count() == 1)
    pg.click('#v-eq [data-sugiv="0"]'); pg.click('#v-eq [data-sugiv="5"]'); pg.click('#v-eq [data-sugiv="6"]'); pg.click('#v-eq [data-sugiv="1"]'); pg.wait_for_timeout(150)
    ok('ticks toggle and show as pressed', pg.locator('#v-eq [data-sugiv][aria-pressed="true"]').count() == 4)
    pg.click('#v-eq [data-sugivcheck]'); pg.wait_for_timeout(200)
    txt = pg.inner_text('#v-eq')
    ok('the check marks the one not-needed tick and shows every role', '1 not needed' in txt and pg.locator('#v-eq .surole').count() == 7 and pg.locator('#v-eq .sugiv.wrong').count() == 1)
    ok('the plan is then written out: asked, model, line, givens, estimate', pg.locator('#v-eq .suplan li').count() == 5 and 'Before computing' in txt and 'Set aside' in txt and 'Asked:' in txt)
    pg.evaluate("SU.page[SU.queue[0].id].giv = new Set(planNeeded(SU.queue[0])); SU.page[SU.queue[0].id].givChecked = false; SU.page[SU.queue[0].id].modelOk = true; SU.plans = 0; renderEq()"); pg.wait_for_timeout(100)
    pg.click('#v-eq [data-sugivcheck]'); pg.wait_for_timeout(150)
    ok('a plan with all three right counts as complete', pg.evaluate("SU.plans") == 1 and 'right givens' in pg.inner_text('#v-eq .verdict:last-of-type, #v-eq .why'))
    ok('the Equations card offers the plan drill per module', pg.evaluate("SU = null; show('eq'); document.querySelectorAll('.sucard [data-su^=\"plan:\"]').length") >= 2)
    pg.evaluate("SU = null; show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Back button at the top, whole-sheet picking, module fold ===')
    pg.evaluate("Q = null; EQ = null; SU = null; RET = []; show('gaps'); jump('ref', 'ref-2')"); pg.wait_for_timeout(250)
    top = pg.evaluate("(() => { const b = document.getElementById('backbtn'); if(!b) return -1; const r = b.getBoundingClientRect(); return r.top; })()")
    ok('after a jump the Back button sits under the tab row, in view (top %spx)' % int(top), 0 < top < 200)
    pg.evaluate("RET = []; backBtn()")
    pg.evaluate("localStorage.setItem(SU_FROM_KEY, 'sheet'); DB.settings.layout = 'one'; suStart('6')"); pg.wait_for_timeout(200)
    pg.evaluate("SU.queue.unshift(SU.queue.splice(SU.queue.findIndex(q => q.id === 'ws6-b2g'), 1)[0]); SU.i = 0; renderEq()"); pg.wait_for_timeout(150)
    ok('whole-sheet mode offers the sheet block by block, with the unprinted lines in two groups', pg.locator('#v-eq .sublock').count() >= 12 and pg.locator('#v-eq [data-suopt]').count() == 0 and pg.locator('#v-eq [data-suline]').count() >= 55 and 'Not printed: reached from a sheet line' in pg.inner_text('#v-eq'))
    pg.evaluate("document.querySelector('#v-eq [data-suline=\"cmin-ss\"]').closest('details').open = true"); pg.wait_for_timeout(100)
    pg.click('#v-eq [data-suline="cmin-ss"]'); pg.wait_for_timeout(200)
    ok('picking the C0 trough line for a stem that gives the peak is wrong, and the right block opens on the right line', pg.evaluate("SU.page['ws6-b2g'].ok") is False and pg.evaluate("(() => { const b = document.querySelector('#v-eq [data-suline=\"cmin-from-cmax\"]'); return b && b.classList.contains('right') && b.closest('details').open; })()"))
    pg.evaluate("localStorage.setItem(SU_FROM_KEY, 'four'); SU = null; show('eq')"); pg.wait_for_timeout(150)
    ok('the Equations card offers the choice of four lines or the whole sheet', pg.locator('#v-eq [data-sufrom]').count() == 2)
    pg.click('#v-eq [data-eqfold="closed"]'); pg.wait_for_timeout(150)
    ok('Collapse all closes every module on the Equations picker', pg.locator('#v-eq details.module[open]').count() == 0 and pg.locator('#v-eq details.module').count() >= 7)
    pg.click('#v-eq [data-eqfold="open"]'); pg.wait_for_timeout(150)
    ok('Expand all opens them again', pg.locator('#v-eq details.module:not([open])').count() == 0)
    pg.evaluate("show('topics')"); pg.wait_for_timeout(100)

    print('\n=== A way back at the top of every drill ===')
    pg.evaluate("Q = null; EQ = null; SU = null; EX = null; DB.settings.layout = 'one'; show('topics'); startSweepOf([byId('ws6-b2g'), byId('m6-p1g')], 'probe')"); pg.wait_for_timeout(200)
    ok('a quiz started from Topics opens with a Back to Topics chip at the top', pg.locator('#v-quiz .sessline .drillback').count() == 1 and pg.inner_text('#v-quiz .drillback') == '← Back to Topics')
    pg.evaluate("DB.settings.layout = 'all'; renderQuiz()"); pg.wait_for_timeout(150)
    ok('the same chip on the one-page layout', pg.locator('#v-quiz .sessline .drillback').count() == 1)
    pg.evaluate("DB.settings.layout = 'one'; Q = null; show('gaps'); startSweepOf([byId('ws6-b2g')], 'probe')"); pg.wait_for_timeout(200)
    ok('a drill started from Weak spots goes back to Weak spots', pg.inner_text('#v-quiz .drillback') == '← Back to Weak spots')
    pg.click('#v-quiz .drillback'); pg.wait_for_timeout(150)
    ok('clicking it returns there and leaves the quiz in place to resume', pg.evaluate("VIEW") == 'gaps' and pg.evaluate("!!Q"))
    pg.evaluate("Q = null; show('eq'); suStart('6')"); pg.wait_for_timeout(200)
    ok('the set-up drill started on Equations offers Stop at the top', pg.inner_text('#v-eq .sessline .drillback') == '← Stop, back to Equations')
    pg.click('#v-eq .drillback'); pg.wait_for_timeout(150)
    ok('Stop returns to the Equations picker', pg.evaluate("SU === null && !!document.querySelector('#v-eq .sucard')"))
    pg.evaluate("show('gaps'); suStart('plan:6')"); pg.wait_for_timeout(200)
    ok('a plan drill started from Weak spots goes back to Weak spots', pg.inner_text('#v-eq .drillback') == '← Back to Weak spots')
    pg.evaluate("SU = null; show('ref'); eqStartIds(['css'], 'type'); show('eq')"); pg.wait_for_timeout(200)
    ok('a typing drill started from the sheet map goes back to Reference', pg.inner_text('#v-eq .drillback') == '← Back to Reference')
    pg.evaluate("EQ = null; show('topics'); startPaper([byId('ws6-b2g')], 5, {title: 'probe', coverage: blueprintCoverage()}); show('exam')"); pg.wait_for_timeout(200)
    ok('a paper started from Topics shows the way back and says the clock keeps running', pg.inner_text('#v-exam .drillback') == '← Back to Topics' and 'clock keeps running' in pg.inner_text('#v-exam .sessline'))
    pg.evaluate("EX = null; show('exam'); DB.settings.layout = 'one'")
    pg.evaluate("startPaper([byId('ws6-b2g')], 5, {title: 'probe', coverage: blueprintCoverage()}); renderExamQ()"); pg.wait_for_timeout(150)
    ok('a paper started on Exam sim itself shows no such chip', pg.locator('#v-exam .drillback').count() == 0)
    pg.evaluate("EX = null; show('topics')"); pg.wait_for_timeout(100)

    print('\n=== A concept question decided by a calculation shows the working ===')
    pg.evaluate("Q = null; EQ = null; SU = null; DB.settings.layout = 'one'; show('topics'); startSweepOf([byId('hw4-2e')], 'probe')"); pg.wait_for_timeout(200)
    ok('before the answer, no working shows', pg.locator('#v-quiz .steps').count() == 0)
    pg.evaluate("(() => { const i = byId('hw4-2e').options.findIndex(o => o.correct); const n = Q.order.indexOf(i); document.querySelectorAll('#v-quiz .opt')[n].click(); })()"); pg.wait_for_timeout(300)
    txt = pg.inner_text('#v-quiz')
    ok('after it, the givens, five steps and the check follow the option explanations', pg.locator('#v-quiz .givens').count() == 1 and pg.locator('#v-quiz .step').count() == 5 and pg.locator('#v-quiz .sanity').count() == 1 and 'The answer rests on a calculation' in txt)
    ok('the chain reaches the comparison with GFR and names why fe alone cannot decide', '28.3 mL/min against GFR' in txt and 'fe = 0.70 alone cannot name the mechanism' in txt)
    pg.evaluate("DB.answers.pop(); save(); Q = null; show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Explain more lands on the exact line ===')
    pg.evaluate("Q = null; EQ = null; SU = null; RET = []; show('topics')")
    terms = pg.evaluate("spotTerms(byId('m4-rm-5'))")
    ok('a question yields the words that name it: ' + ' '.join(terms)[:60], len(terms) >= 2 and any(w.startswith(('secret', 'filt', 'reabs')) for w in terms))
    links = pg.evaluate("linksFor(byId('m4-rm-5')).map(l => l[0] + '|' + l[2])")
    ok('its links name the guide objective in full and a Tell apart section: ' + '; '.join(links)[:120], any(l.startswith('guide|Guide: Module 4, obj.') for l in links) and any(l.startswith('tell|Tell apart:') for l in links))
    pg.evaluate("(() => { const l = linksFor(byId('m4-rm-5')).find(x => x[0] === 'ref'); jump(l[0], l[1], spotTerms(byId('m4-rm-5'))); })()"); pg.wait_for_timeout(300)
    spot = pg.evaluate("(() => { const s = document.querySelector('#v-ref .spot'); if(!s) return null; const r = s.getBoundingClientRect(); return {text: s.textContent.trim().slice(0, 120), top: r.top, inView: r.top > 60 && r.top < window.innerHeight}; })()")
    ok('the Reference jump marks the one line about the mechanism and scrolls it into view: ' + (spot['text'][:70] if spot else 'none'), bool(spot) and spot['inView'] and ('secretion' in spot['text'].lower() or 'reabsor' in spot['text'].lower() or 'filtration' in spot['text'].lower()))
    pg.evaluate("RET = []; backBtn(); document.querySelectorAll('.spot').forEach(x => x.classList.remove('spot'))")
    cover = pg.evaluate("""() => { let n = 0, hit = 0; for(const q of QUESTIONS){ for(const [v, a] of linksFor(q)){ n++; show(v); if(v === 'diag') DG_MOD = 'all'; const t = document.getElementById(a); if(t && spotlight(t, spotTerms(q))) hit++; } } document.querySelectorAll('.spot').forEach(x => x.classList.remove('spot')); return [hit, n]; }""")
    ok('most jumps across the bank land on a line, not just a heading (%d of %d)' % (cover[0], cover[1]), cover[0] >= 0.65 * cover[1])
    pg.evaluate("show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Choosing the unprinted lines ===')
    pg.evaluate("Q = null; EQ = null; SU = null; show('eq')"); pg.wait_for_timeout(150)
    pg.click('#v-eq [data-pick="derived"]'); pg.wait_for_timeout(150)
    ok('the derived chip selects every unprinted line that is not one she said to know (%d)' % pg.evaluate("eqChosen().length"), pg.evaluate("eqChosen().every(id => EQ_BY_ID[id].sheet !== 'yes' && !EQ_BY_ID[id].must) && eqChosen().length === EQUATIONS.filter(e => e.sheet !== 'yes' && !e.must).length"))
    pg.click('#v-eq [data-pick="unprinted"]'); pg.wait_for_timeout(150)
    ok('the unprinted chip adds the six she said to know', pg.evaluate("eqChosen().length === EQUATIONS.filter(e => e.sheet !== 'yes').length"))
    pg.click('#v-eq [data-pick="exam"]'); pg.wait_for_timeout(150)
    ok('the exam chip selects the active exam\'s modules only', pg.evaluate("eqChosen().length > 0 && eqChosen().every(id => examOf(EQ_BY_ID[id].module) === EXAM.id)"))
    pg.evaluate("eqSetChosen(EQ_MUST); show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Stopwatch on every calculation, time per kind on Weak spots ===')
    pg.evaluate("Q = null; EQ = null; SU = null; EX = null; DB.settings.layout = 'one'; show('topics'); startSweepOf([byId('ws6-b3f')], 'probe')"); pg.wait_for_timeout(200)
    ok('a calculation shows a running stopwatch', pg.locator('#v-quiz .qtimer[data-start]').count() == 1)
    pg.evaluate("Q.startedAt -= 125000; const t = document.querySelector('#v-quiz .qtimer'); t.dataset.start = Q.startedAt; tickTimers()"); pg.wait_for_timeout(50)
    ok('past 2 minutes it reads over 2:00', 'over 2:00' in pg.inner_text('#v-quiz .qtimer') and pg.evaluate("document.querySelector('#v-quiz .qtimer').classList.contains('over')"))
    pg.fill('#v-quiz #numIn', '57.72'); pg.keyboard.press('Enter'); pg.wait_for_timeout(250)
    ok('after the answer it freezes on the time taken, and the log keeps it', 'took 2:0' in pg.inner_text('#v-quiz .qtimer') and pg.evaluate("DB.answers[DB.answers.length-1].ms") >= 125000)
    pg.evaluate("DB.answers.pop(); save(); DB.settings.layout = 'all'; startSweepOf([byId('ws6-b3f'), byId('m6-p1g')], 'probe')"); pg.wait_for_timeout(250)
    ok('on the one-page layout the stopwatch waits for the first click into the box', pg.locator('#v-quiz .qtimer.idle').count() == 2)
    pg.locator('#v-quiz .allcard input.numin').first.focus(); pg.wait_for_timeout(100)
    ok('and starts when the box is entered', pg.locator('#v-quiz .qtimer[data-start]').count() == 1)
    pg.evaluate("DB.settings.layout = 'one'; Q = null")
    pg.evaluate("startPaper([byId('ws6-b3f'), byId('m6-p1g')], 5, {title: 'probe', coverage: blueprintCoverage()}); show('exam'); renderExamQ()"); pg.wait_for_timeout(150)
    ok('an exam calculation shows its own stopwatch', pg.locator('#v-exam .qtimer[data-start]').count() == 1)
    pg.evaluate("EX.tMark -= 40000; document.getElementById('exNext').click()"); pg.wait_for_timeout(100)
    pg.evaluate("EX.tMark -= 20000; document.getElementById('exPrev').click()"); pg.wait_for_timeout(100)
    spent = pg.evaluate("EX.spent.map(x => Math.round(x / 1000))")
    ok('time on each paper question accumulates while it is shown: %s s' % spent, spent[0] >= 40 and spent[1] >= 20)
    pg.evaluate("EX = null")
    seed = pg.evaluate("""(() => { window.__keep = DB.answers; DB.answers = []; const n = 0;
      const t = CALC_TYPES.find(x => QUESTIONS.some(q => calcTypeOf(q) === x && x.module === 6));
      const qs = QUESTIONS.filter(q => calcTypeOf(q) === t).slice(0, 3);
      qs.forEach((q, i) => DB.answers.push({qid: q.id, concept: q.concept, result: i ? 'wrong' : 'correct', at: Date.now(), ms: 150000 + i * 10000}));
      const u = CALC_TYPES.find(x => x.module === 2 && QUESTIONS.some(q => calcTypeOf(q) === x));
      QUESTIONS.filter(q => calcTypeOf(q) === u).slice(0, 2).forEach(q => DB.answers.push({qid: q.id, concept: q.concept, result: 'correct', at: Date.now(), ms: 60000}));
      DB.answers.push({qid: qs[0].id, concept: qs[0].concept, result: 'correct', at: Date.now(), ms: 30 * 60000});
      show('gaps'); return {n, t: t.name, u: u.name}; })()""")
    rows = pg.evaluate("[...document.querySelectorAll('#v-gaps .tchart .trow:not(.thead)')].map(r => r.querySelector('.tname').textContent.trim() + ' | ' + r.querySelector('.tval').textContent.trim())")
    ok('Weak spots draws a bar per kind, slowest first, with the middle time: ' + '; '.join(rows)[:120], len(rows) == 2 and seed['t'] in rows[0] and '2:40' in rows[0] and 'over 2:00' in rows[0] and '1:00' in rows[1])
    ok('the 30-minute answer is left out as time away', '3 timed' in rows[0])
    ok('every bar carries the 2-minute line', pg.locator('#v-gaps .tchart .tpace').count() == 2)
    work = pg.inner_text('#v-gaps .twork') if pg.locator('#v-gaps .twork').count() else ''
    ok('the slow, often-missed kind heads "Work on these first" with a drill button', seed['t'] in work and pg.locator('#v-gaps .twork [data-ttype]').count() >= 1 and seed['u'] not in work)
    pg.click('#v-gaps .twork [data-ttype]'); pg.wait_for_timeout(200)
    ok('Drill this kind starts a drill of that kind of calculation', pg.evaluate("VIEW === 'quiz' && Q && Q.pool.every(q => calcTypeOf(q) && calcTypeOf(q).name === %r)" % seed['t']))
    pg.evaluate("DB.answers = window.__keep; save(); Q = null; show('topics')"); pg.wait_for_timeout(100)

    print('\n=== Weak spots: repairs per kind of miss, Reference anchors ===')
    pg.evaluate("Q = null; EQ = null; SU = null")
    land = pg.evaluate("""(() => { const q = QUESTIONS.find(q => q.module === 2 && qType(q) === 'numeric');
      const l = linksFor(q).find(x => x[0] === 'ref'); if(!l) return 'no ref link'; show('ref');
      const t = document.getElementById(l[1]); return t ? t.textContent.trim() : 'no target'; })()""")
    ok('a Module 2 question\'s Reference chip lands on the Module 2 heading, not the one before it: ' + land[:40], land.startswith('Module 2'))
    ok('the sheet map is a Reference anchor', pg.evaluate("refAnchor('Her equation sheet')") == 'ref-0')
    seed = pg.evaluate("""(() => { const pool = suPoolAll().filter(q => QUESTIONS.includes(q));
      const a = pool.find(q => q.module === 2), b2 = pool.find(q => q.module === 3 && q.id !== a.id), c = pool.find(q => q.module === 5);
      const n = DB.answers.length;
      DB.answers.push({qid: a.id, result: 'wrong', missKind: 'setup', picked: '1', t: Date.now()});
      DB.answers.push({qid: b2.id, result: 'wrong', missKind: 'algebra', picked: '1', t: Date.now()});
      DB.answers.push({qid: c.id, result: 'wrong', missKind: 'unit', picked: '1', t: Date.now()});
      DB.answers.push({qid: c.id, result: 'wrong', missKind: 'round', picked: '1', t: Date.now()});
      show('gaps'); const el = document.getElementById('v-gaps');
      const lines = [b2.setup.eq, ...(b2.setup.pre || [])].filter(id => EQ_BY_ID[id]);
      return {n, ids: [a.id, b2.id, c.id], fixes: [...el.querySelectorAll('.fixrow b')].map(x => x.textContent),
        setupChips: [...el.querySelectorAll('.fixrow [data-sheetsetup]')].map(x => x.dataset.sheetsetup),
        unitJump: !!el.querySelector('.fixrow [data-jump^="ref:ref-"]'),
        typeIds: (el.querySelector('.fixrow [data-eqtype]') || {dataset: {}}).dataset.eqtype, lines: lines.join(','),
        cardLines: el.querySelectorAll('.missq .mline').length, cardChips: el.querySelectorAll('.missq .explainmore').length,
        missed: el.querySelectorAll('.missq').length,
        numMissed: [...new Set(DB.answers.filter(x => x.result === 'wrong').map(x => x.qid))].filter(id => byId(id) && qType(byId(id)) === 'numeric' && byId(id).setup && EQ_BY_ID[byId(id).setup.eq]).length}; })()""")
    ok('one repair per kind of miss that happened: ' + ', '.join(seed['fixes']), seed['fixes'] == ['Set-up', 'Unit conversion', 'Algebra', 'Rounding'])
    ok('the set-up repair offers the drill on the module where the line was wrong, and the sheet map', 'plan:2' in seed['setupChips'] and pg.evaluate("!!document.querySelector('#v-gaps .fixrow [data-jump=\"ref:ref-0\"]')"))
    ok('the unit repair jumps into Reference', seed['unitJump'])
    ok('the algebra repair names the lines behind the miss: ' + str(seed['typeIds']), seed['typeIds'] == seed['lines'])
    ok('every missed calculation card shows the line that solves it and Explain-more chips', seed['cardLines'] == seed['numMissed'] >= 3 and seed['cardChips'] == seed['missed'] >= 3)
    pg.click('#v-gaps .fixrow [data-eqtype]'); pg.wait_for_timeout(200)
    ok('clicking it opens the typing drill on those lines', pg.evaluate("VIEW === 'eq' && EQ && EQ.mode === 'type' && EQ.queue.join(',')") == seed['lines'])
    pg.evaluate("EQ = null; show('gaps')"); pg.wait_for_timeout(100)
    pg.click('#v-gaps .fixrow [data-sheetsetup]'); pg.wait_for_timeout(200)
    ok('the set-up chip starts the plan drill on that module', pg.evaluate("VIEW === 'eq' && SU && SU.scope === '2' && SU.mode === 'plan' && SU.queue.every(q => q.module === 2)"))
    pg.evaluate("SU = null; show('gaps')"); pg.wait_for_timeout(100)
    pg.click('#v-gaps .missq [data-jump^="guide:"], #v-gaps .missq [data-jump^="ref:"]'); pg.wait_for_timeout(200)
    ok('an Explain-more chip on a missed card jumps and offers the way back to Weak spots', pg.evaluate("VIEW !== 'gaps' && RET.length && RET[RET.length-1].view === 'gaps'"))
    pg.evaluate("RET = []; DB.answers.splice(%d); save(); show('gaps')" % seed['n']); pg.wait_for_timeout(100)
    ok('the set-up card offers no chip for a scope with no stems', pg.evaluate("""(() => { const keep = EXAM; const e3 = COURSE.exams.find(e => e.id === 3); if(!e3) return true;
      EXAM = e3; const h = suCardHTML(); EXAM = keep; return suScopePool('exam:3').length ? true : !h.includes('data-su="exam:3"'); })()"""))

    ok('no uncaught error', not errs)
    if errs: print('   ', errs[:3])
    b.close()
print('\nLayout test ' + ('passed' if not fails else 'FAILED: %d' % len(fails)))
sys.exit(1 if fails else 0)
