/* ==========================================================================
   THE EQUATION SHEET, LINE BY LINE
   ==========================================================================
   Her exam equation sheet (Basic-Pharmacokinetics-Equations.pdf, two pages,
   52 lines) in the order it is printed: page 1 left column, page 1 right
   column, page 2 left column, page 2 right column. The sheet carries no
   headings and no module labels; each line here is tagged with the module
   that teaches it, the words in a stem that call for it, and the givens it
   needs, so the sheet can be read as blocks.

   SOURCES. The equations are transcribed from the rendered pages of the
   sheet. `module` follows reference.js (the module whose lecture teaches
   the line); `eq` is the matching entry in equations.js, or null where no
   entry drills that line. `when` and `need` restate the "Applies when" and
   "Usually asked for" cells of reference.js and the `holds` text of
   equations.js in a few words; nothing new is asserted.

   `module` 0 marks a line not lectured in Modules 1 to 7a (stability on
   page 2, and the four nonlinear lines, which are final-exam material).

   Plain strings with HTML; {{frac:top|bottom}} stacks a ratio.
   ========================================================================== */
const SHEET_COLS = [
  {pg: 1, col: 'Page 1, left column'},
  {pg: 2, col: 'Page 1, right column'},
  {pg: 3, col: 'Page 2, left column'},
  {pg: 4, col: 'Page 2, right column'},
];

const SHEET_LINES = [
/* ---- page 1, left column ---------------------------------------------- */
{c: 1, module: 1, eq: 'auc-trap', model: 'Any route, from a data table', asks: 'AUC',
 html: '[AUC]<sub>t<sub>n&minus;1</sub></sub><sup>t<sub>n</sub></sup> = {{frac:C<sub>n&minus;1</sub> + C<sub>n</sub>|2}} (t<sub>n</sub> &minus; t<sub>n&minus;1</sub>)',
 when: 'A table of concentrations and times; the AUC between two named times.',
 need: 'Only the rows inside the interval asked.'},
{c: 1, module: 1, eq: 'zero-line', model: 'Zero order', asks: 'C at a time',
 html: 'C = C<sub>0</sub> &minus; k<sub>0</sub>t',
 when: 'Zero order: the same amount lost per hour; a straight line on plain axes.',
 need: 'C<sub>0</sub>, k<sub>0</sub> (amount per time) and t.'},
{c: 1, module: 1, eq: 'first-exp', alsoEq: ['cp-after-stop'], model: 'First order, one compartment', asks: 'C at a time',
 html: 'C = C<sub>0</sub>e<sup>&minus;kt</sup>',
 when: 'First order: the same fraction lost per hour; the concentration at a time.',
 need: 'C<sub>0</sub>, k and t. k comes from the half-life when only t&frac12; is given.'},
{c: 1, module: 1, eq: 'first-ln', model: 'First order, one compartment', asks: 'k, or the time to a level',
 html: 'ln C = ln C<sub>0</sub> &minus; kt',
 when: 'The same line in logs: k from two points, or the time to reach a concentration.',
 need: 'Two concentrations and the time between them.'},
{c: 1, module: 1, eq: 'first-log', model: 'First order, one compartment', asks: 'k, or the time to a level',
 html: 'log C = log C<sub>0</sub> &minus; {{frac:kt|2.3}}',
 when: 'The base-10 form of the same line; a slope read off a log<sub>10</sub> plot.',
 need: 'The same inputs; the slope is &minus;k/2.3, not &minus;k.'},
{c: 1, module: 2, eq: 'amount-exp', model: 'IV bolus, one compartment', asks: 'Amount in the body',
 html: 'D = D<sub>0</sub>e<sup>&minus;kt</sup>',
 when: 'The amount in the body (mg) at a time after an IV bolus, or the amount left after &tau;.',
 need: 'The dose, k and t.'},
{c: 1, module: 2, eq: 'amount-exp', model: 'IV bolus, one compartment', asks: 'Amount in the body',
 html: 'ln D = ln D<sub>0</sub> &minus; kt',
 when: 'The amount line in logs: the time for a given amount to remain.',
 need: 'Two amounts and k, or the dose, the amount left and k.'},
{c: 1, module: 2, eq: 'amount-exp', model: 'IV bolus, one compartment', asks: 'Amount in the body',
 html: 'log D = log D<sub>0</sub> &minus; {{frac:kt|2.3}}',
 when: 'The base-10 form of the amount line.',
 need: 'The same inputs as the line above.'},
{c: 1, module: 2, eq: 'cp-db-vd', model: 'IV bolus, one compartment', asks: 'C0, VD or the amount',
 html: 'C<sub>p</sub> = {{frac:D<sub>B</sub>|V<sub>D</sub>}}',
 when: 'Concentration from an amount, or V<sub>D</sub> = dose &divide; C<sub>0</sub>; she also expects it known.',
 need: 'The amount in the body and V<sub>D</sub>; at time zero the amount is the dose.'},
{c: 1, module: 3, eq: 'cp-infusing', model: 'IV infusion', asks: 'C at a time',
 html: 'C<sub>p</sub> = {{frac:R|Cl}}(1 &minus; e<sup>&minus;kt</sup>)',
 when: '"Infused at" a rate: the concentration before steady state, or the time to a fraction of C<sub>ss</sub>.',
 need: 'R, Cl (or k &times; V<sub>D</sub>), k and the time since the drip started.'},
{c: 1, module: 3, eq: 'css', model: 'IV infusion', asks: 'Css, or the rate R',
 html: 'C<sub>ss</sub> = {{frac:R|Cl}}',
 when: '"Steady state" during an infusion; the rate that gives a target C<sub>ss</sub>.',
 need: 'R and Cl; Cl = k &times; V<sub>D</sub> when a half-life and a volume are given instead.'},
{c: 1, module: 3, eq: 'dl-rk', model: 'Loading dose with an infusion', asks: 'Loading dose',
 html: 'D<sub>L</sub> = {{frac:R|k}}',
 when: 'A loading dose from the infusion rate.',
 need: 'R and k.'},
{c: 1, module: 3, eq: 'dl-css-vd', model: 'Loading dose with an infusion', asks: 'Loading dose',
 html: 'D<sub>L</sub> = C<sub>ss</sub>V<sub>D</sub>',
 when: 'A loading dose from the target concentration.',
 need: 'C<sub>ss</sub> and V<sub>D</sub>; the two D<sub>L</sub> lines give the same dose.'},
{c: 1, module: 2, eq: 'biexp', model: 'IV bolus, two compartments', asks: 'C at a time',
 html: 'C<sub>p</sub> = Ae<sup>&minus;at</sup> + Be<sup>&minus;bt</sup>',
 when: 'Two compartments: A, B, a, b given, or an equation with two exponential terms.',
 need: 'A, B, a, b and t; the sheet writes a and b for &alpha; and &beta;.'},
{c: 1, module: 2, eq: 'k-overall', model: 'IV bolus, two compartments', asks: 'k and the rate constants',
 html: 'k = {{frac:ab(A + B)|Ab + Ba}}',
 when: 'The overall elimination constant of a two-compartment drug.',
 need: 'A, B, a and b.'},
{c: 1, module: 2, eq: 'k12', model: 'IV bolus, two compartments', asks: 'k and the rate constants',
 html: 'k<sub>12</sub> = {{frac:AB(b &minus; a)<sup>2</sup>|(A + B)(Ab + Ba)}}',
 when: 'Transfer from the central to the tissue compartment.',
 need: 'A, B, a and b.'},
{c: 1, module: 2, eq: 'k21', model: 'IV bolus, two compartments', asks: 'k and the rate constants',
 html: 'k<sub>21</sub> = {{frac:Ab + Ba|A + B}}',
 when: 'Transfer from the tissue back to the central compartment.',
 need: 'A, B, a and b.'},
{c: 1, module: 2, eq: 'vp-ab', model: 'IV bolus, two compartments', asks: 'Volumes',
 html: 'V<sub>p</sub> = {{frac:D<sub>0</sub>|A + B}}',
 when: 'The central volume from the two intercepts (A + B is C<sub>0</sub>).',
 need: 'The dose, A and B.'},
{c: 1, module: 2, eq: 'vp-auc', model: 'IV bolus, two compartments', asks: 'Volumes',
 html: 'V<sub>p</sub> = {{frac:D<sub>0</sub>|k[AUC]<sub>0</sub><sup>&infin;</sup>}}',
 when: 'The central volume from the area instead of the intercepts.',
 need: 'The dose, k and the total AUC.'},
{c: 1, module: 2, eq: 'vt', model: 'IV bolus, two compartments', asks: 'Volumes',
 html: 'V<sub>t</sub> = {{frac:V<sub>p</sub>k<sub>12</sub>|k<sub>21</sub>}}',
 when: 'The tissue compartment volume.',
 need: 'V<sub>p</sub>, k<sub>12</sub> and k<sub>21</sub>.'},
{c: 1, module: 2, eq: 'cl-auc', model: 'Any route', asks: 'Clearance',
 html: 'Cl<sub>T</sub> = {{frac:FD<sub>0</sub>|[AUC]<sub>0</sub><sup>&infin;</sup>}}',
 when: 'Clearance from a dose and an area; F = 1 for an IV dose. Also the IV AUC from dose and clearance (Module 7a).',
 need: 'The dose, F and the AUC to infinity.'},
/* ---- page 1, right column --------------------------------------------- */
{c: 2, module: 4, eq: 'fe', alsoEq: ['fe-k'], model: 'Elimination and clearance', asks: 'fe and ke',
 html: 'f<sub>e</sub> = {{frac:D<sub>u</sub><sup>&infin;</sup>|FD<sub>0</sub>}} = {{frac:k<sub>e</sub>|k}}',
 when: '"Excreted unchanged in the urine": the fraction, from amounts or from rate constants.',
 need: 'The amount recovered in urine and the dose, or k<sub>e</sub> and k.'},
{c: 2, module: 4, eq: 'clr', model: 'Elimination and clearance', asks: 'Clearance',
 html: 'Cl<sub>R</sub> = f<sub>e</sub>Cl<sub>T</sub>',
 when: 'Renal clearance from the fraction excreted unchanged.',
 need: 'f<sub>e</sub> and Cl<sub>T</sub>.'},
{c: 2, module: 4, eq: 'clt-sum', model: 'Elimination and clearance', asks: 'Clearance',
 html: 'Cl<sub>T</sub> = Cl<sub>R</sub> + Cl<sub>H</sub>',
 when: 'Two of the three clearances known; the third asked.',
 need: 'Any two, in the same units.'},
{c: 2, module: 4, eq: 'clh', model: 'Elimination and clearance', asks: 'Clearance',
 html: 'Cl<sub>H</sub> = (1 &minus; f<sub>e</sub>) &bull; Cl<sub>T</sub>',
 when: 'Hepatic (metabolic) clearance, found by difference.',
 need: 'f<sub>e</sub> and Cl<sub>T</sub>.'},
{c: 2, module: 4, eq: 'rate-elim', model: 'Elimination and clearance', asks: 'Rate of elimination',
 html: 'Rate of elimination = (Cl)(C<sub>p</sub>)',
 when: '"Rate of elimination" in mg/hr at a stated concentration.',
 need: 'Cl and C<sub>p</sub>; L/hr &times; mg/L leaves mg/hr.'},
{c: 2, module: 5, eq: 'oral-cp', model: 'Single oral dose', asks: 'C at a time',
 html: 'C<sub>p</sub> = {{frac:Fk<sub>a</sub>D<sub>0</sub>|V<sub>D</sub>(k<sub>a</sub> &minus; k)}}(e<sup>&minus;kt</sup> &minus; e<sup>&minus;k<sub>a</sub>t</sup>)',
 when: '"Oral", "absorption", a k<sub>a</sub> or an absorption half-life, a capital F: one dose, concentration at a time.',
 need: 'F, k<sub>a</sub>, k, D<sub>0</sub>, V<sub>D</sub> and t; the two half-lives give the two constants.'},
{c: 2, module: 5, eq: 'tmax', model: 'Single oral dose', asks: 'tmax and Cmax',
 html: 't<sub>max</sub> = {{frac:ln(k<sub>a</sub>/k)|k<sub>a</sub> &minus; k}}',
 when: 'The time of the peak after one oral dose; C<sub>max</sub> is the line above evaluated at t<sub>max</sub>.',
 need: 'k<sub>a</sub> and k only; the dose does not move t<sub>max</sub>.'},
{c: 2, module: 6, eq: 'dmax-ss', model: 'Repeated IV bolus', asks: 'Amount in the body',
 html: 'D<sub>max</sub><sup>&infin;</sup> = {{frac:D<sub>0</sub>|1 &minus; e<sup>&minus;k&tau;</sup>}}',
 when: 'Repeated IV bolus "every &tau; hours": the peak amount at steady state.',
 need: 'D<sub>0</sub>, k and &tau;.'},
{c: 2, module: 6, eq: 'dmin-ss', model: 'Repeated IV bolus', asks: 'Amount in the body',
 html: 'D<sub>min</sub><sup>&infin;</sup> = {{frac:D<sub>0</sub>e<sup>&minus;k&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}}',
 when: 'The trough amount at steady state, just before the next dose.',
 need: 'D<sub>0</sub>, k and &tau;.'},
{c: 2, module: 6, eq: 'davg-ss', model: 'Repeated IV bolus', asks: 'Amount in the body',
 html: 'D<sub>avg</sub><sup>&infin;</sup> = {{frac:FD<sub>0</sub>|k&tau;}}',
 when: 'The average amount over one interval at steady state.',
 need: 'F (1 for IV), D<sub>0</sub>, k and &tau;.'},
{c: 2, module: 6, eq: 'cmax-ss', model: 'Repeated IV bolus', asks: 'Cmax at steady state',
 html: 'C<sub>max</sub><sup>&infin;</sup> = {{frac:D<sub>max</sub><sup>&infin;</sup>|V<sub>D</sub>}} = {{frac:C<sub>0</sub>|1 &minus; e<sup>&minus;k&tau;</sup>}}',
 when: 'The steady-state peak concentration after repeated IV bolus doses.',
 need: 'C<sub>0</sub> (dose &divide; V<sub>D</sub>), k and &tau;.'},
{c: 2, module: 6, eq: 'cmin-ss', model: 'Repeated IV bolus', asks: 'Cmin at steady state',
 html: 'C<sub>min</sub><sup>&infin;</sup> = {{frac:D<sub>min</sub><sup>&infin;</sup>|V<sub>D</sub>}} = {{frac:C<sub>0</sub>e<sup>&minus;k&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}}',
 when: 'The steady-state trough concentration; also C<sub>max</sub><sup>&infin;</sup> &times; e<sup>&minus;k&tau;</sup>.',
 need: 'C<sub>0</sub>, k and &tau;.'},
{c: 2, module: 6, eq: 'cavg-ss', model: 'Repeated IV bolus', asks: 'Cavg at steady state',
 html: 'C<sub>avg</sub><sup>&infin;</sup> = {{frac:D<sub>avg</sub><sup>&infin;</sup>|V<sub>D</sub>}} = {{frac:FD<sub>0</sub>|V<sub>D</sub>k&tau;}}',
 when: 'The average steady-state concentration; a dose for a target average.',
 need: 'F, D<sub>0</sub>, V<sub>D</sub>, k and &tau;; V<sub>D</sub>k is Cl.'},
{c: 2, module: 6, eq: 'cp-n', model: 'Repeated IV bolus', asks: 'C at a time',
 html: 'C<sub>p</sub> = {{frac:D<sub>0</sub>|V<sub>D</sub>}}({{frac:1 &minus; e<sup>&minus;nk&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;kt</sup>',
 when: 'After n IV bolus doses, before steady state, t hours after the nth dose.',
 need: 'n, &tau;, k, t and C<sub>0</sub>; t is counted from the last dose.'},
{c: 2, module: 6, eq: null, model: 'Multiple oral doses', asks: 'C at a time',
 html: 'C<sub>p</sub> = {{frac:Fk<sub>a</sub>D<sub>0</sub>|V<sub>D</sub>(k<sub>a</sub> &minus; k)}}[({{frac:1 &minus; e<sup>&minus;nk&tau;</sup>|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;kt</sup> &minus; ({{frac:1 &minus; e<sup>&minus;nk<sub>a</sub>&tau;</sup>|1 &minus; e<sup>&minus;k<sub>a</sub>&tau;</sup>}})e<sup>&minus;k<sub>a</sub>t</sup>]',
 when: 'After n oral doses, before steady state: the oral line with an accumulation term on each exponential.',
 need: 'F, k<sub>a</sub>, k, D<sub>0</sub>, V<sub>D</sub>, n, &tau; and t.'},
/* ---- page 2, left column ---------------------------------------------- */
{c: 3, module: 6, eq: null, model: 'Multiple oral doses', asks: 'C at a time',
 html: 'C<sub>p</sub><sup>&infin;</sup> = {{frac:Fk<sub>a</sub>D<sub>0</sub>|V<sub>D</sub>(k<sub>a</sub> &minus; k)}}[({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;kt</sup> &minus; ({{frac:1|1 &minus; e<sup>&minus;k<sub>a</sub>&tau;</sup>}})e<sup>&minus;k<sub>a</sub>t</sup>]',
 when: 'Multiple oral doses at steady state: the concentration t hours into an interval.',
 need: 'F, k<sub>a</sub>, k, D<sub>0</sub>, V<sub>D</sub>, &tau; and t.'},
{c: 3, module: 6, eq: 'cmax-ss-oral', model: 'Multiple oral doses', asks: 'Cmax at steady state',
 html: 'C<sub>max</sub><sup>&infin;</sup> = {{frac:FD<sub>0</sub>|V<sub>D</sub>}}({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;kt<sub>max</sub><sup>&infin;</sup></sup>',
 when: 'The steady-state peak after multiple oral doses.',
 need: 'F, D<sub>0</sub>, V<sub>D</sub>, k, &tau; and t<sub>max</sub><sup>&infin;</sup> from the line two below.'},
{c: 3, module: 6, eq: 'cmin-ss-oral', model: 'Multiple oral doses', asks: 'Cmin at steady state',
 html: 'C<sub>min</sub><sup>&infin;</sup> = {{frac:k<sub>a</sub>FD<sub>0</sub>|V<sub>D</sub>(k<sub>a</sub> &minus; k)}}({{frac:1|1 &minus; e<sup>&minus;k&tau;</sup>}})e<sup>&minus;k&tau;</sup>',
 when: 'The steady-state trough after multiple oral doses.',
 need: 'F, k<sub>a</sub>, k, D<sub>0</sub>, V<sub>D</sub> and &tau;.'},
{c: 3, module: 6, eq: 'tmax-ss', model: 'Multiple oral doses', asks: 'tmax and Cmax',
 html: 't<sub>max</sub><sup>&infin;</sup> = {{frac:1|k<sub>a</sub> &minus; k}} ln[{{frac:k<sub>a</sub>(1 &minus; e<sup>&minus;k&tau;</sup>)|k(1 &minus; e<sup>&minus;k<sub>a</sub>&tau;</sup>)}}]',
 when: 'The time of the peak within an interval at steady state, multiple oral doses.',
 need: 'k<sub>a</sub>, k and &tau;.'},
{c: 3, module: 7, eq: 'f-abs', alsoEq: ['f-auc'], model: 'Bioavailability', asks: 'F',
 html: 'F<sub>abs</sub> = ({{frac:AUC<sub>po</sub>|AUC<sub>IV</sub>}})({{frac:D<sub>IV</sub>|D<sub>po</sub>}})',
 when: '"Absolute bioavailability": an oral AUC against an IV AUC, dose-corrected.',
 need: 'Both AUCs and both doses; equal doses make the dose ratio 1.'},
{c: 3, module: 7, eq: 'div-cl-auc', model: 'Bioavailability', asks: 'Dose or AUC',
 html: 'D<sub>IV</sub> = (Cl)(AUC<sub>IV</sub>)',
 when: 'The IV AUC when only clearance is given, or the IV dose from an AUC.',
 need: 'Cl and the IV AUC, or the IV dose and Cl.'},
{c: 3, module: 7, eq: 'fabs-dpo', model: 'Bioavailability', asks: 'Dose or AUC',
 html: 'F<sub>abs</sub>D<sub>po</sub> = (Cl)(AUC<sub>po</sub>)',
 when: 'The absorbed oral dose from clearance and the oral AUC; an equivalent oral dose.',
 need: 'Cl and the oral AUC; divide by F<sub>abs</sub> for the dose to give.'},
{c: 3, module: 7, eq: 'f-rel', model: 'Bioavailability', asks: 'F',
 html: 'F<sub>rel</sub> = ({{frac:AUC<sub>A</sub>|AUC<sub>B</sub>}})({{frac:D<sub>B</sub>|D<sub>A</sub>}})',
 when: '"Relative bioavailability": one formulation "compared to" a named reference, no IV.',
 need: 'The two AUCs and the two doses; B is the reference.'},
{c: 3, module: 0, eq: null, model: 'Stability, not lectured', asks: 'Shelf life',
 html: 'E = E<sub>0</sub> &minus; {{frac:kmt|2.3}}',
 when: 'Stability and shelf life; not lectured in Modules 1 to 7a.',
 need: 'Left as printed.'},
{c: 3, module: 0, eq: null, model: 'Stability, not lectured', asks: 'Shelf life',
 html: 't<sub>eff</sub> = {{frac:2.3[log(D<sub>0</sub>/V<sub>D</sub>) &minus; log C<sub>eff</sub>]|k}}',
 when: 'Duration of effect; not lectured in Modules 1 to 7a.',
 need: 'Left as printed.'},
{c: 3, module: 0, eq: null, model: 'Stability, not lectured', asks: 'Shelf life',
 html: 't<sub>eff</sub> = {{frac:[ln(D<sub>0</sub>/V<sub>D</sub>) &minus; ln C<sub>eff</sub>]|k}}',
 when: 'The same relation in natural logs.',
 need: 'Left as printed.'},
{c: 3, module: 0, eq: null, model: 'Stability, not lectured', asks: 'Shelf life',
 html: 't<sub>eff</sub> = 1.44t<sub>1/2</sub> ln({{frac:D<sub>0</sub>|V<sub>D</sub>C<sub>eff</sub>}})',
 when: 'The same relation written with the half-life.',
 need: 'Left as printed.'},
/* ---- page 2, right column --------------------------------------------- */
{c: 4, module: 0, eq: null, model: 'Nonlinear, not lectured', asks: 'Nonlinear',
 html: 'R = {{frac:V<sub>max</sub>C<sub>ss</sub>|K<sub>M</sub> + C<sub>ss</sub>}}',
 when: 'Nonlinear pharmacokinetics (Module 9, final exam); not yet lectured.',
 need: 'Left as printed.'},
{c: 4, module: 0, eq: null, model: 'Nonlinear, not lectured', asks: 'Nonlinear',
 html: 'K<sub>M</sub> = {{frac:R<sub>2</sub> &minus; R<sub>1</sub>|R<sub>1</sub>/C<sub>1</sub> &minus; R<sub>2</sub>/C<sub>2</sub>}}',
 when: 'Nonlinear; not yet lectured.',
 need: 'Left as printed.'},
{c: 4, module: 0, eq: null, model: 'Nonlinear, not lectured', asks: 'Nonlinear',
 html: 't<sub>1/2</sub> = V<sub>D</sub>({{frac:0.693|V<sub>max</sub>}})(K<sub>M</sub> + C<sub>p</sub>)',
 when: 'Nonlinear; not yet lectured. The only half-life line the sheet prints.',
 need: 'Left as printed.'},
{c: 4, module: 0, eq: null, model: 'Nonlinear, not lectured', asks: 'Nonlinear',
 html: 'Cl<sub>T</sub> = {{frac:V<sub>max</sub>|K<sub>M</sub> + C<sub>p</sub>}}',
 when: 'Nonlinear; not yet lectured.',
 need: 'Left as printed.'},
];

/* The lines she said she does not supply, to print beside the map. */
const SHEET_MISSING = [
 {module: 1, html: 't&frac12; = {{frac:0.693|k}}', eq: 'thalf-first', model: 'First order, any route', asks: 't½ and k', when: 'Every half-life question; k from a half-life.'},
 {module: 2, html: 'Cl = k &times; V<sub>D</sub>', eq: 'cl-k-vd', model: 'Any route', asks: 'Clearance', when: 'Clearance from k and volume, and the other way round.'},
 {module: 4, html: 'CrCl = {{frac:(140 &minus; age)(weight)|72 &times; S<sub>Cr</sub>}} (&times; 0.85 for a woman)', eq: 'crcl', model: 'Renal function', asks: 'CrCl', when: 'Creatinine clearance, in mL/min.'},
 {module: 4, html: 'IBW (male) = 50 kg + 2.3 kg per inch over 5 ft', eq: 'ibw-male', model: 'Renal function', asks: 'CrCl', when: 'The weight that goes into Cockcroft-Gault.'},
 {module: 4, html: 'IBW (female) = 45.5 kg + 2.3 kg per inch over 5 ft', eq: 'ibw-female', model: 'Renal function', asks: 'CrCl', when: 'The weight that goes into Cockcroft-Gault.'},
];
